### ISSUE TITLE
Should the FTP adapter rename function recursively create the target directories if they do not exist?

### ISSUE THREAD

**Issue by chrisdeeming** [thephpleague/flysystem#1014]
### Question

|    Q        |   A
|------------ | ------
| Version     | 1.0.50

I just wanted to validate my thinking before dedicating any time to fixing this.

Given this code for most Flysystem adapter implementations:
```php
$oldPath = 'old/path/to/file.mp4';
$newPath = 'new/path/to/file.mp4';

$fs->move($oldPath, $newPath);
```
In case the directory `new/path/to` does not exist, most file systems would work in such a way that the directories `new`, `new/path` and `new/path/to` would be created during the rename operation.

Unfortunately with the FTP adapter, the `ftp_rename` function does not do this. Before being able to move `file.mp4` you are required to first of all create the directories `new/path/to` otherwise an `E_WARNING` is emitted stating that the "file or directory does not exist".

While I can adjust our code to attempt to create those directories first, I fairly firmly believe that the behaviour should be consistent and I'm fairly sure most file systems would not error in this case, like the FTP adapter does.

So I'm proposing that a change is made whereby the `rename` function of the FTP adapter attempts to recursively create those directories first.

I'm happy to make this change, but obviously only if it is likely to be approved. Any thoughts?

**Comment by frankdejonge** [comment]
That seems very reasonable 👍

**Comment by chrisdeeming** [comment]
That was quick 😀

I'll see what I can do then.

**Comment by frankdejonge** [comment]
Good luck! Be sure to add the docker based integration tests for this. You can checkout the .travis.yml file to see how to run the tests and set this up locally (saves you time when you don't have to wait on travis).
