### ISSUE TITLE
PutStream not work

### ISSUE THREAD

**Issue by sanchezzzhak** [thephpleague/flysystem#1016]
### Bug Report
I have a file Uploader that splits files into parts 
And each part I send as a small file to the server

after the file is submitted, the last part of the file is not added to the end of the file
I recorded a video of the wrong work  https://youtu.be/3a5gMxWIWPM

```
   /** @var Local $adapter */
        $fileSourcePath = $_FILES['file']['tmp_name'];
        $fileStorePath = 'tmp/1.tmp';
        $stream = fopen($fileSourcePath, 'r+');
        if($adapter->has($fileStorePath)){
            $adapter->putStream($fileStorePath, $stream);
            $isWrite = 'put';
        } else {
           $adapter->writeStream($fileStorePath, $stream);
            $isWrite = 'write';
        }
        if (is_resource($stream)) {
            fclose($stream);
        }

        $result = $adapter->getMetadata($fileStorePath);
        if ($result) {
            $result['type'] = $adapter->getMimetype($fileStorePath);
            $result['path'] = $fileStorePath;
            $result['is_write_type'] = $isWrite;
        }

```
If you correct the flags in the `fopen` method, `Local::writeStream`  (line 158)
`w+b` change `a+b`
we get a normal job `putStream`
demo https://youtu.be/cPr-xLLfyLQ

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1@dev

**Comment by frankdejonge** [comment]
The putStream function doesn't append, it only overwrites. If you want to append you should always just use regular PHP functions. Flysystem is a library for FS encapsulation and doesn't support append because it cannot simmulate that for filesystem's that don't support it.

**Comment by sanchezzzhak** [comment]
@frankdejonge Thanks

For those who are faced with this issue, there is a ready plugin
https://github.com/kevengodet/flysystem-concatenate
