### ISSUE TITLE
Util::normalizeRelativePath() broken with absolute path

### ISSUE THREAD

**Issue by rentalhost** [thephpleague/flysystem#1017]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no, but maybe a fix could causes it
| Version     | 1.0.51

#### Summary

There are a divergence with the `Util::normalizeRelativePath()` method when you apply it to a Windows absolute path vs. Linux absolute path. For Windows it works fine, but for Linux it will drop the leading slash, which make the absolute path to a relative.

**For instance:** 

* Windows: if I have a absolute path like: `C:\project\.\path/..\file.ext` and run this method it will be normalized to `C:/project/file.ext`, which is the expected (absolute path keeps absolute path);
* Linux: but if I run the same code on Linux that not have a device identificator (eg. `C:`), like `/project/./path/../file.ext` will be normalized to `project/file.ext`.

Because of that I need write an additional code to "fix" this behaviour for Linux because it diverges from Windows.

**On the other hand:**

1. The "relative" name in `normalize[Relative]Path()` means that it should returns a relative path. But it should modify the absolute path to a relative just "because yes"?
2. The `normalizePath()` (that currently is a proxy to `normalizeRelativePath()`) by otherside doesn't specific if the return will be relativized or not. Maybe it could keeps the leading slash if it is applied?

**Possible solutions:**

1. Allow `normalizeRelativePath()` to keep absolute as absolute;
2. Allow `normalizeRelativePath()` to keep absolute as absolute if a new second parameter is set to true (eg. `($path, ?bool $keepAbsolutism = null)`);
3. Allow `normalizePath()` to keep absolute as absolute;
4. Create a new `normalizeAbsolutePath()` to keep the absolutism or transforms relatives to absolute;

**Related issues:** #965, #761.

**Comment by frankdejonge** [comment]
If you want to use absolute paths you need to set the root path to `/`, this, combined with the relative path equals an absolute path. In either case the root is compared with the resolved path to check for path traversal issues, so the behaviour is the same. So while windows paths are resolved with disk prefix the result is the same. The reason for Flysystem to have this behaviour is because of encapsulation and portability of dependant code, which will not change. If you want the behaviour you're described you need to wrap Flysystem in another object which forces a root of `/` and allows for both relative and absolute paths, based of a prefix managed by that layer.

**Comment by rentalhost** [comment]
The biggest problem is when you are using a third party package, for my case for instance I am using Laravel `base_path()` helper to get the absolute path to a specific file or folder, that could not exists (so I can't use the `realpath()`). And it will returns an absolute path like `/home/user/public_html/some/path` for Linux or `D:/project/some/path` for Windows. With it I could verify if this file or folder exists in an array that should have unique elements, so I use the `Util::normalizeRelativePath()` to ensure that the path will be the same, even if it have some backslash or backdir. To avoid the problem with the "unabsolutize" of this method I should do some hacks:

    public static function normalizeAbsolutePath(string $path): string
    {
        $path = Util::normalizeRelativePath($path);

        if (DIRECTORY_SEPARATOR === '/') {
            $path = DIRECTORY_SEPARATOR . $path;
        }

        return $path;
    }

Because of that I think that a method like `Util::normalizeAbsolutePath()` should exists to ensure that a `/` is added to start of the result (even if it doesn't have), or then throw an exception if the `$path` argument don't have it to make sure that the dev is really expecting and using a absolute path.

**Comment by frankdejonge** [comment]
Are you saying you're using this util outside of Flysystem?

**Comment by rentalhost** [comment]
Yes. I am using it to normalize some paths to make sure that an array of paths have only unique paths. Normalize will help to avoid duplicates even if path is not absolute (eg. have `..` or `//` or uses `\` in some places and `/` in others).

**Comment by frankdejonge** [comment]
Then just copy the code and modify it for your needs. No need to use this outside of Flysystem. It will never function as a standalone feature.
