### ISSUE TITLE
Static analysis error for League\Flysystem\FilesystemInterface::getAdapter

### ISSUE THREAD

**Issue by willpower232** [thephpleague/flysystem#1023]
### Question

We are making use of League\Flysystem\FilesystemInterface::getAdapter() to check if the file exists in S3 but we are seeing an error when analysing the code with [Larastan](https://github.com/nunomaduro/larastan).

```
Call to an undefined method League\Flysystem\FilesystemInterface::getAdapter(). 
```

The code works fine but the error appears when analysing the code, presumably because the `@method` entry for it is missing in the docblock (when compared to other classes).

Is there a more appropriate way to get at the S3 class or see if the file already exists in S3? Or does this need fixing?

At the moment we are ignoring the error manually so this is more of a heads-up but I thought it was worth enquiring about.

|    Q        |   A
|------------ | ------
| Version     | 1.0.22

**Comment by PatrickRose** [comment]
Is there a reason you can't use the `has` method to check for existence? For _most_ use cases you shouldn't need to be accessing the adapter itself.

**Comment by willpower232** [comment]
Ah thank you, please forgive my overthinking it.

**Comment by willpower232** [comment]
I have finally had time to work on this and rediscovered something else we're using the underlying client for.

We're using it for the `createPresignedRequest` method from the AWS SDK.

```
$s3 = \Storage::disk('s3');
$client = $s3->getDriver()->getAdapter()->getClient();
$bucket = \Config::get('filesystems.disks.s3.bucket');

$fileexists = false;
try {
    $fileexists = $s3->has($filepath);
} catch (\Aws\S3\Exception\S3Exception $e) {
    // report exception
}

if (! $fileexists) {
    abort(404);
}

$command = $client->getCommand('GetObject', [
    'Bucket' => $bucket,
    'Key'    => $filepath,
    'ResponseContentDisposition' => 'inline; filename="' . $filename . '"'
]);
$request = $client->createPresignedRequest($command, "+15 minutes");

return redirect((string)$request->getUri());
```

I don't believe that this method is supported by Flysystem so is there a better way to get at the client or would we need to create a separate instance of it?

**Comment by frankdejonge** [comment]
Flysystem does not provide with signed urls, for that you should just use the aws client itself.

**Comment by willpower232** [comment]
Thanks for confirming that. My original query was that using `getAdapter()` to get to `getClient()` caused problems for static analysis.

> The code works fine but the error appears when analysing the code, presumably because the @method entry for it is missing in the docblock (when compared to other classes).
> 
> Is there a more appropriate way to get at the S3 class or see if the file already exists in S3? Or does this need fixing?

**Comment by frankdejonge** [comment]
You could get it from flysystem, but why not just from the DI container?

**Comment by frankdejonge** [comment]
Basically, you shouldn't be dependant on Flysystem, but on the S3 client directly, so also for the creation of the client. You could see it like your code _and_ flysystem are both dependant on AWS.

**Comment by willpower232** [comment]
Replaced the annoying code with the storage facade:

```
$url = \Storage::temporaryUrl(
    $filepath,
    now()->addMinutes(15),
    ['ResponseContentDisposition' => 'inline; filename="' . $filename . '"']
);
```
