### ISSUE TITLE
Unable to access files with \t in the filename on dropbox

### ISSUE THREAD

**Issue by brajnacs** [thephpleague/flysystem#1031]
### Bug Report

I am using a Laravel dropbox adapter to access the files stored on the dropbox. Basically, I am iterating over the directories and accessing each file in them programatically. File names also coming from the API response.

There are some files which have a tab character in them. When seeing the filename in the console it shows as follows.

NG_2018040401_A10_[five-spaces-here]Leslie Cunningham DC0005634.CEL_call_code.txt

In the actual API response, it is coming as follows
NG_2018040401_A10_\tLeslie Cunningham DC0005634.CEL_call_code.txt

There are other files with the similar name (which doesn't have this \t) and they are reading just fine.

Is there any way around this?

#### How to reproduce

I don't know how these files end up having this kind of names as these files are not mine. So i can't create one myself. I will try downloading a file on local disk and try this again.

**Comment by frankdejonge** [comment]
Are you using the @spatie adapter?

**Comment by brajnacs** [comment]
Yes the package I am using depends on the spatie's [dropbox adapter](https://github.com/spatie/flysystem-dropbox).
