### ISSUE TITLE
can you add SSH/Shell adapter for league/flysystem to documentation page?

### ISSUE THREAD

**Issue by oliwierptak** [thephpleague/flysystem#1033]
### Question

Hi,

I've created SSH/Shell adapter for league/flysystem.
It only requires working ssh/scp connection and few very basic shell commands.

https://github.com/oliwierptak/flysystem-ssh-shell
Please let me know if you need more info.

Can you add the link  to the documentation page, under https://github.com/thephpleague/flysystem#community-supported ?

|    Q        |   A
|------------ | ------
| Version     | 1.0.0

**Comment by frankdejonge** [comment]
Hi, you can send a PR to this repo to get it included in the readme 👍
