### ISSUE TITLE
Upload large file (> 1GB) with a local adapter.

### ISSUE THREAD

**Issue by hemratna** [thephpleague/flysystem#1039]
I am trying to upload a large file (> 1GB) with a local adapter.

I am working on Directus https://github.com/directus/api, an opensource headless CMS.

I am using Slim as a backend framework. 

There is not a specific example of a handling file for slim in the documentation https://flysystem.thephpleague.com/docs/guides/uploads/
So I am following the guide for **Plain PHP Upload**

I am getting 500 error for the `fopen` as the file size is large.

I search the repo issues and try to use the readStream and writeStream method as suggested. But unfortunately, I am not able to find the correct solution.

Any reference code example or other resources will be really helpful.

Thanks a lot for such an amazing package. 😊

**Comment by frankdejonge** [comment]
Can you show me the error stack trace?

**Comment by frankdejonge** [comment]
BTW, if this is caused by the `fopen` call there's really not a lot I can do for you, but I'd be surprised if that was the case. To me it seems more likely that the webserver is not accepted the postsize. But let's investigate.

**Comment by hemratna** [comment]
Hi @frankdejonge 
Thanks a lot for such a quick reply.

I am wondering ***Why I need to use `fopen`?*** 

As mentation on the docs https://flysystem.thephpleague.com/docs/guides/uploads/ for the ***Laravel 5 - DI*** example,
Is there any way I can upload directly `Slim\UploadedFile` file object? Something similar to `$request->file('upload')` for the Laravel example.

Can you point me out any example code for `readStream` and `writeStream` with multipart form data?

Regarding the web server, I change the required server var's so the server can accept the 1 GB file. To verify it I tried to upload a file with `move_uploaded_file` function and it is working.

Regarding the error stack, I am using MAMP PRO and I am only getting 500 in the response. Not so helpful message. Nothing in the apache log file (or at least where I am looking).

**Comment by frankdejonge** [comment]
Ah ok, so in PHP you basically have two ways of transporting blobs of data. In string format, or in "resources". The second uses a more memory efficient structure. Also the value underneath is basically a pointer, so passing is around is fine even if things happen with the underlying structure (seeking and stuff like that). I'm not 100% sure what happens when PHP accepts an upload, but I believe it stores it in the temp directory so you open a stream (resource) from there. Otherwise you'd load it in memory and that'll never fit. What can happen is when you're already at your memory limit that opening a resource is just tipping it over the edge. Flysystem internally uses `stream_copy_to_stream` to copy the information from the upload to the destination. This is, for PHP, the most memory efficient and least error prone way.

**Comment by hemratna** [comment]
Thanks a lot, @frankdejonge for letting me know "How flyststem working internally."

But according to example, I have to call the `fopen` function on the uploaded file.

Is there any way around for the `fopen`? because `fopen` for the large file will always fail. 

I couldn't find anything for ***How to use flysystem with Slim?***

**Comment by frankdejonge** [comment]
The thing is, it shouldn't fail, consider this script I just ran:

```php
<?php
const INPUT = __DIR__ . '/file.txt';
const OUTPUT = __DIR__ . '/out.txt';
if (file_exists(OUTPUT)) {
    unlink(OUTPUT);
}

$destination = fopen(OUTPUT, 'w+b');
$handle = fopen(INPUT, 'rb');

var_dump(stream_copy_to_stream($handle, $destination));

fclose($destination);
fclose($handle);
var_dump(memory_get_peak_usage(true)/1024/1024);
```

I used a ~1GB file generated using `dd if=/dev/zero of=file.txt count=1024 bs=1048576`.

This reports a max mem peak of 2mb.

**Comment by hemratna** [comment]
Wow @frankdejonge 
That's really quick.

In your example, I think You have a file already on the server.
In my case, User is uploading a file from the web browser via the form request. 

So on the server side, I am getting this file as `$_FILES[$uploadname]['tmp_name']`

`$stream = fopen($_FILES[$uploadname]['tmp_name'], 'r+');` will return 500 in my case.

I will try to use `stream_copy_to_stream` instead of  `writeStream`.

Thanks a lot for such a quick code example. 😊

**Comment by frankdejonge** [comment]
@hemratna actually Flysystem uses that function internally. That file from $_FILES is also already on the server, or at least partially and constantly written to. If everything else fails you can always try `move_uploaded_file` without Flysystem, but there's something wrong either in your configuration. Can you check the max memory setting of your PHP installation?

**Comment by hemratna** [comment]
The `memory_limit = 128M`

As you suggest I can use `move_uploaded_file`, But as we are open source project and we do officially support the AWS S3 and some other community supported file system drive.

Flysystem really provides powerful architecture to support all of that.😊 Moving back to `move_uploaded_file` doesn't feel the right choice.

**Comment by frankdejonge** [comment]
I converted the script to use Flysystem and it also uses about 2mb of mem:

```php
<?php

use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

include __DIR__.'/vendor/autoload.php';

$filesystem = new Filesystem(new Local(__DIR__));

const INPUT = __DIR__ . '/file.txt';
const OUTPUT = __DIR__ . '/out.txt';
if (file_exists(OUTPUT)) {
    unlink(OUTPUT);
}

$handle = fopen(INPUT, 'rb');

$filesystem->writeStream('out.txt', $handle);


fclose($handle);
var_dump(memory_get_peak_usage(true)/1024/1024);
```

So it really should be enough.

**Comment by frankdejonge** [comment]
I'm AFK now so won't be able to respond until tomorrow, hope you have more luck debugging this.

**Comment by shadowhand** [comment]
https://stackoverflow.com/questions/6135427/increasing-the-maximum-post-size#6135485 ?

**Comment by frankdejonge** [comment]
The weird thing is that he mentioned it's an error from the fopen call. But perhaps we should look at the actual stack trace too.

**Comment by eelkevdbos** [comment]
Just an observation, @frankdejonge uses fopen in forced binary mode (rb), while @hemratna uses r+. The php docs mention portability issues when not forcing binary mode.

**Comment by frankdejonge** [comment]
I’ve validated both work actually. No difference.

**Comment by eelkevdbos** [comment]
Is it possible that the file you use for testing is very clean and might not represent the funky /exotic falsely detected encoding some files can pull off?

**Comment by hemratna** [comment]
@shadowhand `post_max_size = 1024M`. 
I tested the 1 GB file upload with `move_uploaded_file` function and it is working.

Thanks for stopping by. 😊

**Comment by hemratna** [comment]
@eelkevdbos I change my code with `rb`, still no luck.
Can you point me with ***How can I upload 1 GB file from the browser?*** 

The code snippet given by @frankdejonge is working fine if the file is already on the server. But when I try to run the same code with user uploaded file (`$_FILES[$uploadedFile]['temp_name']`) I am getting 500 error.

I am also looking for not to use `fopen` in file upload from the web browser as mentation in the documentation https://flysystem.thephpleague.com/docs/guides/uploads/.  

Any kind of help is really appreciated.

**Comment by hemratna** [comment]
The `fopen` is reading the whole file in memory, So `memory_limit` should be larger than `post_max_size`.

According to https://www.php.net/manual/en/ini.core.php#ini.post-max-size
`Generally speaking, memory_limit should be larger than post_max_size.`

In my case I have to update the `memory_limit=1024M`, If I change `memory_limit` then file got uploaded successfully. But I am afraid this is not possible for some large file sizes like 10GB.

That's the reason I am looking for options which don't require the `fopen`.

**Comment by frankdejonge** [comment]
Fopen does not read the entire file in memory. My example shows that. The file is 1GB and the max mem is 2mb.

**Comment by shadowhand** [comment]
> @shadowhand `post_max_size = 1024M`.
> I tested the 1 GB file upload with `move_uploaded_file` function and it is working.
> 
> Thanks for stopping by. 😊

@hemratna what about `upload_max_filesize` ?

**Comment by shadowhand** [comment]
I cannot tell if `stream_copy_to_stream`, which is [what Flysystem uses][1] attempts to push the entire file through memory at once, from the docs or from [the source][2]. I don't know C at all, but it looks like `stream_copy_to_stream` buffers the writes in the same way that a `fopen(); while(!feof()) { fwrite(); } fclose();` sequence would work.

I think the most helpful thing would be for @hemratna to provide the actual error message and stack trace, because right now we're only guessing at what the error is and I am starting to suspect that it is in the usage, not Flysystem/Slim.

[1]: https://github.com/thephpleague/flysystem/blob/36f1ab08462e8239b616fd3828ace2a78d3a7cbe/src/Adapter/Local.php#L160-L162
[2]: https://github.com/php/php-src/blob/36452922351fe3f87e8714562263247a1dbc15d3/main/streams/streams.c#L1501-L1558

**Comment by frankdejonge** [comment]
@shadowhand as I showed above the memory used for this operation is not the entire file. The example shows this. It’s also how file handlers in general work. So I’m 100% sure it’s not loading the entire file in memory.

**Comment by hemratna** [comment]
@shadowhand I am using MAMP PRO and there is no error in error log file.
In the browser, I am getting 500 without any proper error msg.

@frankdejonge I convert your sample code to work with browser upload file and it is working fine.

I think the issue lies between `Slim\Http\UploadFile` object.

I am requesting you to please open this issue for a couple of days (if possible),
So I can discuss with other participants (and of course with you) regarding my findings.

Thanks a lot for help.

**Comment by frankdejonge** [comment]
Have you raised an issue with the slim repo? Seems more relevant.

**Comment by hemratna** [comment]
@frankdejonge Not yet.
I found some related issue https://github.com/slimphp/Slim/issues/1798
I dig dipper and raise the issue.

**Comment by frankdejonge** [comment]
Looks like the Slim upload object has a getStream method. You should be able to call the detach to get the resource from the stream object.

**Comment by hemratna** [comment]
Below code is working in my use case.

`$handle = fopen($data->file, 'rb');`
`$filesystem->writeStream($location, $handle);`

Thanks a lot for the amazing library.

**Comment by anmar1986** [comment]
Hi hemranta,
i´m trying to build an application which is a contact form and the user can send me a video bigger than 1GB
so can you send me your application ? because i did not chose the php framework til now 
and i can buld it like you with slim framework. 
yours Anmar

**Comment by hemratna** [comment]
Hi @anmar1986 
I used flysystem with [Directus](https://github.com/directus/api) and it's working fine.

But if you are planning to develop a new app from scratch, I am suggesting to go with Laravel (which also use flysystem behind the scene).

**Comment by anmar1986** [comment]
Hello Hemratna,
thanks for your reply, laravel is a little bit big for an application like
this.
which one will you suggest for me ? i mean which php framework would be
better ?

Yours Anmar
