### ISSUE TITLE
Setting preference for mime type extension

### ISSUE THREAD

**Issue by jsgv** [thephpleague/flysystem#1045]
### Question

I am using this package along with `league/flysystem-aws-s3-v3`. 

When I upload a quicktime file with extension `.mov` the mime detection converts to `.qt`. Is there a way to set preference for extensions for mime types that have more than 1 file extension defined? I would prefer to use the `.mov` extension instead of `.qt` for quicktime files.

|    Q        |   A
|------------ | ------
| league/flysystem | 1.0.51
| league/flysystem-aws-s3-v3 | 1.0.23

**Comment by frankdejonge** [comment]
Hi, a PR to set the mime-type in the config would be accepted.

**Comment by d4mn** [comment]
This issue still exists!
