### ISSUE TITLE
ftp_chmod(): Command not implemented for that parameter

### ISSUE THREAD

**Issue by quantumwebco** [thephpleague/flysystem#1046]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.53

#### Summary

FTP in Laravel 5.3 to windows FTP server running filezilla server 0.9.60 throws a CHMOD error

Is this script not compatible with windows ftp servers at all?

#### How to reproduce

In a Laravel 5.3 app, when putting files to a remote ftp disk ```$document = Storage::disk('titan')->put('/20' . $year . '/' . $number . '/' . $name, $file, 'public');```

using settings
```
        'titan' => [
        	'host' => 'xxxxx',
        	'username' => 'xxxxx',
        	'password' => 'xxxxx',
	        'port' => '21',
	        'passive'  => true,
            'driver' => 'ftp',
            'root' => '/',
            'visibility' => 'windows',
        ],
```
It throws the exception 
ErrorException in Ftp.php line 477:ftp_chmod(): Command not implemented for that parameter
in Ftp.php line 477
at HandleExceptions->handleError('2', 'ftp_chmod(): Command not implemented for that parameter', '/var/www/vhosts/titantorque.co.uk/operations.titantorque.co.uk/vendor/league/flysystem/src/Adapter/Ftp.php', '477', array('path' => '2019/TTS190859/work_ticket.xlsx', 'visibility' => 'public', 'mode' => '484')) in ErrorHandler.php line 34

**Comment by frankdejonge** [comment]
Your FTP server doesn't support CHMOD. Nothing we can do on our end to fix that.

**Comment by quantumwebco** [comment]
@frankdejonge Is there no option to turn off the CHMOD? That basically means this script is broken for any windows server

**Comment by frankdejonge** [comment]
For future reference, this is one of the worst issues I've ever seen. You just dump a stack-trace and expect people to jump up and fix it? 🤷‍♂️There's a template to fill out you didn't ignore it, you removed it even. I'm heading out now so won't be responding till later.

**Comment by quantumwebco** [comment]
@frankdejonge Apologies, I thought the stack-trace had everything you would need to know in it?

**Comment by quantumwebco** [comment]
@frankdejonge I'm ever so sorry for upsetting you by not filling out the bug report correctly. Have I lost any chance of support at all now?

**Comment by frankdejonge** [comment]
I’ll look at this somewhere this week. But not everything is fixable from within Flysystem. Can you add the calls you’re making that cause this, an example to reproduce this, which version you’re using, what FTP server you’re using (type+version).

**Comment by quantumwebco** [comment]
@frankdejonge Thanks so much!!! I did update the initial bug report as soon as you said it was the worst you'd ever seen, I tried to make it better. I filled out all the sections and put examples and all the versions of software etc. I've copy/pasted it below. Is this not enough info? I'm really sorry I don't know what other info I can provide. I don't currently have more info about the server apart from that it's windows running filezilla 0.9.60. I added a code example, is that not right? I also showed the settings from the config file too. What else do you need? I tried to provide all the info I have

### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.53

#### Summary

FTP in Laravel 5.3 to windows FTP server running filezilla server 0.9.60 throws a CHMOD error

Is this script not compatible with windows ftp servers at all?

#### How to reproduce

In a Laravel 5.3 app, when putting files to a remote ftp disk ```$document = Storage::disk('titan')->put('/20' . $year . '/' . $number . '/' . $name, $file, 'public');```

using settings
```
        'titan' => [
        	'host' => 'xxxxx',
        	'username' => 'xxxxx',
        	'password' => 'xxxxx',
	        'port' => '21',
	        'passive'  => true,
            'driver' => 'ftp',
            'root' => '/',
            'visibility' => 'windows',
        ],
```
It throws the exception 
ErrorException in Ftp.php line 477:ftp_chmod(): Command not implemented for that parameter
in Ftp.php line 477
at HandleExceptions->handleError('2', 'ftp_chmod(): Command not implemented for that parameter', '/var/www/vhosts/titantorque.co.uk/operations.titantorque.co.uk/vendor/league/flysystem/src/Adapter/Ftp.php', '477', array('path' => '2019/TTS190859/work_ticket.xlsx', 'visibility' => 'public', 'mode' => '484')) in ErrorHandler.php line 34

**Comment by quantumwebco** [comment]
So I guess this package is just not compatible with windows FTP at all then. Thanks for all your help. I really appreciate it.
