### ISSUE TITLE
Gitlab Repository API Adapter [request for addition to documention]

### ISSUE THREAD

**Issue by RoyVoetman** [thephpleague/flysystem#1049]
I created a Gitlab Storage Adapter implementing Gitlab's Repository v4 REST API.

Hereby I would like to request to add this adapter to the documentation. 

[Github page](https://github.com/RoyVoetman/Flysystem-Gitlab-storage)

**Comment by frankdejonge** [comment]
Hi, if you send a PR you can add it 👍
