### ISSUE TITLE
Is not compatible with cloudinary?

### ISSUE THREAD

**Issue by asalout** [thephpleague/flysystem#1060]
flysystem is not compatible with cloudinary?

public function upload(Request $request)
    {
        $file = $request->image;
        $fileName = $request->image->hashName();
        $ext = \File::extension($fileName);
        $fileNameFinal = str_replace('.'.$ext,'', $fileName);
        $img_name = Storage::putFileAs('shared', $file, $fileNameFinal);
        $image = Storage::url($img_name);// don't work
        //$image = Cloudinary::cloudinary_url($img_name.'.'.$ext);// I don't need to use it
        return response(['data' => $image]);
    }

**Comment by frankdejonge** [comment]
It's not clear what you're trying to do to me. What do you expect from Flysystem in this example? Seems like you're using Laravel, correct?
