### ISSUE TITLE
Uploading a zip, archive gets extracted to a folder with orginal file name

### ISSUE THREAD

**Issue by sirber** [thephpleague/flysystem#1062]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes?
| Version     | 1.0.55

#### Summary
Handling a ZIP or other archive format, using local or s3 (did not test other), a folder is created with the original file name and the archive gets copied inside it.

![image](https://user-images.githubusercontent.com/3911428/63939522-78300080-ca35-11e9-8a34-61f0eba8ab42.png)

If I upload a JSON or JPG, no issue.

#### How to reproduce
Using lumen 5.8, with simple code:

> $file = $request->file("file");
> $filename = $file->getClientOriginalName();
> Storage::put("/versions/{$filename}", $request->file);

**Comment by frankdejonge** [comment]
I highly doubt this has anything to do with Flysystem. We don't do anything to the files, let alone extract zip files. Can you verify by using Flysystem alone?

**Comment by sirber** [comment]
WIth this code:
> Storage::put("/versions/{$filename}", file_get_contents($file->getRealPath()));
![image](https://user-images.githubusercontent.com/3911428/63940539-b3333380-ca37-11e9-954a-2240c62f41be.png)

no issue :confused:

**Comment by frankdejonge** [comment]
I've checked with the following script:

```php
<?php 

include __DIR__.'/vendor/autoload.php';

$filesystem = new League\Flysystem\Filesystem(
new League\Flysystem\Adapter\Local(__DIR__)
);

var_dump($filesystem->listContents());
$handle = fopen(__DIR__.'/index.php.zip', 'r');
var_dump($filesystem->putStream('dir/zipname', $handle));
```

This worked as expected. No extraction took place.

**Comment by sirber** [comment]
It's a laravel issue, when passing a stream, laravel use the provided full path as a folder, and the hash of the file as name. dunno why...

**Comment by sirber** [comment]
that fixed it:
![image](https://user-images.githubusercontent.com/3911428/63943339-6d796980-ca3d-11e9-9d8f-55ef41070515.png)
