### ISSUE TITLE
`Local::getVisibility()` bc break in 1.0.55

### ISSUE THREAD

**Issue by LastDragon-ru** [thephpleague/flysystem#1064]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.55

#### Summary

Realization of `Local::getVisibility()` was changed in bafc949bb7f8070a32f41e2ceef0f2644948a1f6 and new realization is not compatible with previous:

- `getVisibility()` may return umask instead of `AdapterInterface::VISIBILITY_*` => in this case `FilesystemInterface::getVisibility()` will also return umask
- Files which were `public` in previous (1.0.53) version are `private` in 1.0.55 (windows/ubuntu)

#### How to reproduce

Update from `1.0.53` to `1.0.55`

![image](https://user-images.githubusercontent.com/1329824/64248509-54cbf080-cf22-11e9-81a6-6f19e06d65d7.png)

**Comment by frankdejonge** [comment]
Hi, can you show me your permission config?

**Comment by LastDragon-ru** [comment]
@frankdejonge, this is Laravel v5.8.34 app, as far I know Laravel doesn't change permission config (yet?). so probably default is used.

In debuger I see:
![image](https://user-images.githubusercontent.com/1329824/64250823-218c6000-cf28-11e9-8a4e-de259d9cc75f.png)


PS: Windows+php 7.2

**Comment by frankdejonge** [comment]
Can you please look this up?

**Comment by LastDragon-ru** [comment]
> Laravel doesn't change permission config

Permissions supported, but not set (=empty) by default:

- https://github.com/laravel/framework/blob/7ae3aaaa00f8ab9298104456a59a4154edd5c395/src/Illuminate/Filesystem/FilesystemManager.php#L154-L165
- https://github.com/laravel/laravel/blob/master/config/filesystems.php

**Comment by frankdejonge** [comment]
This can't be historically corrected.
