### ISSUE TITLE
Allow customization of the Local adapter's default permissions.

### ISSUE THREAD

**Issue by jeffturcotte** [thephpleague/flysystem#1069]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break   | no

#### Scenario

Some libraries/frameworks that use flysystem's Local adapter do not provide a means to configure the [permissions map](https://github.com/thephpleague/flysystem/blob/52b7b96809b71645942d2b04ed64c768f513fce3/src/Adapter/Local.php#L33) and typically rely on the default permissions hardcoded into the adapter class. This can be a huge pain on systems requiring masks, that for whatever reason, are different than the defaults hardcoded into flysystem. While fixing those parent projects to configure permissions per instance is the better solution, sometimes that is not possible.

#### Summary

It would be awesome if the Local adapter had a way to configure the default static permissions array. Maybe a static `League\Flysystem\Adapter\Local::setDefaultPermissionsMap(array $permissions)` method? There would be no BC break as the default permissions would stay exactly the same if not customized, and they could also still be overloaded per instance. 

I can definitely submit a pull request here, but looking for some feedback on the feature and/or implementation first.

Thanks!

**Comment by frankdejonge** [comment]
Hi, I don't like to have this style of configuration in the project. Having this configuration be different per case is a dependency injection framework concern, or a filesystem factory concern. By using either of those approached this problem does not exist anymore and is very easy to implement. If we introduce this for one aspect, this it's hard to refuse other feature request that are similar, and implementing them all does not align with the general technical direction. I hope you understand my position.

**Comment by jeffturcotte** [comment]
Fair enough. I agree with the assessment that this is better handled downstream. Craft CMS is the specific product that does not allow customization of these values. I will try to work through it with them. 

Thanks for the response!
