### ISSUE TITLE
How to write a file from php://temp without intermediate storage

### ISSUE THREAD

**Issue by kwebble** [thephpleague/flysystem#1071]
The data to store in a file is generated in a program. It is too large to fit in memory. I would like to stream this data directly to the final destination, without using a temporary file. I have tried something like this:

    $adapter = new Local('/temp/test/');
    $filesystem = new Filesystem($adapter);

    $stream = fopen('php://temp', 'w');
    $filesystem->putStream('outfile.txt', $stream);

    // Generate some test data.
    fwrite($stream, "The first line\n");
    fwrite($stream, "Line number 2\n");    

    if (is_resource($stream)) {
        fclose($stream);
    }
	
Here the `Local` adapter is used, but that will be configurable.

The result is that the output file is empty.

If the `$filesystem->putStream('outfile.txt', $stream);` is moved after the `fwrite` calls, the data is transferred. But then a temporary file is created first and that is what I would like to prevent.

Is there a possibility to do this with Flysystem?

**Comment by frankdejonge** [comment]
Hi, the order of this is incorrect, that's why the file is empty:

```php
$adapter = new Local('/temp/test/');
$filesystem = new Filesystem($adapter);

$stream = fopen('php://temp', 'w');

// Generate some test data.
fwrite($stream, "The first line\n");
fwrite($stream, "Line number 2\n");    

$filesystem->putStream('outfile.txt', $stream);

if (is_resource($stream)) {
    fclose($stream);
}
```

**Comment by kwebble** [comment]
Yes, I know that works. My question was how to prevent first doing all the `frwite`s because that will create a temporary file.

I would like to stream the data directly from memory by writing to the underlying stream and having Flysystem pass data to the final file.

**Comment by frankdejonge** [comment]
There's no way to do that. It's mostly limited by how the underlying systems are restricted.

**Comment by kwebble** [comment]
OK, good to know. Thanks.
