### ISSUE TITLE
dotx mime type maps to the docx minetype

### ISSUE THREAD

**Issue by j-snow** [thephpleague/flysystem#1080]
Version 1.0.55

In src/Util/MimeType.php the map is:
'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
it should be 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'

**Comment by frankdejonge** [comment]
PR welcome! 👍

**Comment by frankdejonge** [comment]
Also, with the PR please ad some reference so I can check this. I'm not an expert on these mimetypes.
