### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by quantumwebco** [thephpleague/flysystem#1091]
PHP 7.1.16 (and 7.3.0)
Laravel 5.3 (and 6.0)
Flysystem 1.0.57

I have posted an issue before but I never got any answers and so I'm still battling it and trying to work out, is flysystem just not compatible with windows ftp servers at all or is there something I can do to fix this issue? 

When making a call to put files to a windows filezilla 0.9.60 ftp server in laravel 5.3 (or 6.0) it throws ftp_chmod(): Command not implemented for that parameter

```$document = Storage::disk('remote')->put('/dir/filename.ext', $file, 'public');```

Previously I was told told that the server doesn't support chmod. Which would suggest that flysystem won't work with any non POSIX server i.e. windows servers. 

If I comment out lines 447 - 449 

```
if ( ! ftp_chmod($this->getConnection(), $mode, $path)) {
    return false;
}
```

Then it works fine to the windows server but is there a way to bypass this without editing core files? 

I've seen something about extending the FTP adaptor but all of the previous posts are quite old and I'm not sure if this is still necessary? 

Am I missing something or is flysystem not compatible with windows ftp servers out of the box?

Thanks for any help at all in the right direction!

**Comment by quantumwebco** [comment]
For anyone else with the chmod issue on windows, I managed to work around this issue by creating a custom adaptor and filesystem service provider, overriding the setVisibility method where the chmod exception occurs to remove the chmod call, registering the new driver in the service provider and then adding this to providers in config/app.php and setting the driver to my 'windows' in config/filesystem.php

Windows FTP adaptor
```
<?php

namespace App\Drivers;

use League\Flysystem\Adapter\Ftp as FtpAdapter;

class WindowsFTP extends FtpAdapter {
    public function setVisibility($path, $visibility)
    {
        return compact('path', 'visibility');
    }
}
```

and then creating a custom filesystem service provider

windows ftp service provider
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Storage;
use League\Flysystem\Filesystem;
use Illuminate\Filesystem\FilesystemServiceProvider;
use App\Drivers\WindowsFTP;

class WindowsFTPServiceProvider extends FilesystemServiceProvider
{
    public function boot()
    {
        Storage::extend('windows', function($app, $config)
        {
            $client = new WindowsFTP($config);

            return new Filesystem($client);
        });
    }
}
```

I'm not sure if this is the best or right way to do it but it works

**Comment by frankdejonge** [comment]
FTP is not exactly a straightforward protocol, nor is it reliable in terms of following the spec. I generally recommend just extending the functionality to fit your needs. Especially when it comes to FTP it's pretty much impossible to support them all, especially windows ones since they are very hard to test again, if at all possible. Your solution seems straight forward and effective, I'd use that myself in your situation too.

**Comment by quantumwebco** [comment]
Thanks for that @frankdejonge 

I tried to keep the solution as simple and as "Laravel" as possible. I couldn't find much information on a fix online so hopefully it can help someone else with the same issue

Do any windows servers support chmod though? I thought no windows servers support POSIX style permissions? I'm wondering if the FTP server could be set up differently to stop the chmod exception being throw?

**Comment by frankdejonge** [comment]
I honestly don't know tbh. Not a lot of people using these kinds of storage connections from what I see pass by here though, so I doubt they'll really put in the effort. Also considering they (Microsoft) has their own storage solution within Azure.

**Comment by quantumwebco** [comment]
At least there's a workaround and the client's happy now anyway. To be fair I didn't build the system and I have no idea why it has to go to a particular windows server. 

Weird thing is it used to work fine and then all of a sudden stopped working one day. I don't know if it was due to updating flysystem or another composer package or if it was software on the server etc.

I would be interested to hear if anyone else is NOT having the issue to a windows server so I can learn more about why it started erroring.

Thanks a lot @frankdejonge I appreciate your insight
