### ISSUE TITLE
Mime Type of an m3u8 file gives text/plain

### ISSUE THREAD

**Issue by Surt** [thephpleague/flysystem#1098]
### When executing `getMimeType` of an `m3u8` file 'text/plain' is returned.

The correct mimetype should be `'application/x-mpegURL'`  can it be corrected?

Maybe adding `text/plain` to the "not so sure" in_array check. 

```php
// League\Flysystem\Adapter\Local.php:322  getMimetype
if (in_array($mimetype, ['application/octet-stream', 'inode/x-empty', 'application/x-empty'])) {
```

**Comment by frankdejonge** [comment]
A PR for this is welcome 👍
