### ISSUE TITLE
Why do getSize() and getTimestamp() both just return metadata?

### ISSUE THREAD

**Issue by judgej** [thephpleague/flysystem#110]
I can't work out if there is a good reason for this, or if this is just a left-over from some earlier stuff.

In the adapters, both getSize() and getTimestamp() return the same thing: the metadata. getSize() does not return the size and getTimestamp() does not return a timestamp.

The closest guess I have of what these two methods are doing, is that getSize() for an adapter is returning all the metadata, but making sure the size field is in it, if possible.

For each file, there is some basic metadata that has no cost in fetching when looking at he file, and that is always fetched. Some other metadata items involve additional work to get, so I can understand that they may need to be asked for specially, and they will get cached against the file path, which is great. But the naming of these functions compared to what they actually do, has stumped me. I kind of hit this as a problem when writing Flickr adapters, as it kind of led me down the wrong path for a bit.

I suspect if I understood why they do what they do, I could help update the documentation. Or maybe they need a rethink?

**Comment by LostKobrakai** [comment]
I just notices the behaviour of getSize() and to be honest I'm quite baffled by this. I mean the function does tell me it's getting the size, but it doesn't return a size. If someone does need more metadata he should be using getMetadata() and not getSize(). This is super strange and unintuitive, especially as it's not even mentioned in the docs. 

I understand that changing this would be a big BC, but seriously I cannot understand why this was done in that way in the first place.

**Comment by frankdejonge** [comment]
@LostKobrakai because many filesystem operations are expensive, as much data as possible is returned from the adapters. This makes it possible to put caching in place, thus speed up many of the additional operation performed on a certain storage. For example, most cloud filesystem providers specify one call to get all the metadata. If we were only to extract that one piece of data much of the information is lost. So in case of a file browser, where you need multiple kinds of data this would cause many roundtrips over the network, which really hurts performance.

I hope this makes it a little clearer.

**Comment by LostKobrakai** [comment]
I understand that, but couldn't getSize() cache stuff and just return only the size anyways? I mean I would've never expected that call to return an array of metadata.

**Comment by frankdejonge** [comment]
@LostKobrakai well, the Filesystem class receives that response, so you never actually get that response back from the filesystem. But if you are getting that response back, it might be that you're accessing the adapter directly, which you shouldn't do. It should always be wrapped in a FilesystemInterface implementation, like the default Filesystem.

**Comment by LostKobrakai** [comment]
Ohh, then sorry for waisting your time. I'd just looked at the adapter implementation and thought this would be what I get back from the filesystem.

**Comment by frankdejonge** [comment]
@LostKobrakai no problem :)
