### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by nickcheek** [thephpleague/flysystem#1110]
### Bug Report

   ErrorException  : Invalid characters passed for attempted conversion, these have been ignored

  at /vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:576
    572|             return array_sum(str_split($part));
    573|         };
    574|
    575|         // converts to decimal number
  > 576|         return octdec(implode('', array_map($mapper, $parts)));
    577|     }
    578|
    579|     /**
    580|      * Filter out dot-directories.

  Exception trace:

  1   octdec()
      /vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:576

  2   League\Flysystem\Adapter\AbstractFtpAdapter::normalizePermissions()
      /vendor/league/flysystem-sftp/src/SftpAdapter.php:384

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | x.y.z

#### Summary

sftp is breaking after upgrading to php 7.4

#### How to reproduce

$directory = 'ShippingNotifications';
$fs = Flysystem::connection('sftp');
$contents = $fs->listContents($directory,true);

**Comment by frankdejonge** [comment]
@nickcheek what value is octdec receiving?

**Comment by nickcheek** [comment]
> @nickcheek what value is octdec receiving?

I haven't been able to reproduce the error yet.  I'll can let you know when I do.

**Comment by DuckThom** [comment]
I somehow missed this issue in my search, but I also made a bug report for this (and a PR) https://github.com/thephpleague/flysystem/issues/1113
