### ISSUE TITLE
Config class loses flexibility

### ISSUE THREAD

**Issue by kaysonwu** [thephpleague/flysystem#1112]
### Feature Request
When I need to get all the configuration back into the array, it makes things more complicated！

**Comment by frankdejonge** [comment]
Why do you need those values?

**Comment by kaysonwu** [comment]
When I encapsulate the [aliyun OSS](https://github.com/aliyun/aliyun-oss-php-sdk/blob/master/src/OSS/OssClient.php#L1048) adapter, the OSS client allows to pass an array configuration

**Comment by frankdejonge** [comment]
But why do you need it from Flysystem? Flysystem is not a configuration library. It accepts config but is not responsible for exposing it.

**Comment by kaysonwu** [comment]
I eventually want to use this adapter in laravel.  If config can return `settings` or `toArray()`, it's really convenient.

**Comment by frankdejonge** [comment]
You should use your configuration management system for that, not this library.

**Comment by kaysonwu** [comment]
Flysystem is a great library. However, due to the secondary encapsulation of config into classes and not exposing the original config acquisition method, some adapter encapsulation lost flexibility

**Comment by kaysonwu** [comment]
I am looking forward to this configuration can be passed directly, because the parameter type allowed by the oss client is an array.

```
    public function createDir($dirname, Config $config)
    {
 
        $this->client->createObjectDir($this->bucket, $this->applyPathPrefix($dirname), $config);

        return ['path' => $dirname, 'type' => 'dir'];
    }
```

**Comment by kaysonwu** [comment]
If you add the following method to the [Config](https://github.com/thephpleague/flysystem/blob/master/src/Config.php#L106) file, it will not interfere with the existing code! But it has become more flexible, right?

```
public function getSettings()
{
    return $this->settings;
}
```

**Comment by frankdejonge** [comment]
I do not want to expose this information, because I do not believe it's Flysystem's responsibility, even if it's convenient.

**Comment by kaysonwu** [comment]
What are the responsibilities of flysystem's? It is responsible for calling the adapter and passing user parameters. I don't understand why users can pass configurations as arrays. However, when flysystem's gives the adapter, it is only allowed to obtain a single configuration.

If you add the following code, what do you think?

```
/**
     * Get the setting's of all or given key's.
     *
     * @param  array|mixed|null $keys
     * @return array
     */
    public function all($keys = null)
    {
        $settings = $this->fallback instanceof Config
            ? array_merge($this->fallback->all(), $this->settings)
            : $this->settings;

        if (! $keys) {
            return $settings;
        }

        $results = [];

        foreach (is_array($keys) ? $keys : func_get_args() as $key) {
            $results[$key] = isset($settings[$key]) ? $settings[$key] : null;
        }

        return $results;
    }
```

**Comment by frankdejonge** [comment]
It's Flysystem responsibility to act upon the configuration provided, that's it. It's not supposed to be used to share configuration.

**Comment by kaysonwu** [comment]
So, unwilling to enhance it even with extra [loop](https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L503) overhead? 

I personally think it is necessary to enhance the config class, Enhance the ability to get multiple configurations instead of blindly limiting it to take out only one configuration at a time!

**Comment by frankdejonge** [comment]
You’re using strong language here. Can you clarify your usecase better? There’s already a fallback mechanism so you can already have extended configuration.

**Comment by kaysonwu** [comment]
I see the [flysystem-aws-s3-v2](https://github.com/thephpleague/flysystem-aws-s3-v2) adapter you wrote, where the [getOptionsFromConfig](https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L499) method is responsible for getting options from the configuration.

**Before enhancement**

```php
 protected function getOptionsFromConfig(Config $config)
{
        $options = [];
        foreach (static::$metaOptions as $option) {
            if (! $config->has($option)) {
                continue;
            }
            $options[$option] = $config->get($option);
}
       ...
    }
```

**After enhancement**

```php

public function only($keys) 
{
    $keys = is_array($keys) ? $keys : func_get_args();
    $settings = $this->fallback->only($keys);

    if (empty($this->settings)) {
       return $settings;
   }

    return array_merge($settings, array_intersect_key($this->settings, array_flip($keys)));
}

```

```php
 protected function getOptionsFromConfig(Config $config)
 {
        $options = $config->only(static::$metaOptions);
        ...
  }
```

The `Config` class can also add 'all', 'pull' and other practical methods.

Please forgive my love for `laravel`!
