### ISSUE TITLE
 Call to undefined method League\Flysystem\Filesystem::getPermissions() 

### ISSUE THREAD

**Issue by jswails** [thephpleague/flysystem#1115]
### Question
It appears you updated your code just 11 days ago for this file here but it appears to have broken other apps?

PHP Fatal error:  Uncaught Error: Call to undefined method League\Flysystem\Filesystem::getPermissions() 
I see there is no mention of this method now but the composer install calls this method if I  do a fresh install and follow the instructions on your website.
https://flysystem.thephpleague.com/docs/adapter/aws-s3/

Am I missing something here?

**Comment by GrahamCampbell** [comment]
Could you show the stack trace please?

**Comment by frankdejonge** [comment]
@jswails your question is very vague. Can you be a little more specific? There's no getPermissions method on the Filesystem class. The plugin functionality throws this method when you call an undefined method but there's no plugin registered to handle this call. This code has not been changed since 2017, so it's not really likely that this is causing your issue.

**Comment by frankdejonge** [comment]
I'm also not sure why you are linking to the aws-s3 adapter.

**Comment by jswails** [comment]
Sorry just got back to my home computer. here is the stack trace. It wasnt really much in there as it just failed.

PHP Fatal error:  Uncaught Error: Call to undefined method League\Flysystem\Filesystem::getPermissions() in /var/www/html/cumulusclips/cc-core/system/encode.php:55
Stack trace:
#0 {main}
Sure Frank.
Here is my code I am using the example from your website for connecting to Digital Ocean.
Not much code there at all  and it fails immediately on that call. 
I saw that you had a change to a function 12 days ago in this Repo. 

use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$adapter = new AwsS3Adapter($client, 'myDObucket');

    $filesystem = new Filesystem($adapter);
    # edit this for upload to test upload
    $uploadName = $h264FilePath;
    $uploadpath = 'testing.mp4';
    $stream = fopen($_FILES[$uploadpath]['tmp_name'], 'r+');
    $filesystem->writeStream(
        $_FILES[$uploadName]['name'],
        $stream
    );
    if (is_resource($stream)) {
        fclose($stream);
    }

**Comment by frankdejonge** [comment]
@jswails it's very unlikely that this script is causing the error. The call stack says it's called on the filesystem object from `/var/www/html/cumulusclips/cc-core/system/encode.php` at line `55` can you check what that line is?

**Comment by frankdejonge** [comment]
@jswails what versions of the packages do you have installed? I'd like to see the version of league/flysystem, league/flysystem-aws-s2-v3, and for the aws php sdk

**Comment by frankdejonge** [comment]
I've run a test script with this similar code and there's no error.

**Comment by frankdejonge** [comment]
Closing this due to lack of response.
