### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by bjora857** [thephpleague/flysystem#1118]
### Bug Report
Error when using streams and S3 on php 7.4
Works fine on php 7.3
But breaks on php 7.4

#### How to reproduce
Upload a file to s3 using fopen
```
Storage::disk('some-s3-disk');
$disk->put('test.jpg', fopen($imageUrl, "r"));

// Works fine
// $disk->put('test.jpg', file_get_contents($mageUrl));
```

<img width="769" alt="php74" src="https://user-images.githubusercontent.com/237053/71557856-4616c580-2a4c-11ea-9a35-857bced1ecad.png">

**Comment by frankdejonge** [comment]
Hi @bjora857, what's the value of the $imageUrl variable? Are you trying to upload a file by opening a URL?

**Comment by GrahamCampbell** [comment]
> $disk->put('test.jpg', file_get_contents($mageUrl));

Are you actually calling that with the typo in the variable name... That could explain why we are having an array access on "false".

**Comment by bjora857** [comment]
Yes, imageUrl. something like 
`$imageUrl = 'https://happywall-statix.imgix.net/category/hero/landscapes.jpg';`

**Comment by bjora857** [comment]
> > $disk->put('test.jpg', file_get_contents($mageUrl));
> 
> Are you actually calling that with the typo in the variable name... That could explain why we are having an array access on "false".

Sorry. That was just a typo. it should of course be $imageUrl.
The point was, that it works fine if I use file_get_contents, but fails when using fopen

**Comment by frankdejonge** [comment]
It's because PHP can't determine the size (there's no file backing it), I'll make sure it'll check for the existence of the key first. Although, I must say, this is not really what this library was intended for 🤷‍♂

**Comment by GrahamCampbell** [comment]
Maybe the stream size method should actually throw an exception on all versions, intentionally breaking this sort of usage. I'd say it was not a BC break, since a BC break is a change in the intended behaviour, not just edge cases (otherwise all bug fixes would be BC breaks).

**Comment by frankdejonge** [comment]
It's not a BC break for sure, totally agree with that. The method should be passed file handles, the fopen call on a url doesn't provide one.

**Comment by GrahamCampbell** [comment]
I'll send a PR. One sec.

**Comment by frankdejonge** [comment]
@GrahamCampbell while I agree it's not a BC break, I think supporting this is harmless. It'll just be limited in optimisation for some cases for AWS. I'm working on making the size retrieving work for this case. No PR needed.

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/flysystem/pull/1119 is what I have for now. I suppose some code can go before my throw to handle other cases, like possibly AWS, like you say.

**Comment by frankdejonge** [comment]
@GrahamCampbell I've added some remarks to the PR.

**Comment by GrahamCampbell** [comment]
Thanks. Just pulling down the repo to my machine to make the changes.

**Comment by frankdejonge** [comment]
👍

**Comment by GrahamCampbell** [comment]
Pushed. Provisionally, the tests are passing (not all of the runs completed yet).

**Comment by bjora857** [comment]
You guys are awesome. @GrahamCampbell @frankdejonge

**Comment by GrahamCampbell** [comment]
Just to be clear, your code will now not work on either version now. You need to first download the image to disk, then upload it.

**Comment by GrahamCampbell** [comment]
Oh, actually, I think it should be fine, looking at the `AwsS3Adapter` code. ;)

**Comment by frankdejonge** [comment]
I think his code will work now. It just not 100% clear how the aws sdk uploads it. Perhaps in a not very efficient manner.

**Comment by GrahamCampbell** [comment]
I did notice some minor errors in the phpdoc though: https://github.com/thephpleague/flysystem-aws-s3-v3/pull/187. ;)

**Comment by bjora857** [comment]
I can confirm my code works after the fix. 
My usecase was to upload a large image file to s3 from a url, without being restricted by the php memory limit. Anyway, I'm very happy that it got resolved in less than an hour.

**Comment by frankdejonge** [comment]
👍 @bjora857 please consider sponsoring open source authors to keep making this possible.

**Comment by GrahamCampbell** [comment]
> My usecase was to upload a large image file to s3 from a url

You could also stream the file to tmp, then stream it back into php as a resource. That way, if the file download ever fails, you don't end up with a partially uploaded file, or some other cryptic errors.
