### ISSUE TITLE
Using ftp adapter function has() dont work if file need to start escaping a character 

### ISSUE THREAD

**Issue by LuisCamelo** [thephpleague/flysystem#1124]
### Bug Report

On ftp adapter function has() return false for file that start with characters that need escape

|    Q        |   A
|------------ | ------
| Version     | 1.0.6

#### Summary

Using ftp adapter on function has() or read() if the file is by 
eg. [xpto].txt and it is inside a folder eg. imports/[xpto].txt the return will be file not found.
Problem is caused because the function has() on /league/flysystem/scr/Filesystem.php 
``` 
public function has($path)
    {
        $path = Util::normalizePath($path);

        return strlen($path) === 0 ? false : (bool) $this->getAdapter()->has($path);
    }
```
use Util::normalizePath($path) this function clean all \ and make them /

```   
 public static function normalizeRelativePath($path)
    {
        $path = str_replace('\\', '/', $path);
        $path = static::removeFunkyWhiteSpace($path);

        $parts = [];

        foreach (explode('/', $path) as $part) {
            switch ($part) {
                case '':
                case '.':
                break;

            case '..':
                if (empty($parts)) {
                    throw new LogicException(
                        'Path is outside of the defined root, path: [' . $path . ']'
                    );
                }
                array_pop($parts);
                break;

            default:
                $parts[] = $part;
                break;
            }
        }

        return implode('/', $parts);
    }
```

by doing that it cleans the escape for the first character and the ftp response will be false 

in my case we fixed it doing a change on /league/flysystem/scr/Adapter/Ftp.php
in function getMetadata($path)
where i add again the escape for my case

 ```
    public function getMetadata($path)
    {
        if ($path === '') {
            return ['type' => 'dir', 'path' => ''];
        }

        if (@ftp_chdir($this->getConnection(), $path) === true) {
            $this->setConnectionRoot();

            return ['type' => 'dir', 'path' => $path];
        }
       
        $listing = $this->ftpRawlist('-A', str_replace('[', '\\[',str_replace('*', '\\*', $path)));  //changes made here

        if (empty($listing) || in_array('total 0', $listing, true)) {
            return false;
        }

        if (preg_match('/.* not found/', $listing[0])) {
            return false;
        }

        if (preg_match('/^total [0-9]*$/', $listing[0])) {
            array_shift($listing);
        }

        return $this->normalizeObject($listing[0], '');
    }
```

anyway this is a temporary fix for the problem. 
this issue need to be solved for all the characters that need escape

**Comment by Lucifer017** [comment]
Please fix this immediately! I got the same issue.

**Comment by GrahamCampbell** [comment]
> Please fix this immediately! I got the same issue.

I assume you will be submitting a fix for this as a PR immediately then @Lucifer017?

**Comment by Lucifer017** [comment]
> I assume you will be submitting a fix for this as a PR immediately then @Lucifer017?

I mean @LuisCamelo has the fix already.

**Comment by frankdejonge** [comment]
<img width="430" alt="Screenshot 2020-02-16 at 19 57 39" src="https://user-images.githubusercontent.com/534693/74610793-9af2c600-50f6-11ea-8309-ac657143605f.png">

@Lucifer017 since you like to learn something new. Here's a word for you, it's called "entitlement". For example when you demand other people to immediately spend their free time to fix an issue you have.

**Comment by LuisCamelo** [comment]
> > I assume you will be submitting a fix for this as a PR immediately then @Lucifer017?
> 
> I mean @LuisCamelo has the fix already.

i dont have a real fix for this. I simple made a work around for my case but the issue is more complicated than it appears.
