### ISSUE TITLE
Searching files in directory

### ISSUE THREAD

**Issue by gamersalpha** [thephpleague/flysystem#1127]
Hello there, 

can make a search on directory, i got many search on many recursiv folder ?

do u have a solution to do it thanks

**Comment by frankdejonge** [comment]
Hi,

Flysystem does not support searching, since it's not compatible with the underlying filesystems. If you want to search, you can create a listing and do an in-memory search over the result to narrow down the range.

**Comment by gamersalpha** [comment]
lol
it was fast

very thanks :^)

i can use flyssytem to make my search prgrma files or it's better to not using it beacuse is slow ?

**Comment by frankdejonge** [comment]
I would advice against it. As you suggested, filesystems are quite slow. It's better to use a different way than to search on the filesystem. You can also sync the paths to a DB and search there, that will perform better.
