### ISSUE TITLE
FTP List Contents fails randomly

### ISSUE THREAD

**Issue by jekabsmilbrets** [thephpleague/flysystem#1128]
Hi, Im using Lumen v6.3.3 and flysysem that comes with it

I have an scheduled job that lists contents of ftp  and compares with local and then downloads it;

it Runs code:

```
Storage::disk('ftp')->listContents('/');
```

This error occurs randomly on local dev and on remote dev server.

```
Error: {main} {"exception":"[object] (ErrorException(code: 0): implode(): Invalid arguments passed at backend/vendor/league/flysystem/src/Adapter/Ftp.php:572)
```

Problem seems to originate from this part of code:

    
```
private function getRawExecResponseCode($command)
    {
        $response = @ftp_raw($this->connection, trim($command));

        return (int) preg_replace('/\D/', '', implode(' ', $response));
    }
```

Q: How can I get logs from FTP commands?

**Comment by frankdejonge** [comment]
@jekabsmilbrets what kind of FTP server are you talking to?

**Comment by jekabsmilbrets** [comment]
Looks like MS IIS - Reply: 220 Microsoft FTP Service;

But I installed graham-campbell/flysystem package and now I made this contraption and have not failed yet.

```
Flysystem::reconnect('ftp')
                    ->listContents('/')
```

I put it in try/catch, where it does multiple "reconnect" tries if failed and looks like it's working, but I still would like to understand why it failed.

**Comment by frankdejonge** [comment]
@jekabsmilbrets is this a long running process?

**Comment by jekabsmilbrets** [comment]
Thats an scheduled job, that runs every 15 min @ workday hours and every 1 h of workday hours and usually no more than 5 min -> max 10 min;
It fetches list of content, compares with local file list and download missing/changed and launches chains of jobs that imports new/changed files.

**Comment by frankdejonge** [comment]
That's indeed enough time for a FTP connection to drop. For now that redirect thing should work fine. For the next version there will be an improved auto-reconnect (coming soon).

**Comment by jekabsmilbrets** [comment]
Thanks for the info!

Is it somehow possible to get FTP connection/actions log's ?

**Comment by frankdejonge** [comment]
Not in V1, unless you extend it, the `connect` method is probably where you want to log stuff.
