### ISSUE TITLE
Unable to use SFTP with ECDH algorithm

### ISSUE THREAD

**Issue by apmyp1990** [thephpleague/flysystem#1130]
I am using Laravel with the newest version. I need to put a file on a sftp server, but when trying to do so following error occurs:
No compatible key exchange algorithms found.

After some investigation I figured out, that the server needs ECDH key exchange. 

How to fix this error?

**Comment by frankdejonge** [comment]
Hi, you can always inject a SFTP connection which you've provided yourself. So try using phpseclib directly to see how to establish a connection and then provide that connection for use in Flysystem should do the trick for you.

**Comment by apmyp1990** [comment]
The error occurs at phpseclib:
![image](https://user-images.githubusercontent.com/20161590/74639081-8a316700-516d-11ea-8b6f-f926abf9a6d1.png)

**Comment by frankdejonge** [comment]
Not much I can do from Flysystem's side then, sorry about that.

**Comment by apmyp1990** [comment]
I have done some research again, and found that phpseclib will be able to use sftp with ecdh in version 3, but it is still a dev branch. They have implemented following workaround https://github.com/phpseclib/phpseclib2_compat 

Is it possible to include this one in Flysystem?

**Comment by frankdejonge** [comment]
@apmyp1990 I believe you can just use that, if you add a "replaces" clause to your composer.json and add this one you should be fine.
