### ISSUE TITLE
\League\Flysystem\Adapter\Local::deleteDir does not delete directories reliably

### ISSUE THREAD

**Issue by modevelops** [thephpleague/flysystem#1135]
### Bug Report

\League\Flysystem\Adapter\Local::deleteDir does not delete directories reliably. Files are sometimes skipped during deletion, so that a directory cannot be deleted using rmdir() and a corresponding error message appears.

|    Q        |   A
|------------ | ------
| Version     | 1.0.63
| PHP-Version | 7.3.14 (Zend: 3.3.14)
| Server OS | FreeBSD 11.3-RELEASE-p5

#### Summary

It can happen that when you iterate over a RecursiveIteratorIterator object and delete files while doing so, the object changes in a way that the foreach skips files. This results in a rmdir WARNING:

"rmdir(/censored/public/theme/html) [<a href='https://secure.php.net/manual/en/function.rmdir.php'>function.rmdir.php</a>]: Directory not empty" in /censored/vendor/league/flysystem/src/Adapter/Local.php:419 (Details)
6 	File: /censored/vendor/league/flysystem/src/Adapter/Local.php:419 (Details)
	Code:
│	line 417:         unset($contents);
│	line 418:     
├─	line 419:         return rmdir($location);
│	line 420:     }
│	line 421: 
5	File: /censored/vendor/league/flysystem/src/Filesystem.php:251 (Details)
	Code:
│	line 249:         }
│	line 250: 
├─	line 251:         return (bool) $this->getAdapter()->deleteDir($dirname);
│	line 252:     }
│	line 253: 
4 ...

#### Solution

The files and directories to be deleted must first be cached in an array. I created the pull request: https://github.com/thephpleague/flysystem/pull/1136

In my old pull request https://github.com/thephpleague/flysystem/pull/1129 I forgot the `$files = [];` in the provided solution.

**Comment by modevelops** [comment]
Any update if this issue will be resolved?

**Comment by frankdejonge** [comment]
This is an issue with PHP and NAS, I suggest to extend the class for your case. For the next version, the default will be generator based, so having full instant listings is an internal detail that's incompatible with that. Since you're hitting an edge case, handling it as a one off difference is the way to go.
