### ISSUE TITLE
How to overwrite file content?

### ISSUE THREAD

**Issue by felixdorn** [thephpleague/flysystem#1138]
### How to overwrite file content?

| Version  |  1.0.64  
|------------ | ------

```php
$buffer = $this->getFilesystem()->read($path);
$this->filesystem->write($path, $buffer . $content);
```
But it throws an FileExistsException

I played with `setVisibility` but it does not change anything.
```php
$this>getFilesystem()->setVisibility($path, 'public');
```

Also, i found nothing about that on the documentation.

**Comment by frankdejonge** [comment]
Hi @felixdorn, you can use the `->put` or `->update` functions.
