### ISSUE TITLE
ftp_mkdir(): Can't create directory: File exists

### ISSUE THREAD

**Issue by akoSalman** [thephpleague/flysystem#1139]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | x.y.z

#### Summary

When creating a new directory on FTP server, this code `$listing = ftp_nlist($connection, '.') ?: [];` just gets 10,000 directories and if there is more directory in the current directory and of course if the directory that user wants to create is in not listed directories, then this line is executed `return (boolean) ftp_mkdir($connection, $directory);` and user gets below execption:
`
ftp_mkdir(): Can't create directory: File exists
`
The problem is with function `createActualDirectory` in [https://github.com/thephpleague/flysystem/blob/3e69ba5f586b4204cc6164e88bd32fec95ec538e/src/Adapter/Ftp.php#L364](Ftp.php)

I had this problem when using [this package](https://github.com/spatie/laravel-medialibrary)

#https://github.com/spatie/laravel-medialibrary/issues/1745#issue-569466378

**Comment by mravdel** [comment]
@akoSalman did you find solution? I just hit into the same issue with the same medialibrary package

**Comment by ScottyRobinson** [comment]
I have unfortunately hit the same issue with the same package.

**Comment by tovaz** [comment]
Same issue here :(
![Captura de pantalla 2023-07-24 a las 15 05 27](https://github.com/thephpleague/flysystem/assets/11469828/739498f4-c088-4565-b926-83baeb0feed5)

**Comment by hesamzakerirad** [comment]
Same issue here. Anyone managed to solve it?

**Comment by hesamzakerirad** [comment]
> Same issue here. Anyone managed to solve it?

I managed to find a way to solve it. 

I was using `Pure-FTPd` on my centos machine; and switched it to `ProFTPD`. This fixed the issue of loading only 10,000 records. The only drawback is that `ProFTPD` is a bit slower than `Pure-FTPd` which in my opinion doesn't matter.
