### ISSUE TITLE
\League\Flysystem\Adapter\Local::copy does not copy directories

### ISSUE THREAD

**Issue by flangfeldt** [thephpleague/flysystem#1140]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 1.0.63
| PHP version | 7.3.13
| Server OS | Centos 7.7.1908

#### Summary

\League\Flysystem\Adapter\Local::copy does not copy directories. The description of the API states it copies Files and Directories, but with the Local Adapter only Files are copied. See https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/#copy-files-or-directories.

#### How to reproduce

```
$fromPath = '1';
$toPath = '2';

$handle = new Filesystem(
    new Local(
        "/opt/test/",
        LOCK_EX,
        Local::DISALLOW_LINKS,
        [
            "file" => [
                "public" => 0777,
                "private" => 0700
            ],
            "dir" => [
                "public" => 0777,
                "private" => 0700,
            ]
        ]
    )
);

if (is_object($handle)) {
    try {
        if ($handle->has($fromPath)) {
            $handle->copy($fromPath, $toPath);
        }
    } catch (\Exception $ex) {
        echo $ex->getMessage();
    }
}
```

This results in the error message:

``` 
copy(): The first argument to copy() function cannot be a directory
```

**Comment by frankdejonge** [comment]
This was an error in the docs, I've corrected it.

**Comment by flangfeldt** [comment]
Ok, that's a shame. Seems like a great addition. 
Now I have to Frankenstein it outside of the Adapter. 

Thanks for the super fast response anyway.
