### ISSUE TITLE
Add to AdapterInterface

### ISSUE THREAD

**Issue by designermonkey** [thephpleague/flysystem#1142]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | possibly?

#### Scenario

When using the project, we would pass the Filesystem instance into a Repository class for example. Using that Interface we can `getAdapter` expecting an `AdapterInterface`.

All the implementations I can find a use for (`LocalAdapter`, `S3Adapter`) use the `AbstractAdapter` which has public methods on it that aren't supported by the interface.

In a proper OO world, the abstract should not implement public methods that aren't part of the interface. What I would ask for instead is that the interface implement these public methods.

My use case is simple. Our `Repository` responds to work completed based on an event listener. We don't know a piece of information in advance of this event that we need to construct the `Repository`. This info would be updated in the AdapterInterface instance using a method only available on the `AbstractAdapter`. As it's not in the interface, I can't call that method.

Example:

```php
<?php

function save(Something $something): void
{
    $adapter = $this->filesystem->getAdapter(); // instance of AdapterInterface

    // Not allowed according to OO principles
    $originalPrefix = $adapter->getPathPrefix();
    $adapter->setPathPrefix(
        sprintf('%s/%s', $originalPrefix, $something->clientIdentifier())
    );

    // more code here to save stuff

    $adapter->setPrefix($originalPrefix);
}
```

As you can see It's not possible to do the above without breaking the Liskov substitution principle.

If the response is to make the abstract's methods protected, I will still be unhappy ;)

Could it be considered to add them to the interface?

**Comment by frankdejonge** [comment]
The getAdapter methods will be removed from Flysystem alltogether in V2 and will not be added in V1 as it is a bad practice to expose the internals of an abstraction. If you need the adapter, simply depend on the adapter and use DI to get access to it. In a proper OO world, that's how you manage your dependencies.

**Comment by designermonkey** [comment]
It would be an odd approach to have to rely on DI for the adapter implementation and the filesystem class.

I'm sure there's a better way and I'll have a think.
