### ISSUE TITLE
Nested generators and iterator_to_array

### ISSUE THREAD

**Issue by kesselb** [thephpleague/flysystem#1147]
### Question

|    Q        |   A
|------------ | ------
| Version     | 2.x

I tried to migrate `thephpleague/flysystem-webdav` to 2.x and run into an issue with the [listing_contents_recursive](https://github.com/thephpleague/flysystem/blob/0d8cdd573af8b6ad2baa60e4e9ba8a48b86e9bb6/src/AdapterTestUtilities/FilesystemAdapterTestCase.php#L171-L181) test. 

```
    public function listContents(string $path, bool $deep): iterable
    {
        $response = $this->client->propFind($path, $this->properties, 1);

        foreach ($response as $itemPath => $item) {
            if ($itemPath === '/' || $itemPath === $path) {
                continue;
            }

            /** @var int|null $contentLength */
            if (isset($item[self::DAV_GETCONTENTLENGTH])) {
                $contentLength = (int)$item[self::DAV_GETCONTENTLENGTH];
            } else {
                $contentLength = null;
            }

            /** @var string|null $contentType */
            $contentType = $item[self::DAV_GETCONTENTTYPE] ?? null;

            /** @var int|null $lastModified */
            if (isset($item[self::DAV_GETLASTMODIFIED])) {
                $lastModified = strtotime($item[self::DAV_GETLASTMODIFIED]);
            } else {
                $lastModified = null;
            }

            /** @var ResourceType|null $resourceType */
            $resourceType = $item[self::DAV_RESOURCETYPE] ?? null;

            $isDirectory = ($contentType === 'httpd/unix-directory')
                || ($resourceType instanceof ResourceType && $resourceType->getValue() === '{DAV:}collection');

            if ($isDirectory) {
                yield new DirectoryAttributes($itemPath, null);
                if ($deep) {
                    yield from $this->listContents($itemPath, $deep);
                }
            } else {
                yield new FileAttributes($itemPath, $contentLength, null, $lastModified, $contentType);
            }
        }
    }
```

To fetch files and folder recursive we need to traverse the folders (using infinity depth might be easier but is not supported everywhere). 

The test fails because the keys from the inner generator overwrite the keys from the outer generator as described at https://www.php.net/manual/en/language.generators.syntax.php section "Storing into an array (e.g. with iterator_to_array())". 

Do you have any suggestion how to fix that? `$items = iterator_to_array($listing, false);` seems to work for me.

**Comment by frankdejonge** [comment]
So, this one threw me off as well at first. Inside the main package, I've worked around it by re-yielding, which unfolds generator, so you don't get overlapping indexes. Apart from that, your suggestion (passing `false`) is the only alternative that I'm aware of.

**Comment by kesselb** [comment]
>  I've worked around it by re-yielding, which unfolds generator, so you don't get overlapping indexes.

Thanks. That worked for me too.
