### ISSUE TITLE
Service Unavailable Exception for WebDAV adapter

### ISSUE THREAD

**Issue by kesselb** [thephpleague/flysystem#1148]
### Question

|    Q        |   A
|------------ | ------
| Version     | 2.x

https://github.com/kesselb/flysystem-webdav/blob/ea6e40682f7d2ca015e27ab7131aa23709af2568/WebDAVFilesystem.php#L295

A propfind request can timeout or interrupt. I would like to catch that exception and re throw a flysystem exception. 

I guess that might happen to other adapters as well. Is that something a adapter should do (adding a new exception implementing the interface) or a flysystem feature?

**Comment by frankdejonge** [comment]
Hi @kesselb,

You can look at the way the other adapters do this for inspiration. The gist of it is this; All the errors and exceptions from an adapter should be caught (or suppressed if warning), for each case, a helpful exception should be thrown. This exception should implement the `FilesystemException` interface. The provided (and documented) exceptions should be used when the operation itself fails. It's important to pass the exception leading to the final exception is passed along (other adapters do this as well), when there is no exception but an error message, the message should be passed along instead.

Does that make it clear? If not, feel free to ask follow-up questions.

**Comment by kesselb** [comment]
Thanks @frankdejonge :+1: That works for me.
