### ISSUE TITLE
rename/copy not working some regions of Digital Ocean

### ISSUE THREAD

**Issue by jupitern** [thephpleague/flysystem#1150]
### Question

|    Q        |   A
|------------ | ------
| Version     | 1.0.66

rename not working some regions (ams3 for example) Digital Oceans. copy inside rename always return false.
In an old region fra1 it works fine. Any ideia why?

**Comment by frankdejonge** [comment]
Hi, this is not really something Flysystem can fix, this is all covered in how digital ocean follows the S3 spec and how the AWS S3 client is built.

**Comment by jupitern** [comment]
Hi, thanks for the response.
