### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by TerraSkye** [thephpleague/flysystem#1151]
When i was browsing thourght the upgrade docs i fount out that 
under the heading *Writes are now deterministic*
the new methods  are called `write` and `writeStream`
yet the example below that says `writeWrite`

https://flysystem.thephpleague.com/v2/docs/advanced/upgrade-to-2.0.0/

**Comment by Lamicz** [comment]
I have a small error in this block:

- $fileExists = $filesystem->has($path); 
+ $fileExists = $filesystem->fileExist($path);

The new method is called "fileExists"

**Comment by frankdejonge** [comment]
Thanks, I fixed it.
