### ISSUE TITLE
Documentation: Aws S3 adapter says local filesystem

### ISSUE THREAD

**Issue by othercorey** [thephpleague/flysystem#1158]
This is a very minor documentation issue, but I don't know where else to mention it.

https://flysystem.thephpleague.com/v2/docs/adapter/aws-s3-v3/

The V2 Aws S3 adapter says:
>Interacting with the local filesystem through Flysystem can be done by using the League\Flysystem\AwsS3V3\AwsS3V3Adapter.

Instead of:
> Interacting with Aws S3 through Flysystem can be done by using the League\Flysystem\AwsS3V3\AwsS3V3Adapter.

**Comment by OskarStark** [comment]
Your proposal looks correct to me. Are you willing to provide a PR?

**Comment by othercorey** [comment]
Done. I didn't realize it was in the gh-pages branch.
