### ISSUE TITLE
ftp: how to get timestamp with directory listing?

### ISSUE THREAD

**Issue by michabbb** [thephpleague/flysystem#1161]
### Question

within laravel is do this: `Storage::disk('ftp')->listContents()`

and the output shows me:

```
159 => array:8 [
    "type" => "file"
    "path" => "ORDER_20-997483.xml"
    "visibility" => "public"
    "size" => 3940
    "dirname" => ""
    "basename" => "ORDER_20-997483.xml"
    "extension" => "xml"
    "filename" => "ORDER_20-997483"
  ]
```

if i set `$enableTimestampsOnUnixListings` to `true` (directly at src\Adapter\AbstractFtpAdapter.php)
i get my timestamp:

```
159 => array:9 [
    "type" => "file"
    "path" => "ORDER_20-997483.xml"
    "visibility" => "public"
    "size" => 3940
    "timestamp" => 1579172880  <------------- !!!!!!!!
    "dirname" => ""
    "basename" => "ORDER_20-997483.xml"
    "extension" => "xml"
    "filename" => "ORDER_20-997483"
  ]
```
but i have no idea howto call the function `setEnableTimestampsOnUnixListings()` from outside.

thanks for any help !!!

|    Q        |   A
|------------ | ------
| Version     | 1.0.67

**Comment by michabbb** [comment]
some timestamps are in the future:

```
158 => array:9 [
     "type" => "file"
     "path" => "ORDER_19-619187.xml"
     "visibility" => "public"
     "size" => 3944
     "timestamp" => 1608154440
     "dirname" => ""
     "basename" => "ORDER_19-619187.xml"
     "extension" => "xml"
     "filename" => "ORDER_19-619187"
   ]
```
`1608154440` => `GMT: Wednesday, 16. December 2020 21:34:00`

is this a bug ? i try to avoid reading each file individually to get the timestamp of the file, i hope there is a way to get this in only one call.

when i do manually `->getTimestamp('ORDER_19-619187.xml')` i get a correct timestamp:
`1576532044`

🤔 🤷

**Comment by michabbb** [comment]
or: is there a way to get all files ordered by:

- timestamp <-- what I need
- size
- name

???

**Comment by glensc** [comment]
how about `$adapter->setEnableTimestampsOnUnixListings(true)`?

- https://github.com/thephpleague/flysystem/blob/1.0.69/src/Adapter/AbstractFtpAdapter.php#L326

and `$adapter` I believe is what `Storage::disk('ftp')` returns

**Comment by michabbb** [comment]
@glensc thank you very much, you gave me a good hint, so instead of

`Storage::disk('ftp')->listContents()`

i have to do now:

```php
/** @var FilesystemAdapter $adapter */
$adapter        = Storage::disk('ftp');
/** @var Filesystem $driver */
$driver = $adapter->getDriver();
/** @var Ftp $ftpadapter */
$ftpadapter = $driver->getAdapter();
$ftpadapter->setEnableTimestampsOnUnixListings(true);
$remoteContents = $adapter->listContents();
```
which is not very pretty, but working. auto-completion in my phpstorm is not working,
so I used PHPDoc.

so ignoring auto-completion of my IDE:

```php
$adapter = Storage::disk('ftp');
$adapter->getDriver()->getAdapter()->setEnableTimestampsOnUnixListings(true);
$remoteContents = $adapter->listContents();
```
okay, I can live with that 😏
