### ISSUE TITLE
MountManager deprecation in v2

### ISSUE THREAD

**Issue by ganeko** [thephpleague/flysystem#1162]
### Question

|    Q        |   A
|------------ | ------
| Reviewing the version 2 documentation and the branch I see that the MountManager has disappeared. Are there plans to deprecate this class or is it just going to be a breaking change?     | –

**Comment by frankdejonge** [comment]
I've added an `@deprecated` annotation to the mountmanager. Thanks for spotting this.

**Comment by Y0lk** [comment]
So MountManager is being completely removed? Are there plans to replace it with something else?

**Comment by shirkerohit** [comment]
What will be alternative to this? anyone?

**Comment by frankdejonge** [comment]
Either build it yourself or wait until I have time for it (it's very low on my list though).

**Comment by shirkerohit** [comment]
ok. thanks!
