### ISSUE TITLE
Timestamp type missmatch

### ISSUE THREAD

**Issue by yannickroger** [thephpleague/flysystem#1166]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | NO
| Version     | x.y.z

#### Summary
First of all, thanks for this great project.

I ran into an issue, [FilesystemInterface says](https://github.com/thephpleague/flysystem/blob/1.x/src/FilesystemInterface.php#L90)  `getTimestamp()` returns a `string` while in fact, at least for the `Local` adapter, [it returns an int](https://github.com/thephpleague/flysystem/blob/1.x/src/FilesystemInterface.php#L90) .

One of them needs to be adapted.

#### How to reproduce
Trust what the Interface is saying and pass it to a strongly typed method.

**Comment by frankdejonge** [comment]
Nicely spot! It's always weird how you can overlook something like that for such a long time. I've pushed the fix to master, will soon tag the release. Thank you got raising this issue.

**Comment by yannickroger** [comment]
Thanks a lot 😄

**Comment by frankdejonge** [comment]
1.0.69 is tagged and should be available shortly

**Comment by glensc** [comment]
so this issue can be closed
