### ISSUE TITLE
Does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by valehasadli** [thephpleague/flysystem#1167]
Hello. I got a long stack trace. Which is a warning. It will not autoload anymore in Composer v2.0.

Filename and namespace don't matched. I think that it will be a problem after some period.

I'm using 
```
"laravel/framework": "^7.0",
"league/flysystem": "^1.0.8",
```

`Deprecation Notice: Class League\Flysystem\FilesystemException located in ./vendor/league/flysystem/src/FilesystemException 2.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by valehasadli** [comment]
@freekmurze could you check, please?

**Comment by frankdejonge** [comment]
@valehasadli how are you getting this exception? The package doesn't have the file the exception message describes. The file is located at https://github.com/thephpleague/flysystem/blob/1.x/src/FilesystemException.php

**Comment by GrahamCampbell** [comment]
The filename is actually `FilesystemException 2.php`. It looks like this was added manually by someone, and is not a bug in flysystem.

**Comment by GrahamCampbell** [comment]
If you delete your vendor directory and composer cache, and re-run, this definitely won't happen.
