### ISSUE TITLE
Issues with recursively listing files with the FTP adapter

### ISSUE THREAD

**Issue by simonbowen** [thephpleague/flysystem#1168]
https://github.com/thephpleague/flysystem/blob/7106f78428a344bc4f643c233a94e48795f10967/src/Adapter/Ftp.php#L495

When attempting to listContents recursively it wasn't working, I got to the bottom of it by setting recurseManually to true in my configuration. Is this expected behaviour? The condition above I would have expected to be an `||` instead of `&&`.

**Comment by frankdejonge** [comment]
Some FTP servers don't support the commands for good deep listings, so you have to do it by performing many operations instead of one. Since it's more performant to do one call, this option was introduced to allow people to force manual recursion.

**Comment by frankdejonge** [comment]
Btw, since your issue doesn't actually describe an issue. Feel free to open another issue if you still have questions.
