### ISSUE TITLE
More detailed response?  And rate limiting?

### ISSUE THREAD

**Issue by curtiscarlson** [thephpleague/flysystem#1169]
### Question

Storing files to Digital Ocean Spaces, their Documentation says the following: 

Applications should retry with exponential backoff on 503 Slow Down errors.

It is my understanding that the interface only returns a true/false response.  So there is no way to know if you received a 503 response?  Would it trigger a true or a false in this case?

Second question, DO imposes the following rate limits: 

> 750 requests (any operation) per IP address per second to all Spaces on an account
> 
> 150 PUTs, 150 DELETEs, 150 LISTs, and 240 other requests per second to any individual Space
> 
> 2 COPYs per 5 minutes on any individual object in a Space

I can enforce this in my code and will be setting it up but I was wondering if there is a config option for it I may have missed?  

I am using the S3 adapter.  

Thank you!!  

|    Q        |   A
|------------ | ------
| Version     | 1.0.69

**Comment by jasperf** [comment]
So did you ever find out about this @curtiscarlson ? Are there config options to limit requests, or perhaps combine requests or at least queue requests to avoid issues with Digital Ocean Spaces rate limiting built in?

**NB** Saw that Amazon [S3 is more generous ](https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-limit-avoid-throttling/): _You can send 3,500 PUT/COPY/POST/DELETE and 5,500 GET/HEAD requests per second per prefix in an S3 bucket. There are no limits to the number of prefixes that you can have in your bucket_

**Comment by curtiscarlson** [comment]
No, I did not. I've been focused on a different aspect of the project and can't remember what I did or how I got around it but my feeling is I either went a completely different direction or I still have this problem and simply decided to temporarily shelve it in order to stay productive.

**Comment by frankdejonge** [comment]
Hi all, this is not supported in the flysystem interface, however, you can work around this. If you implement the S3 client interface and wrap the actual S3 client with that implementation, you can intercept the exception and extract the information. It's one of the things you can do with the decorator pattern. In V2 we're handling exceptions a little nicer and will be exposing more details that way, however in V1 that's not available. So you'll need to implement the workaround.

**Comment by curtiscarlson** [comment]
@frankdejonge Can you explain in more detail what the workaround is?  And can you speak to whether a 503 would return true or false?

**Comment by frankdejonge** [comment]
The 503 would result in a `false` response.

I've created an example decorator which shows this pattern: https://gist.github.com/frankdejonge/c57f3d67852d730e44a371f4cc70cd20

You can use it like this:

```php

use AcmeCompany\Flysystem\CheckFor503S3Client;
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$client = new S3Client([
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret',
    ],
    'region' => 'your-region',
    'version' => 'latest|version',
]);

$wrappedClient = new CheckFor503S3Client($client);

$adapter = new AwsS3Adapter($wrappedClient, 'your-bucket-name', 'optional/path/prefix');

$filesystem = new Filesystem($adapter);

if ($filesystem->write('something.txt', 'contents') === false) {
  $was503 = $wrappedClient->was503();
}
```

**Comment by frankdejonge** [comment]
Given the alternative approach and the fact that more information is visible in V2, I'm closing this issue.

**Comment by jasperf** [comment]
Had one question. How would I add this decorator in Laravel PHP @frankdejonge ? Do I then still need a new Adapter like Spatie's [Flysytem Dropbox](https://github.com/spatie/flysystem-dropbox)? Would seem overkill if I only want to catch errors 503 and 504 using Digital Ocean Spaces as it is compatible with the Amazon S3 SDK. And also would then perhaps require another Spaces client package on top.. But do not see another way at the moment so was hoping there is...

**Update:**

Trying with a [copy](https://github.com/smart48/flysystem-digital-ocean) of `vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php` and renaming it to `Smart48\FlysystemDigitalOcean` and see if I can just use the clone and then some name changes and the decorator

**Comment by jasperf** [comment]
Actually if I do already have an adapter I guess I can just add the catching of 503 exceptions when `headObject`, `deleteObject` or `listObjects` lead to a 503 in https://github.com/smart48/flysystem-digital-ocean/blob/main/src/DigitalOceanAdapter.php , right? Only see `S3Exception` in main adapter (S3 clone) now..

Only then also need to see if I can use this to `throttle` or `backoff` With[ Laravel queues](https://laravel.com/docs/8.x/queues#throttling-exceptions) you can do this already. Not sure how to implement this yet either. See https://github.com/smart48/flysystem-digital-ocean/issues/1

**Comment by jasperf** [comment]
Well, I am thinking about a new Laravel service provider

```php
<?php

namespace App\Providers;

use Storage;
use App\Exceptions\CheckFor503S3Client;
use Illuminate\Support\ServiceProvider;
use Aws\S3\S3Client as S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

/**
 * Digital Ocean Spaces S3 Client extension
 * 
 * @link https://github.com/thephpleague/flysystem-aws-s3-v2/issues/18
 */
class DigitalOceanSpacesServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        Storage::extend('dospaces', function($app, $config) {
            $client = new S3Client([
                'visibility' => $config['private'],
                'key'    => $config['do_key'],
                'secret' => $config['do_secret'],
                'region' => $config['do_region'],
                'base_url' => $config['do_url'],
                'endpoint' => $config['do_endpoint'],
            ]);

            $wrappedClient = new CheckFor503S3Client($client);

            return new Filesystem(new AwsS3Adapter($wrappedClient, env('S3_BUCKET')));
        });
    }
}
```

that loads the `CheckFor503S3Client`. Seems to be a way to use the S3 adapter and wrap it so I can deal with 503 errors.
