### ISSUE TITLE
How ot move Directory to directory recurcive

### ISSUE THREAD

**Issue by ghost** [thephpleague/flysystem#117]
Hello,
how copie a full directory to another please ?

i have this 

dir/underDir1

and i want this to the final :+1: 

anotherDir/dir/underdir1

and of course move all files on the final directory ?
 a function like this :+1: 
moveDirectory($sourceDirectory,estinationDirectory);

what do u think please?

**Comment by Spholt** [comment]
For anyone coming to this late, the answer is to use:

`Filesystem:rename('path/to/old', 'path/to/new'):`

The documents are not clear that this function can actually be used for directories as well as files. Any files within your directory will also be pulled across to the new location.

Hope this helps :)
