### ISSUE TITLE
Ability to preserve timestamps

### ISSUE THREAD

**Issue by glensc** [thephpleague/flysystem#1174]
Please add a possibility to set timestamps of files when:
- copying
- moving

...files.

and perhaps just `setTimestamp()` method so userspace code could invoke it on their own.

there's [`getTimestamp()`][1] but no accompanying `setTimestamp()` method. why? if the adapter doesn't support setting such property, it could just throw NotImplementedException...

[1]: https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/#get-timestamps

**Comment by glensc** [comment]
Found accidentally from [phpcr][1] plugin footnote, that copy has `$config` argument (added in https://github.com/thephpleague/flysystem/pull/936):

[1]: https://flysystem.thephpleague.com/v1/docs/adapter/phpcr/#indicate-specific-modification-timestamp-when-writing-content

```php
        $this->fs = new MountManager ....

        $mtime = $this->fs->getTimestamp($localFile);
        $config = ['timestamp' => $mtime];
        $result = $this->fs->copy($localFile, $remoteFile, $config);
```

but the extra argument is not even documented:
- https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/#copy-files

> Copy Files
> $response = $filesystem->copy($from, $to);

and not even MountManager docs:
- https://flysystem.thephpleague.com/v1/docs/advanced/mount-manager/#specialized-calls

**Comment by glensc** [comment]
Unfortunately, target adapter I'm using (SftpAdapter) doesn't support the 'timestamp':
- https://github.com/thephpleague/flysystem-sftp/blob/1.0.22/src/SftpAdapter.php#L439

**Comment by frankdejonge** [comment]
Filesystems don't support this, so we can't add this. Could you describe your use-case, perhaps I can help you figure it out without needing this.

**Comment by glensc** [comment]
@frankdejonge there's no fancy use case. I want to move files from one dir to another. I'm using MountManager with LocalAdapter and SftpAdapter.

**Comment by glensc** [comment]
This was partially addressed in the past:
- https://github.com/thephpleague/flysystem-phpcr/pull/8
- https://github.com/thephpleague/flysystem/pull/921
- https://github.com/thephpleague/flysystem/issues/920
- ...

but this did not end well, the suggestion was to use plugin, but as he wrote plugins still do not have appropriate access to needed properties, and plugins are deprecated in 2.0

and I personally think last_modified should be treated as first citizen as is visibility property already now.

**Comment by frankdejonge** [comment]
It is not clear to me why you need to preserve the timestamp. The timestamp is always set as a result of an operation, it's not arbitrary metadata. As explained before, this is also not something that can be abstracted evenly across filesystems, so I'm closing this issue. Feel free to open up another issue with more context about why this functionality is needed. Although, I must say that conceptually I'm not a fan and I think the chances of this functionality as part of Flysystem are very slim.

**Comment by glensc** [comment]
I [explained](https://github.com/thephpleague/flysystem/issues/1174#issuecomment-646171233) why I need to preserve timestamps. Why is that so difficult to understand that timestamps are essential metadata of a file? and why is not really your concern how is this library used, I might not be allowed to disclose anything more than I'm making the backup of files.

Implementation wise, the core should first add timestamp support so plugins can add support, but that's not possible if you keep closing the issue every time somebody brings that up. even for 2.0 which should allow breaking changes to allow such new implementations.

**Comment by frankdejonge** [comment]
@glensc you can move files without preserving timestamps though. So there's nothing preventing you from doing it. So if there is an additional reason, you have not explained it. Why is it so difficult for you to understand that this is not a cross-filesystem thing? It doesn't belong in a cross-filesystem abstraction. Why you need this IS my concern because I'm the maintainer of this library, not some puppet who implements features at your request. If you are not able to explain why without disclosing information then you should work on your communication skills. I keep closing the issue because I am not convinced by your arguments.

Being talked to in this tone is not particularly motivating to grant you my time to implement your feature requests.

**Comment by glensc** [comment]
@frankdejonge you are wrong, using mountmanager to move files timestamps are not preserved. I don't understand what information do you want from me. you have not given a reason why this can't be implemented, just said that plugins don't implement, but looks to me you just don't want to implement in plugins with no reason given. what argument do you need? I need to move files from location-a to location-b, preserving timestamps. simple as that.
