### ISSUE TITLE
Local adapter not updating permissions of file

### ISSUE THREAD

**Issue by robinsonjohn** [thephpleague/flysystem#1181]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 1.0.62

#### Summary

When using the local adapter and a file already exists, changing the permissions has no effect.

#### How to reproduce

```
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

$adapter = new Local(
    'path/to/root',
    LOCK_EX,
    Local::DISALLOW_LINKS,
    [
        'file' => [
            'public' => 0744,
            'private' => 0700,
        ],
        'dir' => [
            'public' => 0755,
            'private' => 0700,
        ]
    ]
);

$filesystem = new Filesystem($adapter);
$filesystem->put('file.txt', 'Some text...', ['visibility' => 'private']);
$filesystem->put('file.txt', 'Some new text...', ['visibility' => 'public']); // File updates, but visibility remains private
```

I have not been able to reproduce this issue with other adapters, as they all seem to update the visibility along with the file.

**Comment by frankdejonge** [comment]
Hi @bayfrontmedia, I've released 1.0.70 which fixes this.

**Comment by robinsonjohn** [comment]
Fantastic! Because 1.0.70 is a pre-release, I had not noticed it existed.

Thank you.

**Comment by frankdejonge** [comment]
@bayfrontmedia just so I understand, what do you mean with pre-release? I fixed it after you posted the issue and tagged a release for this, which is the patch version 1.0.70

**Comment by robinsonjohn** [comment]
When using composer, if I have:

```
"require": {
    "league/flysystem": "^1.0"
  }
```

Version 1.0.62 is the latest version Composer will install.

**Comment by GrahamCampbell** [comment]
> Version 1.0.62 is the latest version Composer will install.

That is not the latest 1.x release, and moreover, there is no reason why composer wouldn't want to resolve the latest release (1.0.70), because both releases have the same "requirements".

**Comment by GrahamCampbell** [comment]
Ah, I think things are misleading because of GitHub's crappy new UI not showing the actual latest release, because it exists only as a tag, and not a "GitHub release":

<img width="169" alt="image" src="https://user-images.githubusercontent.com/2829600/88479909-8559b600-cf4a-11ea-94b3-1863194ba972.png">

**Comment by frankdejonge** [comment]
@GrahamCampbell TIL, thanks for the clarification
