### ISSUE TITLE
File mime type not identified

### ISSUE THREAD

**Issue by carestad** [thephpleague/flysystem#1184]
### Bug Report

Files that previously were identified as `text/plain` now just returns `NULL`. I suspect this has something to do with the switch in 1.1.0 to use `leage/mime-type-detection`, as downgrading to 1.0.69 and 1.0.70 made the detection "work" again. Either way I did not expect an API break like that when upgrading from 1.0.69 to 1.1.0.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.1.0

#### Summary

We rely on the mime type when a user wants to download a file they previously uploaded. It used to return `text/plain` in earlier versions, while the actual type reported by the `file -i <file>` command in Linux and AWS S3 is `application/octet-stream`.

All of the files I have tested so fare are fully functional and can be opened, like [the attached PDF document](https://github.com/thephpleague/flysystem/files/5062743/test-with-headers.pdf) here. However, if one were to open them in a text editor, you can see some MIME headers at the very begining of the file, which may or may not disrupt the detection (my guess). However, the PHP `finfo` method returns just the same as the linux `file -i` command.

#### How to reproduce

1. Download [attached PDF](https://github.com/thephpleague/flysystem/files/5062743/test-with-headers.pdf)
2. Include it in a project using flysystem somehow, and run `->getMimeType()` on it
3. Compare with Linux' `file -i <file>`
4. Compare with `finfo` output

**Comment by frankdejonge** [comment]
Hi, @carestad, can you check if this commit fixes it for you? https://github.com/thephpleague/flysystem/commit/86f553bcc5bb8155cb53b51cddcd80139fbc99e8 I saw the fallback to text/plain was missing there.

**Comment by carestad** [comment]
> Hi, @carestad, can you check if this commit fixes it for you? [86f553b](https://github.com/thephpleague/flysystem/commit/86f553bcc5bb8155cb53b51cddcd80139fbc99e8) I saw the fallback to text/plain was missing there.

Applying the same fix locally seems to work! :+1: I am now seeing `text/plain` where I got `null`.

**Comment by frankdejonge** [comment]
@carestad Great! I'll tag a new version.

**Comment by frankdejonge** [comment]
Version 1.1.1 is tagged, what a great version number! Thank you for your report and for verifying the fix on your end.

**Comment by carestad** [comment]
Cheers for the very quick fix!

**Comment by frankdejonge** [comment]
Oh, I forgot to say: My compliments for creating the clearest ticket on this repo (in my recollection). Wish every ticket was like this 👍
