### ISSUE TITLE
Dealing with possible resource to object conversion by PHP itself

### ISSUE THREAD

**Issue by Girgias** [thephpleague/flysystem#1186]
As this came up in https://github.com/php/php-src/pull/5987

The assertion being made in https://github.com/thephpleague/flysystem/blob/2.x/src/Filesystem.php#L141 is currently problematic for 2 reasons.

1. It only does a "dummy" resource check and therefore allows other resource, such as a mysqli resource.
2. As PHP tries to get rid of the legacy resource type, see https://github.com/php/php-tasks/issues/6, these check would fail the moment the switch is made. This is why there does not exist a ``resource`` type declaration as this would hinder this migration.

To address point 1 one must add some extra checks/handling by using something similar to ``get_resource_type() === 'stream'``.

Addressing point 2 is however harder as until the migration is done there won't be a class where one can use an instanceof check. Moreover, we don't have a timeline as to when streams will be converted and if it's done in a minor release during the PHP 8 release cycle or will be done for the PHP 9 major release.

**Comment by frankdejonge** [comment]
Thanks for the input @Girgias, I'll address the first and wait for the situation to resolve regarding the second.
