### ISSUE TITLE
flysystem dosn't work with filename that has bracket

### ISSUE THREAD

**Issue by shirejoni** [thephpleague/flysystem#1187]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.45

#### Summary

i don't know why but filesystem ftp doesn't response correct when filename has [ bracket ] in the name of file
see this code 
it is laravel code that use  thephpleague/flysystem 
```
        $storage = Storage::disk('dl_ftp');
        dd($path, $storage->exists($path));

```

Response For bot/LAIAL5878_VID_1535446403.mp3:
``` 
"bot/LAIAL5878_VID_1535446403.mp3"
true
```

Response For bot/LAIAL6220_Akbari-1399.05.23[04].mp3:
``` 
"bot/LAIAL6220_Akbari-1399.05.23[04].mp3"
false
```

**Comment by frankdejonge** [comment]
@shirejoni this is fixed in `1.1.3`.
