### ISSUE TITLE
How to download file from aws3

### ISSUE THREAD

**Issue by vanthao03596** [thephpleague/flysystem#1191]
### Question

How i can download file from aws3. I don't use any framework.
|    Q        |   A
|------------ | ------
| Version     | 1.0.62

**Comment by frankdejonge** [comment]
@vanthao03596 you can open a stream using `readStream` on the AWS filesystem, and write it using `writeStream` to the local filesystem. So you need to filesystems.

**Comment by vanthao03596** [comment]
@frankdejonge I wil try it.
Thanks for helping me.

**Comment by frankdejonge** [comment]
👍
