### ISSUE TITLE
Enable proxy SOCKSv5 on SFTP uploads

### ISSUE THREAD

**Issue by pc-magas** [thephpleague/flysystem#1193]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Scenario

As I explained to this stackoverflow issue: https://stackoverflow.com/q/63779043 sometimes sftp uploads need to be done via specific Ips for security reasons. (Eg. Tripadvisor STPF servers implement this feature) hence  automation scripts written in PHP and use leage Flysystem,  many need to use a SovksV5 or similar proxies in for connections with SFTP. 

The idea is that the machine having the allowed ip runs a Socksv5 Proxy and any script that needs to upload via sftp uses this proxy.

#### Summary

In few words I would love a method to configure a proxy connection for SFTP file adapter

**Comment by frankdejonge** [comment]
Hi @pc-magas, I think this you should open a ticket for phpseclib. We don't manage the connection handling, we use that library underneath. I think there's already an open ticket: https://github.com/phpseclib/phpseclib/issues/1117
