### ISSUE TITLE
Pattern search for file in directory Through FTP Adapter

### ISSUE THREAD

**Issue by yusrub** [thephpleague/flysystem#1194]
Hi,
can we do a pattern search for File using FTP Adapter for method listContents()

**Comment by frankdejonge** [comment]
Unfortunately, pattern search is not possible in a cross-filesystem consistent way. If you want pattern search you should implement it without using Flysystem.

**Comment by yusrub** [comment]
thanks, do you have any example which doing a pattern search in PHP?

**Comment by frankdejonge** [comment]
@yusrub you could use array_filter in combination with preg_match. The V2 API is a bit more filter friendly, but it's not out yet (Soon™).
