### ISSUE TITLE
Processing a huge text file in laravel using Filesystem API

### ISSUE THREAD

**Issue by apapilov-sc** [thephpleague/flysystem#1199]
I got a huge 500m file or even greater, i need to parse the text and insert data from the file into db.I know how to accomplish it using plain php (read line by line, or by small chunks).The question is: Is it possible to accomplish using laravel filesystem abstraction (laravel uses "thephpleague flysystem" library).Thanks!

|    Q        |   A
|------------ | ------
| Version     | x.y.z

**Comment by frankdejonge** [comment]
You can use the readStream function, I believe Laravel exposes this as well on the Disk abstraction. For laravel question, in the future please open up an issue with that repository.
