### ISSUE TITLE
Update min PHP version to 7.4

### ISSUE THREAD

**Issue by abenerd** [thephpleague/flysystem#1202]
### Feature Request
Security support for `PHP 7.2` will end in December in two month I think for `flysystemV2` we should update to a newer minimal version of PHP, I propose updating to `PHP 7.4` skipping, the `7.3` release as `7.3`s active support will also end in two months in December. 

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

#### Summary
Update minimal php version to 7.4 as older versions are not actively supported anymore.

**Comment by GrahamCampbell** [comment]
Dropping PHP 7.3 would prevent Laravel 9 from using Flysystem 2. It would have to wait until Laravel 10.

**Comment by frankdejonge** [comment]
This is not needed, I align PHP versions with the major frameworks. We'll make sure to update it more regularly, but making it more strict than the frameworks won't get us anywhere in terms of continued adoption.
