### ISSUE TITLE
Upgrading to v2 question regarding MountManager

### ISSUE THREAD

**Issue by andrei-dascalu** [thephpleague/flysystem#1203]
### Question

Hello,

Seeing how the v2 beta is progressing, we are planning an upgrade process. However, I found the guidelines a bit lacking in that for example we're using the MountManager to manage 2 filesystems (Azure Blob and local).  However, now the MountManager has a big deprecation warning and it will be removed.

However, the upgrade to v2 docs don't mention this bit at all. What will happen with the ability to manage multiple filesystems? I can imaging there are consistency challenges but even the thing abstraction of MM was helpful. Is there something to replace it?

Thanks

**Comment by frankdejonge** [comment]
Hi @andrei-dascalu,

There have been a small number of questions regarding the MountManager (3 across various platforms). Despite that small number, I'll see what I can do. Initially, it was more about reducing the maintenance on my part (less moving parts, less maintenance). I generally like interacting with two sources separately better, but there seems to be a niche need for it.

**Comment by andrei-dascalu** [comment]
Hi,

It would be great to be able to keep this bit. Otherwise the migration would be deeply painful (it's a pretty large application, which already uses an interface with an autowiring DI container). Splitting it would also beg the question as to what we can bind the implementations to (as there's a single interface we're interested in).

Thanks!

**Comment by BusterNeece** [comment]
+1 from me as a heavy user of the MountManager.

I am happy to contribute any time that is needed to help make sure MountManager is compatible with V2 as well.

**Comment by frankdejonge** [comment]
I've added back the mount manager: https://github.com/thephpleague/flysystem/blob/2.x/src/MountManager.php

**Comment by eoghanobrien** [comment]
Will you be removing the deprecation notice in 1.x?

https://github.com/thephpleague/flysystem/blob/2062a9460fc9bb9d05ce0b215176be378f29e372/src/MountManager.php#L24
