### ISSUE TITLE
We should has root dir

### ISSUE THREAD

**Issue by as247** [thephpleague/flysystem#1205]
$flysystem->has('');
$flysystem->has('.');
$flysystem->has('/');
$flysystem->has('\'); 

All return **false** and not pass to adapter to check

Eg: I have Local adapter which base dir is: /home/flysystem/root
then $flysystem->has('') should check for file_exists('/home/flysystem/root')

**Comment by frankdejonge** [comment]
Hi, that is a design flaw in V1 and is not fixable without a BC break. In V2 there is only `fileExists`.

**Comment by as247** [comment]
Can we use both V1 and V2 in same project? will they get conflict?

**Comment by frankdejonge** [comment]
@as247 it is the same package, so that will be a conflict. It's not possible to install two versions in one project.
