### ISSUE TITLE
Avoid misleading FileNotFoundException messages

### ISSUE THREAD

**Issue by MikeHopley** [thephpleague/flysystem#1207]
### Feature Request

When a file is not found, the error message can be incorrect / misleading. This happens because the $path variable used in the error message is not the same as the $location that is checked in the adaptor, which adds a prefix. The prefix is not reflected in the error message.

This is very confusing. The error message should show the actual path that was checked, so that users can debug in a sane way.

|    Q        |   A
|------------ | ------
| New Feature | no, I think (?)
| BC Break    | no, I think (?)

#### Scenario

I'm using Laravel to download a file, like this:

```PHP
$file = storage_path('/app/samples/invoice.pdf');

return Storage::download($file);
```

This gives the following error:

```
League\Flysystem\FileNotFoundException
File not found at path: C:/LaravelProjectFolder/storage/app/samples/invoice.pdf
```

The error message is extremely misleading, because the file **does** exist at that location.

In this case I am using the Local disk. If I dig into the Local adaptor, I can see why the error is wrong:

```PHP
// vendor/league/flysystem/src/Adaptor/Local.php

public function has($path)
{
	$location = $this->applyPathPrefix($path);

	return file_exists($location);
}
```

By dumping the $location variable, I see what path is actually being checked:

```
"C:\LaravelProjectFolder\storage\app\C:/LaravelProjectFolder/storage/app/samples/invoice.pdf"
```

**This** is what the error message should tell me. If the error message were correct, I could immediately see that the prefix is being applied twice, and correct my code:

```PHP
return Storage::download('samples/invoice.pdf');
```

#### Summary

The FileNotFoundException error message should show the full path that was actually checked, including the prefix.

**Comment by frankdejonge** [comment]
This would force a breaking change because the responsibility for the file collision needs to be delegated to the adapter. So this cannot be part of V1. For V2 this mechanism is removed entirely since writes are deterministic there, meaning overwrite by default and failing causes exception at the adapter level.

Long story short, for v1 this is not possible, for v2 it is already done. RC's are going to be tagged soon.

**Comment by MikeHopley** [comment]
Thanks, good to know this excellent package continues to improve. =)
