### ISSUE TITLE
Support PSR-7 StreamInterface

### ISSUE THREAD

**Issue by tadasaa** [thephpleague/flysystem#1208]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Scenario

Files returned as `Psr\StreamInterface` should be supported for upload via specific adapters. Currently, all stream related methods in `League\Flysystem\Filesystem` class validate that streams are of basic php type `resource`, and StreamInterface is not supported. 
The s3 adapter already supports it, so I think other adapters and other places that work with streams/resources should support it as well. I would be willing to provide a PR.

How does that sound?

**Comment by frankdejonge** [comment]
Hi @tadasauciunas,

If you have a PSR stream instance, you can do the following:

```php
$filesystem->writeStream($path, $psrStream->detach());
```

For AWS it makes sense, since it's used by the transport mechanism transport mechanism it depends on directory. For Flysystem, HTTP concerns are not in scope so I stick with the basic types for streams (resources).

**Comment by tadasaa** [comment]
Thanks, completely missed that method.

**Comment by frankdejonge** [comment]
👍 all good
