### ISSUE TITLE
Problem with FTP connection from server

### ISSUE THREAD

**Issue by spaantje** [thephpleague/flysystem#1210]
### Question

Hi, i'm using the Storage/File system in Laravel to connect to an external FTP server. 
This is using this package if i'm not mistaken. 

But now i cannot connect to the external FTP server from the production server (hosted on Forge) but it's working locally. 
The server in question is not under my control. And i already ask the party in question if they could check it on their end, but they say the settings are correct. 

I have the following config in my `filesystems.php`:

```php
 'external-ftp' => [
        'driver'        => 'ftp',
        'host'          => env('FTP_HOST'),
        'port'          => env('FTP_PORT', 21),
        'username'      => env('FTP_USERNAME'),
        'password'      => env('FTP_PASSWORD'),
        'root'          => env('FTP_ROOT', '/'),
        'timeout'       => env('FTP_TIMEOUT', 10),
        'passive' => false,
 ],
```

When i'm running the following on local: `Storage::disk('external-ftp')->directories();` i get a response with directories. 
But when i run the same on the (Forge) server I get the following response: `[]` (so an empty array). 

I'm not totally sure what is wrong and where i should look. Could this be a server configuration on the Forge server?
Is there a way to enable/view some more logging about the connection? 

If this is not the right place for this question please let me know! 

|    Q        |   A
|------------ | ------
| league/commonmark | v1.3.3
| league/flysystem | v1.0.66    
| league/flysystem-sftp | v1.0.22  (I also have this one installed because of another SFTP connection). 
| laravel/framework | v7.4.0

Thanks for any help! 

Kind regards,
Sonny

**Comment by frankdejonge** [comment]
Hi @spaantje,

Can you share any error messages or relevant logs that provide some information into what is happening? Are you using the same credentials as you're using locally? Is the FTP server you're talking to locally the same as production?

My guess is that, while it's both FTP, either the configuration, or the type of FTP server is different. Another thing that can cause listing entries to disappear is when the listing doesn't match the prefix (including the path prefix). This causes entries to be filtered out. Perhaps this gives you some handles to look into it further.

**Comment by spaantje** [comment]
Hi @frankdejonge,

Sadly i don't have any error log because i don't get any errors (thats the weird thing) but i just get an "empty" response on production. If i can enable some more logging some way when doing a request i can provide those (is this possible)?

I'm using the same credentials to connect to the FTP server on local and production. 
And i'm connecting to the same FTP server from production and local. 
There is no prefix/root directory configured on production/local (instead of the / in de config). 
(Only Host, Username and Password are configured in de .env on both local and production and using the same on both).

Local machine is a Mac production is a Linux (forge) server. Maybe there is a difference between both?

**Comment by frankdejonge** [comment]
Hi @spaantje,

Unfortunately, there is not a lot for me to go by. All the tests run on Linux, and those pass. What you could do is add some debugging statements in the vendor code so get some more insights. Flysystem does not provide internal logging. It has to be some server configuration but it's impossible for me to know what's causing this. Sorry.

**Comment by spaantje** [comment]
Hi @frankdejonge ,

Understandable, I will look into adding some debugging. 
Any tips on where to start? 
Maybe listDirectoryContents in League\Flysystem\Adapter\Ftp  ?

**Comment by spaantje** [comment]
It looks like it's failing on the ftp_rawlist command. 

**Local:**
```php
php artisan tinker 
// 
>>> $connection = ftp_connect($host, '21', '90');
=> FTP Buffer resource #888
>>> $isLoggedIn = ftp_login($connection, $username, $password);
=> true
>>> $type       = ftp_systype($connection);
=> "UNIX"
>>> $help       = ftp_raw($connection, 'HELP');
=> [
     "214-The following commands are recognized:",
     "   ABOR   ADAT   ALLO   APPE   AUTH   CDUP   CLNT   CWD ",
     "   DELE   EPRT   EPSV   FEAT   HASH   HELP   LIST   MDTM",
     "   MFMT   MKD    MLSD   MLST   MODE   NLST   NOOP   NOP ",
     "   OPTS   PASS   PASV   PBSZ   PORT   PROT   PWD    QUIT",
     "   REST   RETR   RMD    RNFR   RNTO   SITE   SIZE   STOR",
     "   STRU   SYST   TYPE   USER   XCUP   XCWD   XMKD   XPWD",
     "   XRMD",
     "214 Have a nice day.",
   ]
>>> $list       = ftp_rawlist($connection, '/');
=> [
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-19",
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-21",
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-22",
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-23",
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-24",
     "drwxr-xr-x 1 ftp ftp              0 Aug 26  2020 2019-10-25",
// etc
```

**Production:** 
```php
php artisan tinker 
// 
>>> $connection = ftp_connect($host, '21', '90');
=> FTP Buffer resource #886
>>> $isLoggedIn = ftp_login($connection, $username, $password);
=> true
>>> $type       = ftp_systype($connection);
=> "UNIX"
>>> $help       = ftp_raw($connection, 'HELP');
=> [
     "214-The following commands are recognized:",
     "   ABOR   ADAT   ALLO   APPE   AUTH   CDUP   CLNT   CWD ",
     "   DELE   EPRT   EPSV   FEAT   HASH   HELP   LIST   MDTM",
     "   MFMT   MKD    MLSD   MLST   MODE   NLST   NOOP   NOP ",
     "   OPTS   PASS   PASV   PBSZ   PORT   PROT   PWD    QUIT",
     "   REST   RETR   RMD    RNFR   RNTO   SITE   SIZE   STOR",
     "   STRU   SYST   TYPE   USER   XCUP   XCWD   XMKD   XPWD",
     "   XRMD",
     "214 Have a nice day.",
   ]
>>> $list       = ftp_rawlist($connection, '/');
=> false
```

I have e-mailed the party which is hosting the FTP server to recheck their logs.. 
But if you have any idea's which i could check, please let me know.

**Comment by spaantje** [comment]
Ok. Another update.

When i add a firewall rule in forge to allow all access from ports 1024:65535 than it's working. (adding the IP to restrict access doesn't work for now.). 

So it's looking like it's a firewall issue.

**Comment by frankdejonge** [comment]
@spaantje I hope you were able to resolve your issue. Any update on this? I think we can close the issue since it's a server configuration problem, not a Flysystem issue. Is that ok?

**Comment by spaantje** [comment]
@frankdejonge , Yes offcourse. Thanks for the help.
