### ISSUE TITLE
Getting Error : Allowed memory size exhausted 

### ISSUE THREAD

**Issue by ratnesh-gupta** [thephpleague/flysystem#1212]
### Question

Larvel 6.x
PHP 7.3.X
flysystem-aws-s3-v3 1.0.25

I am getting below, not sure why am getting this. Trying in other environment its working fine.

**Unhandled error**
Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)
**Location**
vendor/league/flysystem/src/Util/ContentListingFormatter.php:54

Need urgent help on this.
Thanks in advance

**Comment by frankdejonge** [comment]
Hi, unfortunately this is not solvable in V1, and V2 already has this solved. You should increase the memory of your PHP configuration to prevent this error. The listing is too big and you're running out of memory.

**Comment by ratnesh-gupta** [comment]
Thanks @frankdejonge . Sure will try as per your suggestion.
Closing this Ticket for now.
