### ISSUE TITLE
ZIP Adapter

### ISSUE THREAD

**Issue by Lctrs** [thephpleague/flysystem#1218]
### Question

Hi.

I have ported the ZIP Adapter to Flysystem V2. Tests run fine locally. I would like to open source it but I'm not sure how. There are 3 options available for me : 

- Including it in this package
- Updating https://github.com/thephpleague/flysystem-ziparchive
- Make my own package

Which one do you prefer ? All options suit me.

**Comment by frankdejonge** [comment]
Hi! A PR for this would be much appreciated 👍 I can then make sure to get it hooked up in the regular release cycle.

**Comment by frankdejonge** [comment]
I publish subsplits from this repo, so it'll end up in the repo you linked to, but the maintenance can be done in this repository.

**Comment by Lctrs** [comment]
Thanks for the input ! PR will land later today.
