### ISSUE TITLE
AsyncAws adapter

### ISSUE THREAD

**Issue by Nyholm** [thephpleague/flysystem#1220]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Summary

For the past few months I've been maintaining an adapter for AsyncAws S3. I've been following the development since beta 1. I notice that it is very similar to the AWS S3 adapter. 

In a very humble request, should I add the AsyncAws S3 adapter under the Flysystem namespace?

**Comment by frankdejonge** [comment]
Hi @Nyholm,

That sounds like a good idea. What did you have in mind in terms of organization and collaboration?

**Comment by Nyholm** [comment]
I believe that I have a good knowledge of AWS API and both SDKs, I also know quite some implementation details of Flysystem. 

I dont want to dump 500 lines of code + test for you to maintain. I would be glad to help out, specifically on the both AWS adapters.

**Comment by frankdejonge** [comment]
@Nyholm are we on a common slack channel perhaps? We can discuss some details.
