### ISSUE TITLE
Gitlab Adapter unable to read file with spaces.

### ISSUE THREAD

**Issue by martynball** [thephpleague/flysystem#1230]
### Bug Report

Attempting to read a file using the Gitlab Adapter, when encountering a file which contains spaces, the exact path: 

```
css-src/less/promo-reviews (iMacs-iMac.local's conflicted copy 2019-02-05).less
```

This is how i'm reading the file:
```
$client = new Client(GIT_ACCESS_TOKEN, 34, GIT_BRANCH, GIT_BASE_URL);
$this->filesystems['remote'] = new Filesystem(new GitlabAdapter($client));

$content = $this->filesystems['remote']->read($file['path']);
```

### Error
> File not found at path: css-src/less/promo-reviews (iMacs-iMac.local's conflicted copy 2019-02-05).less

**Comment by frankdejonge** [comment]
Hi @martynball,

I do not maintain the gitlab adapter. Please open an issue with the corresponding repository.
