### ISSUE TITLE
How to move folder ?

### ISSUE THREAD

**Issue by elvispdosreis** [thephpleague/flysystem#1233]
### Question

I need to move a few hundred files to digital ocean but the process is very slow is there any function or some way to send entire folders

I'm using Space from Digital Ocean

```
$adapterS3 = new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, 'seller-x');
$filesystem = new \League\Flysystem\Filesystem($adapterS3);
$files = $this->glob_recursive(ROOT_PATH . "/www/images/product/" . '*{.jpeg,.jpg,.gif,.webp}', GLOB_BRACE);

foreach ($files as $file){
        $dest = str_replace('\\', '/', $file);
        $dest = preg_replace('/.+?(?=\/images.*)/m', '', $dest);
        $filesystem->put($dest, $file, ['visibility' => 'public']);
}
```

**Comment by gamersalpha** [comment]
hé hé i got the same issue, move files with FLystem is very slow, u can do nothing

he works like that

**Comment by frankdejonge** [comment]
@elvispdosreis unfortunately there is not, S3 is a linea (non-hierarchical) filesystem that does not allow for this.
