### ISSUE TITLE
Class 'League\Flysystem\Adapter\Local' not found {"exception":"[object]

### ISSUE THREAD

**Issue by hellogirls** [thephpleague/flysystem#1239]
### Bug Report

Class 'League\Flysystem\Adapter\Local' not found {"exception":"[object]

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.y.z

#### Summary

There is no more the directory Adapter, So lead to the error "League\Flysystem\Adapter\Local" in lack of Adapter directory.

#### How to reproduce
So Adapter directory code is include  in other package?

**Comment by frankdejonge** [comment]
Hi @hellogirls,

For V2 the package structure was altered, the local adapter is now located at `League\Flysystem\Local\LocalFilesystemAdapter`.

For all the other options, view: https://flysystem.thephpleague.com/v2/docs/adapter/local/
