### ISSUE TITLE
Missing some BC changes in the upgrate to version 2 docs

### ISSUE THREAD

**Issue by wshafer** [thephpleague/flysystem#1243]
### Bug Report
Congrats on the V2 release.  Looks a lot cleaner now.  Great job!

I did however want to report some missing topics in the [Upgrade to 2.0.0](https://flysystem.thephpleague.com/v2/docs/advanced/upgrade-to-2.0.0/) docs.

Adaptors constructors have changed.  No need to go into the details but a quick note that we'll need to update how we construct the adaptor would be nice.

Caching seems to have been removed.  Unless I'm missing something it seems this is no longer supported.  Should be noted somewhere since it was supported in V1.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2

**Comment by Lustmored** [comment]
To glue a gap with cache storage I've created a custom adapter that is lighter on memory yet helpful when you need to access metadata frequently:

https://packagist.org/packages/lustmored/flysystem-v2-simple-cache-adapter

**Comment by frankdejonge** [comment]
I've added this in the upgrade docs as notes. For more docs, feel free to open a PR 👍
