### ISSUE TITLE
Sftp adapter and phpseclib

### ISSUE THREAD

**Issue by wilcol** [thephpleague/flysystem#1248]
Hi there!

First of all. Thank you so much for the efforts of creating and maintaining this module!

I recently switched from v1 to v2 and I'm using the SFTP adapter. The situation is as follows:

When I use `"league/flysystem-sftp": "^2.0"`, it installs both `"league/flysystem"` and `"league/flysystem-sftp"` since `"league/flysystem-sftp"` has a dependency on `"league/flysystem"`. Both package contain the `SftpAdapter` with the same namespace, so this raises 'Ambigious class resolution' warnings by PHP when instantiating this class (and other classes from that package)

When I use `"league/flysystem": "^2.0"` instead of `"league/flysystem-sftp": "^2.0"`, the sftp connections fail because `"league/flysystem"` has no dependency on `"phpseclib/phpseclib": "^2.0"`(which `"league/flysystem-sftp"` does have) because of a missing class from the `"phpseclib/phpseclib""` module.

My solution now is to include `"phpseclib/phpseclib""` next to the `"league/flysystem"` dependency. This works. My composer.json looks like:
`"league/flysystem": "^2.0",
"phpseclib/phpseclib": "^2.0"`

Wouldn't it make sense to add a dependency on `"phpseclib/phpseclib""` within `"league/flysystem"`, or remove the Sftp (and other `"phpseclib/phpseclib""` dependent) stuff from the `"league/flysystem"` module? There is no  mention in the documentation, so following it results in errors right now. Thanks!

**Comment by frankdejonge** [comment]
Hi @wilcol,

I'm guessing I messed up a gitattributes export for this, since that class should not be shipped by default. I'll look into this.

**Comment by wilcol** [comment]
Great, thanks @frankdejonge

**Comment by frankdejonge** [comment]
@wilcol I messed up the casing ... sorry about that, I'll release a fix asap.

**Comment by wilcol** [comment]
Thanks for the swift response!

**Comment by frankdejonge** [comment]
@wilcol it's fixed now in `2.0.1`, when checking the artefact I found another (FTP vs Ftp) which is fixed in `2.0.2`. Thank you for reporting this 👍
