### ISSUE TITLE
MountManager for v2

### ISSUE THREAD

**Issue by EvgenyBarinov** [thephpleague/flysystem#1250]
Could you make MountManager more flexible for v2?
Proposed ways:
1. Convert private methods to protected to allow extending and modification
2. Optimize MountManager
- add public methods to 
  -  mount (add) fileSystem
  - check filesystem exists by key

As I can see it was available in v1 but in v2 it was cut...

**Comment by OskarStark** [comment]
Could you please elaborate a bit on your use case? Thanks

**Comment by EvgenyBarinov** [comment]
I've need to prepare lib to build required fileSystems list by provided configuration (for Spiral framework)
At one point of view it will be more comfortable to build MountManager and add all required fileSystems one by one to existing MountManager.
From another point of view I can use it at initialization step with creating MountManager from builded fileSystems list.

I tend to think that first way is more preferable for me.
In current implementation (with private method) MountManager class can be useless for users despite the fact it is very powerful helper in system with several file systems.

For example I would like to prepare some specific handling for copying files from one fileSystem to another. MountManager has all required functionality and I would like to extend it with my specific manager and prepare required functionality.
But I can't do it in current implementation - private methods forbid it for me...

P.S. I am at investigation stage and prepare some basic architecture for this lib.

**Comment by EvgenyBarinov** [comment]
@OskarStark is it really required to keep all methods of MountManager with private access?
As I can see private in libs is not the best solution...

No developer can take into account any scenario of usage which can be actual for another developer.

**Comment by EvgenyBarinov** [comment]
One more example of usage.
When you are using some bootloaders and DI you need to pass MountManager in boot method as argument but your current implementation blocks this method by the reason init filesystems provided only via constructor - it is not applicable in this case. In this case I need some public method for init server

**Comment by EvgenyBarinov** [comment]
Basic example you can find here
https://github.com/thephpleague/flysystem/pull/1263

I am not sure what kind of problem with ftp tests...

**Comment by Eugentis** [comment]
I've created custom implementation like MountManager
Please close the issue
