### ISSUE TITLE
Fetching meta data in V2

### ISSUE THREAD

**Issue by andris-sevcenko** [thephpleague/flysystem#1255]
### Question

I'm in the process of converting our application of V1 to V2 and it seems that fetching metadata is now quite inefficient, if data items are fetched one by one - at a glance, it seems that for the AWS S3 adapter fetching date modified, filesize and mime-type would produce three requests.

I thought maybe it would be possible to just list exactly the needed file by specifying the path, however, that's not really an option, as `$filesystem->listContent()` (correctly) expect the path to be a directory.

Obviously, there's the chance that I've missed something obvious - it would not be the first time.

**Comment by andris-sevcenko** [comment]
After actually looking at other adapters, it makes more sense to me, since other storage methods might not have the capability of returning all that data at the same time, so fetching all the metadata would actually incur a penalty there.

I guess the best case in my scenario would be, for the storage methods that do support fetching all the metadata at the same time, to provide my own adapter class that extends the base class and adds some per-request caching in-between, to avoid multiple external calls.

I will now see myself out. Thank you.

**Comment by tsmgeek** [comment]
This can be handled by just having an generic return of metadata, where an adapter does not support it then show null, but if it does support then it will be either false or populated with result.
This is far better than current way of multiple requests IMO.
