### ISSUE TITLE
Docs fix?

### ISSUE THREAD

**Issue by EvgenyBarinov** [thephpleague/flysystem#1258]
In flysystem docs it was detected wrong adapter class for advanced usage.
Please check 
- https://flysystem.thephpleague.com/v2/docs/adapter/aws-s3-v3/
`$adapter = new League\Flysystem\AwsS3V3\AwsS3V3Filesystem(...`
=>
`$adapter= new League\Flysystem\AwsS3V3\AwsS3V3Adapter(...`
- https://flysystem.thephpleague.com/v2/docs/adapter/async-aws-s3/
`$adapter = new League\Flysystem\AwsS3V3\AwsS3V3Filesystem(...`
=>
`$adapter= new League\Flysystem\AsyncAwsS3\AsyncAwsS3Adapter(...`

**Comment by Nyholm** [comment]
Thank you. I've added https://github.com/thephpleague/flysystem/pull/1269. 

I dont find any issue on https://flysystem.thephpleague.com/v2/docs/adapter/async-aws-s3/, could you help me?

**Comment by Eugentis** [comment]
@Nyholm As I can see it was fixed [here](https://github.com/thephpleague/flysystem/commit/6bfa0600111d5557a83d1f2d8399cf2d10ebd487)

Thanks!
