### ISSUE TITLE
Feature Request: Stream wrappers

### ISSUE THREAD

**Issue by kingcrunch** [thephpleague/flysystem#126]
Pointing to a tweet: https://twitter.com/auroraeosrose/status/453282082492788738

So it would pretty cool, if I could use something like

``` php
file_put_contents('images://foo/bar.png', $imageData);
```

Also it would (should...) allow me to use Flysystem with existing libraries, that expect an URI-formed path as parameter

**Comment by twistor** [comment]
https://github.com/twistor/flysystem-stream-wrapper/

Spamming your issue queue to garner some interest.
