### ISSUE TITLE
phpseclib3 for the sftp adapter

### ISSUE THREAD

**Issue by stof** [thephpleague/flysystem#1261]
### Question

Is there any plan to update `league/flysystem-sftp` to use phpseclib3 instead of phpseclib 2, so that it supports newer crypto algorithms ? See also https://github.com/thephpleague/flysystem-sftp/issues/111 and https://github.com/thephpleague/flysystem-sftp/issues/110 but I figured out that the 2.x branch of `league/flysystem-sftp` is actually a subtree split from here so I'm bringing it here.

Also, the namespace for the class in v2 includes `PhpseclibV2` so I don't see what the plan could be when migrating to v3

**Comment by IonBazan** [comment]
@stof We could use https://github.com/phpseclib/phpseclib2_compat to maintain compatibility with both.

**Comment by Nyholm** [comment]
There is a PR starting to add a PhpseclibV3 for Flysystem 2

https://github.com/thephpleague/flysystem/pull/1257

**Comment by stof** [comment]
this issue is still relevant, as the PR is still in progress

**Comment by lupo112** [comment]
any progress? i have the same problem with server host key

**Comment by frankdejonge** [comment]
I've merged the PR for this. Interested people can try the v3 variant here: https://packagist.org/packages/league/flysystem-sftp-v3

**Comment by frankdejonge** [comment]
Any feedback on this before I tag an stable version?

**Comment by hbraehne** [comment]
I just upgraded a rather large application from flysystem-sftp to flysystem-sftp-v3 to gain support for DSA keys. In our dev and staging environment everything seems to work as expected. Are there any plans to release a stable version soon?

**Comment by VladimirCyberDev** [comment]
I tried v3 today, haven't noticed any issue, seem to be working as expected.
