### ISSUE TITLE
Unable to set root `/`

### ISSUE THREAD

**Issue by sopptik** [thephpleague/flysystem#1264]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.2

#### Summary

Unable to set root '/'

#### How to reproduce

Set root '/' and try to upload file to some storage e.g. "/home/user/upload". The first slash is removed and is unable to upload anything because the result path looks like "home/user/upload"

**Comment by Nyholm** [comment]
Thank you for this issue and PR. 

What if you used prefix `''`?

**Comment by sopptik** [comment]
It' the same now. If you use '' or '/' the result is '' because of `rtrim`. I need the '/' as a root because the root is used as prefix for the path. But the  PathPrefixer is used here https://github.com/thephpleague/flysystem-sftp/blob/dcd572ecd536d863498671dab18c5014ac26905f/SftpAdapter.php#L57 . Path is cleaned on the left side and root is empty string. The result is 'xxx/example.txt' but should be '/xxx/example.txt'
