### ISSUE TITLE
Use php tmpfile instead of php://temp in ftp

### ISSUE THREAD

**Issue by aliakbarazizi** [thephpleague/flysystem#1267]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Scenario / Use-case

If I want to copy file from ftp to local, I have to call readStream (instead of read because of the memory usage)
In this case I can use other function like `stream_copy_to_stream` to copy stream to local file.
But in somecase It maybe needed to pass `path` of the file instead of stream.

So I have to copy from `php://temp` to a temporarily file and use the file path.

The whole problem is because of `php://temp` has no filepath.

But with `tmpfile` function I can get file path with `stream_get_meta_data($temp)['uri']` and there is no need for second temp file.

#### Summary

Change `$stream = fopen('php://temp', 'w+b');` to `$stream = tmpfile()` in https://github.com/thephpleague/flysystem/blob/508d42c9e3553223a74da1cd1727c49884c726cb/src/Ftp/FtpAdapter.php#L186

Because in some case the stream file path is important

**Comment by Nyholm** [comment]
Hey. Thank you for this issue. 

Using `php://temp` is great for performance. For small files it uses memory and for large files it automatically switches to a file.

The `readStream` method will return a stream. The contract will not specify if that stream is stored in memory or on file. I think `stream_get_meta_data($temp)['uri']` will return a good value if the file is larger than a few megabytes (there is a php.ini setting for this). 

If you have a small file and you need a path, the workaround is (as you says) to dump the file to disk yourself.

**Comment by aliakbarazizi** [comment]
> I think `stream_get_meta_data($temp)['uri']` will return a good value if the file is larger than a few megabytes (there is a php.ini setting for this).

The problem is this is not true, it return php://temp all the time
So in my case, creating two stream and use temporary file has bad performance

**Comment by Nyholm** [comment]
Please see php://temp in the manual: https://www.php.net/manual/en/wrappers.php.php

**Comment by aliakbarazizi** [comment]
@Nyholm Can we add switch in constructor for that? Like a callback function to create resource

I read the full documents, there isn't anyway to get file path

**Comment by aliakbarazizi** [comment]
I can't even override the `readStream` because the `prefixer` and `connectionOptions;` is private.
So if its not possible to change this behavior can we at least make this fields protected?

**Comment by Nyholm** [comment]
I really really don't see the point. This is all because you "sometimes" have to copy a stream to a file. 

I'm not sure if you making the argument that you want to do this because it is convenient for you or if it is because of performance. 

I can only assume it is because you think it is less performant, but I'm not sure that is true..

**Comment by aliakbarazizi** [comment]
I agree with you, But all fields in the library are private, So if I want to override some method I can't.

You are right, it's for me and not about performance. Can we change `private` properties to `protected`?

**Comment by aliakbarazizi** [comment]
I'm not talking about performance, but I think this case is not happened "sometimes"

As you know the FTP driver lack reading to local file ( not just temp file )
(Currently, the best way to do this is to open another stream and copy from one stream to other)


This isn't sometimes. right now the `readStream` is good only for `stream` usage, for example, if you want to use stream to show it to the end-user.  For other types of usage ( create a local copy of a file, process the file with other library or shell command ) has a lack of performance.

If these changes happened, the user can rename the temp file to creating a local copy, or can use `path` of the file for other libraries

So I totally disagree with the word "sometime"

**Comment by Nyholm** [comment]
> But in somecase It maybe needed to pass path of the file instead of stream.

¯\_(ツ)_/¯ 

> Can we change private properties to protected?

You should use compensation over inheritance. 

> As you know the FTP driver lack reading to local file

A generic library cannot assume that it can write to the file system. 


> The usage of stream is for performance, so if you want for example to read a huge file and save it locally, the only way is to use two streams and copy from temp to a new stream.

Please create a small script that shows how much performance benefit we are talking about.

**Comment by aliakbarazizi** [comment]
> You should use compensation over inheritance.

What is compensation? are you mean composition?

> A generic library cannot assume that it can write to the file system.

As you say you do it anyway, If you want to follow this rule read you should use `php://memory` instead of `php://temp`,
For large files ( default more than 2MB ) this library breaks this rule.

> Please create a small script that shows how much performance benefit we are talking about.

```
$temp = fopen('test-local', 'a+');
stream_copy_to_stream($this->readStream($fullName), $temp);
```

We are talking about the performance of the coping from one file ( assume the `php://temp` use file since the file is huge ) to another.

So for each local copy of a file, there is an unnecessary code for `copying` file not `moving`.
If the library use `O(n)` the result always will be about double of that.
Since the library copy file from ftp to temp, after I copy from `temp` to some local file

**Comment by Nyholm** [comment]
> are you mean composition?

Yes. I blame my phone's autocorrect. 

> For large files ( default more than 2MB ) this library breaks this rule.

That is for php to decide. Not this library. 

> We are talking about the performance...

Please show the actual performance. Are we talking about parts of a millisecond?

**Comment by Nyholm** [comment]
Im at a computer now. I ran this script: 

```php
<?php

$loops = 1000;

$start = microtime(true);
for($i= 0; $i<$loops;$i++) {
    $stream = fopen('php://temp', 'w+b');
    fwrite($stream, 'small file');
    fclose($stream);
}

$time = round((microtime(true) - $start) * 1000);
echo 'Small file x '.$loops.' times to php://temp took: '.$time.'ms'.PHP_EOL;


$start = microtime(true);
for($i= 0; $i<$loops;$i++) {
    $stream = tmpfile();
    fwrite($stream, 'small file');
    fclose($stream);
}

$time = round((microtime(true) - $start) * 1000);
echo 'Small file x '.$loops.' times to tmpfile took: '.$time.'ms'.PHP_EOL;

// Produce a 12 MB file
$largeStream = fopen('php://temp', 'w+');
for($i= 0; $i<300000;$i++) {
    fwrite($largeStream, 'large content that is repeatatly added');
}
rewind($largeStream);
@mkdir(__DIR__.'/tmp');


$start = microtime(true);
for($i= 0; $i<100;$i++) {
    $filename = tempnam(__DIR__.'/tmp', 'test');
    $stream =  fopen($filename, 'a+');
    stream_copy_to_stream($largeStream, $stream);
    fclose($stream);
    rewind($largeStream);
}
$time = round((microtime(true) - $start) * 1000);
echo 'Copy big file x 100 times to tmpfile took: '.$time.'ms'.PHP_EOL;

fclose($largeStream);

```

It produced the following output
```
Small file x 1000 times to php://temp took: 1ms
Small file x 1000 times to tmpfile took: 267ms
Copy big file x 100 times to tmpfile took: 1908ms
```

So changing away from `php://temp` is worse for performance and moving the a large file is not really bad.

I vote for closing this issue.

**Comment by aliakbarazizi** [comment]
I'm back too,

You didn't even mention my case in your test.
I'm talking about copying file compare. I add my case test below


If you used `tmpfile` for the third case, the result of the `Copy big file x 100 times to tmpfile took` would be 0, since the file already exists, and you can just rename it, instead of copying. that's why I say, we are talking about copying file performance. Of course, if we do not copy the file, the performance is much **better**. So I don't know why we need **proof** for this.

```php
// Produce a 12 MB file
$largeStream = tmpfile();
for($i= 0; $i<300000;$i++) {
    fwrite($largeStream, 'large content that is repeatatly added');
}
rewind($largeStream);
@mkdir(__DIR__.'/tmp');

$temppath = stream_get_meta_data($largeStream )['uri'];
for($i= 0; $i<100;$i++) {
    $filename = __DIR__ . '/tmp/test';
    rename($temppath  ,$filename); // I'm talking about different in rename, and copy performance!
}
```


I know `php://temp` has better performance in small files. There is no need to prove that.

The problem is when you want to create a local copy or want a path of a file.

So I think the result is like this:

- If the user doesn't want to copy a file locally, "php://temp" is better.
- If the user wants to do this, `tmpfile` is better.


Because of that, I think it's better for performance to user decide this, and add an option to change this behavior in the constructor like a callback function to create tmpfile

**I'm not talking about removing** `php://temp`, this is good in some cases, but in other cases that I mentioned.

PS:
If you think copying local copy and use temp path file is not the case that happens a lot, I understand, that's your decision. I rewrite code for my use case anyway. But I think other people may have a similar issue,

So I'm totally ok with the closing issue, that's your decision to make. I just mention something that may improve this library.

**Comment by Nyholm** [comment]
Making it configurable wont improve the library, it will be more complicated. 

To always using `tmpfile()` as you originally suggested will make it some milliseconds faster for the case where you have big files and do need the path. But it will make it slower for every other scenario. 

Using `tmpflile()` will make the library assume that you are on a writable filesystem. Using `php://temp` leaves that problem to PHP. 

I suggest closing this issue.

**Comment by aliakbarazizi** [comment]
> some milliseconds faster

Wow, I don't know how to prove copying file is not millisecond!
I can't see anyway to tell you copying is very much slower (not millisecond) than moving! Wow
 I guess best thing is closing issue.
Tnx for your time
