### ISSUE TITLE
Where can i find the CMIS flysystem adapter ?

### ISSUE THREAD

**Issue by TOTOleHero** [thephpleague/flysystem#1271]
### Question

Hello, 

Where can i find the adapter for CMIS : https://en.wikipedia.org/wiki/Content_Management_Interoperability_Services

wich follow the specifications : http://docs.oasis-open.org/cmis/CMIS/v1.0/cmis-spec-v1.0.html

Thank's you

**Comment by frankdejonge** [comment]
Hi @TOTOleHero, that adapter does not exist.
