### ISSUE TITLE
V1: ftp commands take longer with each call

### ISSUE THREAD

**Issue by kohlerdominik** [thephpleague/flysystem#1274]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.x.dev

#### Summary

Every time a ftp command is called (for example read(), write(), getTimestamp()), it takes longer for the call to finish than for the previous one.

#### Details
I noticed this very strange bug when processing multiple files in a directory. For each file I do a `getTimestamp()` first, followed by `read()` if the file is older than 60 seconds. For 1 or 2 files, this process is very quick. For 20 files it takes a non-linear longer amount of time, which seems very odd to me. I did some testing, and I'm not really able to pin-point the exact location, so I hope someone has an explanation where this comes from...

Btw: In the real environment i use Laravel Filesystem as abstraction layer, so comments how to optimize my script below do not help me.

#### How to reproduce
For testing yourself, you can clone this repo: https://github.com/kohlerdominik/issue-flysystem
```php
$fs = new Filesystem(
    new Ftp([
        'host'     => '',
        'username' => '',
        'password' => '',
        'root'     => '/',
        'passive'  => true,
        'ssl'      => true,
        ])
);

$files = $fs->listContents('/');

foreach ($files as $file) {
    $startTime = microtime(true);

    $fs->read($file['path']);

    echo "duration: ".(microtime(true) - $startTime)."s\n";
}
```

This script lists all the contents of a directory, and then tries read each file. Its 20 files in total, they are identical. You would assume, that each loop takes rougly the same time to complete. However, this is what really happens:
```
duration: 0.27308297157288s
duration: 0.40937185287476s
duration: 0.49884414672852s
duration: 0.59137797355652s
duration: 0.70347189903259s
duration: 0.81141185760498s
duration: 0.89823007583618s
duration: 1.024658203125s
duration: 1.1164939403534s
duration: 1.2006311416626s
duration: 1.2908051013947s
duration: 1.4007170200348s
duration: 1.4952640533447s
duration: 1.601665019989s
duration: 1.7041099071503s
duration: 1.7988770008087s
duration: 1.9049828052521s
duration: 2.0007920265198s
duration: 2.1265699863434s
duration: 2.2001020908356s
```
The first `read()` takes about 0.27s, while the last one takes more than 2 seconds.

#### Final note
It does not happen in Flysystem V2, which is good news. Unfortunately, i can not really wait for the Laravel 9 release, so I'm somewhat depending on a fix in V1.

**Comment by Nyholm** [comment]
Thank you for a good bug report. Why do you think this is happening? 

What does it say when you profile the test script with Blackfire?

**Comment by frankdejonge** [comment]
@kohlerdominik could you provide a little bit more information about what kind of FTP server you're interacting with, how big the files are and how you've configured your connection? I've got a docker based setup locally with your example but my responses do not show the same picture as your case does.

```
duration: 0.0083250999450684s
duration: 0.0071780681610107s
duration: 0.0080409049987793s
duration: 0.0087959766387939s
duration: 0.012315034866333s
duration: 0.0082178115844727s
duration: 0.007774829864502s
duration: 0.0092730522155762s
duration: 0.014404058456421s
duration: 0.011800050735474s
duration: 0.0085651874542236s
duration: 0.0079119205474854s
duration: 0.008080005645752s
duration: 0.0080280303955078s
duration: 0.0080080032348633s
duration: 0.0078389644622803s
duration: 0.0082278251647949s
duration: 0.00724196434021s
duration: 0.0079870223999023s
duration: 0.0078151226043701s
```

**Comment by kohlerdominik** [comment]
Hi @frankdejonge 

Yea, that's what I would like to see.
Can you run your setup against the FTP server I used for testing, please? It's from a popular Hosting Provider here in Switzerland, so I think the server setup should be "best practice". I'll send you the credentials by mail just now to info at frankdejonge.

- Kind of ftp server: "Pure-FTPd [privsep] [TLS]" (from the welcome message)
- How I configured the connection: [edit] added to the initial post
- The files I used for testing just contain the string "some text", so technically they are exactly 9 bytes.

I have not pointed out that I use a FTPS-connection, so if you didn't check my example repo you might not have seen that.

**Comment by frankdejonge** [comment]
@kohlerdominik the regression originates in the ftp_chdir function, this function is used in the `has` call which is used to assert the file exists before reading it. V2 just tries to read it, but V1 has different heuristics. You can remove the performance regression by disabling asserts (a config setting on the Filesystem: https://flysystem.thephpleague.com/v1/docs/advanced/performance/).

Thanks for sending me the credentials, I was able to dig down to where the regression took place.

**Comment by kohlerdominik** [comment]
@frankdejonge just tested it in the real application, and your suggestion works like a charm. Thanks a lot!

It's interessting, though, that it's this increasing duration for each loop. 

However, for me it's fine to go with `'disable_asserts' => true,`. And Flysystem V2 surely brings some general improvements anyways, so I will be happy to use it once it's available.
