### ISSUE TITLE
Race condition 

### ISSUE THREAD

**Issue by peterkimga** [thephpleague/flysystem#1279]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.0

#### Summary

Hi

I use your package as a part of this implementation:

https://github.com/googleapis/google-api-php-client#caching

I got 2 problems with this.

1) My application makes 2 calls at the same time and I got error:

```
{
    "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: unlink(\/home\/<server_name>\/domains\/<domain>\/app\/..\/cache\/federated_signon_certs_v3): No such file or directory on line 26a in file \/home\/<server_name>\/domains\/<domain>\/vendor\/league\/flysystem\/src\/Adapter\/Local.php."
    }
}
```
So the first request is deleting the file before it got the content and the second one comes in and it throws this error.

2) The Google Auth keys are updated every 24h. There is a specific header telling when they will expire but the file is updated every 2h or so anyway. So the headers are ignored and it uses some default refresh value. If you know what should I add to this setup to use the headers expiry date so the first request after the expiry date will trigger the update of cache would be great.

#### How to reproduce

https://github.com/googleapis/google-api-php-client#caching

and after like 2 hours try to use it with more than 1 request at the same time.

**Comment by frankdejonge** [comment]
Hi, Flysystem does not prevent race conditions. The reason for this is that in distributed or scalable setups there's no sane default without that doesn't rely on non-filesystem locks.

**Comment by peterkimga** [comment]
> Hi, Flysystem does not prevent race conditions. The reason for this is that in distributed or scalable setups there's no sane default without that doesn't rely on non-filesystem locks.

I can see that it does not prevent this, I would not have an error if it did. But what is the solution for questions 1 and 2 then? How to set it up to use expiration header at liest cause I sorted out the problem with 500 error but at least I want to limit it as much as I can. Have it once per 24h not every 2h cause the cache is not using headers :|

Thanks :) Peter

**Comment by frankdejonge** [comment]
@peterkimga I would use something like Redis for this or decorate the cache adapter with locking.

**Comment by frankdejonge** [comment]
Correct me if I'm wrong, the second question is about the use of the other library, not really anything to do with Flysystem itself.

**Comment by peterkimga** [comment]
Actually no. I would like to know if there is an extra configuration to it.

**Comment by peterkimga** [comment]
Is there a config saying "use headers to determine when it expires = true".

I'm not too good at this and I was actually counting on code examples rather what you use because it's not telling me much as well. I was counting on the fact that you will know what to add to that code to make it work better or what other package of league to use and how to do what it should do.

Because all what you just said told me nothing at that point :| Sorry still do not know how to solve my problem.

**Comment by peterkimga** [comment]
I just need to know how to modify that code:

```
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Cache\Adapter\Filesystem\FilesystemCachePool;

$filesystemAdapter = new Local(__DIR__.'/');
$filesystem        = new Filesystem($filesystemAdapter);

$cache = new FilesystemCachePool($filesystem);
$client->setCache($cache);
```

To use the expiry date from the headers of that file:

https://www.googleapis.com/oauth2/v3/certs

and do not create a new cache file until this one is still valid. It sounds like it should be like every 24h.

Not like now, with the above code, every 2h. Cause I got a bad situation with the race condition, 12 times per day vs 1 time per day.

**Comment by frankdejonge** [comment]
@peterkimga flysystem doesn't set any headers. You're asking the wrong open source project. I don't maintain the cache or the Google SDK.

**Comment by peterkimga** [comment]
But do you have one at the league that will handle this? League is storing and creating a cache file as I understand it?

**Comment by frankdejonge** [comment]
@peterkimga there's to my knowledge no league package that does this, sorry. I really think you need to file an issue with the Google SDK.
