### ISSUE TITLE
Bad result when use fileExists method in v2 for directories

### ISSUE THREAD

**Issue by stoynov** [thephpleague/flysystem#1290]
### Bug Report

When using this method `fileExist` to check if the directory exists the result of the method is false. The analogous method from version 1 is `has`.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.*

#### Summary
I have a problem with this method `fileExist` in version 2. For some reason, the method checks `is_file` instead `file_exists`. 
Is there any reason it was made to work that way?

V1 Code
```php
    public function has($path)
    {
        $location = $this->applyPathPrefix($path);

        return file_exists($location);
    }
```

V2 Code
```php
    public function fileExists(string $location): bool
    {
        $location = $this->prefixer->prefixPath($location);

        return is_file($location);
    }
```

#### How to reproduce

Try to check if the directory exists

**Comment by frankdejonge** [comment]
Hi, this was a deliberate action, since it wouldn't work on my filesystem implementations and gave very inconsistent results. Could you explain the case you're working on so I might provide you with an alternative angle?

**Comment by stoynov** [comment]
Hi. I use this method to check if the directory exists. The local adaptor has to have this type of method if you want to go deeper and iterate the list of StorageAttrabute elements. I can use the file_exist function but I think that It will be useful for everyone.

**Comment by fredsal** [comment]
So, the question was, **How to check if directory exists?**

**Comment by reeperbahnause** [comment]
I have the same question for v2.
Is there a nice way to check if a directory exists? 
For sure I could use the `listContents` function but this seems to ignore some S3 directories?
How about a `directoryExists` function? This would prevent side effects for the `fileExists` function?

**Comment by TheCelavi** [comment]
Argument for "directoryExists":

Considering that we can use AWS S3 along with CloudFront, and we need to deliver securely content from directory to the user we need to:

1. determine if user has access to directory
2. determine if directory exists
3. issue signed cookie so user can access to the resources within directory

So this is a big deal breaker for us because we can not determine if there is a valid reason to issue signed cookie or not, we are unable to determine if resource (directory) exists at all.

**Comment by kbond** [comment]
This is a little workaround I have created:

```php
public function exists(string $location): bool
{
    if ($this->flysystem->fileExists($location)) {
        return true;
    }

    try {
        $this->flysystem->visibility($path); // any read method that throws an exception if location isn't found can be used
    } catch (FilesystemException $e) {
        return false;
    }

    return true;
}
```

I'm not sure if this works with all adapters.

**Comment by TheCelavi** [comment]
Hi @kbond! I use "list" method to check if there is a directory, didn't tried "visibility" though...

But in general - it is a workaround and there are problems in a wilderness which needs proper solution (such as I have stated above, AWS do have security tied to "directory", CloudFront CDN depends on it).

**Comment by freekmurze** [comment]
In [laravel-medialibrary](https://spatie.be/docs/laravel-medialibrary/v9/introduction) I'm checking directory existence in several place in the code. It would be very handy if Flysystem v2 would provide such a method out of the box.

**Comment by frankdejonge** [comment]
@freekmurze in medialibrary, why does your library need to know if a directory exists? I'll be checking if I can add a hasDirectory method (which would cause a new major version to be released), but I'm still quite curious why it's needed at all.

**Comment by freekmurze** [comment]
When a file is added to the media library it can also create derived files such as thumbnails. The original file is saved together with those derived files in a directory. The directory itself is named using the id (or uuid) of a `Media` Eloquent model.

In the package directories are being checked to see if the medialibrary is healthy, if a media item has derived files, and also in the tests to check if a directory is removed when the related  `Media` Eloquent model is deleted.

I can work around this, so if you decide to not add a `hasDirectory` it's not a big problem, but it sure would be handy to have such a method out of the box.

**Comment by frankdejonge** [comment]
@freekmurze please check out: https://github.com/thephpleague/flysystem/pull/1401
