### ISSUE TITLE
Please write GitHub releases

### ISSUE THREAD

**Issue by williamdes** [thephpleague/flysystem#1292]
There is no GitHub release since `29 Dec 2019` that makes users see the repository like unmaintained but the docs talks about a V2.

This is confusing and forces the user to have a look to the tags pushed to see the latest version and it's date.

Please go back to writing releases notes 🙏🏻

**Comment by dereuromark** [comment]
It is also very hard to see differences between v1 and v2 if there arent any github release notes on this subject and what actually changed etc.

**Comment by dakur** [comment]
There is [changelog](https://github.com/thephpleague/flysystem/blob/2.x/CHANGELOG.md), [upgrade guide](https://flysystem.thephpleague.com/v2/docs/advanced/upgrade-to-2.0.0/) and [what is new](https://flysystem.thephpleague.com/v2/docs/what-is-new/), but I agree that Release is a convenient place where I look for list-structured information about breaking changes all the time.

Btw all of the places miss information about removed `NullAdapter` (#1303), if you look for it accidentally.

**Comment by williamdes** [comment]
Pong

**Comment by olvlvl** [comment]
We're starting to move to v2 and what would be helpful for us is to include breaking changes like renamed interfaces. We have to figure this ourselves like `League\Flysystem\AdapterInterface` was renamed as `League\Flysystem\FilesystemAdapter`. `@deprecated` mentions with an update path in the 1.x branch would be awesome.
