### ISSUE TITLE
FTPAdapter function "has" gives false positives

### ISSUE THREAD

**Issue by updatedData** [thephpleague/flysystem#1297]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | No
| Version     | 1.x

#### Summary

The call of  `$listing = $this->ftpRawlist('-A', str_replace('*', '\\*', $path));` in `src/Adapter/Ftp.php` in the function `getMetaData` is on some servers returning a list of the directory contents if the requested file is not present. 

Since it's assuming the the check will provide a truthy result it procceeds with `$listing[0]`, even though, at this point, it containts the first file of found from the directory listing.

#### How to reproduce

```
<?php

require 'vendor/autoload.php';

use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Ftp as Adapter;

$filesystem = new Filesystem(new Adapter([
    'host' => 'ftp.example.net',
    'username' => 'foo',
    'password' => 'bar',

    'port' => 21,
    'root' => '/',
    'passive' => true,
    'ssl' => false,
    'timeout' => 30,
    'ignorePassiveAddress' => false,
]));

if($filesystem->has('test.txt')) {
    $filesystem->delete('test.txt'); //crashes as it doesn't exist
}
```

Unfortunaly I have no further informations on how the ftp is configured but it seems relying on `getMetaData` is not sufficient and `has` should include some kind of filename check

**Comment by updatedData** [comment]
Further investigation has shown that the `-A` is making the server output the whole directory list, regardless of what ever is in the path.

**Comment by MrMadClown** [comment]
I had the same Issue with an ftp Server I have no control over.
```
>>> ftp_raw($connection, 'HELP');
=> [
     "214- The following commands are recognized (* =>'s unimplemented).",
     "   USER    PASV    MLFL*   ALLO    XCWD    NOOP    XPWD    EPRT ",
     "   PASS    TYPE    MAIL*   REST    LIST    MKD     CDUP    FEAT ",
     "   ACCT*   STRU    MSND*   RNFR    NLST    XMKD    XCUP    OPTS ",
     "   SMNT*   MODE    MSOM*   RNTO    SITE    RMD     STOU    AUTH ",
     "   REIN*   RETR    MSAM*   ABOR    SYST    XRMD    SIZE    PBSZ ",
     "   QUIT    STOR    MRSQ*   DELE    STAT    RRMD    MDTM    PROT ",
     "   PORT    APPE    MRCP*   CWD     HELP    PWD     EPSV ",
     "214 Direct comments to support@avm.de.",
   ]
   ````
   Is basically all I know, I haven't been able to find any technical Documentation about the avm FTP

**Comment by MrMadClown** [comment]
Well, the Bug and my pull request are both still there. Should not be closed.

**Comment by updatedData** [comment]
Any news on this?
