### ISSUE TITLE
Remove FilesystemException from annotations

### ISSUE THREAD

**Issue by dakur** [thephpleague/flysystem#1304]
`FilesystemException` should not be annotated in `@throws`.

If you catch e.g. `UnableToWriteFile` from `FilesystemWriter#write()` you cover all errors which can occur in method `write()`. There is no need to annotate the interface as well. You can still catch whole `FilesystemException` as it is inferred from `UnableToWriteFile`.

The problem is that IDE complains now that you should catch also `FilesystemException`:

![image](https://user-images.githubusercontent.com/9862581/116999191-91e01b80-acdf-11eb-8fa7-f1c31d319328.png)

**Comment by dakur** [comment]
Btw, `fileExists()`/`UnableToCheckFileExistence` is missing in [docs](https://flysystem.thephpleague.com/v2/docs/usage/exception-handling/).

**Comment by frankdejonge** [comment]
Hi @dakur,

You can receive a FilesystemException because of a connection or misconfiguration problem with several adapters.

**Comment by dakur** [comment]
@frankdejonge Thank you for your response. You mean that also some configuration stuff throw implementations of `FilesystemException`? I think it should have different common exception, because it's different type of failure.

Something like this (names are made up):
- `FilesystemException`
  - `FilesystemOperationException`
    - `UnableToWriteFile`
    - …
  - `FilesystemConfigurationException`
    - `CanNotMountFilesystem`
    - …

This way you won't have the problem which I sketched above – you can catch `UnableToWriteFile` and `FilesystemConfigurationException` separately.

Btw, the common exceptions should inherit from one of `LogicException` or `RuntimeException`. I've heard many times it's best practice to differentiate between these two basic types of exceptions.

**Comment by honiahaka10** [comment]
@frankdejonge 
But should FilesystemException not be a parent class instead of an interface instead?
With an interface this will result in code like that:
`try {
    $content = $filesystem->read('somepath');
} catch(Exception $e) {
    // do exception handling
} catch (FilesystemException $fe) {
   // do exception handling
}`
Without the second catch block, IDE will give a warning about unhandled exception.
