### ISSUE TITLE
SftpAdapter does not catch UnableToConnectToSftpHost

### ISSUE THREAD

**Issue by dakur** [thephpleague/flysystem#1305]
And underlying layer does not annotate it: https://github.com/thephpleague/flysystem-sftp/issues/124

**Comment by dakur** [comment]
not resolved yet

**Comment by stof** [comment]
There is no reason to catch it, as `UnableToConnectToSftpHost` implements `FilesystemException`

**Comment by frankdejonge** [comment]
This expected, as @stof mentioned, it's covered by the contract.
