### ISSUE TITLE
File already exists at path (laravel)

### ISSUE THREAD

**Issue by dot-backend** [thephpleague/flysystem#1308]
**Storage::disk('google')->move('old path_folder','new path folder');**
I can't move a file in drive, how can i move it in laravel, please help.
**I'm from Colombia**

![image](https://user-images.githubusercontent.com/62233231/117243303-9817ea00-adfc-11eb-98ae-ba4a2deaffe5.png)

**Comment by IngDiegoOviedo** [comment]
![image](https://user-images.githubusercontent.com/62233231/117243244-77e82b00-adfc-11eb-8374-caa0a6e40144.png)

**Comment by PaolaRuby** [comment]
@IngDiegoOviedo You have to give more information
Tienes que dar mas información

`Storage::disk('google')` 
which adapter are you using? `League\Flysystem\GoogleCloudStorage\GoogleCloudStorageAdapter` or from third parties 
¿Cual adapter estas usando? `League\Flysystem\GoogleCloudStorage\GoogleCloudStorageAdapter`  o de terceros

which version are you using? V1 or V2

**Comment by dot-backend** [comment]
![IMG-20210518-WA0005.jpg](https://user-images.githubusercontent.com/62233231/118727936-38a4db80-b7f9-11eb-9565-c448d3d34c0e.jpg)


I am new to using it and i do not have as much knowledge, where can i find information?

**Comment by erikn69** [comment]
@IngDiegoOviedo the problem with Google Drive kind of adapter is that they use routes with ids and not real routes like `/path/to/file`, but it is not issue from this package, it is from **Hypweb**, you can ask there, or use other custom adapter,
if you are new maybe seems easier for you [masbug/flysystem-google-drive-ext](https://github.com/masbug/flysystem-google-drive-ext), i test it, and it works with real paths

**Comment by dot-backend** [comment]
@erikn69 thank you very much friends, i need to learn more!

**Comment by erikn69** [comment]
@IngDiegoOviedo [masbug/flysystem-google-drive-ext](https://github.com/masbug/flysystem-google-drive-ext) configs it's the same that [nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive) because was a fork, maybe you can close this issue, and please if works for you masbug/flysystem-google-drive-ext give a star
