### ISSUE TITLE
Keep identifier in paths when MountManager list contents, problem

### ISSUE THREAD

**Issue by SeniorSupportEngineer** [thephpleague/flysystem#1312]
### Question

I don't understand the need of Keep identifier in paths when MountManager list contents. I now have a issue when I need to copy the file. I used in version 2.0.5 the filename also for the target.

`    $this->mountManager->copy(
                        self::SOURCE_PREFIX . $filename,
                        self::TARGET_PREFIX . $filename
                    );
`

Now my code is broken in allot of places. How did you see this in your mind to use it in a way that it works or solve this matter?

**Comment by tofra** [comment]
I've experienced the same issue, it's really bad that there is a backward compatibility issue. The path property now contains "source://". So previously path was '/tmp' and now it's 'source:///temp'

:-(
