### ISSUE TITLE
Directory listing is not sorted

### ISSUE THREAD

**Issue by SeniorSupportEngineer** [thephpleague/flysystem#1313]
### Question

I started testing the upgrade from 1.0 to 2.0.8. after allot of code updates I got it working, only one thing I can't fix is the change of the directory listing. 

It looks like a random sorting of the filenames, while in the old version it was [a - z] and now sometimes it's [z - a] or [a - z] or random.
I need it to be [a - z] because we import data in that order, because of the updates are in that order presented on, lets say, a sFtp.

Is this a bug or can this be updated.

Thank you in advance for your answers.

**Comment by frankdejonge** [comment]
@SeniorSupportEngineer what adapter are you using?

**Comment by SeniorSupportEngineer** [comment]
@frankdejonge I'am using the LocalFilesystemAdapter

**Comment by joshbruce** [comment]
Same question and same response re adaptor. 

https://github.com/8fold/php-shoop/issues/204

**Comment by frankdejonge** [comment]
@Nyholm I'm investigating this one.

**Comment by frankdejonge** [comment]
I've fixed this a PR, please check it out: https://github.com/thephpleague/flysystem/pull/1330
