### ISSUE TITLE
Missing Documentation V2 - Configuration

### ISSUE THREAD

**Issue by internalsystemerror** [thephpleague/flysystem#1327]
### Question

I was wondering what I could pass as the `$config` parameter to the various API calls and I can't find any documentation on the matter. Is it possible to set visibility per file? Does this have to be done at the adapter level?

**Comment by frankdejonge** [comment]
Hi, PR's for documentation are very welcome 👍

**Comment by internalsystemerror** [comment]
I would be happy to contribute, but I would need an answer to my usage question.
