### ISSUE TITLE
Differnt directory separators on Windows

### ISSUE THREAD

**Issue by reeperbahnause** [thephpleague/flysystem#1328]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.1.1

#### Summary

On Windows the last directory separator is a back-slash all other separators a forward-slashes.
This issue is related to #1311 which states that the issue is fixed with version 2.0.7 

#### How to reproduce

1. set up a project on windows 
2. call the Storage::listContents function 
The result will look like this:
```
  class League\Flysystem\DirectoryAttributes#168 (5) {
    private $type =>
    string(3) "dir"
    private $path =>
    string(55) "Documents/2021/06/26/60d4fd5a75818332095430\Attachments"
    private $visibility =>
    string(6) "public"
    private $lastModified =>
    int(1624571226)
    private $extraMetadata =>
    array(0) {
    }
  }
```

**Comment by frankdejonge** [comment]
I don't have a windows setup, nor do I have a CI setup for it. A PR for this would be great.
