### ISSUE TITLE
Class League\Flysystem\AwsS3v3\AwsS3Adapter not found

### ISSUE THREAD

**Issue by iaicam** [thephpleague/flysystem#1329]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.1

#### Summary

Using 2.1.1 of flysystem and 2.1.0 of this aws-s3 package. The class League\Flysystem\AwsS3v3\AwsS3Adapter is not found.

#### How to reproduce

I've created a demo repo that suffers from this problem. https://github.com/iaicam/flysystem-error this was tested using composer 2.1.3 on PHP 8.0.8 and 7.4

**Comment by frankdejonge** [comment]
The class you're trying to resolve has a casing mismatch in the adapter namespace segment:

```diff
-League\Flysystem\AwsS3v3\AwsS3Adapter
+League\Flysystem\AwsS3V3\AwsS3Adapter
```

**Comment by iaicam** [comment]
Thanks for the response, however I updated the example because I had this error when using IntelliJ autocomplete so it seemed odd that would screw up the class name. The error still exists as far as I can see in https://github.com/iaicam/flysystem-error

**Comment by iaicam** [comment]
Never mind, I suck at copying and pasting today.

**Comment by MA812** [comment]
Hello,

I have this error too.
I start with v1 : `{
    "require": {
        "league/flysystem-aws-s3-v3": "^1.0"
    }
}`

All works.
But when I update composer to  `{
    "require": {
        "league/flysystem-aws-s3-v3": "^2.0"
    }
}`
after delete vendor folder and composer.lock file
AND update
`use League\Flysystem\AwsS3v3\AwsS3Adapter;`
`$adapter = new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, $bucketname);`
to
`use League\Flysystem\AwsS3V3\AwsS3Adapter;`
`$adapter = new \League\Flysystem\AwsS3V3\AwsS3Adapter($client, $bucketname);`

and always this error....
` Uncaught Error: Class "League\Flysystem\AwsS3V3\AwsS3Adapter" not found `

How to resolve this error ? I made test with just `listContents` method.

**Comment by frankdejonge** [comment]
@MA812 the class should be `League\Flysystem\AwsS3V3\AwsS3V3Adapter`.

**Comment by gnumoksha** [comment]
some notes:
- this is related to https://github.com/thephpleague/flysystem/issues/1347 (in order to GitHub link this issue on that page)
- the change was on the letter `v` in `AwsS3V3`, from lowercase to uppercase
- one may need to clean PhpStorm cache (File -> Invalidate Caches...)
