### ISSUE TITLE
No file attach method in Zip-archive adapter

### ISSUE THREAD

**Issue by pralhadstha** [thephpleague/flysystem#1333]
### Question
There seems to be no method to attach the files into zip-archive. How do we create a zip archive using the zip-archive adapter?

The snippet from ZipArchiveAdapter file:
https://github.com/thephpleague/flysystem-ziparchive/blob/2.x/ZipArchiveAdapter.php#L61

```
    public function write(string $path, string $contents, Config $config): void
    {
        try {
            $this->ensureParentDirectoryExists($path, $config);
        } catch (Throwable $exception) {
            throw UnableToWriteFile::atLocation($path, 'creating parent directory failed', $exception);
        }

        $archive = $this->zipArchiveProvider->createZipArchive();
        $prefixedPath = $this->pathPrefixer->prefixPath($path);

        if ( ! $archive->addFromString($prefixedPath, $contents)) {
            throw UnableToWriteFile::atLocation($path, 'writing the file failed');
        }
        $archive = $this->zipArchiveProvider->createZipArchive();

        $visibility = $config->get(Config::OPTION_VISIBILITY);
        $visibilityResult = $visibility === null
            || $this->setVisibilityAttribute($prefixedPath, $visibility, $archive);
        $archive->close();

        if ($visibilityResult === false) {
            throw UnableToWriteFile::atLocation($path, 'setting visibility failed');
        }
    }
```

To, add the data into the zip archive we need to add **[addFile()](https://www.php.net/manual/en/ziparchive.addfile.php)** method to the **[write()](https://github.com/thephpleague/flysystem-ziparchive/blob/2.x/ZipArchiveAdapter.php#L61)** method. 
I do not find any linkage to the addFile method in the ZipArchiveAdapter class.

Am I missing any place that performs the zip operation?
Also attaching the adapter class to the filesystem only results in the creation of a zip archive without any files.

I have tried adding the following line of code to the write method and seems to be generating zip with attached files.
```
$archive->addFile($path, $contents);
$archive->close();
```

If possible please point out or provide any docs to the working example of zip archive in v2.

**Comment by frankdejonge** [comment]
Hi, the zip is created automatically. When you use write/writeStream the file is created. Unset the filesystem (and thereby the adapter) to force a write.
