### ISSUE TITLE
Why flysystem creates empty directory by default (through ensureDirectoryExists) instead of throw Exception?

### ISSUE THREAD

**Issue by karrakoliko** [thephpleague/flysystem#1335]
### Question

ensureDirectoryExists method creates empty directory if it doesn't exist by default.

https://github.com/thephpleague/flysystem/blob/e6d7bab6d274953f1bd3a8a028766147ac0c00e5/src/Local/LocalFilesystemAdapter.php#L94
https://github.com/thephpleague/flysystem/blob/e6d7bab6d274953f1bd3a8a028766147ac0c00e5/src/Local/LocalFilesystemAdapter.php#L286

In some cases we expect it to throw exception if invalid path given.
If i made a typo in the root path - flysystem creates the whole path recursively.

```php
$pathWithATypo = '/path/with/a/typo';
$adapter = new ConcreteFlysystemAdapter($pathWithATypo); 
// it checks if a directory $pathWithATypo exists, if not - it creates whole path.
// we can't even check if given path is valid

```

This behavior is not configurable at all, the only thing we can do is to extend every provider and overwrite ensureDirectoryExists method. There is no way to check if the given path exists without creating it. There is no validation of given path: $location given to __construct() goes to ensureDirectoryExists() (right to to is_dir(), mkdir() functions in case of Local adapter) without any validation.

1. Why does it work this way?
2. Why this behavior is not configurable?
3. Isn't it considered as bad design?

**Comment by frankdejonge** [comment]
1. because this is convenient
2. because I prefer supporting one way of interacting
3. I don't believe it is, no.
