### ISSUE TITLE
Exception when iterate over sorted directory listing (v2)

### ISSUE THREAD

**Issue by Yiivgeny** [thephpleague/flysystem#1342]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.2.0

#### Summary

Exception when iterate over sorted directory listing

#### How to reproduce

```php
$l = iterator_to_array($fs->listContents($path)->sortByPath())
// throws
// Objects returned by League\Flysystem\DirectoryListing::getIterator() must be traversable or implement interface Iterator
// at /app/vendor/league/flysystem/src/DirectoryListing.php:68


```
 `iterator_to_array` as a demo, so  `\IteratorIterator` not worked too.

**Also highlighted with PHPStorm**
![изображение](https://user-images.githubusercontent.com/1321010/128225427-df2fa6cc-a080-440e-8835-a16d26c0a187.png)

**Comment by frankdejonge** [comment]
Bugfix released as 2.2.2, thank you for reporting the issue.
