### ISSUE TITLE
Unable to retrieve mimeType on AwsS3V3Adapter

### ISSUE THREAD

**Issue by matdave** [thephpleague/flysystem#1343]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.2.0

#### Summary

When using the AwsS3V3Adapter, I am unable to determine the mime types. 

```
try {
            $mimeType = $this->filesystem->mimeType('knownpath/');
        } catch (FilesystemException | UnableToRetrieveMetadata $e) {
            $this->log($e->getMessage());
        }
```
results in a log file with the error `Unable to retrieve the mime_type for file at location: knownpath`

#### How to reproduce

I am currently using league/flysystem 2.2.0 combined with league/flysystem-aws-s3-v3 2.1.0 tapping into it's built in S3 adapter. 

Everything else seems to work, and the mimeType works when using a local filesystem. I'm not sure what is going wrong.

**Comment by matdave** [comment]
I've done a little further digging, and file objects return the correct mime type, but directory's do not. On the local filesystem they will return "directory", however on AWS they are returning the error.

**Comment by frankdejonge** [comment]
Why do you need the mimetype of a directory?

**Comment by matdave** [comment]
On regular file system it returns that it is a directory. So basically, "consistency" to determine if what is being passed is a directory.

**Comment by frankdejonge** [comment]
Consistency for the sake of consistency is not a compelling reason for me to incur the complexity needed to resolve this. PR is welcome for evaluation, but I do not feel strongly enough about this myself to spend time on it.
