### ISSUE TITLE
There is some restrictions about big files ?

### ISSUE THREAD

**Issue by MA812** [thephpleague/flysystem#1346]
### Bug Report
Hello,
I have some problems about upload of big size, in php. I use flysystem v1. v2 don't work. 
FIles with some Kb or Mb, worked and uploaded with no problems. But Files with 300Mb are not uploaded.
Any method used 'put' ; 'putStream' ; 'writeStream' ...

I need to upload some zip in php,
All try of upload, when not successful take too much time for uploading, maybe because it's big file. 
 
**First try :**
```
// Create or overwrite using a stream.
$putStream = tmpfile();
fwrite($putStream, $custom_contents);
rewind($putStream);
$filesystem->putStream('$custompath', $putStream);

if (is_resource($putStream)) {
    fclose($putStream);
}
```
I got this error :

`Fatal error: Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/functions.php:112 Stack trace: #0 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(75): GuzzleHttp\Promise\exception_for() #1 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait() #2 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}() #3 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #4 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #5 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #6 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #7 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(34): GuzzleHttp\Promise\Promise->wait() #8 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(609): Aws\S3\S3Client->upload() #9 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(391): League\Flysystem\AwsS3v3\AwsS3Adapter->upload() #10 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem/src/Filesystem.php(122): League\Flysystem\AwsS3v3\AwsS3Adapter->writeStream() #11 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/creation.php(184): League\Flysystem\Filesystem->putStream() #12 {main} thrown in /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/functions.php on line 112
`

**Second try :**
`$filesystem->put("$path/{$path}.zip", $endfile, ['visibility' => League\Flysystem\AwsS3v3\AwsS3Adapter::VISIBILITY_PUBLIC]);
`
After changed memory limit of php 'memory_limit'.   
I got Firefox error page 'This connection was reset.'...

**Third try :**
`$filesystem->write("$path/{$path}.zip", $endfile, ['visibility' => League\Flysystem\AwsS3v3\AwsS3Adapter::VISIBILITY_PUBLIC]);` 

AND

 `$putStream = tmpfile();
    fwrite($putStream, $endfile);
    rewind($putStream);
    $filesystem->writeStream("$path/{$path}.zip", $putStream);
    if (is_resource($putStream)) {fclose($putStream);}`

I got this error :
` Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/RejectedPromise.php:16 Stack trace: #0 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/RejectedPromise.php(16): method_exists() #1 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(56): GuzzleHttp\Promise\RejectedPromise->__construct() #2 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\Handler\GuzzleV6\GuzzleHandler::Aws\Handler\GuzzleV6\{closure}() #3 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler() #4 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #5 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(155): GuzzleHttp\Promise\TaskQueue->run() #6 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(182): GuzzleHttp\Handler\CurlMultiHandler->tick() #7 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute() #8 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #9 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #10 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #11 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #12 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #13 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait() #15 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(287): Aws\AwsClient->execute() #16 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(272): Aws\S3\S3Client->checkExistenceWithCommand() #17 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(233): Aws\S3\S3Client->doesObjectExist() #18 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem/src/Filesystem.php(57): League\Flysystem\AwsS3v3\AwsS3Adapter->has() #19 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem/src/Filesystem.php(404): League\Flysystem\Filesystem->has() #20 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/league/flysystem/src/Filesystem.php(66): League\Flysystem\Filesystem->assertAbsent() #21 /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/creation.php(189): League\Flysystem\Filesystem->write() #22 {main} thrown in /home/aa/lampstack-8.0.3-2/apache2/htdocs/ruby/assets/storage/vendor/guzzlehttp/promises/src/RejectedPromise.php on line 16`

#### How to reproduce

1. Have a filesystem environment working.
2. upload via put, putStream, write, writeStream a file with >= of 300 Mb size.

Thanks 

EDIT: 
I will find solution about it.
Like I have my issue closed, I post my questions here...

Maybe, by upgrading to v2, the problem will be disappear. i can't update to v2, there is problem(different of this). 
I need to find solutions

**Comment by frankdejonge** [comment]
This seems to be a problem with guzzle when it switches to streamed requests. Might be good to open an issue with the AWS SDK instead (they have close ties with guzzle) and are better equipped to assist you. Flysystem merely adapts to the underlying SDK's so the error you are faced does not seem to be caused by Flysystem.

**Comment by MA812** [comment]
Hello,
With v2, there is no problem for upload.

It's correct with :

use Aws\S3\S3Client;
use League\Flysystem\AwsS3V3\AwsS3V3Adapter;
use League\Flysystem\Filesystem;
$client = new \Aws\S3\S3Client([
      'endpoint' => '***',
      'credentials' => [
          'key' => '***',
          'secret' => '***'
      ],
      'region' => '***',
      'version' => 'latest'
]);


$adapter = new \League\Flysystem\AwsS3V3\AwsS3V3Adapter($client, $bucket);
$filesystem = new \League\Flysystem\Filesystem($adapter);

**Comment by MA812** [comment]
thanks for help
@frankdejonge

**Comment by frankdejonge** [comment]
All good 👍 glad it worked out for you
