### ISSUE TITLE
Uncaught Error: Class "League\Flysystem\AwsS3V3\AwsS3Adapter" not found with ONLY in v2. v1 work correctly.

### ISSUE THREAD

**Issue by MA812** [thephpleague/flysystem#1347]
### Bug Report

Hello,

I have this error too.
I start with v1 : `{ "require": { "league/flysystem-aws-s3-v3": "^1.0" } }`

All works.
But when I update composer to `{ "require": { "league/flysystem-aws-s3-v3": "^2.0" } }`
after delete vendor folder and `composer.lock` file
AND update
`use League\Flysystem\AwsS3v3\AwsS3Adapter;`
`$adapter = new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, $bucketname);`
to
`use League\Flysystem\AwsS3V3\AwsS3Adapter;`
`$adapter = new \League\Flysystem\AwsS3V3\AwsS3Adapter($client, $bucketname);`

and always this error....
`Uncaught Error: Class "League\Flysystem\AwsS3V3\AwsS3Adapter" not found`

How to resolve this error ? I made test with just `listContents` method.

**Comment by frankdejonge** [comment]
Dude, I already commented on your other post. You didn't even bother to update the issue description.
