### ISSUE TITLE
Cannot resolve argument $testFly of \"App\\Controller\\Api\\IndexController::upload()\": Cannot autowire service \"App\\Flysystem\\testFly\": argument \"$defaultStorage\" of method \"__construct()\" references interface \"League\\Flysystem\\FilesystemOperator\" but no such service exists. Did you create a class that implements this interface?

### ISSUE THREAD

**Issue by JhinChenzy** [thephpleague/flysystem#1350]
### Question

when I just dump the object,
Here is the code
![image](https://user-images.githubusercontent.com/89455146/131307250-85f4ba13-fb64-401f-91f6-626b081021b6.png)
![image](https://user-images.githubusercontent.com/89455146/131307285-d363808e-3561-4809-bf72-b2ed84a12ee7.png)

**Comment by JhinChenzy** [comment]
even like this, there is the same trace
![image](https://user-images.githubusercontent.com/89455146/131307947-cf113d04-b576-4376-87ec-218e4f1a478d.png)

**Comment by BackEndTea** [comment]
Did you install the flysystem bundle? That should normally take care of auto wiring
