### ISSUE TITLE
fileExists() on absolute paths

### ISSUE THREAD

**Issue by armanist** [thephpleague/flysystem#1354]
### Question

When called `fileExists()` of `LocalFilesystemAdapter` with correct absolute file path.. false returned

`fileExists($path)` itself calls:

```
$location = $this->prefixer->prefixPath($location);
```

and this is what prefixPath returns

```
return $this->prefix . ltrim($path, '\\/');
```

where `$this->prefix` already contains full path to the file directory and the `$path` itself also contains full path + filename so it returns absolute path doubled, therefore could not find the file.

**Comment by frankdejonge** [comment]
This is by design. If you want to use absolute paths, you can use `/` as the root.
