### ISSUE TITLE
UI front ends?

### ISSUE THREAD

**Issue by sdwru** [thephpleague/flysystem#1355]
### Question

Are there any basic UI front ends for flysystem?  [Elfinder](https://github.com/Studio-42/elFinder) is one I am aware of.  It's ok but I am hoping there is something more basic out there.

**Comment by frankdejonge** [comment]
Hi :) this is only the underlying library. It's main focus is file storage for applications, so not specifically for user-managed files. There is currently no intention to expand the project focus into this direction.

**Comment by sdwru** [comment]
My question was asking if there are any 3rd party UI's.   I am aware that flysystem is just a library.

**Comment by frankdejonge** [comment]
Not that I'm aware of, you could look through all the packages that depend on flysystem to see if there is perhaps another package like that: https://packagist.org/packages/league/flysystem/dependents?order_by=downloads
