### ISSUE TITLE
Generating Signed URLs with IP Address Restriction

### ISSUE THREAD

**Issue by alexhackney** [thephpleague/flysystem#1360]
First, thank you for your work here. As a php/laravel developer, Flysystem makes working with files soooo much easier. I appreciate your contribution to the community.
### Question

I'm using temporary urls in an app and it's working flawlessly.

I currently create a temporary url with a expired at time of 5 mins for a video playback. The file just plays the entire time with no issue, even if its 5 hours.

The issue is that when you scrub through the time line after the 5 minute mark, the url is invalid now, so it's making a request with an invalid url, so playback fails. If you do the scrubbing during that 5 minute mark, all is well.

Is there a way for me to extend that time period, but also lock the request down to the request address? Meaning, I can make it valid for 5 hours, but only if the request comes from that users IP address. This would prevent sharing the url, which is the reason for the temp url anyways but allow me to make that url good for that much longer.

Thanks again!

**Comment by frankdejonge** [comment]
Hi @alexhackney,

If I'm understanding correctly, your issue is not per se with Flysystem but the Laravel Signed URL functionality, is that correct?

**Comment by alexhackney** [comment]
@frankdejonge Possibly. It looks to me that Laravel's implementation relies on 

````
League\Flysystem\AwsS3v3;
````

I guess I just want to know if the signed url can be tied to an ip at all. I know preventing access to a file isn't 100% possible but there must be a way to make it extremely difficult.

**Comment by frankdejonge** [comment]
They rely on that adapter to lookup the AWS SDK, so they sort of use this library as a service locator (which it should not be used for). My advice would be to either ask the lovely Laravel people or raise an issue with AWS SDK.

**Comment by alexhackney** [comment]
Ok. Thanks.
