### ISSUE TITLE
Why no cache adapter for v2?

### ISSUE THREAD

**Issue by sdwru** [thephpleague/flysystem#1361]
Is it no longer necessary or of little benefit in v2?  I am currently using [elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver) which uses v1 and makes extensive use of the cache adapter.  I am using that in conjunction with the f[lysystem-sftp v1](https://github.com/thephpleague/flysystem-sftp/tree/1.0.22) adapter.  

I am trying to decide if I should keep using that or drop the flysystem abstraction completely and just use a native phpseclib3 SFTP class which I already wrote and seems to work well.   The only thing is it doesn't use any cache and I don't want to have to try write all of that myself.

The main reason I went with the v1 driver was because of the drop in cache and SFTP adapters already available for it.  I see there is a 3rd party cache adapter for v2 but it doesn't appear all that well tested.  Either way I am looking at an extensive re-write of the flysystem-driver if I want to update that for v2.

**Comment by frankdejonge** [comment]
Hi @sdwru

> There are only two hard things in Computer Science: cache invalidation and naming things.
>
> -- Phil Karlton

This thing above is one of the reasons. The other reason is that I personally no longer have the use-case to support this and nobody else has stepped up to contribute or support it. I'd be happy to link to a community supported cache adapter, but I do not have the time to spend on this myself.
