### ISSUE TITLE
ftp_fput(): SSL_shutdown failed

### ISSUE THREAD

**Issue by maximus1127** [thephpleague/flysystem#1365]
I am trying to upload files to storage using FTP. It randomly works and randomly doesn't. When it randomly doesn't, I get this error:

`ErrorException: ftp_fput(): SSL_shutdown failed in C:\laragon\www\workflow\vendor\league\flysystem\src\Adapter\Ftp.php:273`

My config looks like this:

```
       'ftp' => [
            'driver' => 'ftp',
            'host' => 'ftp.myhost.com',
            'username' => 'my_username',
            'password' => 'my_password',
            'port' => 21,
            'passive' => true,
            'ssl' => true,
        ],
```

Currently trying to run on laravel 8.12. Any advice?

**Comment by frankdejonge** [comment]
No clue. FTP servers are pretty shit, can act unstable, and PHP's FTP functions are also "meh".
