### ISSUE TITLE
There is no extension able to load the configuration for 'flysystem'

### ISSUE THREAD

**Issue by abelardolg** [thephpleague/flysystem#1367]
Hi there,

I installed your FTP Adapter (Flysystem v2) into my dockerized Symfony app.

When I launch Postman to test my functionality, this message:
![Captura de pantalla de 2021-10-09 19-38-46](https://user-images.githubusercontent.com/22522883/136668716-5d778ca1-0cfd-435b-b182-20191c2bc67f.png)
is showed.

Inside my services.yaml, I have written:
![Captura de pantalla de 2021-10-09 19-40-13](https://user-images.githubusercontent.com/22522883/136668769-7c682cb3-c09f-4b46-9b74-8c3ed0366dae.png)
![Captura de pantalla de 2021-10-09 19-41-03](https://user-images.githubusercontent.com/22522883/136668811-0031d069-e70c-44f1-b302-083d4137089a.png)

Finally, inside the constructor of my FileService:
![Captura de pantalla de 2021-10-09 19-41-28](https://user-images.githubusercontent.com/22522883/136668830-3666be79-9e85-4333-98f0-3b315bfe76dd.png)

Since the installation of your package doesn't create a flysystem.yaml inside the package dir, I had to add these parameters inside the services.yaml.

Obviously, I have configured those variables inside my .env file.

What's wrong?

**Comment by abelardolg** [comment]
Inside the bundles.php no entry was added related to Flysystem.

**Comment by frankdejonge** [comment]
I have no idea, but I don't think this is a flysystem issue, seems like a DI configuration issue.

**Comment by abelardolg** [comment]
Hi again!

Thanks for replying.

What would it be the best way to add these settings with no write them inside my code?

Best regards.
