### ISSUE TITLE
Remove all prefixer implementation from Adapters, move it to FilesystemPrefixedDecorator.

### ISSUE THREAD

**Issue by Warxcell** [thephpleague/flysystem#1370]
### Bug Report

It's very annying to have prefix implemented per adapter. 
The use-case is: on file write => create CloudFront Invalidation.
I'm doing that by creating Decorator that Decorates FilesystemOperator, and on write methods - do API call to create invalidation.

The problem is that prefix is implemented in underlying adapter. So if I have AwsS3 adapter with prefix `xxx`, and I do

`$filesystem->write('some-file.jpg');`

my decorator doesn't know that this is in "directory" `xxx` and sends wrong invalidation request to CloudFront.

Better way to do this is by creating PrefixedFilesystemDecorator. This way solves the issue by having

- PrefixedFilesystemDecorator
- - MyDecoratorWithInvalidator
- - - Real Filesystem Operator.

Rather that simple approach, currently i'm doing a lot of if checks with `CompilerPass` and alot of if and extract prefix, depending on the adapter. 

Furthermore it will reduce the complexity of each Adapter and will DRY out the prefix implementation from each of them and will have consistent behaviour accross all adapters, and also more SOLID

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     |  ALL

**Comment by frankdejonge** [comment]
When deciding this I've chosen not to implement it this way. The prefixing and stripping is a re-usable class, you can use that for your case as well.
