### ISSUE TITLE
Merge files

### ISSUE THREAD

**Issue by pwjbj** [thephpleague/flysystem#1380]
file(1GB) is divided into blocks and needs to be merged into a new file
code 
        foreach ($blocks as $block){
                $block_filename = $attachment_service::getBlockFilePath($hash_key . '.part.' . $block['chunk']);

                $contents = $this->filesystem->readStream($block_filename);
                $this->filesystem->writeStream($combine_filename, $contents);

            }
The merged file has only one block size

v2  removed function update and updateStream  
How to make it reasonable

**Comment by frankdejonge** [comment]
Hi @pwjbj, the underlying code was the same for write and update, you can use write/writeStream.

**Comment by pwjbj** [comment]
The writestream method overwrites the file without appending, What does the third parameter of the writestream method need to be passed
