### ISSUE TITLE
can't detectSystemType for windows

### ISSUE THREAD

**Issue by bblemm** [thephpleague/flysystem#1383]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.5

#### Summary

The response from windows-ftp-server has a human readable format.
This contains padding whitespaces.

In function normalizeWindowsObject() is a trim used for this problem,
but in detectSystemType() is the item unfiltered used and the function returns always ‘unix’.

Finally, the item can’t be normalized because there are no 9 parts for unix format.

#### How to reproduce

Testable with windows server or with unit test, response has prefixed white spaces in meta data.

##### Test
tests/FtpTests.php
`
    if (strpos($directory, 'file4.txt') !== false) {
        return [
            '    2016-05-23  12:09PM                  684 file4.txt',
        ];
    }
`

##### Fix

`    protected function detectSystemType($item)
    {
        return preg_match('/^[0-9]{2,4}-[0-9]{2}-[0-9]{2}/', trim($item)) ? 'windows' : 'unix';
    }`

**Comment by frankdejonge** [comment]
Supplied PR is merged and released as 1.1.7
