### ISSUE TITLE
PHP 8.1.0	The ftp parameter expects an FTP\Connection instance now; previously, a resource was expected.

### ISSUE THREAD

**Issue by pierrexp9** [thephpleague/flysystem#1386]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.x

#### Summary

When using PHP 8.1, the ->disconnect() method does not work on League\Flysystem\Adapter\Ftp

#### How to reproduce

- Install php 8.1
- Etablish a FTP connection
- Call disconnect on the Adapter
- The FTP connection is still alive (check with `netstat -peanut | grep :21` for example)

With PHP 8.1, ftp_connect no longer returns a resource, but a `FTP\Connection` instance.

and ftp_close now expect a `FTP\Connection` instance : https://www.php.net/manual/en/function.ftp-close.php

Failed test that could be linked : https://github.com/thephpleague/flysystem/runs/4278136545?check_suite_focus=true
```
1) League\Flysystem\Ftp\FtpAdapterTest::disconnect_after_destruct
Failed asserting that true is false.
```

**Comment by frankdejonge** [comment]
@pierrexp9 please fill out the bug template, otherwise issues will be closed.

**Comment by pierrexp9** [comment]
@frankdejonge done ! thanks for the warning before shooting :)

**Comment by frankdejonge** [comment]
@pierrexp9 thanks for filling in the missing information. I just pushed a commit that addresses this, can you check it out to verify?

**Comment by pierrexp9** [comment]
@frankdejonge Hello Frank,
it seems that the build is failing : https://github.com/thephpleague/flysystem/commit/3d395569e09e2549f30b0bed6b7be3b9a56943bd

I suggest using this method to stay compatible with older php versions : 
(I have tested this code with php8.0 and php8.1 successfully)

```
private function hasFtpConnection(): bool
{
        return ( gettype($this->connection) === 'object' && get_class($this->connection) === 'FTP\Connection' )
             || is_resource($this->connection);
}




```

**Comment by frankdejonge** [comment]
Hi @pierrexp9, that build was failing on PHPStan, the instance of check works in PHP on non-existent classes just fine, so it should not be incompatible with older versions of PHP. Also, that's the 2.x line, so it shouldn't affect you on 1.x now :)

**Comment by pierrexp9** [comment]
@frankdejonge allright, thanks for the info, I thought this would fail, but I just tested and you are correct !
Ok for the 1.x (max version for Laravel at the moment)
Thank you for the very quick fix ! :+1:

**Comment by frankdejonge** [comment]
@pierrexp9 all good. I'll tag a 1.x version to ship this fix.

**Comment by frankdejonge** [comment]
Version 1.1.8 was tagged.
