### ISSUE TITLE
[FTP adapter] LIST command not compatible with latest FileZilla server

### ISSUE THREAD

**Issue by astehlik** [thephpleague/flysystem#1387]
### Bug Report

Providing options with the FTP `LIST` command (e.g. `LIST -aln /`) is not supported any more by the FileZilla server.

I'm not sure if the new behavior is violating any RFCs or if allowing options is actually a non Standard behavior.

My suggestion would be to add an option that disables the usage of LIST options (which seems to fix the issue).

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.3.2

#### Summary

Version 1.1.0 of the FileZilla server does not allow arguments in the `LIST` command any more.

This command works:

```
LIST /
```
This fails with `450 - Couldn't open the file`

```
LIST -aln /
```

#### How to reproduce

Try listing files with the latest FileZilla server as remote:

```php
// This will always return an empty list with a FileZilla server
// even if there are files / directories in the root directory.
FilesystemOperator::listContents('')
```

This is the log output of the FileZilla server:

![grafik](https://user-images.githubusercontent.com/956513/144629455-5b4a9648-c260-4d64-8fa1-4f9e526ea952.png)

## Hint

It took me a while to figure out the problem because I got a totally unrelated error.

The `listContents()` call does not throw an Exception, it simply returns an empty list.

But when you upload a file after listing the contents (in the same request) you get an error:

`Warning: ftp_fput(): Unable to build data connection: ECONNABORTED - Connection aborted`

I hope this helps when someone has a similar issue.

**Comment by marvinschroeder** [comment]
We also run into this problem with FileZilla Server v1.3.0

**Comment by Xinecraft** [comment]
I also got an empty array for a few FTP servers but works fine on others. 
After some debugging found that removing `-aln` from the ftp_rawlist in the package works. 
Checking this issues page earlier would have saved some hours of debugging. 😅

**Comment by frankdejonge** [comment]
@Xinecraft what type of FTP server is that?

**Comment by Xinecraft** [comment]
![image](https://user-images.githubusercontent.com/3089863/173302377-ac4eec72-713e-4e45-b664-ea26af20fac9.png)

Seems like `Multicraft 2.3.5 FTP Server`. It's a Minecraft server management panel lot of hosting companies use. Don't know what running use under the hood. It get installed in both Windows and Linux

> @Xinecraft what type of FTP server is that?

**Comment by LiaraAlis** [comment]
I can confirm this. Would be good if this issue can be resolved.

**Comment by frankdejonge** [comment]
Please upgrade to 3.4.0 or above to resolve this issue.
