### ISSUE TITLE
Make it possible to change the path prefix in v2

### ISSUE THREAD

**Issue by stancl** [thephpleague/flysystem#1389]
### Feature Request

Hey, first time contributing so sorry if this is duplicate, though I didn't find any related issues.

|    Q        |   A
|------------ | ------
| New Feature | no (re-adds v1 feature)
| BC Break    | no

#### Scenario / Use-case

I maintain a large [multi-tenancy package](https://github.com/archtechx/tenancy) for Laravel, which includes logic for scoping the filesystem disks to the selected tenant.

With flysystem v1, it essentially does something like:
```php
/** @var FilesystemAdapter $filesystemDisk */
$filesystemDisk = Storage::disk($disk);

$originalPath = $filesystemDisk->getAdapter()->getPathPrefix();

// make some modifications & store the old prefix in case we need to switch back to the central context

$filesystemDisk->getAdapter()->setPathPrefix($newPrefix);
```

However, in v2 this feature seems inaccessible. I noticed that there's a `$prefixer` property on `LocalFilesystemAdapter`, but there's no way to either replace it, or replace the `PathPrefixer`'s `prefix` property.

#### Summary

I think the simplest backwards-compatible implementation would be adding `getPrefix()` and `setPrefix()` methods to `PathPrefixer`.

I saw this issue https://github.com/thephpleague/flysystem/issues/1370 and that specific implementation would make my logic much cleaner, but for local disks I can make it work well with the `$prefix` getter & setter.

Though one issue I see is that the `$prefixer` property on `LocalFilesystemAdapter` is private. So that would also need a getter.

With that I could do:
```php
if (method_exists($disk, 'getPrefixer')) {
    $prefixer = $disk->getPrefixer();

    if ($prefixer instanceof PathPrefixer) {
        $originalPath = $prefixer->getPrefix();

        // ...

        $prefixer->setPrefix($newPath);
    }
}
```

Having an interface instead of the `method_exists()` check would be nicer, but as I said I'm completely happy with the simpler implementation too, if it makes maintenance and BC easier for you.

**Comment by stancl** [comment]
@frankdejonge if you could let me know that this is a change you'd accept, I'm more than happy to submit a PR. Thanks!

**Comment by frankdejonge** [comment]
Hi @stancl, I'm not open to a PR for this. An alternative would be to create a prefix based filesystem operator decorator, which can allow you to change it. As a design principle the encapsulation should not be mutated after creation as this can lead to consuming code not being able to know trust it and getting irregular responses. Instead it's better to create a new instance (almost no overhead there) for the case with the different prefix.

**Comment by stancl** [comment]
Hey @frankdejonge, thanks for the reply. I see, that makes sense.

> Instead it's better to create a new instance (almost no overhead there) for the case with the different prefix.

The package's current code is this (a bit messy, but should be understandable):

```php
/** @var FilesystemAdapter $filesystemDisk */
$filesystemDisk = Storage::disk($disk);
$this->originalPaths['disks'][$disk] = $filesystemDisk->getAdapter()->getPathPrefix();

if ($root = str_replace(
    '%storage_path%',
    storage_path(),
    $this->app['config']["tenancy.filesystem.root_override.{$disk}"] ?? ''
)) {
    $filesystemDisk->getAdapter()->setPathPrefix($finalPrefix = $root);
} else {
    $root = $this->app['config']["filesystems.disks.{$disk}.root"];
    $filesystemDisk->getAdapter()->setPathPrefix($finalPrefix = $root . "/{$suffix}");
}

$this->app['config']["filesystems.disks.{$disk}.root"] = $finalPrefix;
```

You can see that the code changes the prefix both on the adapter instance and in the Laravel config. I understand your proposed solution would be basically telling the framework to forget the current instance, and instead use a new one with the right prefix? I think instantiating a new adapter manually would be a bit difficult in the context of Laravel, so simply forgetting the current instance and changing the config which will be used for making the new instance might work.

Which means that in the code above, I'd remove the `setPathPrefix()` logic and use Laravel's `$filesystemManager->forgetDisk($disk)`.

Would that be a good way to do this?

**Comment by frankdejonge** [comment]
The integration of Laravel is a `config` to `instance` relationship, since you do not want an instance with that config, I don't think it matches your case. Constructing your own instance is not very hard to do, so I would suggest to do that or check if laravel wants to introduce a dynamic disk creation method.

**Comment by stancl** [comment]
I believe that in Laravel, the config serves as a sort of recipe for creating the disk. With some internal factory classes handling the actual creation.

I'm not sure if you can add a custom-made instance into the registered disks, but it probably wouldn't be a good idea anyway, because then I'd have to reimplement Laravel's logic which makes sure that the created disks respect the disk configuration.

So I'm thinking that changing the config and having Laravel forget the current instance will force it to re-create the disk the next time it's used.

**Comment by frankdejonge** [comment]
Closing this issue as a: wontfix
