### ISSUE TITLE
MountManager - Make mountFilesystem() public - like it was before and like the doc say it is

### ISSUE THREAD

**Issue by cgaube** [thephpleague/flysystem#1395]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no 
| BC Break    | no

#### Summary

Same issue as 
https://github.com/thephpleague/flysystem/issues/1286

```
@Rikijs what's the use-case that requires you to dynamically register filesystems?
```

Because all the methods in the MountManager service are private it makes it difficult / impossible to extends it 
My use case is that I want to lazy load the file systems of the mount manager so i do not have to create all the adapters at once.

With version 1 I was able to extend the MountManager and only load the filesystem that was called when it was called by using the $mountManager->mountFilesystem();
see example here https://github.com/aftdev/framework/blob/main/packages/filesystem/src/FileManager.php#L58

> Why dont I want to create all the filesystems before before creating the MountManager ?

In the world of dependency injection, a service could depend on the mount manager but only use it to access files on one Filesystem
Some filesystem may or may not require expensive setup time 
By allowing lazy loading it would avoid having this problem of instantiating all filesystems that may or may not be slow. 

I would love to hear if anybody can think about alternatives to this "issue"
The fact that MountManager only accepts an array (primitive) in its constructor make it impossible to use lazy loading by using an ArrayAccess object for example
An alternative would would be to create a LazyLoadedFileSystem to would proxy all function to the lazy loaded file system. kind of messy

I would also love to hear the reasoning behind making all class functions private. Is it so they can be easily modified without worrying about breaking changes ?

Thank you for your time 

At the very least I think changing the documentation to remove 
>// Or mount them later
$manager->mountFilesystem('local', $local);

would be helpful 
https://flysystem.thephpleague.com/v2/docs/advanced/mount-manager/

**Comment by yahyaerturan** [comment]
+1

Documentation says it can be added manually but IDE/Code says it is private. I thought to PR it, but change is quite minor, so  I gave up.
