### ISSUE TITLE
Move replicate adapter to core?

### ISSUE THREAD

**Issue by ro0NL** [thephpleague/flysystem#1409]
Would you consider moving the replicate adapter into core?

ref https://github.com/thephpleague/flysystem-replicate-adapter/issues/8

**Comment by frankdejonge** [comment]
A PR would be reviewed and accepted if submit to this repo.

**Comment by ajgarlag** [comment]
@frankdejonge I'm interested in contributing a replicate adapter compatible with v2 (I need it to support PHP 7.4), but I see that v3 was released some months ago.

- Will you accept this new adapter for V2? If the response is affirmative, I will update it to be compatible with V3 too. 
- Should I add a composer.json and a README.md file to allow the sub-split of the replicate adapter?

Edited: My PR #1492 did not receive any feedback so, I've released my [own package](https://packagist.org/packages/ajgl/flysystem-replicate) to provide a replicate adapter.
