### ISSUE TITLE
[Bug][FTP adapter] Writing files with folder in location needs to write to duplicate subfolders.

### ISSUE THREAD

**Issue by mynameisbogdan** [thephpleague/flysystem#1410]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.3.2

#### Summary

Using `league/flysystem-ftp` to write file `example.txt` to a folder like `TEST` by using location `TEST/example.txt` doesn't work. If you create `TEST/TEST` then it will write to `TEST/TEST/example.txt`

Without `TEST/TEST` created it gives:
![Screenshot 2022-01-26 at 14 58 06](https://user-images.githubusercontent.com/707714/151167014-8af758e8-db0e-4247-aba3-4a77b7f03c5e.jpg)

#### How to reproduce
```php
$filesystem->write('TEST/example.txt', 'contents');
```

**Comment by frankdejonge** [comment]
@mynameisbogdan hi, could you PR a test case that shows this? The current test suite seems to cover this case which passes, so either I don't fully understand the issue, or something weird is going on.

**Comment by mynameisbogdan** [comment]
I'll give it a try, but it seems like the issue can't be replicated when a `root` option is set.

**Comment by frankdejonge** [comment]
@mynameisbogdan you can add a test that sets up the root as well

**Comment by mynameisbogdan** [comment]
I'm sorry but I tried 3 docker images for a FTP server and all failed in one way or another.

But it seems like the primary issue was failing to run`ftp_chdir($this->connection, '');`:
`ftp_chdir(): Failed to change directory.`

Setting option `root` to `/` and not a empty string which is the default on the bundle, seems to fix my issue with the nested folders.

**Comment by mynameisbogdan** [comment]
I added a test using empty string as root in #1411.

**Comment by frankdejonge** [comment]
Please checkout #1412

**Comment by mynameisbogdan** [comment]
@frankdejonge I just tested it and it fixes my use case for `TEST/example.txt` but if I use `TEST/TEST/example.txt` it writes the file correctly but creates an empty dir `TEST/TEST/TEST`.

Will you target the 2.x branch with your fixes or only 3.x?

**Comment by mynameisbogdan** [comment]
Scenario:
```php
$filesystem->write('dirname/dirname/path.txt', 'contents');
$filesystem->write('dirname1/dirname2/dirname3/path.txt', 'contents');
```

First run is okay
![Screenshot 2022-01-27 at 14 40 59](https://user-images.githubusercontent.com/707714/151361169-a4a2a753-c18d-4f32-986f-7aa466dec958.jpg)

Second run and after is not:
![Screenshot 2022-01-27 at 14 44 14](https://user-images.githubusercontent.com/707714/151361387-808cbf92-743f-4e8e-8a24-fb0cbcc4b0ab.jpg)
![Screenshot 2022-01-27 at 14 44 42](https://user-images.githubusercontent.com/707714/151361400-47b86bc8-146a-437f-ad30-601bf2dd5e71.jpg)

Another scenario:
```php
$filesystem->write('dirname/dirname/dirname/path.txt', 'contents');
$filesystem->write('dirname1/dirname2/dirname3/path.txt', 'contents');
```

First run is okay
![Screenshot 2022-01-27 at 14 49 23](https://user-images.githubusercontent.com/707714/151362064-8e2da4c8-8714-4583-8cdd-2c7697fe7805.jpg)

Second run and after is not:
![Screenshot 2022-01-27 at 14 50 03](https://user-images.githubusercontent.com/707714/151362183-db5d7807-f653-4c93-bbfd-478c8014f1c7.jpg)
![Screenshot 2022-01-27 at 14 49 23](https://user-images.githubusercontent.com/707714/151362222-ca492a0c-66c8-48ff-b4ec-c89e544689b6.jpg)

**Comment by frankdejonge** [comment]
@mynameisbogdan I've adjusted the caching of the connection root, I've also adjusted the test case to use your described case. Could you verify the fix?

**Comment by mynameisbogdan** [comment]
@frankdejonge I'll give it a try in an hour and get back to you.

Also I think you should add a test for `dirname/dirname/path.txt` as well.

**Comment by mynameisbogdan** [comment]
@frankdejonge I just tested and the fix works 100% for me.

Will you release a new version for 2.x with this fix?

Thank you for your time.

**Comment by frankdejonge** [comment]
My plan was to release this as a patch upgrade for v3

**Comment by mynameisbogdan** [comment]
I can't upgrade to PHP 8 yet, so if you're kind to release a new version for v2 as well.

If not, I hope it's okay using `root` = `/` in the meanwhile.

Thank you.

**Comment by frankdejonge** [comment]
I'm still maintaining v1 for a while and of course v3, I'm only one person so I hope you understand if I don't. It's great that this issue is not fixed, but from a user perspective it can also be fixed by explicitly specifying the default root directory, which makes it a minor issue to keep IMO.
