### ISSUE TITLE
[3.x] Breaking change on `FtpAdapter`

### ISSUE THREAD

**Issue by nunomaduro** [thephpleague/flysystem#1414]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.2
| Package    | https://github.com/thephpleague/flysystem-ftp

#### Summary

The commit https://github.com/thephpleague/flysystem-ftp/commit/813bc063658ad3741e7f58fcb86286b5702ccd49 introduces a breaking change where the `FtpAdapter::__construct` on the line `$this->rootDirectory = $this->resolveConnectionRoot($this->connection());` is trying to resolve the given connection. 

Usually, I would expect the adapter only to try to resolve the connection on methods such as `read`, `readStream`, etc, and not while trying to instantiate the `FtpAdapter` class.

#### How to reproduce

Try to create new instance of `FtpAdapter` with an invalid connection.

**Comment by frankdejonge** [comment]
@nunomaduro what is the BC break in your opinion?

**Comment by nunomaduro** [comment]
In fact there are 2 breaking changes:

- The first breaking change is related to the `FtpAdapter::__construct` that is now throwing a `League\Flysystem\Ftp\UnableToConnectToFtpHost` exception when a given connection is invalid. That is behavior was not there in the past, therefore is a breaking change. As example, it breaks the existing Laravel Test suite, as we give a dummy connection that `__construct` argument.

- The second breaking change, is related to the fact that the connection is now eagerly resolved instead of lazy resolved. Meaning that places in my code, such as Laravel Service Providers that create `FtpAdapter` instances, are now actually resolving connections, even if I don't even use those connections later at HTTP level for example.

**Comment by frankdejonge** [comment]
PR welcome 👍

**Comment by frankdejonge** [comment]
Fixed in 3.0.3
