### ISSUE TITLE
Undefined constant Servdebt\\SlimCore\\Filesystem\\S3\\AsyncAwsS3Adapter::EXTRA_METADATA_FIELDS

### ISSUE THREAD

**Issue by jupitern** [thephpleague/flysystem#1415]
### Bug Report

I get the error bellow after update to 3.0.* when calling function fileSize() with AsyncAwsS3Adapter

Undefined constant Servdebt\\SlimCore\\Filesystem\\S3\\AsyncAwsS3Adapter::EXTRA_METADATA_FIELDS
at vendor/league/flysystem-async-aws-s3/AsyncAwsS3Adapter.php 
line 444

```php
foreach (static::EXTRA_METADATA_FIELDS as $field) {
```

works changing to self::

**Comment by frankdejonge** [comment]
@jupitern are you extending that adapter by any chance?

**Comment by jupitern** [comment]
yes. forgot to mention that. sorry.

**Comment by christoph-kluge** [comment]
Same here but custom extended class. The temporary solution from @jupitern works like a charm.

In case the const stays private maybe moving the accesor from `static` to `self`?

```
- foreach (static::EXTRA_METADATA_FIELDS as $field) {
+ foreach (self::EXTRA_METADATA_FIELDS as $field) {
```
