### ISSUE TITLE
Best way to trasfer a very large file between two remote filesystems

### ISSUE THREAD

**Issue by fabio-ivona** [thephpleague/flysystem#1417]
### Question

I am trying to transfer a very large file (~20GB) between two remote filesystems

My initial plan was to use a stream, so I implemented this one:

```php
$source = new Filesystem(new SftpAdapter([
    'host' => 'xxx.xxx.xxx.xxx',
    'username' => 'jarvis',
    'privateKey' => '*******',
    'port' => 666,
    'root' => '/var/www/'
]));

$stream = $source->readStream('backup.tar.gz');

$dest->writeStream('backup.tar.gz', $stream);
```

but the execution freeze at `$source->readStream()` and I get a connection timeout

Am I missing something? shouldn't the stream be a ligthweight resource?

Maybe there is a better way to achieve this?

Thanks for all your effort in building this great tool :heart:

**Comment by frankdejonge** [comment]
@fabio-ivona can you see if your temp directory is writable?

**Comment by fabio-ivona** [comment]
Yep, it is writable, if I try with a smaller file everything goes well

**Comment by frankdejonge** [comment]
@fabio-ivona sorry for the delay. I don't have any solid leads for this issue. It could be a phpseclib issue, but I'm not sure. I do know PHPSecLib allows you to define some constants that put it in verbose mode, which might give you some more idea of what is going on.

**Comment by fabio-ivona** [comment]
@frankdejonge thanks for your answer! I'll try to debug it with verbose mode.

I'm closing this as I'm not 100% sure is a flysystem issue and will update if there are new info

**Comment by frankdejonge** [comment]
👍
