### ISSUE TITLE
Flysystem 3 logo in documentation, installation documentation

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1419]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | doc

#### Summary

The documentation implies that Flysystem is at Version 3, but there are no docs for it.  If 3 is in beta, can there at least be a page for that on the documentation, with upgrade instructions, BC breaks, etc.?

![image](https://user-images.githubusercontent.com/619585/153416069-0365153a-3904-4299-a3ad-fcd898a50233.png)

As a newbie who is using this via a bundle (first oneup, now phpleague), I'm confused about which version this is.  The logo says flysystem3, but there's no documentation.  Can you drop the version in the logo, or add a note about updating to version 3 like you have with version 2? 

This is further complicated by the installation instructions saying that V2 is in beta:

https://flysystem.thephpleague.com/v2/docs/getting-started/#installation

![image](https://user-images.githubusercontent.com/619585/153416806-c7ef15f5-8efa-4d13-9d27-72e931cca919.png)

**Comment by frankdejonge** [comment]
Hi, I've updated the docs. V3 is an extension of V2 with only an adapter interface BC break, so no consumer-code BC break.

**Comment by tacman** [comment]
I still find this confusing.  Isn't v2 fully released?  And v3?  Again, I'm a newbie who doesn't want a beta release.

**Comment by frankdejonge** [comment]
V2 and V3 are both released, there is no beta.

**Comment by frankdejonge** [comment]
I just noticed that beta note, removed that.

**Comment by tacman** [comment]
Thanks!  

I would also recommend that the links to the version 1 docs move to the bottom, maybe even under a "Legacy" header.  Mostly this is because I tend to view the sidebar links sequentially, so I first read Getting Started, then I glaze over Security Policy, then I click on Version 1 Docs, and I've unknowingly switched to a new website, and now everything I'm reading is wrong.  

Since a web search may lead someone to either the v1 docs or the v2/3 docs, perhaps you could add to the v1 pages something like Symfony does:

![image](https://user-images.githubusercontent.com/619585/153713453-cb4e4065-6368-4bda-b157-ab823f647d7b.png)

Again, I'm just relaying my experience as a newbie who is trying to the flysystem, flyysystem-bundle  and liip-imagine to install.

**Comment by frankdejonge** [comment]
I liked that suggestion, so I made it so.
