### ISSUE TITLE
Drop support for php < 7.4 in version 2

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1420]
### Feature Request

Is there any reason to keep support for PHP 7.2?  That's the minimum in composer.json for v2 (v3 is 8.0.2+).

7.2 is dead, 7.4 adds typed properties, etc.  Even if 2.0 isn't being actively developed, flysystem-bundle has the same minimum requirement of 7.2.  If this library bumps to 7.4, then the bundle, which is being actively developed and works for both v2 and v3, can bump to 7.4 as well.

**Comment by frankdejonge** [comment]
I don't plan to support V2 as long as I do V1, this issue will resolve itself.
