### ISSUE TITLE
League\Flysystem\CorruptedPathDetected

### ISSUE THREAD

**Issue by KeanVatharo** [thephpleague/flysystem#1426]
### Question

Hi PHP Devs,
I got an error on my production environment, that I'm not sure about what happening.
The error was: 
**League\Flysystem\CorruptedPathDetected**
**Corrupted path detected: [PATH_TO_MY_FILE]/file.pdf**

I'm using Spatie Media Library package to upload attachments, files.. but when files are uploading, sometime it's working and sometime it wasn't working then popup that error message above.

Your help will much appreciated.
Thanks

**Comment by frankdejonge** [comment]
It has to do with unicode chars not being allowed that could cause path traversal and other types of security issues. Without seeing the actual path it's hard to give a more meaningful response tho. So, if you can share some more details, that would be great.

**Comment by KeanVatharo** [comment]
> It has to do with unicode chars not being allowed that could cause path traversal and other types of security issues. Without seeing the actual path it's hard to give a more meaningful response tho. So, if you can share some more details, that would be great.

Thank you, The errors are now gone. I've changed the file path to something else that is different than Unicode chars and it is working without any issues at all.

Thank you so much!
