### ISSUE TITLE
Handle non-UTF-8 paths

### ISSUE THREAD

**Issue by m-vo** [thephpleague/flysystem#1429]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | debatable :slightly_smiling_face: 
| Version     | 2 & 3

#### Summary

Paths that contain non-UTF-8 characters are problematic as they behave differently across operating systems. For instance, passing a string with such characters  to `dirname` will produce another result on Windows as it does on Linux [depending on the set codepage](https://www.php.net/manual/en/function.dirname.php). It's also not easily possible to create files with non-UTF-8 names on some systems (like MacOS or Windows), but they can e.g. still be copied. In fact this is where errors typically start appear: people copying files across file systems. 

In my view, trying to correctly support non-UTF-8 paths has few benefits but brings portability issues, while not caring about them can introduce subtle errors. You can handle this client side, but the Flysystem `Filesystem` or adapters would IMHO be better suited for this.

Detection could look like this:

```php
if (preg_match('//u', $path) !== 1) {
    // bad path; ignore or throw an exception
}
```

#### How to reproduce
1. To verify different behavior of `dirname`, run the following on the console:
    ```console
    php -r 'var_dump(dirname("b\xE4r/x"));'
    ```
    It outputs `string(3) "b�r"` on Linux and `string(4) "bär"` on Windows.

2. To see this in effect you could write a file `b\xE4r` with the `LocalFilesystemAdapter`. You'll get a file with the name `bär` on Windows and `b\xE4r` on Linux. I assume if you instead write a file `foo` in an existing directory `b\xE4r`, you'll most likely get an error that the directory does not exist on Windows (though I'm on Linux and cannot test this).

To facilitate testing, it's possible to set a compatible codepage on windows with `sapi_windows_cp_set(1252);` and then run the commands. The output then matches the one on Linux, which allows creating "malformed" files/directories. It's not a suitable workaround for the initial problem, though.

**Comment by frankdejonge** [comment]
There is a path normalizer interface that can be used to implement this check, does that help?
