### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::getAdapter()

### ISSUE THREAD

**Issue by mengnarorth** [thephpleague/flysystem#1431]
use League\Flysystem\Adapter\Local;

Call to undefined method League\Flysystem\Filesystem::getAdapter()
if (!$this->storage->getDriver()->getAdapter() instanceof Local) {
            Handler::error('Error', 'only works for local storage.');
}

Laravel 9

**Comment by frankdejonge** [comment]
Closing as it seems this issue was not created by a human.
