### ISSUE TITLE
How would one get the path prefix?

### ISSUE THREAD

**Issue by grenadecx** [thephpleague/flysystem#1436]
In version 1.x it was possible to get the path by calling getPathPrefix function on the adapter. This seems to be removed. How would one solve it now?

**Comment by frankdejonge** [comment]
If you have the prefix and the path, you can concatenate the strings to get the full path.

**Comment by grenadecx** [comment]
Yeah I understand that. What if I don't?

**Comment by frankdejonge** [comment]
You pass it the prefix when you construct the adapter, so you have it, right?

**Comment by grenadecx** [comment]
I don't. Well, Laravel probably does at some point. But alright, if that's the only method now I'll make due. Thanks.

**Comment by frankdejonge** [comment]
in Flysystem 1.x there was an ever sliding scale of people complaining about not getting access to the all the internals, which basically converted the adapter into a service locator and configuration machine, which this is not. Configuration should be managed separately, and expose configuration setting deliberately. This is not a responsibility of a filesystem abstraction library. It was something that landed in Flysystem but I have regretted that decision, so reverted it for V2.

**Comment by grenadecx** [comment]
Alright, that make sense. Thanks for taking the time to respond.
