### ISSUE TITLE
Improve support for PHP 8.1

### ISSUE THREAD

**Issue by marckyes** [thephpleague/flysystem#1453]
Hi Frank,

the folks at Google have just released a new version of their Cloud Storage library, which fixes an [issue](https://github.com/googleapis/google-cloud-php/issues/4554) happening when using php 8.1.

Flysystem seems to be affected by it, we and other users of `spatie/laravel-google-cloud-storage` have been running into issues mentioned [here](https://github.com/spatie/laravel-google-cloud-storage/issues/15) and [here](https://github.com/spatie/laravel-google-cloud-storage/issues/18).

Should we open a PR with the updated dependency (^1.26)?

**Comment by frankdejonge** [comment]
Hi @marckyes, this is package allows the installation of the fixed version so I do not see the need for upgrading that minimum version. People who will install at a later time will install automatically the corrected version. So upgrading this here doesn't actually fix anything here. Similar to how bugs can be introduces in Flysystem, I do not expect other packages to change their required version on this package.

**Comment by marckyes** [comment]
Gotcha (`~` vs `^`), sorry for wasting your time 🙏. Thanks for the explanation :)

**Comment by frankdejonge** [comment]
@marckyes no worries, you came here with good intentions, trying to make it better for other people and I can only say that I appreciate that 👍
