### ISSUE TITLE
Update documentation for ZipArchive

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1462]
Searching the Flysystem Documentation for ZipArchive shows the results below.

The first link is to version 1, which doesn't work anymore:

https://flysystem.thephpleague.com/v1/docs/adapter/zip-archive/#article

The second link is a reference to the moved adapters:

https://flysystem.thephpleague.com/v1/docs/advanced/upgrade-to-1.0.0/#relocated-adapters

But the link under "Relocated Adapters" for ZipArchive is broken:

![image](https://user-images.githubusercontent.com/619585/167130531-9527a331-f006-4df1-b359-077e22f69673.png)

https://flysystem.thephpleague.com/docs/adapter/zip-archive/

I've submitted a PR for the  README in zip-archive, but some documentation would be very helpful.  Is ZipArchive still officially supported? 

https://flysystem.thephpleague.com/docs/

![image](https://user-images.githubusercontent.com/619585/167131250-2a5f5e97-08aa-43a5-a631-bc2be24d1dc3.png)
 
Thanks.

**Comment by frankdejonge** [comment]
This is done (https://flysystem.thephpleague.com/docs/adapter/zip-archive/). A PR would have been helpful. Seven thumbs up, no contributions... :shrug:
