### ISSUE TITLE
StatCache disabled in SftpAdapter

### ISSUE THREAD

**Issue by sdwru** [thephpleague/flysystem#1463]
Is there a particular reason StatCache is disabled on PHPSeclib SFTP adapter or is that a legacy thing from back when flysystem used its own cache?

https://github.com/thephpleague/flysystem/blob/670df21225d68d165a8df38587ac3f41caf608f8/src/PhpseclibV3/SftpConnectionProvider.php#L142

**Comment by frankdejonge** [comment]
Version 3.14.0 will allow you to configure this.
