### ISSUE TITLE
Would block based operations be in scope of this library?

### ISSUE THREAD

**Issue by meidlinga** [thephpleague/flysystem#1480]
### Question

I would like to see support for block based writes. In my understanding, a file can be written only as whole making it hard to use with very large files.
A block based write would solve this problem, since we could process and send smaller chunks before commiting.
In a local file system this could be implemented with fwrite and a file position. 
In Azure this could be implemented using $blobRestProxy->createBlobBlock.

I am aware that this is a complex topic and would be willing to contribute, but wanted to clarify upfront if this would fit.

**Comment by frankdejonge** [comment]
I don't have the capacity to support a new vertical of abstraction. I'd encourage people who need this to create their own library.
