### ISSUE TITLE
Type Error in FTP Adapter after upgrading to PHP 8.0 (src/Adapter/Ftp.php line 577)

### ISSUE THREAD

**Issue by adrenth** [thephpleague/flysystem#1481]
### Bug Report

After updating my project to from PHP 7.4 to PHP 8.0.19 (Laravel 6.x app) the FTP Adapter `League\Flysystem\Adapter\Ftp` gave the following error:

```
In Ftp.php line 577:
 implode(): Argument #1 ($pieces) must be of type array, string given
```

Which leads to the following code:

```php
private function getRawExecResponseCode($command)
{
    $response = @ftp_raw($this->connection, trim($command));

    return (int) preg_replace('/\D/', '', implode(' ', $response)); // <---- line 577; $response is of type `string`
}
```

Apparently the native `ftp_raw` method returns a `string` as return value instead of `array|null`.

Setting the connection configuration `passive = true` fixes the issue for now. But this kind of type errors should not occur.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.9

#### Summary

The PHP error is resulting in not be able to upload files to a FTP location.

**Comment by frankdejonge** [comment]
According to the PHP docs, that should not be possible. Perhaps it's a PHP bug? https://www.php.net/manual/en/function.ftp-raw.php

**Comment by adrenth** [comment]
@frankdejonge I have reported this issue on the PHP repository as well. And there is some new input to this issue, see: https://github.com/php/php-src/issues/9667#issuecomment-1266635489

I will try their suggestion to my own `CustomFtp` adapter (which extends `Ftp` adapter) to check if this is the case.

**Comment by frankdejonge** [comment]
Version `1.1.10` should fix the effect of this.

**Comment by adrenth** [comment]
@frankdejonge Thank you! I confirm it solves the issue. The PHP community will take care of the rest ;-)
