### ISSUE TITLE
Hard time writing file with an empty string

### ISSUE THREAD

**Issue by vasilvestre** [thephpleague/flysystem#1484]
Question
I'm actually creating an adapter and I have trouble updating a file with an empty stream. Using base64, it always fail due to the service not supporting data:application/x-empty;base64, as a content. With a local file that have an empty body, this Flysystem exception appear League\Flysystem\UnableToWriteFile: Empty file

How should I handle this ?

**Comment by vasilvestre** [comment]
My bad, I failed with the exception thrown. In fact the service does not allow empty files, while flysystem tests require to be able to upload one. How could I handle this ?

**Comment by frankdejonge** [comment]
Hi, is this still relevant? I don’t have any pointers as there is very little info in the issue. If you supply things like installed versions and used adapters I may be able to help.

**Comment by vasilvestre** [comment]
My failing test is here : https://github.com/vasilvestre/flysystem-cloudinary-adapter/blob/main/tests/CloudinaryAdapterTest.php#L260
Actually the adapter works fine to me, I use it in a project. Last problem I have is the entity delete not removing the file in cloudinary but it's another issue I guess

**Comment by frankdejonge** [comment]
If your underlying filesystem doesn't allow creating empty files, letting it fail is the correct behaviour. Nothing more to do with that I guess. As for the unable to delete the file, I don't know cloudinary that well, so not able to help there 😅

**Comment by vasilvestre** [comment]
>> If your underlying filesystem doesn't allow creating empty files, letting it fail is the correct behaviour. Nothing more to do with that I guess.

Right thank you !

>> As for the unable to delete the file, I don't know cloudinary that well, so not able to help there sweat_smile

Delete do work, but the function does not seem to be called. There's a flystem option to delete file on adapter when you remove the entity, I don't know if any more configuration is needed to enable this.

**Comment by frankdejonge** [comment]
Flysystem doesn't have entities so I don't really understand what you mean.

**Comment by vasilvestre** [comment]
> Flysystem doesn't have entities so I don't really understand what you mean.

I must be confused about flysystem and gaufrette which use flysystem. Thank you for help
