### ISSUE TITLE
Call to private method League\Flysystem\MountManager::mountFilesystem

### ISSUE THREAD

**Issue by nabeeljavaid** [thephpleague/flysystem#1485]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.21

#### Summary

I am getting following error when I try to mount later

Error: Call to private method League\Flysystem\MountManager::mountFilesystem()

According to documentation "mountFilesystem" should be public please see attached screenshots

![Flysystem V3 - Mount Manager - Documentation](https://user-images.githubusercontent.com/2786954/174005035-61be918c-9c82-4ffd-8e45-58ac83108c73.png)
![Flysystem V3 - Mount Manager - Call to undefined method](https://user-images.githubusercontent.com/2786954/174005056-1c4bd7ce-ed15-4f80-bdd3-b6feef49c725.png)

#### How to reproduce

// Add them in the constructor
$mountManager = new League\Flysystem\MountManager([
    'ftp' => $ftp,
    's3' => $s3,
]);

// Or mount them later
$mountManager->mountFilesystem('local', $local);

**Comment by frankdejonge** [comment]
Removed the docs section, this was a copy/paste error.
