### ISSUE TITLE
Laravel 9 Calling the Storage::exists() method before Storage::files() doesn't list the files

### ISSUE THREAD

**Issue by karunkshrestha** [thephpleague/flysystem#1486]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0

#### How to reproduce
`
//Breaks
Storage::disk('ftp')->exists('test');

$files = Storage::disk('ftp')->files('test');
dd($files);

//This returns empty array
//^ []

//If however I comment out the exists() check, it works.
//Storage::disk('ftp')->exists('test');

$files = Storage::disk('ftp')->files('test');
dd($files);

//output:
// array:2 [
  0 => "test/first.xml"
  1 => "test/second.xml"
]

`

**Comment by frankdejonge** [comment]
Please open an issue with the laravel repository.
