### ISSUE TITLE
Resolve browser path

### ISSUE THREAD

**Issue by loevgaard** [thephpleague/flysystem#1491]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Scenario / Use-case

When I use flysystem to save my files, oftentimes I would also want to be able to reference them via an URL. Say I saved my file to `/var/www/public/images/image.jpg` on `https://example.com` then I would love to be able to call a method that would return `https://example.com/images/image.jpg`

**Comment by frankdejonge** [comment]
This is now supported using public URLs: https://flysystem.thephpleague.com/docs/usage/public-urls/

**Comment by loevgaard** [comment]
Thank you ❤️
