### ISSUE TITLE
LocalFilesystemAdapter side effect

### ISSUE THREAD

**Issue by Radiergummi** [thephpleague/flysystem#1496]
### Bug Report
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | `3.0.21`

#### Summary
I'm using the [FlySystem Bundle for Symfony](https://github.com/thephpleague/flysystem-bundle), and inject a `FilesystemOperator $localStorage` into one of my classes; it is configured to use a path not available on my local machine, but within a Docker container. This class is then used in a custom introspection command (showing the current pipeline configuration), which I intended to run on the local machine.

As the local filesystem adapter is injected into the class, and the class is in turn injected into my command instance, the adapter will be instantiated, too. Unexpectedly, though, this causes [the mount path to be validated](https://github.com/thephpleague/flysystem/blob/dea729954c596bdb6cdaecba6f73df9f3e2c4255/src/Local/LocalFilesystemAdapter.php#L94), yielding an exception:

```
In UnableToCreateDirectory.php line 20:
                                                                            
  Unable to create a directory at /opt/storage. mkdir(): Permission denied
```
  
**I would have expected this check upon the first filesystem operation, not sooner, that is: I would strongly expect library code to not have any side effects in their constructor - just as I would never expect a database class to attempt to connect within its constructor.**

This feels like a bug to me. What's the rationale behind executing runtime sanity checks in the constructor?

This was [first reported in the flysystem-bundle repository](https://github.com/thephpleague/flysystem-bundle/issues/102#issuecomment-1168486202).

#### How to reproduce

1. Create an instance of a local filesystem adapter configured to use a path that _might_ be available later
2. Witness the exception

**Comment by frankdejonge** [comment]
Hi @Radiergummi,

In order to maintain backwards compatibility, I've added a new constructor arguments that allows you to defer root directory creation until a write (or copy/move) happens. This ensures the current usages that rely on this behaviour do not break, while you can opt-into lazy setting up when needed. I'm expecting to release this as 3.1.0 today.

**Comment by Radiergummi** [comment]
Hi @frankdejonge,

thank you, that's great! I'll follow this up in the bundle repository.
