### ISSUE TITLE
Can't read multiple files sequentially using FTP Adapter

### ISSUE THREAD

**Issue by annis-souames** [thephpleague/flysystem#1522]
### Bug Report

I am trying to use the FTP adapter to read multiple files from an ftp server sequentially, the problem is that the adapter can read the first file successfully, then it throws `League\Flysystem\UnableToReadFile with message 'Unable to read file from location` for the 2nd file , the third file is read successfully then the fourth can't be read, etc.

I am using the `read` method provided by the adapter, this also happens when trying to read the same file multiple times : first call to the method, the file is read successfully, then 2nd time it throws the same exception, then the third time it's read successfully, etc.

#### How to reproduce

After connecting to an ftp server, try to read a given file `file.txt` multiple times using `$ftpAdapter->read('path/to/file.txt)' (without destructing the ftpAdapter).

**Comment by frankdejonge** [comment]
I've added a test case for this, which passes (https://github.com/thephpleague/flysystem/commit/6159c91d401edb207d113376e607a4256a05101f). Must be something with your specific FTP server. Have you contacted the administrator with this issue?
