### ISSUE TITLE
LocalFilesystem throws exception on `mimeType($directory)`

### ISSUE THREAD

**Issue by jakejohns** [thephpleague/flysystem#1534]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.16

#### Summary

Since [this commit](https://github.com/thephpleague/flysystem/commit/dea729954c596bdb6cdaecba6f73df9f3e2c4255#diff-7b9e8c38cc39b1ca85d7f5fc1979c7ef05760422b352502936ab140bc2630b34R371) `LocalFilesystemAdapter` `$filesystem->mimeType($target);` throws an exception if the `$target` is a directory. Previously, it would return the string `directory`. 

#### How to reproduce

Call `mimeType` on a directory.

```php
<?php
// $ mkdir -p fake/foo/bar/baz
// $ tree fake
// fake
// └── foo
//     └── bar
//         └── baz
//
// 3 directories, 0 files

require 'vendor/autoload.php';

$rootPath = './fake';
$adapter = new League\Flysystem\Local\LocalFilesystemAdapter($rootPath);
$filesystem = new League\Flysystem\Filesystem($adapter);
var_dump($filesystem->mimeType('foo'));

// ## 3.0.15
// string(9) "directory"

// ## 3.0.16
// PHP Fatal error:  Uncaught League\Flysystem\UnableToRetrieveMetadata: Unable to retrieve the mime_type for file at location: ./fake/foo
```
#### How to solve

Use `file_exists` instead of `is_file`

**Comment by frankdejonge** [comment]
Why do you need to know the mime-type of a directory?

**Comment by jakejohns** [comment]
@frankdejonge , I think a better question is *why would this throw an exception*? It's not an exception circumstance.

Examples would include places where `$target` is defined by user input, or a loop, etc. and I *do not yet know* that a specific item is a directory.

(furthermore, this introduced a breaking change in a patch update)
