### ISSUE TITLE
Issue when uploading filename with RLM

### ISSUE THREAD

**Issue by hsul4n** [thephpleague/flysystem#1538]
Version: 3.0.16

Getting `Corrupted path detected` when uploading a file that contains [right-to-left-mark](https://en.wikipedia.org/wiki/Right-to-left_mark) (RLM).

Here's an example for filename
```
Foo Bar - (Without RLM)
Foo‏ Bar - (With RLM)
```

Here's `League\Flysystem` package throws exception:
https://github.com/thephpleague/flysystem/blob/f5e93fad64cff5f45a1f79246dae15b31099b105/src/WhitespacePathNormalizer.php#L19

**Comment by frankdejonge** [comment]
Hi @hsul4n,

The default path normalizer removes anything that may cause path escalations and does so aggressively. You're free to implement your own path normalizer to accept this, or you can remove these characters before passing them to Flysystem. For security reasons, I will not make the default less strict.

**Comment by hsul4n** [comment]
I've solved the issue by replacing `RLM` and all things goes will, but I open issue because `RLM` unicode character is used common within Arabic regions and doesn't relate to any security issue.

**Comment by frankdejonge** [comment]
I'm going to close this issue as this issue can be worked around. I'm not going to loosen the restrictions because that might open up more security cases.
