### ISSUE TITLE
phpspec/prophecy is now explicitely needed for tests

### ISSUE THREAD

**Issue by DavidPrevot** [thephpleague/flysystem#1540]
### Bug Report

Since PHPUnit dropped phpspec/prophecy from its dependencies (https://github.com/sebastianbergmann/phpunit/issues/5033), the following errors are triggered when running the testsuite with latest PHPUnit.

~~~
There were 97 errors:

1) EmptyDirPluginTests::testPlugin
PHPUnit\Framework\Exception: This test uses TestCase::prophesize(), but phpspec/prophecy is not installed. Please run "composer require --dev phpspec/prophecy".
[…]
~~~

Regards

David

**Comment by frankdejonge** [comment]
The v1 doesn't use latest PHPUnit and v3 doesn't use phpspec. How did you get this error?
