### ISSUE TITLE
update flysystem phpseclib 

### ISSUE THREAD

**Issue by fransweerts** [thephpleague/flysystem#1541]
#### Summary
When I try to install flysystem-sftp-v3  composer can not install it because of the phpseclib dependency. 

- flysystem-sftp-v3  uses phpseclib v3. See composer : https://github.com/thephpleague/flysystem-sftp-v3/blob/3.x/composer.json 

- flysystem core uses phpseclib v2.  See composer: https://github.com/thephpleague/flysystem/blob/3.x/composer.json

Is it possible to update phpseclib to v3?

**Comment by frankdejonge** [comment]
Hi @fransweerts,

That's a dev dependency, so it doesn't conflict. I just tried it and it works. One of your other dependencies may be conflicting here.

**Comment by frankdejonge** [comment]
[composer.lock.txt](https://github.com/thephpleague/flysystem/files/9452671/composer.lock.txt)

lock file for proof
