### ISSUE TITLE
Bug when setting a 'root' path in s3 adapter

### ISSUE THREAD

**Issue by omaressaouaf** [thephpleague/flysystem#1542]
### Description

This issue occurs when using Laravel s3 disk and specifying root path in the config. what happens is when generating a s3 url using the storage facade the end path character "/" is being converted to "%5C" which is  the hex ASCII representation of "backslash" . if I remove the root path from the config , then everything works as expected . i saw a couple of people reporting this issue in Laravel but the latter claims that this is not a Laravel issue but a flysystem bug.

#### How to reproduce

1. Setup a disk in Laravel config filesystem.php that uses the s3 driver
2. Define a 'root' key in the filesystem config for that disk 
```php
 s3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
            'root' => "tenants/" // when specifying root the issue occurs
        ],
```
3. Try to generate an s3 url or temporary url using the Storage facade

```php
Storage::disk("s3")->url("media/1/picture.png");
```
#### Expected result

`https://bucket-name.s3.amazonaws.com/tenants/media/1/picture.png`

#### Actual results

`https://bucket-name.s3.amazonaws.com/tenants%5Cmedia/1/picture.png`

**Comment by laurentmeuwly** [comment]
This happen on Windows system.
Add the `'directory_separator'` to your s3 block inside the filesystems config.

 ```
s3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
            'root' => "tenants"
            'directory_separator' => '/'
        ],
```
This solves the same problem on my side:
PHP: 8.1.9
Laravel: 9.31.0
flysytem-aws-s3-v3: 3.5.0

**Comment by frankdejonge** [comment]
Please open an issue with Laravel, this functionality is not part of Flysystem.
