### ISSUE TITLE
Reading and Writing csv files from S3 using streams 

### ISSUE THREAD

**Issue by yourwebmaker** [thephpleague/flysystem#1545]
## Question
 I’m currently working with big files so I’m obligated to use streams and I’m trying to use CSV league combined with Flysystem. The files are stored in S3.
I managed to upload a new empty file normally using the following code.
``` php
$storage = $container->get(Filesystem::class); // this is an instance League filesystem, using the S3 Adapter
$fileName = self::FILE_NAME;
$headers = [‘email’ , ‘full name’];
$stream = tmpfile();
$writer = Writer::createFromStream($stream);
$writer->insertOne($headers);
$storage->writeStream($fileName, $stream);
```
Porem quando tentamos adicionar novo conteudo a esse csv, nada acontece.
When I try to add new content to the file created before, nothing happens, the **writeStream** doesn’t seem to update the file and also does not update the stream with the new content.
```php
$storage = $container->get(Filesystem::class);
$filePath = self::FILE_NAME;
$stream = $storage->readStream($filePath);
$writer = Writer::createFromStream($stream);
$newLines = [
            [‘[mail@mail.com](mailto:mail@mail.com)’,‘manjil’],
            [‘[mail@mail.com](mailto:mail@mail.com)’,‘daniel’]
];
$writer->insertAll($newLines);
$storage->writeStream($filePath, $stream)
```
Is there something I’m doing wrong? When we use with local file system adapter, it works as expected because the **insertAll** updates the file directly which does not occur in S3.

**Comment by frankdejonge** [comment]
What version of Flysystem are you using?

**Comment by Silva404** [comment]
I'm im the same project as Daniel, we are using  flysystem 3.2.1, flysystem aws 3.2 and CSV league version 9.8

**Comment by frankdejonge** [comment]
The default AWS S3 adapter stream reads, this causes the underlying resource to not be seakable. Flysystem rewinds seekable streams when writing by default. The local adapter read streams are seekable, that's why it works there. You can configure the AWS S3 adapter to not stream reads, which makes the read stream seekable, which then makes you example work.

I used this example code to verify and it worked:

```php
<?php

use Aws\S3\S3Client;
use League\Csv\Writer;
use League\Flysystem\AwsS3V3\AwsS3V3Adapter;
use League\Flysystem\Filesystem;

include __DIR__.'/vendor/autoload.php';

$key = 'redacted';
$secret = 'redacted';
$options = [
    'version' => 'latest',
    'credentials' => compact('key', 'secret'),
    'region' => 'redacted',
];

$client = new S3Client($options);
$adapter = new AwsS3V3Adapter($client, 'redacted', streamReads: false);
$storage = new Filesystem($adapter);
$storage->write('test.csv', '');

$filePath = 'test.csv';
$stream = $storage->readStream($filePath);
$writer = Writer::createFromStream($stream);
$newLines = [
    ['[mail@mail.com](mailto:mail@mail.com)', 'manjil'],
    ['[mail@mail.com](mailto:mail@mail.com)', 'daniel'],
];
$writer->insertAll($newLines);
$storage->writeStream($filePath, $stream);

var_dump($storage->read($filePath));
```

**Comment by Silva404** [comment]
Using this example, it works but there is another issue, we are trying to insert more content in the file per batch and if you run it again instead of inserting new content it will override the existing one. What are doing wrong?

**Comment by Silva404** [comment]
@frankdejonge

**Comment by frankdejonge** [comment]
This is not as free support channel, @Silva404
