### ISSUE TITLE
Delete directory fails when symlink is broken

### ISSUE THREAD

**Issue by Dmcz** [thephpleague/flysystem#1560]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 1.1.9

#### Summary
Delete directory fails when symlink is broken. 

Directory example
```bash
root@php-webserver:/home/test# tree
.
|-- failure
|   `-- test.txt -> /home/test/test1.txt
|-- success
|   `-- test.txt -> /home/test/test.txt
`-- test.txt
```

delete `/home/test/success` successed, but failed to delete `/home/test/failure`
throw exception "Unreadable file encountered:"

I think,  if the type is "link", there is no need to judge whether it is readable or not?
just return the result of "unlink()"

**Comment by frankdejonge** [comment]
Flysystem 1.x is not maintained anymore apart from security fixes, please upgrade to 3.x where this is fixed.
