### ISSUE TITLE
S3: add getClient() method to AwsS3V3Adapter

### ISSUE THREAD

**Issue by franksl** [thephpleague/flysystem#1561]
Hello,
I think it would be very useful to retrieve the S3 client instance passed to the constructor, so that it could be used to perform operations outside the filesystem.
Thanks,
Frank

**Comment by yellow1912** [comment]
I was about to ask the same question as well. The filesystem should also expose a method to get the adapter object.

The only issue with getClient is that it's very specific to aws and I don't know how we can/should put that method into the interface as well.

**Comment by frankdejonge** [comment]
Flysystem is not a service locator. Either use reflection to get it, or resolve the client from the same place you're getting it from to supply it to the adapter.

**Comment by franksl** [comment]
That's at least debatable in my opinion, flysystem to me represents my filesystem, which I see as a service. And I think I should be able to get informations and features about my filesystem as long as perform operations or extend the ones that are not implemented (correctly because they may not be supported by all adapters).
In any case I understand and respect your point even if I don't agree with it. 
I'll rely on something else, avoiding reflection totally, that is simply not the way of doing things in my opinion.
Thanks,
Frank
