### ISSUE TITLE
Undefined array key "type"

### ISSUE THREAD

**Issue by frankmichel** [thephpleague/flysystem#1563]
We have recently switched from v1 to v3 of this package. However, the v3 version is throwing the following error when trying to access files in an existing directory like so:

```
$disk = Storage::disk('sftp');
$directories = $disk->directories('documents'); // this will only be used for testing to dump and check if the directory exists
$files = $disk->files('documents/whitepapers');
```

`dump($directories)` will succesfully return:

```
array:1 [
  0 => "documents/whitepapers"
]
```

However $files cannot be used, since an error is being thrown:

```
League\Flysystem\UnableToListContents
Unable to list contents for 'documents/whitepapers', shallow listing

Reason: Undefined array key "type"
```

So the **Undefined array key "type"** of the StorageAttributes is causing the issue. However, I have no idea how to fix this. It worked fine in v1 of the package with the same server, directories and files.

Is that an issue in the package or am I doing something wrong here?

_The code is running on PHP 8.1.8 and Laravel 9.30.1 with league/flysystem-sftp-v3 3.5.2_

See also https://github.com/thephpleague/flysystem-sftp-v3/issues/7 and https://github.com/thephpleague/flysystem-sftp-v3/pull/8

**Comment by frankdejonge** [comment]
Fixed in 3.5.3
