### ISSUE TITLE
Incompatibility between league/flysystem-adapter-test-utilities:^3 and league/flysystem:^2

### ISSUE THREAD

**Issue by ajgarlag** [thephpleague/flysystem#1572]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | league/flysystem-adapter-test-utilities:^3

#### Summary

Currently, [`composer.json`](https://github.com/thephpleague/flysystem/blob/3.x/src/AdapterTestUtilities/composer.json) file for `league/flysystem-adapter-test-utilities` allows installation with Flysystem V2, but in https://github.com/thephpleague/flysystem/blob/3.x/src/AdapterTestUtilities/FilesystemAdapterTestCase.php#L317 the method `directoryExists` (added in V3) is being tested unconditionally.

I can provide a PR removing the compatibility with V2 from composer.json or skipping tests for `directoryExists` method if no present in the adapter. @frankdejonge, what would be your preferred option?

#### How to reproduce

You can see the problem reproduced when testing my V2 compatible replicate adapter with `league/flysystem-adapter-test-utilities:^3` in https://github.com/ajgarlag/flysystem-replicate/actions/runs/3284991347/jobs/5411595525

**Comment by frankdejonge** [comment]
@ajgarlag let's remove compatibility with V2, it's almost fully out of support anyway 👍

**Comment by ajgarlag** [comment]
@frankdejonge PR submitted.

I'd like to have #1571 and #1574 labeled with `hacktoberfest-accepted` if you agree.
