### ISSUE TITLE
delete method reliable?

### ISSUE THREAD

**Issue by rlzdesenv** [thephpleague/flysystem#1575]
Is the delete method reliable?
even if I pass a directory to it, it won't delete it?

`$filesystem->delete('/directory')`

**Comment by frankdejonge** [comment]
you should use deleteDirectory to delete a directory

**Comment by rlzdesenv** [comment]
> you should use deleteDirectory to delete a directory

yes I would just like to be sure that the `delete` method does not delete a directory if the parameter is entered by mistake in it

**Comment by frankdejonge** [comment]
For the local filesystem if its not a file, there is no deletion. For cloud filesystems it does a delete by name, which could delete a virtual directory, but wouldn't actually delete the files as they are only prefixed with the directory name as a key. So it should be safe. That said, if you want to be 1000% sure, you can always check if the file exists using `fileExists` to ensure it's a file.
