### ISSUE TITLE
Possible to support a StreamInterface

### ISSUE THREAD

**Issue by Deltachaos** [thephpleague/flysystem#1579]
I need to reopen #795 with this issue.

The solution provided there to always use `StreamInterface::detach` is ignoring the fact that there are streams that cannot be detached. This is the reason why `detach` can also return `null`.

Handling streams in php is not consistent. The only real accepted userland interface is `Psr\Http\Message\StreamInterface` which is widely supported in the community.

Why was this interface created? It was created because `stream_wrapper_register` for custom userland stream implementations is just a mess.

Now one can argue: What has this to do with flysystem? Answer is simple: Currently there is no way to write programmatically generated data consistently on the fly to an adapter. The reason is that as mentioned in #795, `stream_get_meta_data` will always return `seekable` for custom wrappers.

Programmatically generated streams of data that should be written to a file, cannot be seeked. Any useland implementation for a stream of programmatically generated data will fail for example with the AWS S3 adapter, as it trys to seek in the stream and then has inconsistent data.

How does generating a stream of data by an algorithm would work in PHP? We do now have `Generators` that makes this extremely easy. For example:

```php
<?php

function myGenerator() {
  yield 'HA';
  yield 'LLO ';
  yield 'WE';
  yield 'LT';
}

$stream = new \phpstreams\Stream(myGenerator());

// now i have an PSR-7 Steam object, but any library that is able to convert a Stream object into a resource, like for example \GuzzleHttp\Psr7\ StreamWrapper will fail as they are always seekable
```

**Comment by frankdejonge** [comment]
If you can't do this in user-land, how do you expect Flysystem to do it?
