### ISSUE TITLE
NotFoundException thrown when using exists method with Google Cloud Storage adapter

### ISSUE THREAD

**Issue by ajanini** [thephpleague/flysystem#1581]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.10.2   |
| Adapter Name      | GCS |
| Adapter version   | 3.10.0   |

#### Summary

I'm using Laravel 9.36.4 with [Spatie Driver](https://github.com/spatie/laravel-google-cloud-storage) 2.0.5.
When testing if a file exists, a `Google\Cloud\Core\Exception\NotFoundException` is thrown instead of the expected boolean return.

#### How to reproduce

```php
$disk = Storage::disk('public');
$exists = $disk->exists('foobar.txt');
dd($exists);
```

Results in:

<img width="1242" alt="Captura de Tela 2022-10-25 às 12 26 30" src="https://user-images.githubusercontent.com/3225794/197815914-4e5afbac-25a9-4c22-8af6-7c9a62073fdb.png">

---

Not sure if I'm doing something wrong...

**Comment by frankdejonge** [comment]
@ajanini what version of `google/cloud-storage` are you using?

**Comment by ajanini** [comment]
@frankdejonge google/cloud-storage 1.28.1.

It looks like the problem is with the Spatie driver.
I was able to get it working by downgrading `spatie/laravel-google-cloud-storage` from 2.0.5 to **2.0.3**.

Please forgive me. This issue may be closed.

**Comment by frankdejonge** [comment]
All good @ajanini 👍 thanks for reporting back
