### ISSUE TITLE
Test generating_a_public_url really public?

### ISSUE THREAD

**Issue by tinect** [thephpleague/flysystem#1592]
### Question

Is it really intended that the test [generating_a_public_url](https://github.com/thephpleague/flysystem/blob/712478fdaab4ad79b14e01d3f378208555f33e56/src/AdapterTestUtilities/FilesystemAdapterTestCase.php#L794) want's to access to a test-domain?

This seems overambitious to me in a test 🤔

**Comment by frankdejonge** [comment]
Hi :) yes, that is the intention. What better proof than the real deal.

**Comment by tinect** [comment]
Hi @frankdejonge
okay, I see the reasons now :-) real-live-tests on real external storage 👍 

Thank you! :-)
