### ISSUE TITLE
Change namespace to flysystem readonly

### ISSUE THREAD

**Issue by abeltas** [thephpleague/flysystem#1597]
Hellow, congratulation master.

The problem was with PHP 8.1, readonly is now part of the language. and causes the file to come out out of date and generate an alert.

![Captura de pantalla 2022-11-23 155137](https://user-images.githubusercontent.com/16218186/203635256-5b5cf2f8-5d75-45b3-b6c8-f591632c2c50.png)

**Comment by frankdejonge** [comment]
Isn’t this a problem with the IDE? I thought this wasn’t reserved as a namespace segment. I’ll check

**Comment by frankdejonge** [comment]
Hi @abeltas,

I can run this code and it's just fine:

```php
namespace Abstract\Echo\Else\False {

class Lol {}

}

namespace {
    var_dump(new Abstract\Echo\Else\False\Lol());
}
```

PHPStorm doesn't have an issue with this, I'm guessing you're using VsCode? Perhaps you can file an issue with them. I'm going to close the PR since I don't think it's worth it to make people migrate namespace. Thanks for flagging it tho 👍
