### ISSUE TITLE
LocalFilesystemDriver::listContents() is unusable for real workloads

### ISSUE THREAD

**Issue by dvcsiky** [thephpleague/flysystem#1606]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | all   |
| Adapter Name      | Local |
| Adapter version   | all   |

#### Summary

Using `DirectoryIterator` is problematic.
The listing is obtained (see php-src/ext/spl_directory.c) by spl_filesystem_dir_open() immediately, then cached.
So that when someone iterates on the result, it is guaranteed to be outdated.

The symptom superficially matches that of #472.

```
RuntimeException: SplFileInfo::getType(): Lstat failed for [%s]
#%d /vendor/league/flysystem/src/Adapter/Local.php(509): SplFileInfo::getType
#%d /vendor/league/flysystem/src/Adapter/Local.php(509): League\Flysystem\Adapter\Local::mapFileInfo
#%d /vendor/league/flysystem/src/Adapter/Local.php(452): League\Flysystem\Adapter\Local::normalizeFileInfo
#%d /vendor/league/flysystem/src/Adapter/Local.php(288): League\Flysystem\Adapter\Local::listContents
#%d /vendor/league/flysystem/src/Filesystem.php(272): League\Flysystem\Filesystem::listContents
```
(Note the error example is from 1.x, but the problem exists in 3.x / Laravel 9 as well.)

#### How to reproduce

It is quite hard. It requires a file to be deleted during iteration.
So the default "hey, we have a simple request/response workflow in a single thread" mindset is not going to help here.

I can reproduce it at any time, however, by adding a delete to any file into `LocalFilesystemDriver`, within the loop, after the `DirectoryIterator` was created.

#### Suggested solution

I suggest that `RuntimeError`s are caught in the foreach loop for the whole of `SplFileInfo::whatever()` calls, and if it matches the `Lstat failed` error, just ignore them and continue.

Sadly, due to the unparalleled foresight of the PHP devs, `errno` (or something) is not passed as `$code` for RuntimeException; as such, it is hard (i.e. not quite feasible) to distinguish between different causes of `RuntimeException`s.

If anything, and this solution is acceptable, I may send a pull request. But first please indicate that you understand the problem in general.

**Comment by dvcsiky** [comment]
This issue is linked to pionl/laravel-chunk-upload#108 where it was raised.

**Comment by dvcsiky** [comment]
Please note that, depending on handling, this may pose a similar but different problem with remote storage interfaces, exacerbated by the fact that increased network delays could cater for more changes within the same iteration. But I did not check other drivers, this is just speculation on my side.

**Comment by architechpro** [comment]
+1, still experiencing this problem

**Comment by frankdejonge** [comment]
Should be fixed in the next release. Word of advice, using a smug title that suggest this tool is not suitable for "real" workloads doesn't get maintainers into the mood to spend their free time fixing shit for you. Also, if this was so important for you, where's the PR?

**Comment by dvcsiky** [comment]
> Should be fixed in the next release. Word of advice, using a smug title that suggest this tool is not suitable for "real" workloads doesn't get maintainers into the mood to spend their free time fixing shit for you. Also, if this was so important for you, where's the PR?

In order:
1. Thanks. Really.
2. I am fed up with people got "inclusived" to places like google, apple and similar now maintain that they have "credentials" which make them to create completely inconsiderate stuff purported suitable for various purposes, whilst ignoring comments or notices from sensible-minded people because they are "offensive", and keep mentioning their credentials instead.
Sorry if this is not you. Really.
3. This is my work account. Due to the people mentioned above not only develop, but also "sit" on "committees" and similar on open source projects, I have like 5-8 pull requests still open on GitHub with my other accounts, not merged even after 3-5-8-any completed "change requests", or even being outright ignored (after "PRs are welcome" notions).
So that I won't ever create a pull request or fix anything in any open source project _unless explicitly requested_.
Again, sorry for this as well.

**Comment by frankdejonge** [comment]
> I am fed up with people got "inclusived" to places like google, apple and similar now maintain that they have "credentials" which make them to create completely inconsiderate stuff purported suitable for various purposes, whilst ignoring comments or notices from sensible-minded people because they are "offensive", and keep mentioning their credentials instead.

Perhaps this is my language gap, but I have no clue what you're trying to say here. I don't work at apple or google. I do think that people should behave properly on open source, so that means leading with respect rather than having to earn it as a maintainer from the people that benefit from my code. I supply the same courtesy to the users of the library. I've been doing this stuff for close to 10 years now, even in large patches in my career when I wasn't even using PHP.

**Comment by dvcsiky** [comment]
>  I don't work at apple or google.

I didn't want to imply that, I just said it is sort of a burnout – i.e. if you try to board the bus 8 times and get refused, you are reluctant to try it for the ninth time. Similar for getting across the board politely anywhere.

> I've been doing this stuff for close to 10 years now

Then you must be fed up with it as well. :P

Anyway, thanks for the fix, and sorry if I offended you whom I did not want.

**Comment by frankdejonge** [comment]
All good. I do understand the frustration. It usually is a matter, at least in my experience, of mis-aligned value systems between contributor and maintainer. I have some PR's open for long periods of time as well when the solution direction is not something I'm comfortable with having to keep alive after the drive-by contributor is long gone. In the end, this stuff is all opt-in for people, so if they don't like it 🤷 

anywho, hope you have a good week

**Comment by dvcsiky** [comment]
> when the solution direction is not something I'm comfortable with having to keep alive after the drive-by contributor is long gone

This is a reasonable approach for e.g. new features that involve reorganizing the whole "guts" of some library/application/module, but I think it is not acceptable for bugs.
I think in these cases the maintainer/original developer/etc. should at least suggest some alternative approach they deem acceptable (if they are wanting to maintain the package at all in the future, that is).
