### ISSUE TITLE
STOR out of sequence with NoopCommandConnectivityChecker on some servers

### ISSUE THREAD

**Issue by lingonl** [thephpleague/flysystem#1610]
Not really a bug, not really a question, but maybe helpful for others running into this issue:

On some servers, you will get a 500 "out of sequence" error on some commands (STOR is one of them). It took me a while to figure out that this had to do with a NOOP command from the NoopCommandConnectivityChecker. Somehow the NOOP command reset the passive-state of the connection, and would refuse to handle uploads. Luckily there is a RawListFtpConnectivityChecker that did not have these issues.

**Comment by frankdejonge** [comment]
Since there's really nothing I can do about this, I'll close the issue. But perhaps it helps somebody.
