### ISSUE TITLE
fix: restore rootLocation on LocalFilesystemAdapter

### ISSUE THREAD

**Issue by paul-thebaud** [thephpleague/flysystem#1611]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.11.0   |
| Adapter Name      | Local |
| Adapter version   | ?   |

#### Summary

With the #1582 PR, the `rootLocation` property of [local adapter was removed](https://github.com/thephpleague/flysystem/commit/e6fbd8ba8da735f3237e1f73c881c809ed4f0ab9#diff-7b9e8c38cc39b1ca85d7f5fc1979c7ef05760422b352502936ab140bc2630b34) and replaced by `$this->prefixer->prefixPath('/')` to get the root path inside `ensureRootDirectoryExists `. This is bad, because when using a "fake" `/` root on Windows (to get access to all disks with a unique filesystem instance), the `prefixPath` method will return an empty string.

#### Proposition

I think you should restore the `rootLocation` property on the class and use it inside the `ensureRootDirectoryExists` method.

#### How to reproduce

Configure a local adapter on windows with a `/` root path. Ensure root directory exists will crash.

**Comment by frankdejonge** [comment]
It was restored. Release coming soon.

**Comment by paul-thebaud** [comment]
Thanks a lot @frankdejonge!
