### ISSUE TITLE
Unable to delete a folder with many files using AsyncAWS

### ISSUE THREAD

**Issue by shyim** [thephpleague/flysystem#1615]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.10.4   |
| Adapter Name      | async-aws|
| Adapter version   | 3.10.3   |

#### Summary

Unable to delete a large folder. Deleting some files by UI then deleting the whole folder works (Maybe some pagination issues?)

(Used Minio)

```
In Response.php line 422:
                                                                                                       
  HTTP 400 returned for "http://127.0.0.1:9000/asset?delete=".                                         
                                                                                                       
  Code:    MalformedXML                                                                                
  Message: The XML you provided was not well-formed or did not validate against our published schema.  
  Type:                                                                                                
  Detail:
```

#### How to reproduce

Create a folder with 5k files and try to delete them

**Comment by frankdejonge** [comment]
Sounds like a Async AWS problem? Any reason that makes you think it's a Flysystem issue?

**Comment by shyim** [comment]
I am not sure. If I chunk these entries, it did worked for me. I am not sure where the problem actual is: Flysystem which puts so many elements into the client or the client itself :)

https://github.com/thephpleague/flysystem/blob/3.x/src/AsyncAwsS3/AsyncAwsS3Adapter.php#L189

**Comment by frankdejonge** [comment]
@Nyholm any recommendations how to handle a situation like this? The normal AWS SDK uses a paginated deletion strategy. Anything like that available for async-aws?

**Comment by Nyholm** [comment]
Hm.. Generally: Async-aws is dumb. There is no smart extra logic it in that is not part of the API specification. 
I think the AsyncAwsS3Adapter needs to implement the "pagination". Ie in [the loop](https://github.com/thephpleague/flysystem/blob/3.x/src/AsyncAwsS3/AsyncAwsS3Adapter.php#L178) we should make a `deleteObjects` request for every 100(?) object.
