### ISSUE TITLE
Need `Filesystem::getPathNormalizer()`

### ISSUE THREAD

**Issue by rulatir** [thephpleague/flysystem#1616]
### Feature Request

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12   |
| Adapter Name      | not applicable |
| Adapter version   | not applicable  |

#### Scenario / Use-case

I want to use a `PathNormalizer` for something, and I want to be 219% certain that I use THE exact same `PathNormalizer` implementation THAT is also used by the `Filesystem` I am doing things with.

It is unfairly punishing to be required to reengineer the whole application bootstrap process so that I can instantiate a `PathNormalizer` and then inject it both into the `Filesystem` and into my class that needs to use it.

#### Summary

I need `Filesystem::getPathNormalizer()`, or `Filesystem::normalizePath()`.

**Comment by frankdejonge** [comment]
That is not a concern of this library. Using language like "is unfairly punishing" doesn't sway me to expose internals of Flysystem, just because you need to be 219% sure.

**Comment by frankdejonge** [comment]
PS: If you be 100% sure, use a factory service that enforces it for you and call it a day 👍

**Comment by rulatir** [comment]
"Engineer around my opinionatedness".

**Comment by frankdejonge** [comment]
🤷‍♂️ no clue

**Comment by rulatir** [comment]
Agreed.

**Comment by rulatir** [comment]
Library author: "that is not a concern of this library"
Library: [literally specifies an interface that captures the concern and provides reference implementations, just not to end users]
