### ISSUE TITLE
AsyncAwsS3 adapter - Unable to create temporary URL

### ISSUE THREAD

**Issue by Ang3** [thephpleague/flysystem#1624]
### Bug Report

Error when I try to get a temporary URL with the [AsyncAwsS3Adapter](https://github.com/thephpleague/flysystem-async-aws-s3).

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12.1   |
| Adapter Name      | AsyncAwsS3Adapter |
| Adapter version   | 3.10.3   |

#### Summary

I'm using Symfony and the bundle [oneup/flysystem-bundle](https://github.com/1up-lab/OneupFlysystemBundle) integrating this awesome Flysystem library. The Async S3 client and filesystem have been created and integrated successfuly. Operations like read, upload, etc work great. However, the method `getTemporaryUrl` does not working, I get the following error from the adapter:

`Unable to generate temporary url for /my_filename: Call to undefined method AsyncAws\S3\S3Client::getPresignedUrl()`

Indeed, this method does not exist in the `Async S3 client` but in the `Async SimpleS3 client`.
Actually, it seems the adapter considers to always have a `SimpleS3Client` to get a temporary URL.

#### How to reproduce

```php
$client = new AsyncAws\S3\S3Client();

// The internal adapter
$adapter = new League\Flysystem\AsyncAwsS3\AsyncAwsS3Adapter(
    // S3Client
    $client,
    // Bucket name
    'bucket-name',
    // Optional path prefix
    'path/prefix',
    // Visibility converter (League\Flysystem\AsyncAwsS3\VisibilityConverter)
    new League\Flysystem\AsyncAwsS3\PortableVisibilityConverter(
        // Optional default for directories
        League\Flysystem\Visibility::PUBLIC // or ::PRIVATE
    )
);

$filesystem = new League\Flysystem\Filesystem($adapter);
$temporaryUrl = $filesystem->temporaryUrl('path/to/file.txt', new \DateTime('+1 hour'));
```

**Comment by phamviet** [comment]
hi @frankdejonge can you share any thoughts and plans on this? I can issue PR for this in case needed.

**Comment by frankdejonge** [comment]
There are two clients, to use this functionality you need to use the `AsyncAws\SimpleS3\SimpleS3Client` client implementation.

**Comment by Ang3** [comment]
Hi, thank you for your answer. Maybe it should be good to fix the documentation then:

> The following adapters have temporary URL generation capabilities:
> 
> **AWS S3**
> Async AWS S3
> Azure Blob Storage
> Google Cloud Storage
> - https://flysystem.thephpleague.com/docs/usage/temporary-urls/

Finally and just for information, the native AWS S3 client supports this feature.

**Comment by phamviet** [comment]
Agree it was intended to use `SimpleS3Client` but from our needs we do want to customize a bit signing params such as: `ResponseContentDisposition` so that customers can download the file with re-defined filename. It is obviously that SimpleS3Client is too simple api to support that extra parameters where other adapters such as Native Aws, Azure do support.
