### ISSUE TITLE
Unable to check existence for: <fileName>

### ISSUE THREAD

**Issue by sushmarana1602** [thephpleague/flysystem#1626]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.0   |
| Adapter Name      | aws s3|
| Adapter version   | aws-sdk-php-laravel 3.5  |

#### Summary

exists method throwing error Unable to check existence for: <fileName>
not going to the else block.
#### How to reproduce

```php

$fileName= "logs/test.json";
 if (Storage::disk('s3')->exists($fileName) {
  return true;
} else {
  return false;
}
```

**Comment by frankdejonge** [comment]
This happens when there is a network error or some other type of configuration error. You should check the track trace and the corresponding error messages.
