### ISSUE TITLE
Unable to specify `listContents()` return type to satisfy phpstan?

### ISSUE THREAD

**Issue by jamieburchell** [thephpleague/flysystem#1631]
### Question

With the following code, phpstan level 9 reports:

> Method sourceFiles() should return array<string> but returns array.

```
/**
 * Example
 *
 * @return string[]
 */
function sourceFiles(): array
{
    $files = $this->source->listContents('/', false)
        ->filter(fn (StorageAttributes $attributes) => $attributes->isFile()),
        ->sortByPath()
        ->map(fn (StorageAttributes $attributes) => $attributes->path()),
        ->toArray();

    return $files;
}
```

I have also tried using type hints of `array`, `array<int, string>`, `array<string>` to no avail.

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12.2   |
| Adapter Name      | SFTP  |
| Adapter version   | 3  |

**Comment by frankdejonge** [comment]
It took some generics magic, but I think this commit fixes it for you: https://github.com/thephpleague/flysystem/commit/dcd781b99072f70a23afcb0e28ce655eef58973b
