### ISSUE TITLE
Сannot create a directory

### ISSUE THREAD

**Issue by daniilly** [thephpleague/flysystem#1636]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12.0 |
| Adapter Name      | WebDav |
| Adapter version   | 3.12.0 |

#### Summary

Hi, the _WebDAVAdapter::createDirectory_ method on the first check exits the method without creating the directory.

#### How to reproduce

- Call the _createDirectory_ method with path parameter e.g. "root/test_folder". 
- This path is split up into an `array("", "root", "test_folder", "")` in which the first and last elements of the array are empty strings.
- At the first check, we exit the method.

Piece of code that causes the problem:

```php
if ($directory === '.' || $directory === '') {
    return;
}
```

Maybe I'm doing something wrong, but it looks like a bug.

**Comment by frankdejonge** [comment]
Hi,

This piece of code works:

```
/**
     * @test
     */
    public function creating_a_directory_with_leading_and_trailing_slashes(): void
    {
        $this->runScenario(function () {
            $adapter = $this->adapter();
            $adapter->createDirectory('/some/directory/', new Config);

            self::assertTrue($adapter->directoryExists('/some/directory/'));
        });
    }
```

Could you supply a PR with a reproducable error scenario?
