### ISSUE TITLE
Unable to get `lastModified()` on folder

### ISSUE THREAD

**Issue by ogrosko** [thephpleague/flysystem#1637]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.2.12   |
| Adapter Name      | SFTP |
| Adapter version   | 3.10.3   |

#### Summary

When trying to fetch info about last modification on folder (`$disk->lastModified('folder/path/')`not a file path) `League\Flysystem\UnableToRetrieveMetadata` exception is thrown. `mtime` info are fetched from folder but `League\Flysystem\DirectoryAttributes` is returned [here](https://github.com/thephpleague/flysystem-sftp-v3/blob/3.x/SftpAdapter.php#L219). Shouldn't be there `League\Flysystem\StorageAttributes` used instead? Or miss I something?

#### How to reproduce

```php
$disk = Storage::disk('sftp');
$folders = $disk->directories('some-folder');
$disk->lastModified($folders[0]);
```

**Comment by frankdejonge** [comment]
This is not exposed because it doesn't adhere to the multi-filesystem mindset of the package. It's not available for many types of filesystems.
