### ISSUE TITLE
getAdapter missing

### ISSUE THREAD

**Issue by Phillip85** [thephpleague/flysystem#1642]
### Question

the getAdapter() method is missing in v3

right now i have some projects where i need to force reconnect to the server:

```
        Storage::disk('stupid_server')
            ->getDriver()
            ->getAdapter()
            ->disconnect();

        Storage::disk('stupid_server')
            ->getDriver()
            ->getAdapter()
            ->connect();
```

i do not see any possible  way to do this in v3 anymore

(The Server has some weird timeout timings, if i upload / download multiple files in a loop, i need do reconnect between every upload / download. if not it ends up in a (Cannot connect to stupid_server:22. Error 110. Connection timed out))

---

Second question, same Problem:

I use the getAdapter() function to get some debug data when a connection does not work:

```
define("NET_SSH2_LOGGING", SSH2::LOG_SIMPLE);
try {
// do some sftp stuff
}  catch (\Exception $e) {
            /** @var \League\Flysystem\Filesystem $conn */
            /** @var SftpAdapter $a */
            $a = $conn->getAdapter();
            /** @var SFTP $c */
            $c = $a->getConnection();
            dd($e->getMessage(), $c->getLog());
}
```

is there any new way to get debug data from the connection?

**Comment by frankdejonge** [comment]
This request has been denied multiple times already. Either use reflection or get the adapter from your DI container, flysystem is not a service locator.
