### ISSUE TITLE
Copy across filesystems/adapters

### ISSUE THREAD

**Issue by futzlarson** [thephpleague/flysystem#1643]
### Question

Hoping this is the correct repo. I see [this previous issue](https://github.com/thephpleague/flysystem/issues/296) so it seems possible, but I'm wondering how to accomplish this in Laravel? Right now I'm doing something like this:

```
$contents = Storage::disk('s3_connect')->get($oldFile);
Storage::disk('s3')->put($newFile, $contents);
```

But I imagine a straight copy bucket-to-bucket would be (much) faster, especially for larger files. Is that possible? Something similar to this command w/ rclone:

`rclone copyto $src $dest`

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 1.1.10   |
| Adapter Name      | league/flysystem-aws-s3-v3 |
| Adapter version   | 1.1.10   |

**Comment by frankdejonge** [comment]
This version is no loner supported, but if you're on 1.x the mount manager on the latest version does support from filesystem copy actions.
