### ISSUE TITLE
PathPrefixedAdapter::$prefix should be protected, not private

### ISSUE THREAD

**Issue by XAKEPEHOK** [thephpleague/flysystem#1644]
### Feature Request

[`PathPrefixedAdapter::$prefix`](https://github.com/thephpleague/flysystem-path-prefixing/blob/cdf55f8d46739456dee575effc2d4cd7cd094705/PathPrefixedAdapter.php#L34) should be protected, not private

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12.3   |
| Adapter Name      | [PathPrefixedAdapter](https://github.com/thephpleague/flysystem/blob/3.x/src/PathPrefixing/PathPrefixedAdapter.php) |
| Adapter version   | 3.10.4   |

Hello!
Usually, I think, that all properties, that can has private visibility should has private visibility. But not in this case.

I use [PHP-DI](https://php-di.org/) container, which make adapter and filesystem for me. And in my case [PathPrefixedAdapter](https://github.com/thephpleague/flysystem/blob/3.x/src/PathPrefixing/PathPrefixedAdapter.php) implement feature for isolation files between different users. If we are use classic php-fpm everything works fine.

But for things like [RoadRunner](https://roadrunner.dev/) its a trouble, because i have one long running php propcess which handle multiple requests from different users, and i need to change path prefix in runtime, for existed adapter.

I can not create new adapter, and put it in DI container, because i already has many other already created objects (services, controllers, etc) with injected adapter, and i can't re-create all of them (for performance reasons)

If [`PathPrefixedAdapter::$prefix`](https://github.com/thephpleague/flysystem-path-prefixing/blob/cdf55f8d46739456dee575effc2d4cd7cd094705/PathPrefixedAdapter.php#L34) will be protected instead of private, i can easily create my own adapter, and extend it from PathPrefixedAdapter instead of copy-paste all its code

**Comment by frankdejonge** [comment]
You can create an adapter proxy by implementing the adapter interface which allows you to re-assign an adapter without forcing internal restructuring of existing adapters. This proxy would be injected, and instructed to replace the inner adapter when you so desire, preventing you to re-create all depending services.

**Comment by XAKEPEHOK** [comment]
Yes, i can, like a few other solutions e.g. copy-paste this adapter code too. But can you tell any reason, why this property should be private? Just because?

**Comment by frankdejonge** [comment]
Because protected means it’s part of the public API I need to support, which I do not want to.
