### ISSUE TITLE
Using magic method __call

### ISSUE THREAD

**Issue by artem-dev2** [thephpleague/flysystem#1650]
### Question

Since the `Filesystem` constructor accpets `FilesystemAdapter` object which implements `FilesystemAdapter` interface, instead of having all the adapter methods in `Filesystem.php` class with access to relevant adapter methods like:
```
public function fileExists(string $location): bool
{
        return $this->adapter->fileExists($this->pathNormalizer->normalizePath($location));
}
```

can't it be to have a magic `__call()` there, which will transfer the access to relevent adapter methods?

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.0.0   |
| Adapter Name      | N\A|
| Adapter version   | N\A   |

**Comment by frankdejonge** [comment]
It could be, but I don't like that style of programming.
