### ISSUE TITLE
Does flysystem have loggin ability?

### ISSUE THREAD

**Issue by mkoskl** [thephpleague/flysystem#1653]
### Question

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | latest  |
| Adapter Name      | - |
| Adapter version   |  -  |

Does flysystem have logging ability? I.e. setting logger which will then log everything that happens? Like when I move file, it would log that "file a was renamed to b" etc.?

Or if not, is there any kind of event system where I could add my own logger?

Br, Miika

**Comment by frankdejonge** [comment]
Hello, you can add the logging capabilities by decorating an adapter, implementing the same interface and forwarding the calls.

**Comment by mkoskl** [comment]
Ok, thanks for answer. I'll close this.
