### ISSUE TITLE
Bug on sftp-v3/SftpAdapter.php (2.5)

### ISSUE THREAD

**Issue by TerenceVy** [thephpleague/flysystem#1654]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 2.5   |
| Adapter Name      | SftpAdapter.php |
| Adapter version   | x.y.z   |

#### Summary
Hello,

When i use the fuction listContents($dir) it returns an object generator empty et to get value i need to do a foreach on the listContents() function.
When the $dir exists in the foreach i get the value of each file/folder. But when the directory does not exist i have an error 500 that say 
"Warning: Invalid argument supply for foreach()".
I tried to do some thing but the only thing that works that give not an error 500 is to add in the vendor in
league/flysystem-sftp-v3/SftpAdapter.php line 260
```
        if ($listing === false) {
            return;
        }
```
        

#### How to reproduce
Connect to an sftp server and do this : 
```
$sftpContents = $sftpStorage->listContents($directory);
foreach ($sftpContents as $content) {
    echo "Ok";
}
```
If the $dir exists there is no error, if not i've got a 500

Thank you.

**Comment by frankdejonge** [comment]
Hi, the version you are using is no longer supported. Please upgrade to 3.x and try to see if the problem persists.

**Comment by TerenceVy** [comment]
Hi,

I cannot upgrade to 3.x beacause my project use php 7.4

**Comment by frankdejonge** [comment]
Sorry to hear that. Regardless, I do not support this version anymore. I'm a single dev, with a day job and a family.

**Comment by TerenceVy** [comment]
It is okay, i just did a patch and it works fine ! 
Thank you, have a nice day
