### ISSUE TITLE
Azure Storage Adapter affected by the retirement of a library in March 2024

### ISSUE THREAD

**Issue by dmoreno** [thephpleague/flysystem#1655]
### Question

Microsoft has published the retirement notice: [The Azure Storage PHP client libraries will be retired on 17 March 2024](https://azure.microsoft.com/en-us/updates/retirement-notice-the-azure-storage-php-client-libraries-will-be-retired-on-17-march-2024/).

I see that the flysystem Azure storage adapter uses the affected Microsoft library in [composer.json]( https://github.com/thephpleague/flysystem-azure-blob-storage/blob/1a38d3243a89cc95144f0665dce08b561cc52117/composer.json#L11).

Announcement on the github repo of [azure-storage-php](https://github.com/azure/azure-storage-php#microsoft-azure-storage-php-client-libraries-deprecated).

There is still enough time, but has the flysystem project thought of alternatives?

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.12.3   |
| Adapter Name      | flysystem-azure-blob-storage |
| Adapter version   | 3.10.3   |

**Comment by frankdejonge** [comment]
That's unfortunate. I have to be honest and say that I will not support a version where I need to use the rest API myself. It'll be up to the community to provide their own version and publish that to packagist.
