### ISSUE TITLE
S3 pathPrefix stripping an extra character

### ISSUE THREAD

**Issue by PDXfoster** [thephpleague/flysystem#1656]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.8.0   |
| Adapter Name      | aws S3 |
| Adapter version   |  3.12.2   |

#### Summary

Ran across a strange bug that I haven't quite nailed down all the way, but it appears to be stemming out to the PathPrefixer::stripPrefix method - I feed in the following S3 resource: `s3://some_bucket/some_bucket_root/staging/some_resource/1111/some_directory/a_relevent.pdf`

I admittedly have a somewhat complex path, but the behavior of the stripPrefix is pretty unexpected, and this is what I can't track down - I use the following for troubleshooting in the stripPrefix method:
```
dd([
    'prefix_length' => strlen($this->prefix),
    'prefix' => $this->prefix,
    'path' => $path,
    'prefix_stripped' => substr($path, strlen($this->prefix))
]);
```

output:
```
 [ // vendor/league/flysystem/src/PathPrefixer.php:35
  "prefix_length" => 9
  "prefix" => "/some_resource/"
  "path" => "staging/some_resource/1111/some_directory/a_relevent.pdf"
  "stripped" => "ome_resource/1111/some_directory/a_relevent.pdf"
]
```

so the result seems to be that the prefix length is calculated using a leading slash, and then rtrim($prefix, '\\/') is applied before substr($path, strlen($this->prefix) is applied, which results confusingly in the leading character of one of my directories being removed. As a short term patch, I've removed the leading "/" on `/some_bucket_root` - > now `some_bucket_root`, but that shouldn't affect the directory `some_resource`, and it makes it very confusing and difficult to troubleshoot. I think removing `$this->prefix = rtrim($prefix, '\\/');` from the constructor, and calling it intentionally elsewhere could alleviate the problem, but I'm not sure if there are unintended consequences from that, or where else it would need to be called.

**Comment by frankdejonge** [comment]
@PDXfoster Hi, could you perhaps explain how you get into this situation? Can you provide an example where this problem occurs? Or perhaps, are you using the prefixer standalone? The normal usage never used the full style urls you're describing. I do see that the bucket name is also in that URL, which the Flysystem implementation does not do either. I'm having difficulties seeing how this problem occurs.
