### ISSUE TITLE
UnableToCheckExistence.php error

### ISSUE THREAD

**Issue by applibs** [thephpleague/flysystem#1659]
Last version 3.0.0 has error with PHP 8.2:
UnableToCheckExistence.php - PHP 8.2 compiler error: line 14, Using ${var} in strings is deprecated, use {$var} instead [2]

**Comment by frankdejonge** [comment]
I don't think this is the case in the latest version. Couldn't find any instance of this syntax
<img width="633" alt="image" src="https://user-images.githubusercontent.com/534693/236415138-ba47febf-b8ed-46a4-ac0a-e2814075743a.png">
