### ISSUE TITLE
Declaration of AWS

### ISSUE THREAD

**Issue by fernandoaguilarviquez** [thephpleague/flysystem#1663]
### Bug Report

Declaration of Aws\HashingStream::seek($offset, $whence = Aws\SEEK_SET) must be compatible with Psr\Http\Message\StreamInterface::seek(int $offset, int $whence = Psr\Http\Message\SEEK_SET): void

#### Summary

Declaration of Aws\HashingStream::seek($offset, $whence = Aws\SEEK_SET) must be compatible with Psr\Http\Message\StreamInterface::seek(int $offset, int $whence = Psr\Http\Message\SEEK_SET): void

#### How to reproduce

In laravel with a large file

**Comment by zeevx** [comment]
Yes, I am experiencing this too.

**Comment by frankdejonge** [comment]
@fernandoaguilarviquez are you sure this isn't an issue with the AWS SDK? None of this code you're referencing is in this package.

**Comment by zeevx** [comment]
It is the AWS SDK, a new version was tagged 5 days ago that I think fixed this.
See this: https://github.com/aws/aws-sdk-php/issues/2681

**Comment by mrsimonbennett** [comment]
Same issue here :/

**Comment by frankdejonge** [comment]
Why is this issue filled here? This has nothing to do with Flysystem code.

**Comment by ckovey** [comment]
I also got this error and upgrading `aws-sdk-php` to `3.269.5` resolved it
