### ISSUE TITLE
$mountManager->move/write - return NULL, expected true/false

### ISSUE THREAD

**Issue by Onore** [thephpleague/flysystem#1670]
Hi.

I am switching Flysystem from V1 to V3
And code doesn't work because result is strange always return NULL

It is the error in function description or?

MountManager.php
...
 * @return **bool True on success, false on failure.**
     */
    public function write($path, $contents, array $config = [])

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.15.1   |
| Adapter Name      | flysystem-aws-s3-v3 |
| Adapter version   | 3.15.0   |

**Comment by frankdejonge** [comment]
In v3, the write method does not have a boolean return, it's a `void` on success and an Exception on failure, which provides more contextual information than `false`.
