### ISSUE TITLE
Azure Client EOL

### ISSUE THREAD

**Issue by lrljoe** [thephpleague/flysystem#1673]
With the Client going EOL there's a community supported fork to keep it maintained

Will you accept some PRs to use the forked version of the library instead?

**Comment by frankdejonge** [comment]
@lrljoe sorry, but I will not unless it is maintained for longer period of time. I will accept PR's with links to the adapter, or even installation docs.

**Comment by lrljoe** [comment]
No problem, figured I'd ask!
