### ISSUE TITLE
SFTP error with custom port

### ISSUE THREAD

**Issue by exstreme** [thephpleague/flysystem#1675]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.0.0   |
| Adapter Name      | sftp|
| Adapter version   | 3.0.0   |

#### Summary

Trying add Sftp driver in Laravel 10 with custom port, but became an error:

TypeError : League\Flysystem\PhpseclibV3\SftpConnectionProvider::__construct(): Argument #6 ($port) must be of type int, string given, called in \vendor\league\flysystem-sftp-v3\SftpConnectionProvider.php on line 193
 \vendor\league\flysystem-sftp-v3\SftpConnectionProvider.php:81
 \vendor\league\flysystem-sftp-v3\SftpConnectionProvider.php:193
 \vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:215
 \vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:152
 \vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:120
 \vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:83
 \vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:338
 \app\Jobs\ProcessFlowGa4.php:86
 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
 \vendor\laravel\framework\src\Illuminate\Container\Util.php:41
 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
 \vendor\laravel\framework\src\Illuminate\Container\Container.php:661
 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php:128
 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:141
 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:116
 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php:132
 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php:124
 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:141
 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:116
 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php:126
 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php:70
 \vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php:98
 \vendor\laravel\framework\src\Illuminate\Queue\SyncQueue.php:43
 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php:253
 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php:229
 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php:77
 \vendor\laravel\framework\src\Illuminate\Foundation\Bus\PendingDispatch.php:193
 \vendor\laravel\framework\src\Illuminate\Foundation\Bus\Dispatchable.php:19
 \tests\Jobs\ProcessFlowTest.php:32

#### How to reproduce
add lib

composer require league/flysystem-sftp-v3 "^3.0"

add in config/filesystems.php

'sftp' => [
            'driver'   => 'sftp',
            'host'     => env('SFTP_HOST'),

            // Settings for basic authentication...
            'username' => env('SFTP_USERNAME'),
            'password' => env('SFTP_PASSWORD'),

            // Settings for SSH key based authentication with encryption password...
            // 'privateKey' => env('SFTP_PRIVATE_KEY'),
            // 'passphrase' => env('SFTP_PASSPHRASE'),

            // Settings for file / directory permissions...
//            'visibility' => 'private', // `private` = 0600, `public` = 0700
//            'directory_visibility' => 'private', // `private` = 0700, `public` = 0755

            // Optional SFTP Settings...
            // 'hostFingerprint' => env('SFTP_HOST_FINGERPRINT'),
            // 'maxTries' => 4,
            // 'passphrase' => env('SFTP_PASSPHRASE'),
            'port'     => (int) env('SFTP_PORT', 22),
            'root'     => env('SFTP_ROOT', ''),
            // 'timeout' => 30,
            // 'useAgent' => true,
        ],
define SFTP_PORT in env file
add code to run driver:
Storage::disk('sftp')->put($fileName, $data);

**Comment by frankdejonge** [comment]
Looks like a Laravel issue, please open an issue there. This config is type tested and works as a standalone lib.
