### ISSUE TITLE
PHP 8.1 Can't get list on files/directories with FTP adapter

### ISSUE THREAD

**Issue by webappbuilder** [thephpleague/flysystem#1676]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.15.1     |
| Adapter Name      | FTP |
| Adapter version   | 3.15.0    |

#### Summary

PHP 8.1.15+ Can't get list on files/directories with FTP adapter in PASSIVE mode.

#### How to reproduce

Run any method to get list of entries under PHP 8.1.15+

**Comment by frankdejonge** [comment]
What kind of FTP server are you connected to?
