### ISSUE TITLE
Problem with ftp listing from untipical server

### ISSUE THREAD

**Issue by michal-kulik** [thephpleague/flysystem#1677]
### Question

| Q                 | A       |
|-------------------|---------|
| league/flysystem-ftp |                3.15.0   |
| PHP version | PHP 8.2.6 (cli)|
| Laravel | Laravel Framework 10.13.5|

Hi, I cannot download folders from client ftp server.

 League\Flysystem\UnableToListContents

  Unable to list contents for '/Menswear/Menswear_Spring_2024/Milan_lookbook/High/', shallow listing

Reason: Metadata can't be parsed from item 'drwxrwxrwx folder 0 Jun 16 17:28 Valentino_LB_56' , not enough parts.

In Laravel 8 I had custom ftp adapter, but now it does not work anymore on Laravel 10. Please help how to deal with that

**Comment by frankdejonge** [comment]
The FTP adapter handles most cases. If your specific flavour of FTP doesn't work, I recommend rolling your own adapter. It's not ideal, but FTP is so fucked up, it's virtually impossible to handle all flavours in one adatper.
