### ISSUE TITLE
Image preview issue while migrating to flysystem 2

### ISSUE THREAD

**Issue by kashifau** [thephpleague/flysystem#1679]
I am currently using flysystem 1 in my cakephp 3.10 app. I am using AwsS3V3Adapter to store and retrieve images and dropzone.js for uploading and deleting files. I am currently in the process of migrating my cake app to v4 and flysystem to v2. I am getting an error when dropzone is sending get request to .json file and response object is empty. I have tried various solutions but none of them are working. Any idea where should I look for the problem?

**Comment by frankdejonge** [comment]
There is very little information to go by. If there is more info, feel free to comment and we can re-open the issue.
