### ISSUE TITLE
Unix-Style Visibility does not work correctly

### ISSUE THREAD

**Issue by AntistressStore** [thephpleague/flysystem#1702]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.15   |
| Adapter Name      | local |

#### Summary

I use your product in Laravel 10. I spent many days configuring the correct permissions for folders and files. However, fine-tuning rights in the digital style of Linux does not work.
I think that's because the data type is int. And it misconverts rights with a leading zero.
However, even if a number without a leading zero, the rights are still created incorrectly.
in class
League\Flysystem\UnixVisibility\PortableVisibilityConverter
private int $filePublic = 0644,
private int $filePrivate = 0600,
private int $directoryPublic = 0755,
private int $directoryPrivate = 0700,

#### How to reproduce
```php
use League\Flysystem\UnixVisibility\PortableVisibilityConverter;
 
$visibilityConverter = PortableVisibilityConverter::fromArray([
'file' => ['public' => 0770,'private' => 0604,],
'dir' => ['public' => 0760,'private' => 0777,],
]);

dump($visibilityConverter);

League\Flysystem\UnixVisibility\PortableVisibilityConverter^ {#7900 // vendor/psy/psysh/src/ExecutionLoopClosure.php(53) : eval()'d code:1
  -filePublic: 504
  -filePrivate: 388
  -directoryPublic: 496
  -directoryPrivate: 511
  -defaultForDirectories: "private"
}
```
Laravel 10
config/filesystems.php
```php
 'disks' => [
'log_data' => [
            'driver' => 'local',
            'root' => storage_path('log_data'),
            'visibility' => 'private',
            'permissions' => [
                'file' => [
                    'private' => 7777,
                ],
                'dir' => [
                    'private' => 7777,
                ],
            ],
        ],
]

//

\Storage::disk('log_data')->put('vnb','fsf');
```

```bash
bash# ls -l

d--xr----t 2 yoda yoda   4096 сен  8 22:22 log_data

```
The correct combination of rights with such a config should be - drwxrwxrwx, not d--xr----t

Laravel 10
config/filesystems.php
```php
'log_data' => [
            'driver' => 'local',
            'root' => storage_path('log_data'),
            'visibility' => 'private',
            'permissions' => [
                'file' => [
                    'private' => 0764,
                ],
                'dir' => [
                    'private' => 0764,
                ],
            ],
        ],

//

\Storage::disk('log_data')->put('vnb','fsf');
```

```bash
bash# ls -l

drwxr--r-- 2 yoda yoda   4096 сен  8 22:29 log_data

```

The correct combination of rights with such a config should be - drwxrwxr--, not drwxr--r--

**Comment by frankdejonge** [comment]
This is not an issue with Flysystem, but mostly likely the effect of a umask configuration. The default umask of 0022 deducts permissions from the configuration settings specified above, resulting in a different (less permissive) setting than expected. The `integer` type as it is expressed in, it the recommended way for PHP, when dumping it out you get a different value, but the value is correct. A `var_dump` of `0777` shows the number `511`, and a `var_dump` of `511` produces the string octal value of `"777"`. Subtracting the default umask from `0764` is effectively `0742`. I hope this clears it up.
