### ISSUE TITLE
Error suppression is hiding the real error

### ISSUE THREAD

**Issue by SamanthaAdrichem** [thephpleague/flysystem#1704]
| Q                 | A       |
|-------------------|---------|
| Flysystem Version | linux/ubuntu/docker   |
| Adapter Name      | vendor/league/flysystem-ftp/FtpAdapter.php |
| Adapter version   | still in latest   |

#### Summary

In this file : https://github.com/thephpleague/flysystem-ftp/blob/3.x/FtpAdapter.php
On line 192 you have this nasty little `@` symbol
```$result = @ftp_fget($this->connection(), $stream, $location, **$this->connectionOptions->transferMode());```

In our environment this caused the error to just be 'Unable to read' no reason nothing.
By removing the `@` symbol the actual error came up.

Namely: php_connect_nonb() failed: Operation in progress (115)

It would be better to instead of suppressing the error with an `@` catch it and give it on as the reason.

Rougly something like
```
$reason = null;
set_error_handler(function(
    int $errno,
    string $errstr,
    string $errfile,
    int $errline,
    array $errcontext
) use ($reason) { 
    $reason = $errstr . ' (' . $errno. ')';
    return true;
});
$result = @ftp_fget($this->connection(), $stream, $location, **$this->connectionOptions->transferMode());
restore_error_handler();
```

**Comment by frankdejonge** [comment]
The call below fetches the error and puts the reason in the message: https://github.com/thephpleague/flysystem-ftp/blob/3.x/FtpAdapter.php#L197
