### ISSUE TITLE
Debug option for AwsS3V3 adapter

### ISSUE THREAD

**Issue by FernandoIberian** [thephpleague/flysystem#1708]
### Question

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.15.1   |
| Adapter Name      | Aws S3 V3 |
| Adapter version   | 3.15.0  |

Is there any way to debug the request made from `Aws\S3\S3ClientInterface`?

Right now, the only way of getting some error is `League\Flysystem\AwsS3V3\AwsS3V3Adapter` catching some `Throwable` by `Aws\S3\S3ClientInterface`, but at it is stated [on the docs](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3ClientInterface.html#_upload), instead of throwing exceptions it just returns a `Aws\ResultInterface` (which is very sad).

Sometimes (i suspect by [this documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#S3AsynchronousErrorCodeList)) it just returns 200 and the file is not beign uploaded. It's easyly fixable by checking if the file existes after uploading, but it will be very usefull for me if i could just be sure WHY sometimes the files are beign uploaded and others don't.

Thank you for this wonderfull library!

**Comment by frankdejonge** [comment]
I think this is a question best asked on the AWS PHP SDK repository instead of here, I don't maintain the SDK nor do I provide debug options for it.
