### ISSUE TITLE
Wrong url for uploaded file only on windows

### ISSUE THREAD

**Issue by naciriii** [thephpleague/flysystem#1716]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.17.0  |
| Adapter Name      | league/flysystem-aws-s3-v3 |
| Adapter version   | 3.16.0  |

#### Summary
- The issue occurs only in windows os  in laravel when trying to upload a file to a subfolder(configured bucket prefix ) in an s3 bucket, after uploading successfully then trying to get the url of the file, a backslash is added between the prefix and the file name (Notice the added %5C in the url)

**url(Linux):**
https://xxx.s3.eu-central-1.amazonaws.com/f8544585a096713041d999eea4dc6141-6532b0719e5c3/avatars/kZaqchiSn7zA33FZ7Qh82OJTojciE3qIsFtJ9pCu.png
** url (windows): **
https://xxx.s3.eu-central-1.amazonaws.com/f8544585a096713041d999eea4dc6141-6532b0719e5c3%5Cavatars/kZaqchiSn7zA33FZ7Qh82OJTojciE3qIsFtJ9pCu.png

https://
xxx.s3.eu-central1.amazonaws.com/
f8544585a096713041d999eea4dc61416532b0719e5c3
**%5C**
avatars/
kZaqchiSn7zA33FZ7Qh82OJTojciE3qIsFtJ9pCu.png;

#### How to reproduce
```php
$path = $file->store('avatars', 's3');
$url = Storage::disk('s3')->url($path);
// $url is fine on linux based systems, on windows a %5C (a url encoded backslash \) is prepended before avatars
```

**Comment by frankdejonge** [comment]
I believe Laravel has their own way of generating public urls, they don't use Flysystem native functionality IIRC.
