### ISSUE TITLE
AdapterDefinitionFactory::createDefinition() breaking change

### ISSUE THREAD

**Issue by stefan1144** [thephpleague/flysystem#1720]
### Bug report 

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.18.0   |

#### Summary

The BC was introduced in this version in the `League\FlysystemBundle\Adapter\AdapterDefinitionFactory` , `createDefinition` method.
`?string $defaultVisibilityForDirectories` has been added as the last argument, however there is no value set by default (null, per example).

Although class is marked as “internal” it is quite useful, we are using it, and adding third optional parameter could have default value.
Thanks.

**Comment by frankdejonge** [comment]
Hi @stefan1144, can you raise this issue with the https://github.com/thephpleague/flysystem-bundle repository? That way the maintainers see it.
