### ISSUE TITLE
Undefined $options in the S3 client documentation

### ISSUE THREAD

**Issue by facorazza** [thephpleague/flysystem#1734]
The [documentation regarding the S3 client](https://flysystem.thephpleague.com/docs/adapter/aws-s3-v3/) mentions an `$options` parameter that can be passed to the S3 client.

That parameter doesn't seem to be defined anywhere.

**Comment by sdespont** [comment]
Relative to https://github.com/aws/aws-sdk-php see constructor options

Then, you can submit a PR to improve the doc

**Comment by frankdejonge** [comment]
Closing this as this is not a Flysystem issue. Thanks for helping out, @sdespont 👍
