### ISSUE TITLE
Add pCloud support

### ISSUE THREAD

**Issue by Neustradamus** [thephpleague/flysystem#1735]
Dear @thephpleague team,

Can you add pCloud support?

I have found:
- @LucaF87: https://github.com/LucaF87/flysystem-pcloud
- @fayouz: https://github.com/fayouz/flysystem-pcloud

Thanks in advance.

**Comment by frankdejonge** [comment]
@Neustradamus I think this is better served as a community provided package.

**Comment by Neustradamus** [comment]
@frankdejonge: It is has been solved?

**Comment by frankdejonge** [comment]
Ive closed the issue because I have no intention of providing this adapter. As mentioned, you can create it and release it on packagist as a community supported package.
