### ISSUE TITLE
Copy from remote URL to a filesystem

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1739]
### Question

What is the best way to copy a remote file to S3 using Flysystem?

I see that MountManager::copy works between filesystem, but I just want to copy a url like https://dummyimage.com/600x400/000/fff to a filesystem.

My first instinct was to load it to /tmp and then copy it, but I'm sure there's a way to stream directly without an intermediate file.  Can you point me to documentation or an example?

Thanks!

**Comment by frankdejonge** [comment]
I think you should be able to open a stream by using `fopen` on the file URL, like:

```php
$handle = fopen($url, 'r');
$filesystem->writeStream($destination, $handle);
```

**Comment by tacman** [comment]
Thanks.  I'm using Symfony's httpClient to stream the input, but am not sure if this is correct:

```php
                $response = $this->httpClient->request('GET', $url);
                // https://symfony.com/doc/current/http_client.html#streaming-responses
                    $filesystem->writeStream($code, $client->stream($response));
                    foreach ($client->stream($response) as $chunk) {
                        $filesystem->write($code, $chunk->getContent());
                    }
// without streaming
//                    $this->defaultStorage->write($code, $request->getContent());
```

This doesn't seem right, the second chuck will overwrite the first.  But I couldn't figure out what parameters to send when calling writeStream.

**Comment by frankdejonge** [comment]
@tacman you're most likely looking to use `$response->toStream()` The other interface is a sort of iterator which abstracts over `fread` on a predetermined chunk size.

**Comment by tacman** [comment]
Yep, that works, thanks!
