### ISSUE TITLE
Allow public Storage::getAdapter() to get the storage adapter

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1740]
Often when debugging a missing image, I want to know what adapter the storage is using, and ideally what the configuration parameters are.  So instead of getting a message the a file is missing, I'd rather get a message that the file is missing on a specific adapter with specific config set, like the prefix and root.

I've created an issue on Liip https://github.com/liip/LiipImagineBundle/issues/1555 but I don't they can solve it elegantly.

**Comment by frankdejonge** [comment]
Anything you pass into flysystem you can resolve yourself. Flysystem is not a DI or a service locator.

**Comment by tacman** [comment]
Would you consider returning more detailed data about a file not found?

**Comment by frankdejonge** [comment]
Sorry, but a misconfiguration that takes a bit of figuring out why it was wrong for me does not constitute enough reason to add this. I've had these kind of bugs with configuring web-servers in the past, I understand it's frustrating, but not every "could have been easier" is worth the time and effort to introduce and maintain additional functionality. Pardon my directness, but I don't agree this is an issue that needs to be solved.
