### ISSUE TITLE
Error installing in Laravel 10 with sail/Docker and composer

### ISSUE THREAD

**Issue by stratboy** [thephpleague/flysystem#1742]
Hi, I'm trying to install this package in Laravel 10, Sail environment.

`sail composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies`

But it throws an error at the end of installation while generating optimized autoload files:

`Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1` 

Can't find the reason why? Any idea here?

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.0  |
| Adapter Name      | league/flysystem-aws-s3-v3|

**Comment by frankdejonge** [comment]
Please raise an issue with the laravel or Sail repository.
