### ISSUE TITLE
Can't get list of files on directory with FTP adapter in PHP 8.3

### ISSUE THREAD

**Issue by lanz1** [thephpleague/flysystem#1761]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.23.1   |
| Adapter Name      | FTP |
| Adapter version   | 3.23.1   |

#### Summary

Can't get list of files on directory with FTP adapter in PHP 8.3

League\Flysystem\UnableToListContents ─── vendor/league/flysystem/src/UnableToListContents.php:17 
│ Unable to list contents for '/{directory}', shallow listing Reason: array_sum(): Addition is not supported on type string 

#### How to reproduce

Laravel 11 + PHP 8.3

$driver = Storage::createFtpDriver([
            'host' => value,
            'port' => value,
            'username' => value,
            'password' => value,
            'throw' => true,
        ]);

$driver->files('path');

#### Possible fix

Locally can be fixed by casting values in FtpAdapter.php row 488 as:

return array_sum(array_map(fn ($permission) => (int) $permission, str_split($part)));

**Comment by ixperiencenl** [comment]
Same issue here on L11 and PHP8.3.4
league/flysystem-ftp ^3.6

Thanks for your fix

**Comment by mpe85** [comment]
@frankdejonge When will there be a release including this fix? Thank you

**Comment by frankdejonge** [comment]
Sorry for the delay, 3.28.0 is out now.
