### ISSUE TITLE
Strpos result comparison

### ISSUE THREAD

**Issue by yannouche34490** [thephpleague/flysystem#1765]
https://github.com/thephpleague/flysystem/blob/4c44347133618cccd9b3df1729647a1577b4ad99/src/MountManager.php#L353

Hello,

when you make comparison between strpos result and 1, PHP will cast the result to a int even if function returns false. It can result an unexpected true comparison. 

Best regards.

**Comment by frankdejonge** [comment]
In this it's not a problem, because `false` would convert to `-1` and that would mean there is no `://`, which also would be incorrect
