### ISSUE TITLE
documentation - aws - ListObjects privileges seems no longer exists

### ISSUE THREAD

**Issue by mathela59** [thephpleague/flysystem#1770]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version |  3   |
| Adapter Name      | aws-s3 |
| Adapter version   | 3.X   |

#### Summary

When trying to connect a S3, with the correct IAM permissions policy, i didn't manage to find the "ListObjects" privileges to allow in IAM.

I don't know what are the impacts of such a modification

#### How to reproduce

https://awspolicygen.s3.amazonaws.com/policygen.html try to find listObject in this policy generator, the aws console is the same.

**Comment by frankdejonge** [comment]
I think the permission is ListBucket, not ListObjects, the action is ListObjectsV2
