### ISSUE TITLE
Error Message: Unable to list contents for '', shallow listing

### ISSUE THREAD

**Issue by danielrona** [thephpleague/flysystem#1775]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | [3.25.1](https://github.com/thephpleague/flysystem/releases/tag/3.25.1)   |
| Adapter Name      | [flysystem-adapter-sftp3](https://github.com/thephpleague/flysystem-sftp-v3) |
| Adapter version   | [3.25.1](https://github.com/thephpleague/flysystem-sftp-v3/releases/tag/3.25.1)   |

#### Summary
Error Message: Unable to list contents for '', shallow listing

Since upgrading from 3.25.0 to 3.25.1 probably related to ["Early simple return of connectivity check. Set connection to null on disconnect."](https://github.com/thephpleague/flysystem/commit/53ddb77e1c54a7bc58af1e5d91baafe1f6bd84d8)),  without that it works just fine.

#### How to reproduce

I can only reproduce this with 1 of the many sftp servers we have to connect to.

Server responds with SSH-2.0-PSFTPd, wich seems to be a implementation for windows systems

Connecting with 3.25.0 to SFTP works

Connecting with 3.25.1 to SFTP fails with Error Message: Unable to list contents for '', shallow listing

When removing commit [53ddb77e1c54a7bc58af1e5d91baafe1f6bd84d8](https://github.com/thephpleague/flysystem/commit/53ddb77e1c54a7bc58af1e5d91baafe1f6bd84d8) it still works.

#### Solution
We're going to use a custom Adapter for said SFTP, just thought this might be worth an issue if other users experience the same.

**Comment by frankdejonge** [comment]
@danielrona since the affected version, a new version was released which makes the PING an opt-in feature, is the problem still there for that version?

**Comment by danielrona** [comment]
@frankdejonge I haven't tried it yet but I'll give it a go in the next days and report back

**Comment by danielrona** [comment]
@frankdejonge yes, as expected f27e4c8a0db2f6edcefcab3947b5c619f2472e5b fixed it.

name     : league/flysystem-sftp-v3
versions : * 3.26.0
