### ISSUE TITLE
SimpleConnectivityChecker causes unexpected behavior when use the ping method to check connectivity

### ISSUE THREAD

**Issue by gmorgas** [thephpleague/flysystem#1776]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.25.0   |
| Adapter Name      | [flysystem-adapter-sftp3](https://github.com/thephpleague/flysystem-sftp-v3) |
| Adapter version   | 3.25.0   |

#### Summary

Error Message: Unable to list contents for '', shallow listing\n\nReason: Expected NET_SFTP_HANDLE or NET_SFTP_STATUS. Got packet type: 

Since upgrading from 3.23.1 to 3.25.0 related to ["Add ability to proactively close FTP and SFTP connections."](https://github.com/thephpleague/flysystem/pull/1763/commits/e0196771030aeeb2909e56a6613ba3d2c08168c2), without using ping to check the connection, they work without a problem. The problematic part in ping method is close_channel.

Solution
Revert this change and use previous check.

**Comment by frankdejonge** [comment]
Next minor version will revert the behaviour, making the ping usage an opt-in feature instead.
