### ISSUE TITLE
flysystem-cached-adapter remove but what is the alternative of it 

### ISSUE THREAD

**Issue by harsh16021992** [thephpleague/flysystem#1806]
"league/flysystem": "^1.0.40" is supported [flysystem-cached-adapter](https://github.com/thephpleague/flysystem-cached-adapter)
but in new version "league/flysystem": "^3.0" they remove dependecis 
i m using storage PhpRedis class for my project now it give me error after update 

Fatal error: Uncaught Error: Class "League\Flysystem\Cached\Storage\PhpRedis" not found in /var/www/app/src/Backend/PhpRedisFlysystemStorage.php:5 Stack trace: #0 /var/www/vendor/silverstripe/framework/src/Core/Manifest/ClassLoader.php(88): require_once() #1 [internal function]: SilverStripe\Core\Manifest\ClassLoader->loadClass('FOS\\Flysystem\\C...') #2 /var/www/vendor/silverstripe/config/src/Transformer/PrivateStaticTransformer.php(43): class_exists('FOS\\Flysystem\\C...') #3 /var/www/vendor/silverstripe/config/src/Collections/MemoryConfigCollection.php(73): SilverStripe\Config\Transformer\PrivateStaticTransformer->transform(Object(SilverStripe\Config\Collections\MemoryConfigCollection)) #4 /var/www/vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(91): SilverStripe\Config\Collections\MemoryConfigCollection->transform(Array) #5 /var/www/vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(67): SilverStripe\Core\Config\CoreConfigFactory->createCore() #6 [internal function]: SilverStripe\Core\Config\CoreConfigFactory->SilverStripe\Core\Config\{closure}() #7 /var/www/vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(150): call_user_func(Object(Closure)) #8 /var/www/vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(93): SilverStripe\Config\Collections\CachedConfigCollection->getCollection() #9 /var/www/vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(81): SilverStripe\Config\Collections\CachedConfigCollection->get('SilverStripe\\Co...', 'module_priority', 1) #10 /var/www/vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(114): SilverStripe\Core\Config\Config_ForClass->get('module_priority', 1) #11 /var/www/vendor/silverstripe/framework/src/Core/Manifest/ModuleManifest.php(231): SilverStripe\Core\Config\Config_ForClass->uninherited('module_priority') #12 /var/www/vendor/silverstripe/framework/src/Core/BaseKernel.php(202): SilverStripe\Core\Manifest\ModuleManifest->sort() #13 /var/www/vendor/silverstripe/framework/src/Core/CoreKernel.php(32): SilverStripe\Core\BaseKernel->bootManifests(false) #14 /var/www/vendor/silverstripe/framework/src/Control/HTTPApplication.php(132): SilverStripe\Core\CoreKernel->boot(false) #15 /var/www/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #16 /var/www/vendor/silverstripe/framework/src/Control/HTTPApplication.php(138): SilverStripe\Control\HTTPApplication->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #17 /var/www/vendor/silverstripe/framework/src/Control/HTTPApplication.php(113): SilverStripe\Control\HTTPApplication->execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), false) #18 /var/www/public/index.php(42): SilverStripe\Control\HTTPApplication->handle(Object(SilverStripe\Control\HTTPRequest)) #19 {main} thrown in /var/www/app/src/Backend/PhpRedisFlysystemStorage.php on line 5

**Comment by tinect** [comment]
f.e. https://github.com/jgivoni/flysystem-cache-adapter

there might be more found by using search engines.

**Comment by harsh16021992** [comment]
Ok thanks

**Comment by tinect** [comment]
@harsh16021992 you might want to close this issue, don't you?

**Comment by harsh16021992** [comment]
sure you can

**Comment by tinect** [comment]
I cannot do it, you have to do it.
