### ISSUE TITLE
ftp_fput(): I won't open a connection to 172.31.48.80 (only to 47.104.....)

### ISSUE THREAD

**Issue by hulang** [thephpleague/flysystem#1815]
### Question

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.28.0   |
| Adapter Name      | FtpAdapter |
| Adapter version   | 3.28.0   |

There are no issues with local testing

An error occurred on the server

**Comment by frankdejonge** [comment]
Closing this as the issue provides no description that I can action on.
