### ISSUE TITLE
gcs cant retrieving URL

### ISSUE THREAD

**Issue by holiq** [thephpleague/flysystem#1834]
### Bug Report

| Q                 | A       |
|-------------------|---------|
| Flysystem Version |   v3 |
| Adapter Name      | GoogleCloudStorageAdapter |
| Adapter version   | v3.28.0   |

#### Summary

when i upload image on filament with [spate media library](https://filamentphp.com/plugins/filament-spatie-media-library), i got this

![Screenshot from 2024-11-24 18-29-37](https://github.com/user-attachments/assets/6c1c1547-0d4d-49a6-86b8-f8d118157d11)

this my provider for create the disk gcs

![image](https://github.com/user-attachments/assets/407ea09a-1a96-4520-a522-338072304470)

**Comment by frankdejonge** [comment]
Seems like a Laravel issue, not a Flysystem issue.
