### ISSUE TITLE
php8.4.1，league/flysystem1.1.10，League\\Flysystem\\Filesystem::get(): Implicitly marking parameter $handler as nullable is deprecated, the explicit nullable type must be used instead 

### ISSUE THREAD

**Issue by 2606062632** [thephpleague/flysystem#1835]
League\\Flysystem\\Filesystem::get(): Implicitly marking parameter $handler as nullable is deprecated, the explicit nullable type must be used instead

**Comment by frankdejonge** [comment]
V1 is out of support for a long time now
