### ISSUE TITLE
Problems with FTP adapter

### ISSUE THREAD

**Issue by zupolgec** [thephpleague/flysystem#191]
I'm trying to use this library to connect to a WS_FTP server. I encounter the same problem I had some time ago with the PHP FTP functions: directory listing, file getting/putting only work if filepaths are sent to the FTP connection with double quotes (") around.

**Comment by kinncj** [comment]
https://github.com/thephpleague/flysystem/issues/451

**Comment by frankdejonge** [comment]
Fixed by #451

**Comment by php-dedicated-developers** [comment]
hi,
get a list of directories and files within the folder with space in a name. you can try with below code in PHP.
```
$conn = ftp_connect($hostname, $port, $timeout);
ftp_chdir($conn, $path);
//will give us directories or files with name in space
$children = ftp_rawlist($conn,'-a .');
```
[PHP ftp_rawlist() get directory list with space in name](http://guruquest.net/question/php-ftp_rawlist-not-getting-directory-list-with-white-space-in-name/)

**Comment by RubtsovAV** [comment]
It already fixed
