### ISSUE TITLE
Check Symlink

### ISSUE THREAD

**Issue by tomfischerNL** [thephpleague/flysystem#203]
Hi There, 

Just made a quick fix to check whether the type is 'dir, file or link (symlink)'

In the file
\League\Flysystem\Adapter\AbstractFtpAdapter.php link 262 I added:

```
if ($type === 'dir') {
            return compact('type', 'path');
        }
        elseif($type === 'file')
        {
            if($permissions{0} === 'l')
            {
                $type = 'link';
            }
        }
```

Now you can check if there is a symbolic link so that the read() method doesn't get any errors. ;)

**Comment by jonnott** [comment]
Really could do with a way to work around symlinks, for both Local and FTP adapters..
