### ISSUE TITLE
Copy Directory 

### ISSUE THREAD

**Issue by newtonianb** [thephpleague/flysystem#234]
How can I copy a directory from sourcePath to targetPath ?

**Comment by kachkaev** [comment]
Why can't there be a plugin that does it? I'm asking because this seems like a pretty common task. I don't quite understand the complexity of the assumptions, to be honest. One recursive function + one caller method.

Maybe the complications may arise with large hierarchies or file sizes – I don't have much experience with these cases. @frankdejonge, could you please explain?

Searching "flysystem copy directory" points to this page first, so this is probably the best place for a discussion.

I'd like to do something like that at the moment:
```$mountManager->copyDir('zipfs://source/dir', 'localfs://target/dir');```

**Comment by maximelebastard** [comment]
+1

**Comment by bkuhl** [comment]
if `copy` doesn't support both files and directories it should probably renamed to the more explicit `copyFile()`.

**Comment by symball** [comment]
+1 for this request; would make OneUp incrediby powerful. Similar to Kachkaev, i'm wanting to go from zipfs to S3.

**Comment by symball** [comment]
In the meantime, for any pondering a quick way of performing this, in the example below, I'm using mountManager to handle the two filesystems

> $contents = $mountManager->listContents('scratch://'.$publication->getSlug(), true);
>       foreach ($contents as $fileNode)
>       {
>         if($fileNode['type'] == 'dir')
>         {
>           $mountManager->createDir('s3://'.$fileNode['path']);
>           continue;
>         }
> 
>         $mountManager->put(
>           $fileNode['filesystem'].'://'.$fileNode['path'],
>           's3://'.$fileNode['path']
>         );
>       }

**Comment by bkuhl** [comment]
Not the ideal approach, but the S3 package supports uploading a directory under the covers:

```php
        $s3Client = app('s3Client');
        $this->s3Client->uploadDirectory(
            $localDirectory,
            $awsBucket,
            $pathPrefixInAWS,
            $awsOptions
        );
```

**Comment by leith** [comment]
@symball Would you need to use `createDir()` when they would be created implicitly by wrapping the `put()` in a `$fileNode['type'] == 'file'` (or `!= 'dir'`) check?

**Comment by symball** [comment]
For my usage,  the above was something I put together very quickly and it is looping through a huge list of files. at the time thought it wouldn't hurt to simply have directories created, it is supposed to be copying from one filesystem to another so missing even empty directories breaks that.

**Comment by deepak1725** [comment]
For Guys still having this Issue. please refer
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html

**Comment by rulatir** [comment]
> For Guys still having this Issue. please refer
> https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html

This issue is not s3 specific.
