### ISSUE TITLE
Rackspace upload large files

### ISSUE THREAD

**Issue by modernmediaca** [thephpleague/flysystem#246]
Rackspace uses

    $transfer = $container->setupObjectTransfer(array(
        'name' => 'video.mov',
        'path' => '/home/jamie/video.mov',
        'metadata' => array(
            'Author' => 'Jamie'
        ),
        'concurrency' => 4,
        'partSize'    => 1.5 * Size::GB
    ));

    $transfer->upload();

To upload large files. Is there anyway to do this in Flysystem?

**Comment by frankdejonge** [comment]
I'm transferring this to the rackspace repo.
