### ISSUE TITLE
OpenStack bulk delete

### ISSUE THREAD

**Issue by basz** [thephpleague/flysystem#262]
According to https://godoc.org/github.com/ncw/swift not all servers accept the bulk delete command (I found this to be the case on cloudvps.nl's object store). This means that deleteDir may fail with an Forbidden error.

I guess this should be made configurable via an allowsBulkDeletions setting on the adapter..? And if it doesn't allow for bulk delete it should use regular deletes.

**Comment by frankdejonge** [comment]
Closing this, if needed it can be re-opened.
