### ISSUE TITLE
Adapter for SCP/SSH

### ISSUE THREAD

**Issue by Remo** [thephpleague/flysystem#270]
Surprisingly, I haven't found a discussion about this. Has anyone every thought about a supporting SCP/SSH?

As far as I can see, the SCP functionality of phpseclib is quite limited, only `get` and `put` are supported (https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SCP.php).

Unless I'm missing something, this would be a bit tricky to implement as it would mean that we'd have to execute some SSH commands to list files. I'm not SCP expert, but I might help a bit if there's any interest.

**Comment by frankdejonge** [comment]
Since I'm already swamped with work. I'll close this, a PR will be much appreciated from whomever wants this added.
