### ISSUE TITLE
ReadStream, writesteam not creating files until complete download

### ISSUE THREAD

**Issue by sankarsuda** [thephpleague/flysystem#273]
Hi I am using readstream, writestream functions to download 1Gb+ files from sftp server.

```
$manager->writeStream('local://'.$entry['basename'],
                        $manager->readStream('sftp://'.$entry['basename'])
        );
```

When we initiate the request file is not creating in location until it download complete file into memory.
If the file size is big existing with fatal error.

Is there any way create file immediately and start writing into file without using much memory?

**Comment by veilig2000** [comment]
This still isn't possible yet...is it?

I was trying the same thing in a laravel app - downloading a file from S3. It appeared my app had to fully download the file from S3 before it would respond to the client.

Is there a better way I should be handling this?

    $s3Client = S3Client::factory([
        'key' => '<key>',
        'secret' => '<secret>',
    ]);
    $s3Client->registerStreamWrapper();                                                    

    $filesystem = new Filesystem(
        new AwsS3Adapter($s3Client, '<bucket>')
    );

    return \Response::stream(function() use ($filesystem, $file) {
        fpassthru($filesystem->readStream($file));
    }, 200, $headers);
