### ISSUE TITLE
[AWS Adapter] Get all metadata stored in S3

### ISSUE THREAD

**Issue by aanton** [thephpleague/flysystem#285]
Hi.

I wonder if there is any way to get all the metadata stored on S3 using the filesystem object. I have tried the `getMetadata` method but the S3 adapter normalizes the returned metadata (i suppose to standardize the behavior of the adapters).

This is the code i use to test it:

``` php
<?php

require 'vendor/autoload.php';

use Aws\S3\S3Client;
use League\Flysystem\AdapterInterface;
use League\Flysystem\Cache\Noop;
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\AwsS3;

$client = S3Client::factory(array(
    'profile' => 'default',
    'region' => 'eu-west-1'
));

// Configuration (change it properly)

$bucket = 'my-bucket';
$localFile = '/path/to/image.jpg';
$key = 'tmp/demo-flysystem.jpg';

// 1. Create a new file using FlySystem

$filesystem = new Filesystem(new AwsS3($client, $bucket, ''), new Noop());

// Clean up previous test
if ($filesystem->has($key)) $filesystem->delete($key);

$filesystem->writeStream($key, fopen($localFile, 'r'), [
    'visibility' => AdapterInterface::VISIBILITY_PUBLIC,
    'Expires' => '10',
    'Metadata'     => [
        'param1' => 'value1',
        'param2' => 'value2'
    ]
]);

$data = $filesystem->getMetadata($key);
var_dump($data);
```

An screenshot of my debugger:

![phpstorm-flysystem-awss3-getmetadata](https://cloud.githubusercontent.com/assets/717192/4678108/33b7d4ae-55f1-11e4-8786-fc979b808b3d.jpg)

Thanks for your support and time.

Regards,
Armando

**Comment by socieboy** [comment]
Hi guys! @frankdejonge Do you have a way to upload a file with the metadata for amazon?

**Comment by frankdejonge** [comment]
@socieboy you can use the `Metadata` option when writing:

```php
$filesystem->writeStream($location, $stream, ['Metadata' => ['key' => 'value']]);
```

**Comment by socieboy** [comment]
How do a read all files on the bucket with the metadata included on that request.?
