### ISSUE TITLE
Feature request: copy & rename methods allowing overwrite the destination file

### ISSUE THREAD

**Issue by aanton** [thephpleague/flysystem#292]
Hi.

Currently the copy & rename methods throw an exception if the destination file exists. It would be great if this behavior could be defined when calling the methods, perhaps with an optional parameter to allow overwriting (by default it would be false to keep backward compatibility).

@FrenkyNet what do you think?

Regards,
Armando

**Comment by patkar** [comment]
:+1:

**Comment by bogdanghervan** [comment]
+1

**Comment by kallealberg** [comment]
+1

**Comment by mediamonks-robert** [comment]
+1

**Comment by justinkwanlee** [comment]
+1

**Comment by briedis** [comment]
+1

**Comment by anydasa** [comment]
+1

**Comment by Ronnie-J** [comment]
+1

**Comment by frankdejonge** [comment]
ForceCopy and ForceRename plugins are now provided, tagged and released.

**Comment by Anahkiasen** [comment]
@frankdejonge What version are those tagged under, I don't see any release since June 3?

**Comment by schmunk42** [comment]
@frankdejonge The `MountManager` should also get these methods.
