### ISSUE TITLE
Question: How to get the complete path (including filesystem path) of a File instance

### ISSUE THREAD

**Issue by aanton** [thephpleague/flysystem#294]
Hi @FrenkyNet.

I am trying to get the complete path of a File instance but i failed. I have found a workaround using the FileSystem instance:

``` php
$filesystem->getAdapter()->applyPathPrefix($key)
```

This is the code to test it:

``` php
<?php

require 'vendor/autoload.php';

use League\Flysystem\Adapter\Local;
use League\Flysystem\File;
use League\Flysystem\Filesystem;

// Configuration (change it properly)
$path = '/home/aanton/tmp/flysystem';
$localFile = '/path/to/local/image.jpg';
$key = 'tmp/image.jpg';

$filesystem = new Filesystem(new Local($path));

// Clean up previous test
if ($filesystem->has($key))
{
    $filesystem->delete($key);
}

$filesystem->putStream($key, fopen($localFile, 'r'));
$file = $filesystem->get($key);

function my_file_tasks(File $file, FileSystem $filesystem)
{
    var_dump($file->getPath());
    var_dump($filesystem->getAdapter()->applyPathPrefix($file->getPath()));
}

my_file_tasks($file, $filesystem);
```

I would like to avoid the FileSystem dependency in my `my_file_tasks` function. I know i can change the signature and work with the (string) path, but the File object give me some other valuable information.

Any suggestions? :)

Regards,
Armando

**Comment by aanton** [comment]
Finally we extended the File class to add a new method "getFullPath".

Regards,
Armando

**Comment by dupuchba** [comment]
@aanton you resolved your problem but let me propose you another solution that comply with `flysystem` principles (e.g not exposed specific storage info).

You could have load the image with the `readStream()` method of the `File` class with for example Imagine or other image processing libraries that take `resources`as argument.

```
$imagine = new Imagine();
$image = $imagine->read($file->readStream()); 

$cropManager = new CropGenerator($config);
$newFile =  $cropManager->create($image, $rules);
```

**Comment by frankdejonge** [comment]
@dupuchba a PR with this as an example in the docs would be much appreciated, I think many will benefit from knowing this.

**Comment by dupuchba** [comment]
@frankdejonge I'll try to do it tonight.

**Comment by srmklive** [comment]
I believe you can get the base path of an adapter like this:
```
$path = '/home/aanton/tmp/flysystem';
$localFile = '/path/to/local/image.jpg';
$key = 'tmp/image.jpg';

$local = new Local($path);
$filesystem = new Filesystem($local);

echo $local->getPathPrefix(); // Get the base path for an adapter
```

**Comment by pthreat** [comment]
@frankdejonge I actually question myself for using this library when I read that you don't know "why would someone need a full path", in my case I need the full path of a certificate file stored on my local FS.

**Comment by tacman** [comment]
similar to #1740
