### ISSUE TITLE
Problem with renaming folders using AWS-S3 adapter

### ISSUE THREAD

**Issue by zaak** [thephpleague/flysystem#295]
I'm using following sequence:
```php
$filesystem->createDir('foo/bar');
$filesystem->rename('foo/bar', 'foo/baz');
```
Folders are created properly, but renaming throws following exception:
```
Fatal error: Uncaught Aws\S3\Exception\NoSuchKeyException: AWS Error Code: NoSuchKey
```

Flysystem v0.5.9
AWS-SDK v2.7.1

**Comment by frankdejonge** [comment]
The outcome for this discussion is not entirely clear to me, seems resolved. If not this issue can be re-opened on the repo of the corresponding adapter.

**Comment by mstaack** [comment]
@frankdejonge has there been any updates on this topic? Having the same issue.
Currently the preferred way to handle a folder rename is @Flightfreak approach?
