### ISSUE TITLE
Copying files between filesystems

### ISSUE THREAD

**Issue by dinamic** [thephpleague/flysystem#296]
We have some files that are a few gigabytes each and would like to get them transferred via copying from one filesystem to another filesystem.

I have tried the following:

```
$manager = new Flysystem\MountManager(array(
    'local'  => $local,
    'remote' => $remote,
));

$isCopied = $manager->copy('local://'. $filename, 'remote://test.bin');
```

However, it does not work. When I dump to see what's going wrong, it seems it is trying to create a folder "/tmp/remote:". The "/tmp" is the root folder of the local adapter.

I guess I am not doing things the right way.

Could you give me any advise on how to copy a file from one filesystem to another filesystem, having in mind they are a few gigabytes each and I don't really want to store them in memory?

**Comment by mirfilip** [comment]
For newcomers, it's worth mentioning above is no longer the case. `MountManager::copy` supports copying between different adapters.

**Comment by Nek-** [comment]
@frankdejonge there's no more doc about it at all isn't it ^^' ?
