### ISSUE TITLE
Support One Drive and Mega.co.nz

### ISSUE THREAD

**Issue by moazam1** [thephpleague/flysystem#299]
Great package! Can you add support for One drive and mega.co.nz?

**Comment by sagikazarmark** [comment]
Here is a great article about Mega:

http://julien-marchand.fr/blog/using-the-mega-api-with-php-examples/

There is no (and won't be any) official PHP clients as the client side encryption they use is released as a C library. So either a PHP extension is needed (how about no?) or the client must use the HTTP API.

**Comment by jacek-b** [comment]
I've started working on the integration with OneDrive, I'll keep you posted about the progress!

**Comment by jacekbarecki** [comment]
OneDrive adapter ready! See #606 or go directly to the repo: https://github.com/jacekbarecki/flysystem-onedrive

**Comment by frankdejonge** [comment]
This can be supplied by the community if needed.
