### ISSUE TITLE
Big Files tooo long to write !

### ISSUE THREAD

**Issue by ghost** [thephpleague/flysystem#310]
Hello,
well i m using flystem, but i have a big issues.

i musing flystem to create a new file.

i open a big csv files more than 60000 lines, and i create a new file with text with this csv files.

but the time traitement is reallly big.
i think is flystem ?

i make a shoot :
if i have a csv files with 1000 lines, if i create  2 files with it, i have a time traitement = 64s
for the same csv files if i do it in On files the time traitement is 124s

why the the writing files with flystem is soo long, please ?

edit : 

i think my problem is my writTxt function :: 

```
function writeTxt($string, $dstLogFiles, $nameFiles = 'logFiles.txt') {
    $today = date("Y-m-d H:i:s");
    $content = "";
    if ($dstLogFiles -> has($nameFiles))
        $content = $dstLogFiles -> read($nameFiles);
    $content .= $string;
    $dstLogFiles -> put($nameFiles, $content);
}
```

like u see the fils is read evrytime i use this function.
i need to write a function who add line without readinf files.
well i think with flysystem u can't add string content on files without reading the all files ?

to solve my problem i m using this function : 

```
function updateF($s, $dst, $name) {
    $fp = fopen("PATHFILES".$name,"a"); 
    fwrite($fp, $s);
    fclose($fp);    
}

```

Please what do u think, how use flystem to update files without reload the entire files ?

**Comment by ychoucha** [comment]
sorry how i can make it works

i m really stuck with this bugs

**Comment by twistor** [comment]
From your example above:
```php
function writeTxt($string, $dstLogFiles, $nameFiles = 'logFiles.txt') {
    $today = date("Y-m-d H:i:s");

    if ($dstLogFiles->has($nameFiles)) {
        $stream = $dstLogFiles->readStream($nameFiles);
        $dstLogFiles->putStream($nameFiles, $stream);
        fclose($stream);
    }
}
```

There should be error checking above in case `readStream()`, or `putStream()` failed.
