### ISSUE TITLE
Mime type for stream uploads

### ISSUE THREAD

**Issue by Azuka** [thephpleague/flysystem#34]
I noticed that my stream uploads for objects like jpg files are getting force-downloaded in the browser and it seems the mime type for streams is not being set. Is there a way to specify the mime type manually, or detect it from the stream? This is for Amazon S3.

Thanks.

**Comment by barryvdh** [comment]
@frankdejonge what about guessing the mimetype based on the filename if it's not set? For example with https://github.com/guzzle/guzzle/blob/v3.8.1/src/Guzzle/Http/Mimetypes.php
