### ISSUE TITLE
Add support for AWS S3 reduced redundancy

### ISSUE THREAD

**Issue by atrauzzi** [thephpleague/flysystem#342]
See here for more information: http://docs.aws.amazon.com/AmazonS3/latest/dev/SetStoClsOfObjUploaded.html

...which details that putting information in the bucket with the header `x-amz-storage-class: REDUCED_REDUNDANCY` which stores the data using lower cost resources.

**Comment by frankdejonge** [comment]
@atrauzzi I'd gladly merge a PR for this in one of the following repo's:

http://github.com/thephpleague/flysystem-aws-s3-v2
http://github.com/thephpleague/flysystem-aws-s3-v3

**Comment by creocoder** [comment]
@frankdejonge Is there any plans to remove \League\Flysystem\Adapter\AwsS3 from main repository? As i understand external services adapters moved to separate repos (webdav, aws, dropbox, etc).

**Comment by GrahamCampbell** [comment]
> Is there any plans to remove \League\Flysystem\Adapter\AwsS3 from main repository? 

Yes. it's already removed on another branch.
