### ISSUE TITLE
Same plugin, different Adapters?

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/flysystem#350]
Maybe I'm not understanding Plugins correctly, but there are two use-cases for Plugins, right?

 1.  Simplify common tasks for Flysystem based on the public API's
 2.  Add new functionality using the underlying adapters directly. 

So 1. is just handy to avoid doing the same thing, but 2 is adding functionality that is missing from Flysystem. But is it possible to abstract that? And what is recommended? Or is that out of the scope of this project?

For example, [falc/flysystem-sftp-symlink-plugin](https://github.com/Falc/FlysystemSftpSymlinkPlugin) and [falc/flysystem-local-symlink-plugin](https://github.com/Falc/FlysystemLocalSymlinkPlugin) add the same functionality for 2 different adapters. Would it make more sense to have 1 plugin that supports multiple adapters?

And then it would be necessary to be able to check if the Flysystem is supporting the Adapter or not.

    $filesystem = new Filesystem(new Adapter\Local(__DIR__.'/path/to/files/'));
    $filesystem->addPlugin(new SymlinkPlugin);
    if($filesystem->supports('symlink')){
        return $filesystem->SymlinkPlugin($link, $target);
    } else {
        return false;
    }

My use-case would be for using this abstraction in elFinder (https://github.com/Studio-42/elFinder/pull/928), to provide the same functionality to multiple adapters, if possible. Not much concrete now, but was thinking about how to add extra functionality (archiving/symlink).

**Comment by Markcial** [comment]
The use of the plugin on the mount manager was solved in a relatively recent issue, i am not 100% sure that the solution might work for you, but there were a update for a plugin used in different filesystems as a shared plugin

**Comment by frankdejonge** [comment]
@barryvdh the plugins are designed to extend the Filesystem class. Since the FilesystemInterface allows you to access the adapter it can also be used to interact with that. The main reason (like the provided plugins do) however, is to extend the Filesystem functionality.
