### ISSUE TITLE
Root directory isn't actually a root

### ISSUE THREAD

**Issue by jschreuder** [thephpleague/flysystem#36]
If I configure a path as the root of my adapter I would expect it to work as the root and not allow access down from there. Otherwise it's really more of a "home" directory, or "initial" directory. When I hand it a path with multiple "../../" in there, it will gladly allow me outside of the root.
(note: this is based on the Local adapter as I haven't used any of the others yet)

A possible fix might be something along these lines in the `prefix()` method:

``` php
<?php
    protected function prefix($path)
    {
        if (empty($path)) {
            return $this->root;
        }

        $path = realpath($this->root.Util::normalizePath($path, DIRECTORY_SEPARATOR));
        if (strpos($path, $this->root) !== 0) {
            throw new \OutOfBoundsException('You cannot go outside the root directory.');
        }

        return $path;
    }
```

This is an issue with possible security concerns as well. Even though the dev using this lib still should do his own input filtering, the library shouldn't allow paths below something called a 'root' as an extra layer of security. Or the setting should be renamed to something that doesn't imply it's the lowest the adapter will go.

**Comment by alexweissman** [comment]
Does `normalizePath` also check for encoded paths, like `%2e%2e%2f` or others mentioned in the [OWASP page](https://www.owasp.org/index.php/Path_Traversal)?
