### ISSUE TITLE
Remove Caching From The Flysystem Cache

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/flysystem#367]
Now that we have that caching adapter, we don't need to duplicate the functionality in the flysystem class.

**Comment by frankdejonge** [comment]
@GrahamCampbell you're figured out why I extracted it ;)

**Comment by GrahamCampbell** [comment]
Yeh, it's a cool idea. We should probably move the actual cache stuff out of the main flysystem repo too.

**Comment by GrahamCampbell** [comment]
Also, I'm loving the architectural changes you're making. :)

**Comment by frankdejonge** [comment]
@GrahamCampbell indeed, I'm not sure where to move them to though. Preferably I'd only have to hint a PSR cache interface, and remove them all together. But that seems to be a stretch for now.

**Comment by GrahamCampbell** [comment]
Yeh, could you just create a flysystem-cache repo and put all the cache adapters in there?

**Comment by frankdejonge** [comment]
@GrahamCampbell I'll do that.

**Comment by frankdejonge** [comment]
@GrahamCampbell also, I don't know if you got my tweet, but if you're still up for helping out with the adapter moves => much appreciated.

**Comment by GrahamCampbell** [comment]
Just seen it now. I don't have any time just now, but give me a few hours, and I should be able to help. :)

**Comment by frankdejonge** [comment]
This is done in the 1.0 PR.

**Comment by GrahamCampbell** [comment]
:+1:
