### ISSUE TITLE
Is there a similar package like flysystem for .NET?

### ISSUE THREAD

**Issue by vuchl** [thephpleague/flysystem#369]
As said in the title I am looking for a package that works like flysystem but is compatible with .NET.

**Comment by frankdejonge** [comment]
I have no clue. I'll leave this issue open for a bit if others want to respond.

**Comment by boekkooi** [comment]
@vuchl To my knowledge there isn't a full featured package or lib like flysystem for .NET.
There are things like;
- https://github.com/tathamoddie/System.IO.Abstractions/ for testing (and looks extend-able) 
- https://github.com/pofider/AzureBlobFileSystem/ for azure and local
- https://github.com/mgernand/Portable.IO for .NET, Windows Phone etc.

There's probably a ton more on https://www.nuget.org

**Comment by frankdejonge** [comment]
@boekkooi thank you for the suggestions! @vuchl does that help you out?

**Comment by vuchl** [comment]
Yes that's quite comprehensive. Thank you guys!
