### ISSUE TITLE
How to use wildcards in filesystem->has($path)

### ISSUE THREAD

**Issue by babaggeii** [thephpleague/flysystem#371]
I'm trying to access a file with unknown extension, so I want to do something like this:

    $filesystem->has($path . '/' . $currentUser['username'] . '.*')

But this doesn't work. How can I use the wildcard in this situation?

**Comment by barryvdh** [comment]
Perhaps list the contents of the folder and match the values yourself?

**Comment by frankdejonge** [comment]
@babaggeii what @babaggeii says is correct. Things like this can easily be created on top of Flysystem. A list contents with a preg_match on the paths would be all you need.
