### ISSUE TITLE
Namespace Proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/flysystem#374]
How about we move the exception classes to their own namespace in this repo?
`League\Flysystem\FileExistsException` => `League\Flysystem\Exceptions\FileExistsException` etc.

**Comment by aranw** [comment]
I'm for this, as the project grows the number of exceptions grow its always useful to have them in one central place. A good example of how this is useful is when using the generated API docs like Symfony's 

e.g. http://api.symfony.com/2.3/Symfony/Component/DependencyInjection/Exception.html

**Comment by JulienTant** [comment]
I'm for :+1:

**Comment by billmn** [comment]
Agree ... this allow a better files organization,
but what for <code>League\Flysystem\Plugin\PluginNotFoundException</code> ? Where do you move it?

https://github.com/thephpleague/flysystem/blob/master/src/Plugin/PluginNotFoundException.php

**Comment by frankdejonge** [comment]
It would move to `League\Flysystem\Exception\PluginNotFoundException`, I guess?

**Comment by frankdejonge** [comment]
Also, the namespace name. All the other namespaces are singular. So I presume the namespace would be `League\Flysystem\Exception`, note the missing `s`. Just to keep consistency.

**Comment by billmn** [comment]
@frankdejonge :+1:

**Comment by lahaxearnaud** [comment]
+1

**Comment by jasonlewis** [comment]
Singular indeed. :+1+ for `League\Flysystem\Exception`.

**Comment by atrauzzi** [comment]
:+1: to singular, and I support either approach.

Is there any case to be made for execptions to live with what throws them, rather than in one big pile of exceptions?

**Comment by aztech-dev** [comment]
I'm all for exceptions living in the namespace where they are thrown, with base exceptions living in the root package NS. Some exceptions can share name but not semantic meaning depending on who throws them (ie. Stupid example, but you could have two specialized InvalidArgumentException's with different CTOR's and properties. Stuffing them in the same NS would force longer names unnecessarily...)

**Comment by potherca** [comment]
:+1: for `League\Flysystem\Exception`

**Comment by sagikazarmark** [comment]
Is the `Exception` needed in the class name if it is moved under the `Exception` namespace?

`League\Flysystem\Exceptions\FileExists`?

**Comment by GrahamCampbell** [comment]
It's too late now. 1.0.0 has been tagged. This will have to wait until 2.0.

**Comment by frankdejonge** [comment]
After considering many arguments, I think keeping the exceptions close to what throws them outweighs the separation in this case. There are only a couple exceptions, not a whole lot, which makes the downsides of introducing a BC break not worth while at this point. When and if there are more exceptions introduced this discussion can continue, until then it's a wont-fix.
