### ISSUE TITLE
Zip only saves when object destroyed

### ISSUE THREAD

**Issue by doppynl** [thephpleague/flysystem#375]
When working with the Zip adapter, the changes I make to the zip are only saved once the \League\Flysystem\Adapter\Zip object is destroyed.

Is there a way to write the changes to disk on request? Without destroying the object.

There is a method "reopenArchive" in the Zip adapter, but it is protected.
Also, it is obviously not on the AdapterInterface as most other adapters will make the changes instantly

Perhaps something of a method "flushChanges" can be added on the Filesystem class that in turn will call the adapter telling it to "flushChanges" if that might be needed.
This will be a bit weird for other adapters that apply changes instantly though.

**Comment by frankdejonge** [comment]
@doppynl sounds like a good suggestion. Could you move this issue to http://github.com/thephpleague/flysystem-ziparchive ?

**Comment by doppynl** [comment]
Can't move an issue, but created a new one there.

**Comment by GrahamCampbell** [comment]
This one can be closed.

> Can't move an issue, but created a new one there.

Yeh, that's why @frankdejonge meant. :)
