### ISSUE TITLE
1.0.0-alpha is incorrect

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/flysystem#376]
That tag should have been `1.0.0-alpha1`. Now we can't have any further alpha releases because composer reads `1.0.0-alpha` as newer than `1.0.0-alpha1` or `1.0.0-alpha2`.

**Comment by frankdejonge** [comment]
@GrahamCampbell I'll retag and remove it from packagist. Just a sec.

**Comment by frankdejonge** [comment]
Retagged!

**Comment by GrahamCampbell** [comment]
Also, this alpha tag doesn't make much sense, because i was getting dev versions from the master branch, but I have prefer stable enabled, so now I have your alpha tag. It only makes sense to tag an alpha once you've actually merged it to the master branch.

**Comment by frankdejonge** [comment]
@GrahamCampbell doesn't that conflict with the 1.0-dev tag then?

**Comment by GrahamCampbell** [comment]
`1.0-dev` is not a "tag". It behaves differently.

**Comment by GrahamCampbell** [comment]
It would make more sense to just merge this stuff to the master instead of creating an alpha tag. People can use 0.5.x if they want a stable version surely?

**Comment by frankdejonge** [comment]
@GrahamCampbell since the bootstrapping is different and some dev version are relying in 1.0-dev this could break their stuff. The tag on this branch works just fine though?

**Comment by GrahamCampbell** [comment]
Not for me is what I'm saying. I was getting changes from the master until you tagged this alpha release, and now composer will only load this alpha tag.

**Comment by GrahamCampbell** [comment]
I was relying on `~1.0@dev` and now composer is loading this alpha tag.

**Comment by frankdejonge** [comment]
@GrahamCampbell ok, what do you suggest then?

**Comment by frankdejonge** [comment]
@GrahamCampbell I just installed ~1.0@dev, I just get the dev-master branch. Not the alpha release.

**Comment by GrahamCampbell** [comment]
Try installing with "prefer-stable" enabled. That's where this issue lies.

**Comment by GrahamCampbell** [comment]
I'm using laravel 5 with prefer stable enabled. It's a website that's in production. :)

**Comment by GrahamCampbell** [comment]
https://styleci.grahamjcampbell.co.uk/repos

**Comment by frankdejonge** [comment]
@GrahamCampbell so, you're blaming me from living on the bleeding edge? ;)

**Comment by frankdejonge** [comment]
@GrahamCampbell if I merge this into master, you'll get the same error though, right?

**Comment by GrahamCampbell** [comment]
> so, you're blaming me from living on the bleeding edge? ;)

No, I'm saying there's no point in keeping this on another branch. You might as well merge it into the master since it's going to cause issues either way.

**Comment by frankdejonge** [comment]
@GrahamCampbell ahh, ok :+1:
