### ISSUE TITLE
Do Will Still Need A Wiki On This Repo?

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/flysystem#377]
The info in this wiki is quite old, and is no longer relevant.

**Comment by frankdejonge** [comment]
@GrahamCampbell which parts are no longer relevant? The adapter internals are still the same.

**Comment by GrahamCampbell** [comment]
The upgrading to 0.2 bit.

> The adapter internals are still the same.

That stuff would be better moved to the gh-pages docs.

**Comment by frankdejonge** [comment]
True, that's old. I've got a new version of the gh-pages for the release though.

**Comment by frankdejonge** [comment]
I've removed the 0.1 -> 0.2 page.
