### ISSUE TITLE
Suggest to rename `NullAdapter` to `Dummy`

### ISSUE THREAD

**Issue by creocoder** [thephpleague/flysystem#384]
This will allow avoid `Adapter` suggix and raise consistency with other adapters names.

**Comment by frankdejonge** [comment]
I'd be open to renaming it to DevNull, which is how it acts. Dummy is not specific enough. People know how /dev/null behaves.

**Comment by GrahamCampbell** [comment]
I think "NullAdapter" is fine. It's consistent with our other adapter names.

**Comment by barryvdh** [comment]
To be fair, it isn't really consistent.

    Adapter\Ftp
    Adapter\Local
    Adapter\NullAdapter

So to be consistent it would be `Adapter\Null` or `Adapter\DevNull` etc.

**Comment by frankdejonge** [comment]
I don't think we can name it `Null` though. Which is why I initially called it `NullAdapter`.

**Comment by frankdejonge** [comment]
I'm going to leave this as is. While naming is important, I don't think this weighs anywhere near heavy enough to cause a rename.
