### ISSUE TITLE
Upload files from HTTP streams

### ISSUE THREAD

**Issue by themao** [thephpleague/flysystem#386]
Is it possible to upload binary files via URLs (e.g. images)? Currently, when using writeStream(), it tries to rewind the http resource, which is not supported, so the only way to cope with that task seems to download it to a temporary folder.

**Comment by frankdejonge** [comment]
@themao which version are you using?

**Comment by themao** [comment]
0.1, installed with composer, along with OneUp bundle (dev-master) for Symfony2

**Comment by frankdejonge** [comment]
@themao the OneUp bundle seems to require 0.4, could you verify this? In later version this is already resolved.

**Comment by themao** [comment]
@frankdejonge you are right! I've made a mistake, 0.1 is the version of OneUp bundle, and it in fact requires 0.4. 

But the problem seems to be in League\Flysystem\Filesystem.php:148 - it tries to rewind the stream with Util::rewindStream($resource)

**Comment by frankdejonge** [comment]
@themao I think this is fixed in the newer versions of flysystem. Could you check that out?

**Comment by frankdejonge** [comment]
This is fixed in newer versions of Flysystem.
