### ISSUE TITLE
Outdated docs?

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem#394]
It seems like Cache are all moved out to https://github.com/thephpleague/flysystem-cached-adapter and thus we have to require that in composer to use Cache. Also, since the namespace also changed, even the document on https://github.com/thephpleague/flysystem-cached-adapter looks wrong?

Edit: it seems like only the git docs are not updated, http://flysystem.thephpleague.com/caching/ looks good

**Comment by frankdejonge** [comment]
@yellow1912 thanks, I just refer to the docs now.
