### ISSUE TITLE
Support for getting file url when applicable?

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem#396]
S3 for example has getObjectUrl which will returns the object URL. This is quite useful to serve the uploaded files/images to the public.

Can you consider supporting this when applicable or perhaps return the client via public get method so we can use it to do what we want? Or perhaps there is already a way to do this that I don't know of?

**Comment by barryvdh** [comment]
Related: #247 
You could write a plugin to handle it with the Adapter directly. Don't think there is a common solution yet.

**Comment by yellow1912** [comment]
Understood, but I have the same question with the person in the above thread: How do I get the client to return the url since the method to expose the client is not there?

**Comment by barryvdh** [comment]
It is in the v2: https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L111
So if you create a PR to add it to v3, it will probably get accepted.

**Comment by frankdejonge** [comment]
@yellow1912 I'm open for a PR like @barryvdh suggested, but there are currently no plans to expose public urls. The main reason being that this is not functionality that all the filesystems provide and it can easily be prepended to the path in userland code.
