### ISSUE TITLE
Caching docs

### ISSUE THREAD

**Issue by jasonvarga** [thephpleague/flysystem#398]
I'm trying to set up Stash Caching based off the docs:

``` php
use Stash\Pool;
use League\Flysystem\Adapter\Local as Adapter;
use League\Flysystem\Cached\Storage\Stash as Cache;

$pool = new Pool();
// you can optionally pass a driver (recommended, default: in-memory driver)

$cache = new Cache($pool, 'storageKey', 300);
// Storage Key and expire time are optional

$adapter = new Adapter(__DIR__.'/path/to/root');

$filesystem = new Filesystem($adapter, $cache);
```

But when doing `new Filesystem($adapter, $cache);`, I get the following error:

> Fatal error: Uncaught exception 'LogicException' with message 'A config should either be an array or a Flysystem\Config object.'

Have things changed since these docs were written? Am I missing something?

**Comment by sheeep** [comment]
It seems like you're using the version 1.0 of flysystem. Check out the [upgrade notice](http://flysystem.thephpleague.com/upgrade-to-1.0.0/#caching).

```php
use League\Flysystem\Adapter\Local;
use League\Flysystem\Cached\CachedAdapter;

$decoratedAdapter = new CachedAdapter($adapter, $cacheAdapter);
$filesystem = new Filesystem($decoratedAdapter);
```

Docs are currently outdated.

**Comment by jasonvarga** [comment]
Great, thanks for pointing that out.

**Comment by frankdejonge** [comment]
@sheeep yeah, it's an adapter decorator now. The docs cover this.
