### ISSUE TITLE
Adapter files?

### ISSUE THREAD

**Issue by AV4TAr** [thephpleague/flysystem#399]
Hey, I was going to test flysystem with S3, but there is no S3 adapter in the code, is this right?

```
PHP Fatal error:  Class 'League\Flysystem\Adapter\AwsS3' not found
```

**Comment by GrahamCampbell** [comment]
This is not a bug. The class was removed from this repo and moved to it's own repo.

**Comment by AV4TAr** [comment]
Ah cool (I'm not crazy!!! jeje), will update the doc to reference that.
