### ISSUE TITLE
Base Test for adapters

### ISSUE THREAD

**Issue by dbu** [thephpleague/flysystem#401]
As all adapters implement the same interface and are supposed to behave the same way, I think it would make a lot of sense to have one or more base tests that ensure the correct behavior. The adapter tests could extend those base tests and do the bootstrapping.

If we can agree on that, i could try to do a PR for that and update the included tests to use the test suite.

I would propose to create a Test namespace inside src - it is code that is useful to 3rd party adapters too. I would split into several tests: ReadTestCase, ReadMetadataTestCase, WriteTestCase, WriteDirTestCase, DeleteTestCase, VisibilityTestCase to make the size of each test more manageable. Adapter specific tests can then extend the base cases that make sense for that adapter, but still overwrite test methods or skip them if they do not apply.

**Comment by frankdejonge** [comment]
A PR would be very welcome. If you want to discuss this, we can discuss here or on IRC.

**Comment by dbu** [comment]
i will start with a first test so we can discuss a concrete example.

**Comment by frankdejonge** [comment]
@dbu awesome, thanks a bunch!

**Comment by dbu** [comment]
oh snap. sorry to have left that lying around forever.
