### ISSUE TITLE
Filesystem::listContents() with $directory '/'

### ISSUE THREAD

**Issue by nao-pon** [thephpleague/flysystem#405]
$directory = '/';
$this->adapter->listContents($directory, $recursive); result is [ '/hoge.txt' ]

Util::normalizeDirname('/') is '' empty string.
Util::dirname('/hoge.txt') is '/'

so $mapper return `false`

**Comment by frankdejonge** [comment]
@nao-pon I've just pushed a fix here: https://github.com/thephpleague/flysystem-copy/commit/38817a80487a52b6e00327dae19fb3d2cdfcb2ea

Can you see if that works for you? I think it should, and if so I'll tag a 1.0.1 for this fix.

**Comment by nao-pon** [comment]
Hi! @frankdejonge,

Thanks for your  solution.

I checked https://github.com/thephpleague/flysystem-copy/commit/38817a80487a52b6e00327dae19fb3d2cdfcb2ea and it was fixed.　:+1:
