### ISSUE TITLE
[doc request] improve api page

### ISSUE THREAD

**Issue by dbu** [thephpleague/flysystem#409]
http://flysystem.thephpleague.com/api/ just lists the methods of the Filesystem class. i think it would make more sense to explain how things work and then point the user to that class and make sure the phpdoc annotations are good and explain the behaviour as precisely as possible.

**Comment by cnanney** [comment]
On the topic of docs, I just updated to 1.0 and I see in the upgrade guide that "some helper functions have been moved to plugins", but I can't find anything about how the plugin system works or how to use any of the provided plugins.

I found some documentation for it in a fork: https://github.com/pborreli/Flysystem#plugins

**Comment by barryvdh** [comment]
Caching is also out-of-date. It stil for to 0.x versions.

**Comment by frankdejonge** [comment]
In the recent API docs update this was improved.
