### ISSUE TITLE
delete('filename.txt') not returning on success

### ISSUE THREAD

**Issue by Twiebie** [thephpleague/flysystem#415]
`$filesystem->delete('filename.txt');` doesn't seem to return anything if it succeeds. Only false if it fails.

`$filesystem->deleteDir('path/to/directory');` however returns 'boolean true' if it succeeds.
 
Thanks.

**Comment by barryvdh** [comment]
Which adapter?

**Comment by Twiebie** [comment]
Aws S3 V2.

**Comment by zaak** [comment]
I've hit the same issue, already logged in thephpleague/flysystem-aws-s3-v2#5

**Comment by Twiebie** [comment]
Ah, I missed that!

Closing this duplicate.
