### ISSUE TITLE
Dropbox adapter not listing paths/contents correctly

### ISSUE THREAD

**Issue by reidd** [thephpleague/flysystem#416]
I have just tried using the dropbox adapter. If I just try a simple `var_dump` of `listPaths` I get an empty array returned where an array of images is expected. The same issue occurs when I use `listContents`. If however I set the recursive flag to `true` both responses work. Additionally if I call both sets with the recursive flag as `true` only the first call returns a response. The path is definitely correct as I can `read` one of the images correctly within the same directory.

NOTE: I have tested using the local filesystem adapter without the recursive flags set and this works as expected.

I am currently using the `dev-master` version but I have also tested and confirmed the bug against the latest stable version (`0.4.2`)

**Comment by frankdejonge** [comment]
@reidd Hi, the latest stable version is 1.0.1, in which the adapter has been moved out into it's own repository (requires slightly different bootstrapping). On the 0.x version, the last version was 0.5.12. Could you check if that version works? I haven't heard of this problem before. If you still see the problem in the latest version. Could you create an issue on the corresponding repository and close this one? The repository is located at: http://github.com/thephpleague/flysystem-dropbox

**Comment by reidd** [comment]
Hey Frank, sorry I was referring to the versions of the Symfony extension (`oneup/flysystem-bundle`). The `league/flysystem` version from my composer file was referencing `0.5.3`. I have just updated to ensure it uses `1.0.1`. With this update `listContents` now works as expected without the recursive flag, so it seems an issue with the older version. FYI if I try `listPaths` now though I get the following error:

```
[BadMethodCallException]                                         
  Call to undefined method League\Flysystem\Filesystem::listPaths
```

This is not an issue for me though as I can use `listContents`.

**Comment by frankdejonge** [comment]
@reidd the issue you describe can be fixed by including the ListPaths plugins.

**Comment by reidd** [comment]
Ok thanks for the help. The documentation still specifies `listPaths` without the plugin:
http://flysystem.thephpleague.com/api/
