### ISSUE TITLE
Warning error by rewind() with network stream pointer

### ISSUE THREAD

**Issue by nao-pon** [thephpleague/flysystem#419]
"Warning: rewind(): stream does not support seeking in league/flysystem/src/Util.php on line 237"

I got this error when using network stream pointer.

I make filepointer like this
```php
$fp = stream_socket_client('ssl://'.$url['host'].':443');
fputs($fp, "GET {$url['path']} HTTP/1.0\r\n");
fputs($fp, "Host: {$url['host']}\r\n");
fputs($fp, "\r\n");
while(trim(fgets($fp)) !== ''){};
return $fp;
```

**Comment by frankdejonge** [comment]
@nao-pon how are you using this? Are you creating your own adapter?

**Comment by nao-pon** [comment]
@frankdejonge  I use [elFinder 2.1](https://github.com/Studio-42/elFinder/tree/2.1) + [elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver).

elFinder Dropbox volume driver is throw network stream file pointer on file copy/move.

It's a cheap way, `@rewind()`?

**Comment by barryvdh** [comment]
@nao-pon Are you trying to copy one stream (from you [Dropbox volume driver](https://github.com/Studio-42/elFinder/blob/2.1/php/elFinderVolumeDropbox.class.php#L1095)) to a stream from the Flysystem driver?

Have you tried using the Flysystem Dropbox driver?

You are using the stream_socket_client() method to avoid having to load the file in memory when using the streams?

**Comment by nao-pon** [comment]
> You are using the stream_socket_client() method to avoid having to load the file in memory when using the streams?

Yes, Because able to deal with a big file.

**Comment by barryvdh** [comment]
Okay, but http(s) streams are not seekable, so it will fail. That's probably not a problem when you copy it once, but will be if you try to read it again, because it's empty then, right?

**Comment by nao-pon** [comment]
There is a problem after twice certainly, but is there a case called more
than twice?

**Comment by barryvdh** [comment]
You can't know for sure, but I guess that would be a limitation to the user who provides a non-seekable stream.

From http://php.net/fseek
> Not all streams support seeking. For those that do not support seeking, forward seeking from the current position is accomplished by reading and discarding data; other forms of seeking will fail.

So a non-seekable stream should be something to be aware of in Flysystem. From the fseek comments, a suggestion is made to check if the stream is seekable using http://php.net/stream_get_meta_data

    function fseekable($stream) {
      $meta = stream_get_meta_data($stream);
      return $meta['seekable'];
    }

I guess that is better then supressing a warning, right?

**Comment by nao-pon** [comment]
@barryvdh , @frankdejonge Thanks! I respect your idea sincerely. :-)
