### ISSUE TITLE
Flysystem sftp

### ISSUE THREAD

**Issue by danr1979** [thephpleague/flysystem#426]
Hi.

I am having difficulty getting the flysystem sftp plugin to work. Would you be able to provide an example of how to use it to upload a file please? Should I use the "upload" method or perhaps "copy"? I've used the regular flysystem adapter OK but I constantly get a "file not found" message when using the sftp adapter even though the file exists.

The only thing I've noticed from the stack trace is that the path to the file has the leading slash stripped off by the flysystem library which invalidates the path.

I'd appreciate any help you can offer.

Thanks.

**Comment by frankdejonge** [comment]
@danr1979 Hi, have you set the root path in the Sftp adapter instantiation?

**Comment by danr1979** [comment]
Yes, but does the root path represent the local path where I want to upload from or the remote path where I am uploading to? I have tried both without success. 

Also, I'm not sure what method I should be using: "copy" seemed the best fit but perhaps I should read the local file's contents & then use the write method to write it to the remote location? The file I am uploading is a zip file however so I'm not sure if my method above would work. 

An example of how you would go about uploading a zip file would be really helpful please. 

Thanks for your time.

**Comment by toin0u** [comment]
@danr1979 This may help you :) https://gist.github.com/toin0u/5c9e709dd2a0cb9f63b0

**Comment by GrahamCampbell** [comment]
@toin0u The context is through my Laravel wrapper, so all the setup stuff isn't needed. You can just skip to the ::write() stuff.

**Comment by danr1979** [comment]
@toin0u @GrahamCampbell Thanks both.  If I was uploading a zip file to an sftp server though should I use the "read" method to get its contents and then write that to the server using the "write" method?

**Comment by toin0u** [comment]
@GrahamCampbell Oh sorry - I wasn't aware.

@danr1979 it depends which methods you want to use:
- `write` accepts a string https://github.com/thephpleague/flysystem/blob/master/src/AdapterInterface.php#L26
- `writeStream`accepts a ressource https://github.com/thephpleague/flysystem/blob/master/src/AdapterInterface.php#L37

It's better to `writeStream` is it's a big file ;)

**Comment by danr1979** [comment]
Perfect! I'd missed writeStream for some reason.  I'll give it a try.  Thanks for your help.

**Comment by toin0u** [comment]
You're welcome :) Maybe you can close this issue if it's resolved ;)
