### ISSUE TITLE
Concrette adapters should be final

### ISSUE THREAD

**Issue by creocoder** [thephpleague/flysystem#430]
@frankdejonge Just to prevent people from bad design decisions its good idea to make classes finalized where it make sense. Please read:

http://ocramius.github.io/blog/when-to-declare-classes-final/

And consider make classes final where it make sense.

**Comment by frankdejonge** [comment]
While it's a nobel thing to suggest... The opposite side of "preventing people from bad design decisions" is, unfortunately, "forcing them to obey your coding philosophy". For the record, I know Marc's opinions on this and agree with many/most/maybe all of them. This is, IMO, not the place to enforce them.

**Comment by creocoder** [comment]
> forcing them to obey your coding philosophy

There no my/your/anybody else coding philosophy. Everything is simplier. There is **wrong** object oriented design, there is **right** object oriented design.

Any drawbacks of making `\League\Flysystem\Filesystem` final? Its already extensible by plugins. If someboby will make `MyFilesystem extends \League\Flysystem\Filesystem` does not it obvious it will be 100% wrong decision? Or is there any sense to extends any adapter? Why you care about all those "wrong design" coders?

> This is, IMO, not the place to enforce them.

May I be honest? Does not this mask fear about loose library popularity? There is no objective reasons to leave classes extensible. By making classes final you'll not only satisfy perfectionists, you also help all those "inheritance oriented coders" to start thinking. I also think it will raise feedback.
