### ISSUE TITLE
Cannot check if given path is a directory

### ISSUE THREAD

**Issue by tpavlek** [thephpleague/flysystem#442]
Given a particular `/path/to/directory/`, I want to determine if `directory` is actually a directory.

There doesn't seem to be a way to accomplish this short of using some string manipulation to go down to `/path/to` and list all directories and see if `directory` is in there.

Is there a better way to do this, and if not, there really ought to be.

**Comment by frankdejonge** [comment]
You can do this by checking the type in the metadata:

```php
$metadata = $filesystem->getMetadata('path/to/dir/');

$isDir = $metadata['type'] === 'dir';
```

**Comment by frankdejonge** [comment]
@tpavlek ping ^

**Comment by tpavlek** [comment]
Thanks for this!

I guess I missed the first email. I'll try this when I get into the office
today and close if resolved.

Thanks :)

**Comment by tpavlek** [comment]
Thanks, this was exactly what I needed :)
