### ISSUE TITLE
root is write-only accessible for local (was this a change)?

### ISSUE THREAD

**Issue by SteamboatColorado** [thephpleague/flysystem#443]
Sorry, I have been struggling with a change in the way a root is setup for local.
In the past, I made root the user account on the system.  For instance "/home/pedward" and not
"/home/pedward/public_html"

I tend to like to put files I need to write and read (yaml) outside of web root, such as "/home/pedward/settings".  If I make root (for flysystem) web root "/home/pedward/public_html", I do not think I can get to the higher directories.  If I make root the top path ("/" or even "/home/pedward"), I get issues that now it is not writable.  This is a new change.

This has been a challenge for me.  Is there a mode or flag I can use to pass so that local could setup root to a non-writable, but readable location for local?

Great stuff you have.  I am very grateful for your contribution and work.

**Comment by pascaldevink** [comment]
+1 This threw me off when I needed the Local adapter to just read a file. I thus wasn't expecting errors about the folder not being writable.

**Comment by frankdejonge** [comment]
@SteamboatColorado / @pascaldevink, I've just pushed a commit which only checks if it's a dir and if it's readable, could you check if this works for you? I'll tag a release shortly after.

**Comment by pascaldevink** [comment]
This should work!

**Comment by SteamboatColorado** [comment]
Thanks Frank.  It did work.  What I did was to make root "/" and by doing so, I am able to use absolute paths in my scripts.  I have not done a check to see if it is now doing "//home/pedward/settings" verses "/home/pedward/settings", but I will check this weekend.  I think sometimes unix is forgiving if you try to pass double // forward slashes in file paths.  So, I am back in using Flysystem again.  Thanks.

**Comment by frankdejonge** [comment]
@SteamboatColorado welcome back ;)
