### ISSUE TITLE
listDirectoryContents recurvise in FtpAdapter for servers with limited LIST -lna capabilities

### ISSUE THREAD

**Issue by pae23** [thephpleague/flysystem#447]
Some ftp server have a limit for the recurvise listing.

I code a recurive per dir listDirectoryContents  
```
        $listing = ftp_rawlist($this->getConnection(), '-lna ' . $directory, $recursive);
        if ($listing === false) {
            return array();
        }
        $result = [];
        foreach ($this->normalizeListing($listing, $directory) as $filename => $object) {
            if (in_array($filename, array('.', '..'))) {
                continue;
            }
            $path = $object['path'];
            $result[] = $object;

            if ($recursive && $object['type'] == 'dir') {
                $result = array_merge($result, $this->listDirectoryContents($path));
            }
        }

        return $result;
```

I'd be happy to push request it but I want to be sure you are interested and if so how you want I integrate it. I think a new 'clientsideRecursive' item in configurable would be fine.
If you prefer to do it by yourself, you can copy/paste my code.

Regards

**Comment by jupitern** [comment]
this change would be great since most FTP servers pulled the support for recursive listing

**Comment by frankdejonge** [comment]
Recently implemented and released.
