### ISSUE TITLE
Google Cloud Storage driver

### ISSUE THREAD

**Issue by bogdanghervan** [thephpleague/flysystem#448]
It would be great if flysystem had support for GCS.

https://cloud.google.com/storage/docs/overview

**Comment by ChrisTerBeke** [comment]
Made this small Service provider to get this to work in the mean time:

```
<?php namespace App\Providers;

/*
 *	    ____  ____  _____   ____________
 *	   / __ / __ /  _/ | / /_  __/ __
 *	  / /_/ / /_/ // //  |/ / / / / /_/ /
 *	 / ____/ _, _// // /|  / / / / _, _/
 *	/_/   /_/ |_/___/_/ |_/ /_/ /_/ |_|
 *
 *	Copyright Printr B.V. All rights reserved.
 *	This code is closed source and should under
 *	nu circumstances be copied or used in other
 *	applications than for Printr B.V.
 *
 */

use Illuminate\Support\ServiceProvider;
use Storage;
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v2\AwsS3Adapter;
use League\Flysystem\Filesystem;

class GcsAppsServiceProvider extends ServiceProvider
{
	public function register()
	{

	}

	public function boot()
	{
		Storage::extend('GCS_APPS', function( $app, $config )
		{
			$client = S3Client::factory(array(
				'key' => $config['gcs_key'],
				'secret' => $config['gcs_secret'],
				'base_url' => $config['gcs_base_url'],
			));

			return new Filesystem(new AwsS3Adapter($client, $config['bucket']));
		});
	}
}
```

Have fun with it :)

**Comment by fedeisas** [comment]
+1

@ChrisTerBeke I'm not sure how your implementation works. Does the Google Cloud Storage API has the same endpoints as the AWS S3 service just with a different `base_url`?

**Comment by ChrisTerBeke** [comment]
Yes! Their protocol is exactly the same (in order to make transitioning easy).

**Comment by barryvdh** [comment]
See https://cloud.google.com/storage/docs/migrating#migration-simple

> In a simple migration from Amazon S3 to Google Cloud Storage, you can use your existing tools and libraries for generating authenticated REST requests to Amazon S3, to also send authenticated requests to Google Cloud Storage. [..] 
> In your existing tools or libraries, make the following changes:
> - Change the request endpoint to use the Google Cloud Storage request endpoint.
> - Replace the Amazon Web Services (AWS) access and secret key with the corresponding Google Cloud Storage access key and secret key (collectively called your Google developer key).

**Comment by fedeisas** [comment]
Great! Thanks @ChrisTerBeke @barryvdh

**Comment by bcalik** [comment]
Is there any progress on the native integration?

**Comment by matthewgoslett** [comment]
We needed to have both AWS V3 and Google Storage adapters in place simultaneously, so the V2 driver was not an option as a work-around.
We've built a Google Storage driver here -> https://github.com/Superbalist/flysystem-google-storage and are currently using it in production.
It does however still need unit tests - please feel free to contribute if you have the time.

**Comment by behramcelen** [comment]
:+1:

**Comment by ivanjaros** [comment]
I need this :D

**Comment by paulcanning** [comment]
@ChrisTerBeke if I want to use the AWS adapter for GCS, what should the `base_url` be?

I am currently using the Superbalist GCS adapter, but I don't think it streams the uploads properly.

**Comment by ChrisTerBeke** [comment]
@paulcanning The base URL for GCS is https://storage.googleapis.com.

**Comment by paulcanning** [comment]
Cheers! I'm keen to try the AWS v2 adapter to see how it copes with huge uploads.

**Comment by sandywilkins** [comment]
Where do I find the key and secret? I don't see it in the console.
