### ISSUE TITLE
Finfo_buffer triggering exception on HHVM

### ISSUE THREAD

**Issue by azcoppen** [thephpleague/flysystem#449]
Env: Ubuntu 14.04 with HHVM 3.6.0

HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

Laravel 4.2 with Intervention/Image (require "intervention/image": "2.*") and AWSS3 driver.
Code:

// make $client, etc
$filesystem = new Filesystem(new Adapter($client, \Config::get('s3.bucket')));
$original_path = '_files/example.jpg'; // S3 URL
$original_image = \Image::make($file->getRealPath())->encode('jpg'); // from file upload

            try {
                $filesystem->write($original_path, $original_image, ['visibility' => 'public']);
            } catch (\Exception $e) {
                \Log::warning('Exception writing  image ('.$original_path.'): '.$e->getMessage());
            }

Error returned is:

dev.ERROR: exception 'ErrorException' with message 'Argument 1 to finfo::buffer() must be of type ?string, Intervention\Image\Image given' in /var/www/webapp/server/vendor/league/flysystem/src/Util/MimeType.php:23

Works fine on OSX. Image output string is fine (viewed in log file).

Following solutions have not worked:
- (string) $original_image or __toString()
- encode('jpg') output

Mime-type errors with Intervention also reported by colleague on Ubuntu 12 since last Friday. Unsure as to whether it's an Intervention problem, or Flysystem. 

Is there any way to set a config flag to deliberately bypass finfo? Can't see anything in the docs.

**Comment by frankdejonge** [comment]
@azcoppen Flysystem only allows string values or stream resources. I'd raise an issue for this as the imagine repository. String values work, so there must be something else going on. Perhaps you can look at the glide project, this uses this and the imagine package. Since this is not an issue with flysystem, I'm closing this.
