### ISSUE TITLE
Ability to use FakeS3 

### ISSUE THREAD

**Issue by aejnsn** [thephpleague/flysystem#456]
I am attempting to develop using FakeS3 for testing, rather than using actual S3, which costs money. I may have overlooked it, but I don't see a port configuration setting for S3 filesystems. I cannot find a way to use flysystem with FakeS3, I may be overlooking something, but perhaps this could be added to the roadmap.

**Comment by frankdejonge** [comment]
@aejnsn the port configuration should be done on the client, flysystem only consumes that client. I suggest you look into how this is done using the aws sdk. In other words, this is not an issue that can be solved within flysystem.

**Comment by aejnsn** [comment]
Very good. FakeS3 ended up not working for what I was hoping to accomplish, and flysystem doesn't work dynamically with buckets anyway. I should be mocking this in testing anyway. Thanks!
