### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::getWithMetadata

### ISSUE THREAD

**Issue by dprevite** [thephpleague/flysystem#461]
Trying to call `getWithMetadata()` like described here http://flysystem.thephpleague.com/api/ throws an undefined method error.

```php
$file = '/path/to/file.txt';
$filesystem = new Filesystem(new Local(dirname($file)));
$data = $filesystem->getWithMetadata(basename($file), ['mimetype']);
var_dump($data);
```

I'm on Flysystem commit e0b31a9.

**Comment by zaak** [comment]
@dprevite this feature was moved to a [plugin](https://github.com/thephpleague/flysystem/blob/master/src/Plugin/GetWithMetadata.php). You need to register it first, like

**Comment by frankdejonge** [comment]
@dprevite The comment by @zaak is correct. I've added a note in the docs about this.

**Comment by ctf0** [comment]
@zaak is it possible to use `getWithMetadata()` with `listContents()` ?

**Comment by zaak** [comment]
@ctf0: It depends on adapter type and metadata you need, but in general I think there's no way to directly use `getWithMetadata()` with `listContents()`. You can always extend adapter and overwrite `listContents()` so it returns listing with metadata you need.

**Comment by ctf0** [comment]
@zaak yeah got it, the usage is exactly the same as `listContents` but you get to include whatever else you want to have.

many thanx.
