### ISSUE TITLE
Timeout problems

### ISSUE THREAD

**Issue by smisse** [thephpleague/flysystem#463]
Hi Frank, 
I'm trying to create a simple copy from dropbox to ftp program, but I'm receiving Curl Timeout errors. The reason is probably a subfolder which contains thousands of small images. 
I think there are 2 options: 
I increase the Curl timeout. Which I don't want to because that would mean I would have to mess around in the flysystem files.
Or, and I prefer this about, I discard the subfolder. Is there an easy way to do that ?
Hereunder is my error message.
Marc 
( ! ) Fatal error: Uncaught exception 'Dropbox\Exception_NetworkIO' with message 'Error executing HTTP request: Operation timed out after 0 milliseconds with 0 out of 0 bytes received' in C:\wamp\www\flysystem\vendor\dropbox\dropbox-sdk\lib\Dropbox\Curl.php on line 76
( ! ) Dropbox\Exception_NetworkIO: Error executing HTTP request: Operation timed out after 0 milliseconds with 0 out of 0 bytes received in C:\wamp\www\flysystem\vendor\dropbox\dropbox-sdk\lib\Dropbox\Curl.php on line 76
Call Stack
#	Time	Memory	Function	Location
1	0.0000	248472	{main}( )	..\copyfromdrop.php:0
2	0.0130	1283248	copyfiles( )	..\copyfromdrop.php:17
3	0.0140	1330856	League\Flysystem\MountManager->listContents( )	..\copyfromdrop.php:30
4	0.0140	1331448	League\Flysystem\Filesystem->listContents( )	..\MountManager.php:158
5	0.0140	1331792	League\Flysystem\Dropbox\DropboxAdapter->listContents( )	..\Filesystem.php:351
6	4.6553	1702136	League\Flysystem\Dropbox\DropboxAdapter->listContents( )	..\DropboxAdapter.php:249
7	4.6553	1702432	Dropbox\Client->getMetadataWithChildren( )	..\DropboxAdapter.php:240
8	4.6553	1702984	Dropbox\Client->_getMetadata( )	..\Client.php:773
9	4.6553	1703096	Dropbox\Client->doGet( )	..\Client.php:786
10	4.6553	1703096	Dropbox\RequestUtil::doGet( )	..\Client.php:1379
11	4.6553	1705168	Dropbox\Curl->exec( )	..\RequestUtil.php:224

**Comment by frankdejonge** [comment]
@smisse unfortunately this is not solvable from within Flysystem. The dropbox sdk doesn't seem to support a timeout option. There's no way to Flysystem to manipulate this. I recommend you create an issue on the dropbox php sdk repo to add this. When released this can be added to the dropbox adapter.
