### ISSUE TITLE
[Insight] Text files should end with a newline character - in src/Adapter/SynologyFtp.php, line 8

### ISSUE THREAD

**Issue by Tjoosten** [thephpleague/flysystem#466]
**[in src/Adapter/SynologyFtp.php, line 8](https://github.com/thephpleague/flysystem/blob/768703274efa648ad63ac7646ad85c4e6a7f77e9/src/Adapter/SynologyFtp.php#L8)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
namespace League\Flysystem\Adapter;

class SynologyFtp extends Ftpd
{
    // This class merely exists because of BC.
}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c47e83c6-db97-4de3-be43-0ae3103062ed/analyses/1)_

**Comment by frankdejonge** [comment]
A fix has been pushed, thanks :+1:

**Comment by Tjoosten** [comment]
Graag gedaan, Frank! 
No problem, Frank!
