### ISSUE TITLE
Determine if a path is a file or a directory

### ISSUE THREAD

**Issue by jjanvier** [thephpleague/flysystem#469]
Hello there,

Your library is totally awesome, thanks for this :)

I just miss a little feature which is to know if a path on the file system is a file or a directory. I didn't find anything about that and I really don't want to test if `'dir' === $file['type']`
I could do a PR if you want.

**Comment by frankdejonge** [comment]
@jjanvier in the current state, that's what you'd do. Could you explain more about your particular case? Perhaps there's an alternative method I can help out with.
