### ISSUE TITLE
Allow to create writable streams

### ISSUE THREAD

**Issue by adeons** [thephpleague/flysystem#471]
I know its possible to stream data to a file using `writeStream`, but it requires a readable stream.

Many PHP APIs that allow to generate content, dont provide a generator/input stream, but instead they take an output stream (see [`Imagick::writeImageFile`](http://php.net/manual/en/imagick.writeimagefile.php) for an example).

I do not know if its possible to implement with every adapter, but i would like the filesystem interface had a method to create a writable stream (may be non-seekable for simplicity).

Something like:

``` php
$output = $filesystem->writableStream($fileName);
// generate and stream something to the file
fclose($output);
```

**Comment by nel15** [comment]
It would be very usefull. For example in ReactPHP I can log all incoming request data like this:
```javascript
$stream = new React\Stream\Stream(fopen('log.txt', 'w+'));
$request->pipe($stream);
```
But no way to use react streams and fly streams togehter

**Comment by twistor** [comment]
This is not easy to implement with the current API. In fact, it's not easy to implement in PHP at all. All you have to do is:
```php
$handle = tmpfile();
// Or
$handle = fopen('php://temp', 'w+');

$image->writeImageFile($handle);

$filesystem->writeStream($path, $handle);
fclose($handle);
```

For the React example, you can try https://github.com/twistor/flysystem-stream-wrapper. I'm not familiar with React, but if it calls `fflush()` on the log file then it will work. If it doesn't call `fflush()` it will still work, but the file won't get updated until the handle is closed. The stream wrapper will work for the Imagick example as well, but it's overkill.

**Comment by zartdinov** [comment]
StreamWrapper of [Gaufrette](https://github.com/KnpLabs/Gaufrette#streaming-files) (another filesystem abstraction layer) also doesn't work cleanly with React. I will try inspect it later.
