### ISSUE TITLE
Indicate all exceptions thrown by public methods

### ISSUE THREAD

**Issue by eilgin** [thephpleague/flysystem#475]
The public API from FilesystemInterface doesn't show all possible exceptions that can be thrown. For example, if the file does not exist when we try to delete it, there's a FileNotFoundException that get thrown instead of returning a `false` value.
Is there a plan to add all possible exceptions to the public API so we don't have to browse all the source ?

**Comment by frankdejonge** [comment]
Thanks to a PR it does now! :dancer:
