### ISSUE TITLE
Cannot use absolute path in windows

### ISSUE THREAD

**Issue by JosephSilber** [thephpleague/flysystem#476]
When using Windows, an absolute path does not start with a `/`, so [this is wrong](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/AbstractAdapter.php#L56). You end up with the full path being duplicated, and the operation failing.

You can easily test this on windows with this:

    $filesystem->put('c:\test\filename.txt', 'contents');

This will try to create the following directory:

    c:\test\c:\test

and you'll get the following error:

```
ErrorException (E_WARNING)
mkdir(): Invalid argument on line 53 in league\flysystem\src\Adapter\Local.php
```

**Comment by GrahamCampbell** [comment]
?
