### ISSUE TITLE
Create hash of file

### ISSUE THREAD

**Issue by Tombi10** [thephpleague/flysystem#482]
What's about creating hashes of files?
Should I try it with own functions and libraries or would this be a good new feature for upcoming features of the flysystem?

**Comment by frankdejonge** [comment]
@Tombi10 this is not a planned feature for flysystem. Mostly because there's no portable behaviour and hashes can't (as far as I know) be created from streams, which would only make it applicable for local usage. You could however write a plugin which supplies this behaviour.

**Comment by maetthu** [comment]
hashes can actually be created from streams using hash_init/hash_update_stream functions. Just created a plugin which makes use of that: https://github.com/emgag/flysystem-hash
