### ISSUE TITLE
Add new line character

### ISSUE THREAD

**Issue by Tjoosten** [thephpleague/flysystem#498]
**[in src/Adapter/SynologyFtp.php, line 8](https://github.com/thephpleague/flysystem/blob/768703274efa648ad63ac7646ad85c4e6a7f77e9/src/Adapter/SynologyFtp.php#L8)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
namespace League\Flysystem\Adapter;

class SynologyFtp extends Ftpd
{
    // This class merely exists because of BC.
}
```

---------------------

**Comment by frankdejonge** [comment]
@Tjoosten this is already fixed on dev-master.

**Comment by Tjoosten** [comment]
O ok srry i didn't know that

**Comment by frankdejonge** [comment]
@Tjoosten no worries :) A new patch release will be tagged in about 2 weeks, I'm on holidays now :)

**Comment by Tjoosten** [comment]
Have a great time then
