### ISSUE TITLE
OpenStack object storage support?

### ISSUE THREAD

**Issue by Grummfy** [thephpleague/flysystem#504]
Hi,
is there any plan to support openstack object storage?
http://developer.openstack.org/api-ref-objectstorage-v1.html#storage_object_services

**Comment by frankdejonge** [comment]
@Grummfy I can certainly see a case for this. There seems to be an SDK, though no docs, which is problematic. Also the tiny bit of docs has errors, like specifying two different minimum php versions... which not bad, but it's one of those "signs".

**Comment by Grummfy** [comment]
Yep, but we can explore directly the api of fix the sdk. Because over the number of people who start using openstack and people who create compatible api ....

**Comment by Grummfy** [comment]
seems there is somehing over there : https://gist.github.com/BaptisteDixneuf/85dc4419a0398446d2d3

**Comment by phpdiddy** [comment]
I'm using Flysystem with OpenStack right now. Rackspace is built on OpenStack so it was just a matter of configuring the client to point to OpenStack instead of Rackspace.

**Comment by frankdejonge** [comment]
@phpdiddy good to know! Closing this issue then.
