### ISSUE TITLE
Google Storage API with AWS SDK v3 Issue

### ISSUE THREAD

**Issue by golevel** [thephpleague/flysystem#505]
This has been posted a few times and some working code has been floating around, but no longer seems to work.

https://github.com/thephpleague/flysystem/issues/448

It seems that the version of AWS shipped with Flysystem no longer supports the AWS v2 Authentication Headers and breaks if you try to use Google Storage Interoperable credentials.

I posted some details here but it looks like a pretty serious snag for anyone wanting to use Google Storage since Google's claim to support AWS's SDK is no longer proving true:

http://stackoverflow.com/questions/30790265/why-doesnt-google-storage-api-work-with-amazon-sdk-v3

**Comment by frankdejonge** [comment]
@golevel flysystem doesn't ship with one by default but you can use v2 and v3 with flysystem, if you want to use v2 just `composer require league/flysystem-aws-s3-v2`.
