### ISSUE TITLE
Vague error reporting

### ISSUE THREAD

**Issue by golevel** [thephpleague/flysystem#508]
I just had an issue where my S3 flysystem stopped working all of a sudden. All I got in my Laravel log was '403 forbidden'. I had to go hardcode a test to write a sample file to S3 to get a proper error. Is there a way to get the verbose error from Amazon without having to circumvent flysystem?

**Comment by frankdejonge** [comment]
@golevel which version of the aws sdk are you using?

**Comment by golevel** [comment]
3.0.3

**Comment by frankdejonge** [comment]
@golevel this is not possible from within flysystem unfortunately. You can pass a debug flag to the aws sdk iirc, but nothing more is available from within flysystem.
