### ISSUE TITLE
Needs a way to detect a plugin

### ISSUE THREAD

**Issue by mrclay** [thephpleague/flysystem#510]
No one passed a FileSystem can judge whether it supports `listFiles()`, so they all have to add the plugin. I suggest adding a public `hasPluginMethod($method)` to PluggableTrait.

If this sounds good I can send a PR.

**Comment by frankdejonge** [comment]
@mrclay what's the use-case for programatically checking for a plugin? My guess would be that this should be detected during development.

**Comment by mrclay** [comment]
I have a custom Directory object that wraps a filesystem and it can return nested Directories, each passing along the FS. So it's a problem that the Directory can't decide whether its dependency is sufficient until run-time. I could call the plugin in a try/catch in the constructor but that seems messy.

**Comment by mrclay** [comment]
I guess I should type hint on FilesystemInterface, since that's more honest about not promising a `listFiles` method.

**Comment by frankdejonge** [comment]
@mrclay why not always just use the plugin, it doesn't matter a whole lot in terms of mem or execution time?

**Comment by mrclay** [comment]
Mainly it's not clean: If I have to add the plugin every time I'm passed a FS, then I can't pass in a FS with a custom `listFiles` plugin; it will be overwritten.

I'm closing this in favor of auto-loading the built-in plugins (#511).
