### ISSUE TITLE
Auto-add the built-in plugins

### ISSUE THREAD

**Issue by mrclay** [thephpleague/flysystem#511]
It's confusing to users that Filesystem is documented to have `getWithMetadata()`, `listFiles()`, etc. yet these have to first be manually added as plugins.

I think for the few plugin methods in the phpDocs, `findPlugin()` should auto-add the underlying plugins.

I'll send a PR if you agree.

**Comment by frankdejonge** [comment]
It's very little effort to add these plugins. They're intentionally otherwise the entire API could have been optional. They're a way to keep BC, but not strictly part of the API.
