### ISSUE TITLE
Cant read files with spaces from ftp (with ssl)

### ISSUE THREAD

**Issue by mikaelmattsson** [thephpleague/flysystem#513]
I get a FileNotFoundException
```php
    $files = $filesystem->listContents('/path');
    $file = end($files); // path/last file.txt
    $content = $filesystem->read($file['path']); // FileNotFoundException
```

Same problem when trying to access by a string:
```php
    $content = $filesystem->read('path/last file.txt'); // FileNotFoundException
```
Both examples work if I rename the file on the server to `last_file.txt` and change the string in the second example to `path/last file.txt`

I'm using version 1.0.4 and Laravel version 5.1

**Comment by frankdejonge** [comment]
@mikaelmattsson hi, would you happen to know which kind/type of Ftp server you're talking to?

**Comment by mikaelmattsson** [comment]
Pure-FTPd with FTPS with explict. "TLS" is set to 3.

**Comment by frankdejonge** [comment]
@mikaelmattsson this should be fixed by not using the Ftp but the Ftpd adapter.

**Comment by oxygens** [comment]
I'm using the `\League\Flysystem\Adapter\Ftpd` adapter. The `\League\Flysystem\Filesystem::has()` function returns `false` for files which contain the space character.

**Comment by sifex** [comment]
@oxygens Same here, still unable to find a solution.
