### ISSUE TITLE
Interface should include getURL() or getRealPath()

### ISSUE THREAD

**Issue by RyanThompson** [thephpleague/flysystem#514]
I think I've looked everywhere. While, for example, you can get the full URL using the AwsAdapter you can't for the others.

Overall this seems like something that should be built in? This way you can include the URL for an S3 file in a view for use with an image tag or something.

Am I completely missing it or is there no standard interface for getting the real path / URL for a file?

**Comment by RyanThompson** [comment]
After looking into this - I can see it's not a cross-adapter possibility.

**Comment by frankdejonge** [comment]
@RyanThompson sorry for not responding earlier, this is indeed a tricky one. I've thought about this many times before and concluded a while back that public url's are out of scope, they're easy to create outside of flysystem while creating a lot of complexity internally.

**Comment by RyanThompson** [comment]
Ya there is no clear conecept that could be implemented that wouldn't be heavy. 

The plugin layer would be a good candidate for adding that though ^_^

Killer package! I'm using it in the soon to release PyroCMS and love it!

**Comment by frankdejonge** [comment]
Oh wow, that's awesome! Looking forward to the install spike!

**Comment by cogentParadigm** [comment]
Sorry if I am oversimplifying but does this have to be complicated? It makes sense that not all filesystems are . Something like this would be nice:

```php
interface PublicFilesystemInterface extends FilesystemInterface {
    public function getPublicPath($path);
}
```

**Comment by twistor** [comment]
It's more complicated than that.
I've implemented exactly this for Drupal.

For the Local, Ftp, Sftp adapters, this is a non-starter. The external URL can be arbitrary.

For S3, Dropbox, etc. it's still complicated. 

Using S3 as an example, the adapter would need to have knowledge of:

- The protocol to serve. HTTP/HTTPS
- The bucket. (The adapter already has this)
- Whether a CNAME is used.
- Whether the CNAME contains the bucket. (bucketname.s3.amazonaws.com, my.bucketname.com) or the bucket should be in the path (s3.amazonaws.com/bucketname)

This is a lot of complexity for something that will apply to less than half of adapters.
