### ISSUE TITLE
[Improvement] The Handler class really should have a getter for the filesystem.

### ISSUE THREAD

**Issue by RyanThompson** [thephpleague/flysystem#519]
I understand it's not pertinent to the resource information but as an implemented library, for developers who are doing anything out of the box, no getter is pretty harsh.

Laravel, by example uses it's own File class based on Symfony and it has getFilesystem() and if anything, I think that is a good indicator in support of Flysystem following suite.

**Comment by RyanThompson** [comment]
https://github.com/thephpleague/flysystem/pull/520

@frankdejonge what are your thoughts on this?

**Comment by frankdejonge** [comment]
@RyanThompson could you explain the feature with a use-case perhaps? I don't see lots of harm including this but I struggle to find anything that really fits this.

**Comment by RyanThompson** [comment]
Here's a simple generic example:

// File uploaded here

$file = $mountManager->get('foo://path.jpg'): // Get uploaded file

$events->fire(new FileWasUploaded($file)):

From any listener there is now no way to access that files filesystem at all. So for example if you put a URL prefix on your custome filesystem, you can't access that.

In my case I set a disk interface from he CMS on the filesystem class I extend yours with - and I need access to it in order to determine, for example, permissions.

But I can't get the disk off the filesystem cause I can't get the filesystem off the file. So I have to do a fair amount of fussing around before the upload to have the proper arguments for the event. 

And if my needs grow, I now need to rewrite a bit to accommodate new arguments. It'd be nicer to let the filesystem carry those objects.

**Comment by RyanThompson** [comment]
Sorry for the typos - sent from my phone!
