### ISSUE TITLE
Local filesystems with a large number of directories

### ISSUE THREAD

**Issue by regularjack** [thephpleague/flysystem#523]
I had to workaround EXT3's limit of files or directories in a directory ([32k](https://en.wikipedia.org/wiki/Ext3#Functionality)). I accomplished this by implementing a custom `Adapter` that *spreads* files and directories directly on the root of the filesystem into 4 sublevels. So, a directory (or file) with name `foo` will be interpreted as `0/b/e/e/foo`, where `0bee` are the first four characters of `sha1('foo')`. I put the code up at https://gist.github.com/regularjack/1fe7ff7b9336b197c0d8. 

This is just a little background and is not the motive of this issue. The problem is that this use case, having a (local) adapter that applies a prefix which is a function of the `path`, is not supported by [Filesystem::listContents](https://github.com/thephpleague/flysystem/blob/1.0.4/src/Filesystem.php#L291):

```php
# src/League/Flysystem/Filesystem.php
public function listContents($directory = '', $recursive = false)
{
    ...
    if ($recursive === false && Util::dirname($entry['path']) !== $directory) {
        return false;
    }
    ...
}
```

If `$recursive` is `false`, the `if` condition always evaluates as false because of the prefix that is applied by the adapter. Is there a reason for the Filesystem to explicitely check for recursive paths? I would say that it's the responsibility of the Adapter to not include recursive paths if they weren't requested.

Is there any chance that check can be removed? If not, any suggestions on how to implement this use case?

Thanks!

**Comment by frankdejonge** [comment]
@rossriley this is done so responses can be cached in adapter decorators like the cached-adapter-decorator. It can utilise this response for future calls. While it seems like it's in the wrong place, is saves a lots of calls in some scenario's at zero cost.
