### ISSUE TITLE
'listContents' method doesn't work on Windows OS

### ISSUE THREAD

**Issue by 7brend7** [thephpleague/flysystem#528]
Hi,

I have this problem in laravel 5 when trying fetch directories list with 'allDirectories' method.

Here is an example:
```php
$adapter = new Local(__DIR__);
$filesystem = new Filesystem($adapter);
var_dump($filesystem->listContents('vendor', true));
```

I've got 
```
array (size=0)
  empty
```

And I think the reason is in this commit https://github.com/thephpleague/flysystem/commit/258dfa65f0b0a471618ae7af1e6cb775df34ad1c.
I use Windows 7 and all paths are with '\'. Perhaps DIRECTORY_SEPARATOR will be better in this case.

**Comment by frankdejonge** [comment]
@7brend7 just fixed, 1.0.9 is on your way!
