### ISSUE TITLE
Using ZipArchive with multiple filesystems

### ISSUE THREAD

**Issue by taion809** [thephpleague/flysystem#531]
Hello,
So this may be a simple issue, but I am having trouble figuring out how best I can accomplish this.

I would like to create a ZipArchive, add files to it, and then move it to another filesystem.

For example:

```php
// Example fs's, could be anything but typically I'm building a zip locally and moving to a remote fs
// Or generating a zip for download
$localStorageAdapter = new Local($root);
$localStorageFs = new Filesystem($localStorageAdapter);
$remoteStorageAdapter = new Local($root);
$remoteStorageFs = new Filesystem($remoteStorageAdapter);

$mount = new MountManager(['local' => $localStorageFs, 'remote' => $remoteStorageFs]);

// This fs is the zip that will be created and moved into the $remoteStorageFs
$zipfs = new Filesystem(new ZipArchiveAdapter($zipPath));
$zipfs->put('document', "stuff");
$zipfs->put('document_two', "moar stuff");
$zipfs->getAdapter()->getArchive()->close();
```

At this point I am unsure about how I could move that zip archive into the remote fs without using fopen and putStream, if I were to create it within the `$localStorageFs` and use the mount manager to `move` it instead the `$localStorageFs` does not show that zip as having been created (so no entry in `listContents("local://");`

**Comment by frankdejonge** [comment]
@taion809 when the ZipArchive is closed (I would advice to unset the filesystem), you can open een stream from the location where it's stored and use writeStream on the filesystem you want to store it in.

**Comment by taion809** [comment]
Alrighty, thanks :)
