### ISSUE TITLE
documentation of the prefix option

### ISSUE THREAD

**Issue by mikeSimonson** [thephpleague/flysystem#533]
That option seems to be common with pretty much every adapter but is not always mentioned and never described.

Should we add a description for it in all the adapters page or a generic page somewhere else ?

**Comment by twistor** [comment]
It is common for lots of adapters, but doesn't apply to all of them, nor should it. Unless documentation is missing, per-adapter docs are correct.

**Comment by frankdejonge** [comment]
It's a per adapter thing, for example, the ftp adapter doesn't have a prefix but a root. It's a configuration option handled by multiple adapters, thus implemented in a standardised manner.
