### ISSUE TITLE
LocalAdapter: read() empty file

### ISSUE THREAD

**Issue by advicente** [thephpleague/flysystem#540]
I'm having problems reading an empty file. The following message is returned: "[ERROR] File not found at path: (...)".

Both directories and file $fileName exists, which an empty file. But I can't get file contents using method read().

This is my code:
```
$srcFileSystem = new Filesystem(new LocalAdapter(''));
$dstFileSystem = new Filesystem(new FtpAdapter($ftpConfig));

$dstFileSystem->write($newFileName, $srcFileSystem->read($fileName));
```

Any help will be appreciated.

**Comment by frankdejonge** [comment]
@advicente my guess is this is an FTP error rather than a LocalAdapter error?

**Comment by advicente** [comment]
Ok, I have figured out the problem was in my code, the local path was wrong.
So I guess I can close this... Thanks.
