### ISSUE TITLE
Public directory permissions for local driver

### ISSUE THREAD

**Issue by bcat-eu** [thephpleague/flysystem#541]
Following #525 I'd propose to set dir.public permission to 0775 instead of 0755, since 0755 is hardly "public".

https://github.com/mzur/flysystem/blob/master/src/Adapter/Local.php#L24

At the moment any application (Linux server) that works in cli as some user as well as via http / server software would have at least two users that would have their own files, so there is no (clean) way of implementing say tmp dir cleanup via command line if the files were created using http requests.

**Comment by twistor** [comment]
I have a feeling we're going to keep seeing people ask for various tweaks to how the permissions are set up.

#542

**Comment by bcat-eu** [comment]
@twistor thank you!
