### ISSUE TITLE
AWSS3 0 byte downloads

### ISSUE THREAD

**Issue by sergeh** [thephpleague/flysystem#543]
I'm not exactly sure what I'm doing wrong but for some reason when I try to force a download it returns a 0 byte file even though the file is in the bucket. Uploading files to the bucket works fine.

Here's what I have for forcing a download via ajax when a user clicks a button
```php
  $exists = Flysystem::has($file_path);

  if ($exists) {
    $stream = Flysystem::readStream($file_path);
    return Response::stream(function() use($stream) {
        fpassthru($stream);
    }, 200, [
        'Content-Type' => Flysystem::getMimetype($file_path),
        "Content-Length: " => Flysystem::getSize($file_path),
        "Content-disposition" => "attachment; filename=\"" . basename($file_path) . "\"",
    ]);
  }
```
`getSize` and `getMimetype` return the correct info but `stream_get_contents($stream)` returns null, any ideas why?

**Comment by frankdejonge** [comment]
@sergeh Hi, which adapter are you using, v2 or v3?

**Comment by GrahamCampbell** [comment]
Looks at this line: `fpassthru($stream);`. You forgot a return.

**Comment by sergeh** [comment]
@frankdejonge I'm using v2 but I think I figured the solution, removing the `:`from `"Content-Length:` seems to have worked, running some more tests and will report back

**Comment by frankdejonge** [comment]
@GrahamCampbell that's not needed, it's a function to output a resource.

**Comment by frankdejonge** [comment]
@sergeh well, that sounds pretty reasonable. It probably caused a malformed header to be returned, causing recipient to error while interpreting the http response.

**Comment by frankdejonge** [comment]
@sergeh if it works now and nothing is broken, could you close the issue? Otherwise, feel free to ask more questions.

**Comment by sergeh** [comment]
@frankdejonge just did more tests on production and it seems to work fine, thanks!
