### ISSUE TITLE
Status of stream?

### ISSUE THREAD

**Issue by arman-h** [thephpleague/flysystem#546]
Hello all, not sure if this is the place to ask a question, the Google group mailing list didn't seem like a good option either, so here it is:

Is there a way to know whether a file stream was uploaded completely? Is there a status attribute or method to check when streaming ends (and whether it has completed successfully)?

**Comment by frankdejonge** [comment]
@arman-h hi, the writeStream method returns a success boolean to indicate a successful upload. You can use the `is_resource` function on the handle you passed to the function to check if the resource is still open. Some SDK's will close it after the upload.

**Comment by arman-h** [comment]
@frankdejonge thanks for the quick reply.

I couldn't find this info in the docs, perhaps it's worth adding?
