### ISSUE TITLE
There's no way to deal with "append-mode" in the AdapterInterface

### ISSUE THREAD

**Issue by castarco** [thephpleague/flysystem#549]
Hi. I'm working on a new adapter similar to the "Replicate Adapter", but with other purposes. The structure is the following: there are two adapters, the main one, and the fallback. All the write operations are done using the main adapter, and the read operations too, but if a file can't be found through the main adapter, then the fallback adapter is used. Obviously it isn't so simple, there are many corner cases here and there, and one of these cases are is the "append-mode" when writing.

The Local adapter allows using the append writing mode, but through the writeFlags passed to the constructor, this isn't anything that can be "understood" by any other adapter. It would be nice to add a getter to the AdapterInterface, something like `getWriteMode` .

Currently, when a file is accessible through the fallback adapter but not through the main adapter, I'm being obliged to copy the file from the fallback adapter to the main adapter and then do the write operation to ensure that I'm not breaking the Local adapter semantics. If I have something like the proposed method, then I can avoid doing the copy operation when the _"write mode"_ isn't _"append"_.

I know that extending the interface can be controversial because it may break compatibility with existent adapters, so may be it's worth to find another clean and elegant solution.

**Comment by twistor** [comment]
I think a direction like #696 makes sense.
