### ISSUE TITLE
$listing = ftp_nlist($connection, '.') returns false in case of empty dir.

### ISSUE THREAD

**Issue by nkornel** [thephpleague/flysystem#551]
I'm trying to upload some files to a currently not existing directory via FTP, but the `ftp_nlist` returns false, so the following `foreach` loop fails. However when calling the `ftp_mkdir` inside `createActualDirectory` directly, it can create the directory.

    Storage::createDir('example') => This fails with false from ftp_nlist.

    Storage::put(
            'example/'.$cd->owner_id.'/'.$cd->filename,
            file_get_contents(\Request::file('docFile')->getRealPath()) => This also with the same error.

I am using the Storage facade inside Laravel.

This is from the FTP Adapter:

    protected function createActualDirectory($directory, $connection)
    {
        // List the current directory
        $listing = ftp_nlist($connection, '.');
        
        foreach ($listing as $key => $item) {
            if (preg_match('~^\./.*~', $item)) {
                $listing[$key] = substr($item, 2);
            }
        }

        if (in_array($directory, $listing)) {
            return true;
        }

        return (boolean) ftp_mkdir($connection, $directory);
    }

**Comment by frankdejonge** [comment]
@nkornel have you got the ftp connection to be configured to be passive by any chance? If not that might fix it as the ftp_nlist function tends to give only false results when it's not set to passive.

**Comment by nkornel** [comment]
Hi Frank, 

Yes, it was in fact configured as passive. Getting other error now. Since I wasn't able to discover why this happens, I gave total permissions to the user on the server to test out the basic FTP functionality. Now I'am getting `Undefined offset: 8` for the `normalizeUnixObject list()` line (399).

The `$item` parameter is an error string: "ftpd: foo/267/document.pdf: No such file or directory.".

**Comment by frankdejonge** [comment]
@nkornel it seems like you should be using the Ftpd adapter instead of the Ftp adapter.

**Comment by nkornel** [comment]
Thank you @frankdejonge , that did the trick. The only concern remains that without debugging how I should have discovered that I would have to use the Ftpd variant of the Adapter?

Thanks again.

**Comment by frankdejonge** [comment]
@nkornel that's a tough one. One for which I do not have the answer. Not only is FTP and anything related to it plain horrible, the number of way it has manifested itself is beyond controle. The Ftpd variety is one of those "slightly off" cases, only determined by the error messages. PHP is not the language where you'd want to take those responses into account and take another route, having to re-determine that at runtime always doesn't feel like the way to go. I'm glad this is fixed for you though.

**Comment by nkornel** [comment]
@frankdejonge thorough answer. However I am not a experienced PHP programmer, already found out from experience, that in case of it, following messages is not the way to go. I found the issue #305 which is similar to mine, as I am working on an integration with that particular NAS type as well. Luckily it works now. Thank you, and keep going, flysystem is a great package!

**Comment by frankdejonge** [comment]
@nkornel will do! and thank you :)
