### ISSUE TITLE
Backblaze B2 Adapter

### ISSUE THREAD

**Issue by aarondfrancis** [thephpleague/flysystem#552]
Backblaze has just entered the cloud storage market, with pretty amazing prices.

I'd love to see a B2 Adapter.

https://www.backblaze.com/b2/cloud-storage.html

**Comment by martinlindhe** [comment]
+1

**Comment by dennisoderwald** [comment]
+1

**Comment by phpcodemonkey** [comment]
+1

**Comment by iansltx** [comment]
Just got my beta invite. Bug me about this until it happens :)

**Comment by Failcookie** [comment]
+1 as well. Definitely a beneficial one for me.

**Comment by svenluijten** [comment]
+1 Been looking around for an adapter for B2 and flysystem supporting it would be awesome.

**Comment by ahlee2326** [comment]
+1

**Comment by iansltx** [comment]
Spent the last few hours designing/building the underlying client for this. When I've got a bit more progress I'll link to it from here.

**Comment by iansltx** [comment]
Got the underlying B2 client to the point where I don't mind it seeing the light of day. Mostly untested, and haven't actually touched the Flysystem side more than building out the constructor, but have a look and PR if you'd like. Can't touch this again 'til next weekend, other than reviewing PRs :)

https://github.com/iansltx/b2-flysystem-adapter

And yes, the actual API client will get moved to its own repo once I'm happy with the interface it has...and know that it's working properly.

**Comment by Mark-H** [comment]
I've started a bounty for this: 
[![bountysource](https://api.bountysource.com/badge/issue?issue_id=26874333)](https://www.bountysource.com/issues/26874333-backblaze-b2-adapter)

**Comment by jpmurray** [comment]
You guys might want to take a look at [cwhite92/b2-sdk-php](https://github.com/cwhite92/b2-sdk-php) and [cwhite92/flysystem-b2](https://github.com/cwhite92/flysystem-b2). It's a WIP, but a good one ! :)

**Comment by guruas3** [comment]
any news?

**Comment by travisulrich** [comment]
@iansltx 
> Bug me about this until it happens :)

Consider yourself bugged :) 

(and thanks for the work you've put in so far)

**Comment by skydiver** [comment]
I was able to implement b2 as a laravel disk
Check https://github.com/skydiver/laravel-flysystem-b2
Let me know if there is any issues ...

**Comment by twistor** [comment]
https://github.com/mhetreramesh/flysystem-backblaze added to README.

**Comment by jgbneatdesign** [comment]
+1
