### ISSUE TITLE
[Encryption Plugin] 

### ISSUE THREAD

**Issue by mms-hamburg** [thephpleague/flysystem#553]
Is there a way to attach this package
`https://github.com/philios33/PHP-AES-File-Encryption` dynamically as a Plugin.

..like a beforeSave  and beforeGet  kinda ....

The Doc about Plugins doesnt help me much. http://flysystem.thephpleague.com/plugins/

Thanks for any hints/advices

**Comment by Baachi** [comment]
You can build your own adapter which decorate an other adapter and encrypt/decrypt it before passing it to the orignal adapter.
If you don't know what i mean, google `decorator pattern` and you will get an idea what i mean :)

**Comment by mms-hamburg** [comment]
Sure this makes sense.
https://github.com/thephpleague/flysystem-adapter-decorator

**Comment by frankdejonge** [comment]
@mms-hamburg that package only seems to work for local files, if I'm not mistaking. Therefor it won't work with flysystem, unless it's a local only plugin, which kind of defeats the purpose of flysystem altogether. What you could look into is using the eventable filesystem which has before and after hooks: https://github.com/thephpleague/flysystem-eventable-filesystem

**Comment by mms-hamburg** [comment]
@frankdejonge  thanks for your info!
so basically using the eventable filesystem & this https://github.com/phpseclib/phpseclib  is the right way to go?
