### ISSUE TITLE
Ftp adapter unusable with ftp server behind firewall with NAT

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/flysystem#556]
I had to upload a file to an FTP server behind a firewall using NAT. This FTP server is not under my control. The FTP adapter wouldn't work, which I traced down to http://www.elitehosts.com/blog/php-ftp-passive-ftp-server-behind-nat-nightmare/ and https://bugs.php.net/bug.php?id=55651

Obviously these are PHP limitations, however that can be mitigated if there'd be a curl based ftp adapter. Curl provides the CURLOPT_FTP_SKIP_PASV_IP option which makes it possible to fix this issue.

**Comment by frankdejonge** [comment]
@RonRademaker A option has been added, which is in master but not yet released, for both 5.6 and 7.0. I've added an `ignorePassiveAddress` option which (when set to true) makes sure the ftp option is set to not use the passive address.
