### ISSUE TITLE
Deleting multiple files?

### ISSUE THREAD

**Issue by mjanda** [thephpleague/flysystem#557]
S3 supports deleting multiple files in one call (http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_deleteObjects), but there is no way to use that in Flysystem. I'm not sure if other services can do something like that or if it's something worth implementing if only S3 supports it. So I'm asking if there is interest before I'll try to put together PRs.

Thinking along the lines that delete() should take array - in that case call deleteMulti() on adapter. AbstractAdapter would have deleteMulti that loops over the array and calls delete() for individual files.

**Comment by frankdejonge** [comment]
@mjanda currently only deleting directories is supported, which also deleted all the underlying files. There's no "just delete these unrelated files" call. Currently only aws supplies this, for which it's easy to create a plugin for. I'll take this into consideration for the next version of flysystem though. For 1.0 it's out of scope.

**Comment by notflip** [comment]
Old thread but I'm wondering, since this will not be implemented, is it possible to use the FlySystem class to get underlying methods that AWS provides? Such as this deleteObjects in the example from @mjanda

**Comment by frankdejonge** [comment]
@notflip you should use the SDK directly for this. Flysystem does not need to be in the middle of this, it only adds complexity in this library which is bad for the maintainability while not fulfilling a Flysystem capability or benefit the cross filesystem api

**Comment by notflip** [comment]
Thanks for clarifying! I managed to get the underlying aws library using `getAdapter()->getClient()` and continue from there

**Comment by frankdejonge** [comment]
@notflip I would advice not to use this method, it is not longer available in V2. You should use your DI container and declare your dependencies directly instead.

**Comment by notflip** [comment]
@frankdejonge Thank you for clarifying!
