### ISSUE TITLE
FTP adapter bug: $filesystem->has() returns false

### ISSUE THREAD

**Issue by flylord** [thephpleague/flysystem#563]
Similar to https://github.com/thephpleague/flysystem/issues/539
Next command return false if I am testing regular file. It is working for directories  

``` php
Context::getContext()->fs->has('ftp://' . $testFile);
```

My system:
vsFTPd 3.0.2
"league/flysystem": "dev-master"
PHP Version 5.6.4-4ubuntu6.3

If I do some small change in getMetadata() in ftp adapter, function has() is working

``` php
    public function getMetadata($path)
    {
        $connection = $this->getConnection();

        if ($path === '') {
            return ['type' => 'dir', 'path' => ''];
        }

        if (@ftp_chdir($connection, $path) === true) {
            $this->setConnectionRoot();

            return ['type' => 'dir', 'path' => $path];
        }

        $rootDir = ftp_pwd($connection);
        ftp_chdir($connection, dirname($path));

        $listing = ftp_rawlist($connection, basename($path));

        ftp_chdir($connection, $rootDir);

        if (empty($listing)) {
            return false;
        }

        return $this->normalizeObject($listing[0], '');
    }
```

**Comment by frankdejonge** [comment]
@flylord could you look if the Ftpd adapter works for you? I see you're using FTPd instead of FTP.

**Comment by flylord** [comment]
@frankdejonge Ftpd adapter is not working

**Comment by flylord** [comment]
I forgot to put my ftp adapter setting:
```php
$ftp = new Filesystem(new FtpAdapter([
    'host' => FTP_HOST,
    'username' => FTP_USER,
    'password' => FTP_PASSWD,

    /** optional config settings */
    'port' => 21,
    'root' => FTP_UPLOAD_PATH,
    'passive' => true,
    'ssl' => false,
    'timeout' => 30,
]));
```

**Comment by flylord** [comment]
By the way, even with pure PHP, using only http://php.net/manual/en/ref.ftp.php , I have to do chdir() before I can check with ftp_rawlist if some regular file exists

**Comment by flylord** [comment]
I did some more testing. Function listDirectoryContents($directory, true) is working only from Ftpd but not from Ftp adapter. When I find out some info more, I will post it here. I don't have any deep knowledge about ftp servers, so I am slow with solving or finding cause of this problem  :(

**Comment by a-harvie** [comment]
I've got the same problem, using `vsftpd: version 3.0.2`.

Switching adapters from Ftp to Ftpd doesn't solve the problem. Outputing the result from `STAT` for a file I know exists (from [Adapters/Ftpd] (https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Ftpd.php#L12)):

```
Array
(
    [0] => 213-Status follows:
    [1] => 213 End of status
)
```

If I use Ftp instead of Ftpd and [apply flylord's change](https://github.com/thephpleague/flysystem/issues/563#issuecomment-147728171), I get the file as expected. 

For what it's worth, I get an error from command line FTP if I don't chdir unless I specify a local file to copy to:

Check that the file is there:
```
ftp> ls
229 Entering Extended Passive Mode (|||23085|).
150 Here comes the directory listing.
drwx------    4 1001     1001         4096 Oct 28 09:55 dir1
drwx------    4 1001     1001         4096 Oct 28 09:55 dir2
drwx------    4 1001     1001         4096 Oct 28 09:55 dir3
drwx------    4 1001     1001         4096 Oct 28 09:55 dir4
drwx------    4 1001     1001         4096 Oct 28 09:55 dir5
226 Directory send OK.
ftp> ls dir3/out
229 Entering Extended Passive Mode (|||55109|).
150 Here comes the directory listing.
-rw-------    1 1001     1001       180049 Oct 29 13:23 inventory.xml
-rw-------    1 1001     1001         1296 Oct 29 13:39 ship-125.xml
-rw-------    1 1001     1001         1296 Oct 29 13:32 ship-126.xml
-rw-------    1 1001     1001         1296 Oct 29 13:34 ship-127.xml
226 Directory send OK.
```
Try to get the file without specifying local filename:
```
ftp> get dir3/out/inventory.xml
local: dir3/out/inventory.xml remote: dir3/out/inventory.xml
ftp: Can't access `dir3/out/inventory.xml': No such file or directory
```
Try again with local filename
```
ftp> get dir3/out/inventory.xml inventory.xml
local: inventory.xml remote: dir3/out/inventory.xml
229 Entering Extended Passive Mode (|||36212|).
150 Opening BINARY mode data connection for dir3/out/inventory.xml (180049 bytes).
100% |*************************************************************************************************************|   175 KiB    4.56 MiB/s    00:00 ETA
226 Transfer complete.
180049 bytes received in 00:00 (3.49 MiB/s)
```

**Comment by renatomefidf** [comment]
I had the same issue, while applying @a-harvie solution it worked for me!
@frankdejonge do you have any idea if this can be a working solution?

**Comment by flylord** [comment]
@renatomefidf you can make your own adapter. In that way, it is working great. Problem is that ftp servers are not acting in same way. I made my own adapter for vsftpd :)

**Comment by oxygens** [comment]
I tried @a-harvie 's fix, and no change. Files which contain spaces still return `false`.
Tried with `Ftp` and `Ftpd`.

**Comment by sifex** [comment]
@oxygens Did you ever manage to get the spaces working?

**Comment by oxygens** [comment]
I gave up on lftp and flysystem (lftp had serious issues with UTF-8 or other encodings) and wrapped around the WinSCP assembly/library (which is basically putty's SCP) using JavaScript on WSH. Works perfectly with all possible FTP servers. The only problem is having to run it in Windows, and it cannot be run on the website's command if it is not on the same machine or the Apache servers is not elevated :(

**Comment by RubtsovAV** [comment]
I fixed the bug and wait for merge of PR https://github.com/thephpleague/flysystem/pull/708
