### ISSUE TITLE
Local adapter setVisibility cannot fail

### ISSUE THREAD

**Issue by Bob4ever** [thephpleague/flysystem#564]
The method \League\Flysystem\Adapter\Local::setVisibility doesn't respond to result of chmod:
https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L331

Shouldn't it more look like?

```php
    public function setVisibility($path, $visibility)
    {
        $location = $this->applyPathPrefix($path);
        $type = is_dir($location) ? 'dir' : 'file';
        if (!@chmod($location, $this->permissionMap[$type][$visibility])) {
            return false;
        }

        return compact('visibility');
    }
```

The @ sign isn't nessary but otherwise there could be some warnings.

I'm not sure whether there is a reason for the missing failure.

**Comment by frankdejonge** [comment]
@Bob4ever it can now! ;)
