### ISSUE TITLE
Atomic Writes with the Local Adapter

### ISSUE THREAD

**Issue by PatrickRose** [thephpleague/flysystem#567]
Hi,

A quick search of the issues and PRs didn't find this: Is there a plan for the core to support atomic writes with the local file system. AFAIK this is probably only important for the Local adapter instead of most of the others.

Should I instead extend the Local Adapter for my purposes and do atomic writes that way?

**Comment by frankdejonge** [comment]
@PatrickRose I'd say extend it for now, there are many considerations when implementing atomic file operations.

**Comment by PatrickRose** [comment]
I'll look into sending a PR at a later date with the skeleton of what I've done so far.

I think for my purposes I'm able to get away with writing to /tmp then `rename()` to the correct. I'm not so sure about the general case (by which I mean Windows).

**Comment by frankdejonge** [comment]
@PatrickRose you could use `sys_get_temp_dir` to determine the path, which should cover this case.

**Comment by PatrickRose** [comment]
The issue is that `rename()` will fail on Windows if the new file exists, whereas Unix will overwrite the file according to a [comment on the man page for rename](http://php.net/manual/en/function.rename.php#60341). Dealing with that sounds hard. 

You also can't do the same thing that I've done with updateStream (namely writing to a stream opened by tmpfile then renaming it), because you can't rename an opened stream on Windows and closing it will delete the file. That sounds less hard since you can use tempnam instead.
