### ISSUE TITLE
Cannot catch exceptions

### ISSUE THREAD

**Issue by craftpip** [thephpleague/flysystem#568]
Hello, 
i generated some obvious errors, for example: 
`$filesystem->has('nonExistentDir');`
It seems `Try catch` isn't working for this. The error bypasses try catch.

Thank you.

**Comment by frankdejonge** [comment]
@craftpip what errors are you getting?

**Comment by craftpip** [comment]
hello
I'm sorry, the error is not at `$filesystem->has('nonExistentDir');`

But I'm not able to catch the errors, when i try to login with incorrect information. or when it reaches timeout.

**Comment by frankdejonge** [comment]
@craftpip what do you mean with login?

**Comment by craftpip** [comment]
When using the FTP,FTPS,SFTP adapters. (or others)
i try to login to servers with incorrect credentials. 

code: 
```php
try {
    // the $ftpadapter and $flysystem is initiated here.
    // later i do try to listContents of the ftp server. (The login information i provided were invalid)
    $a = $filesystem->listContents(); // this gives the error.
} catch ( \Exception $e){
    // But the error is not caught here.
    echo $e->getMessage();
}
```

Also, I'm using FuelPHP framework.

**Comment by craftpip** [comment]
For example: 
`Fuel\Core\PhpErrorException [ Warning ]:
ftp_systype(): Sorry, cleartext sessions are not accepted on this server.`

cannot be handled.

**Comment by frankdejonge** [comment]
@craftpip I'm not sure what we could do from flysystem's side to improve this. It seems like you've got misconfiguration, so you need to fix the credentials rather than catch the error at runtime.

**Comment by craftpip** [comment]
I'm despirate to get Flysystem working with FuelPHP, i need to handle FTP exceptions because I'm building a FTP connection test GUI, which needs to show errors. 
However the exceptions are caught in `set_error_handler` but doesn't really help. 

Anyways thanks for your support Frank. :)

**Comment by frankdejonge** [comment]
@craftpip I don't think Flysystem is the tool to do that. It is meant to be used when you have valid credentials.

**Comment by craftpip** [comment]
@frankdejonge Thanks again man. :)
