### ISSUE TITLE
Exceptions from delegated classes

### ISSUE THREAD

**Issue by PatrickRose** [thephpleague/flysystem#570]
I'm not entirely sure if my thoughts on this are correct - if they aren't I'd love to know why! - but I feel like the Adapters should throw Flysystem exceptions instead of throwing [insert delegated library name here] exceptions.

I've just come across this with the Rackspace adapter where Guzzle threw a 503 exception. Since the point of Flysystem is that I don't know what filesystem is in use I feel like I shouldn't be adding catches for Guzzle exceptions - instead the adapter should catch and throw a chained exception (so the developer can inspect that exception if they need it).

**Comment by PatrickRose** [comment]
Just seen #77 - unsure if related.

I do feel that I shouldn't be wrapping my flysystem calls in `catch(GuzzleException $ex) {...} catch(AmazoneException $ex)` - it's be better to do `catch(FlysystemException $ex)`

**Comment by frankdejonge** [comment]
@PatrickRose Hi, Flysystem only catches exception of expected cases, for instance not finding a file is caught, while invalid keys for a given provider is not. The distinction made here is between dev-time and run-time. Everything that should be fixed at dev-time (configuration etc) isn't caught, this way Flysystem doesn't become a black box where one doesn't anymore know why things aren't working. It's a little "in your face" but it does give the best end result.

**Comment by PatrickRose** [comment]
The issue is that Guzzle throwing a 503 for the Rackspace adapter isn't a dev-time issue. Our issue was the Swift filestore was full which is feasible to happen in production (even if we try and mitigate it).

At run time, we don't *know* we're writing to Swift though. We could just as easily be writing to Amazon (which might respond similarly) or wherever and they'll all have their own exceptions that we would (in theory) need to catch instead of the web request failing. I'm arguing for Flysystem wrapping them in a `FlysystemDelegatedException` (or something better named):

```php

namespace League\Flysystem;

class DelegatedException extends \Exception
{
    public function __construct($message = "", $code = 0, \Exception $previous = null) {
        if (is_null($previous)) {
            throw new \InvalidArgumentException('No previous exception was given');
        }

        parent::__construct($message, $code, $previous);
}
```

Then no matter what I can handle any exception to verbally slap the user or whatever *and still have access to the information from the previous exception*. If it's something that we actually don't want to handle at runtime then we can throw it further up the chain, but usually all I need to know is that something went wrong and I should make the user try again.

**Comment by frankdejonge** [comment]
@PatrickRose you might as well catch the global exception class then. The wrapping and re-throwing seems redundant to me.
