### ISSUE TITLE
MIME type extension detection fallback not invoked when "application/x-empty" detected

### ISSUE THREAD

**Issue by ivarb** [thephpleague/flysystem#571]
Hi,

I'm using a Local FlySystem adapter setup with the Memory cache adapter plugin enabled. 
Calling `FileSystem::getMimeType()` often returns `application/x-empty` for files where the proper mime type should be detectable based on the file's extension.

This is triggered by the Memory plugin, that first calls the `Util::guessMimeType()` method with boolean `false` passed as the value for content (because the Memory adapter does not read the file's content.). See:
https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/Storage/AbstractCache.php#L240-L244

Then, the `League\Flysystem\Util` component first tries to detect the mime type based on the content passed (no `empty()` check is applied to `$content`). See https://github.com/thephpleague/flysystem/blob/master/src/Util.php#L162-L165

The `Leage\FlySystem\Util\MimeType` component uses `Finfo::buffer()`, which always seems to return `application/x-empty` when `false` (or an empty string) is passed to it.
See https://github.com/thephpleague/flysystem/blob/master/src/Util/MimeType.php#L25-L28

It might be a good idea to detect `application/x-empty` in https://github.com/thephpleague/flysystem/blob/master/src/Util.php#L164 and to fallback to extension based detection instead.

CLI example PHP 5.6:
```
php > echo (new Finfo(FILEINFO_MIME_TYPE))->buffer('');
application/x-empty

$ php -v
PHP 5.6.13-1+deb.sury.org~trusty+3 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Thanks in advance for the support!

**Comment by ivarb** [comment]
Note; I'm using FlySystem version `1.0.15`

**Comment by ivarb** [comment]
@frankdejonge thanks!

**Comment by frankdejonge** [comment]
@ivarb welcome :+1:
