### ISSUE TITLE
Touch

### ISSUE THREAD

**Issue by TheCelavi** [thephpleague/flysystem#577]
I can not find in source nor documentation - is it change of file modification time possible? I mean, not for certain adapter - rather to all adapters, via API? 

I am working on some incremental backup app, and it is impossible to do so nicely without something which would allow me to change modification date.

**Comment by TheCelavi** [comment]
Is anyone familiar with this?

**Comment by frankdejonge** [comment]
@TheCelavi iirc adapter like aws don't support this operation. Which makes it difficult to abstract without creating very inefficient polyfill methods.

**Comment by TheCelavi** [comment]
Thanks @frankdejonge - now I will go somewhere quiet and kill myself :(

**Comment by frankdejonge** [comment]
@TheCelavi hehe, why did you need touch in the first place? Perhaps there's another way around it.

**Comment by TheCelavi** [comment]
I am working on backup library (which is based on kbond/php-backup). Major idea was to support snapshot backups as well. So the best course of action would be to implement snapshot backup as incremental backup (like rsync), so I would check for mtime, and if source is newer than target, I would overwrite it. Otherwise, I would skip it.

Now, after coping from source to destination -> destination file have mtime as current timestamp, so that is why I need that gentle touch :)

There are a lot of ways around, I could store mtime of all files in some file (per example)... in order to support flysistem....

**Comment by frankdejonge** [comment]
@TheCelavi wouldn't another solution be just to check wether the backed up file has a older timestamp?

**Comment by TheCelavi** [comment]
OMG, this is sooooooooo embarrassing! You have just pointed out, publicly, how stupid I am! OMG! Now I am really going to go somewhere quiet and kill myself!  :-D

Thanks man, again, I am a moron.

**Comment by frankdejonge** [comment]
@TheCelavi haha, no worries man, glad we've found a way to work around it :)

**Comment by TheCelavi** [comment]
Easy for you to say - you do not have to carry around this burden by yourself... :D

**Comment by jon-mcclung-sertainty** [comment]
@TheCelavi it's not a big deal. No one even reads issues from 3 years ago, so no one will see your public shame :)

**Comment by TheCelavi** [comment]
Yeah, lucky me!

**Comment by adrenth** [comment]
@TheCelavi @jon-mcclung-sertainty Well, I did... 😉
