### ISSUE TITLE
S3 ListContents not showing all items

### ISSUE THREAD

**Issue by nodefortytwo** [thephpleague/flysystem#580]
Hi,

I have a folder in s3 with 1500ish files numbered 1 to 1500. ListContents is only returning 317 items (weird number). Testing with the S3 SDK directly returns the correct number of files.

Using laravel 5.1 with:
"league/flysystem-aws-s3-v3": "^1.0"

This works:

        $s3 = Storage::disk('s3')->getDriver()->getAdapter()->getClient();
        $iterator = $s3->getIterator('ListObjects', [
            'Bucket' =>  env('S3BUCKET'),
            'Prefix' => $chunk_folder
        ]);

        $files = [];
        foreach($iterator as $file){
            $files[] = $file['Key'];
        }

This Doesn't:
`Storage::getContents($chunk_folder);`

**Comment by frankdejonge** [comment]
@nodefortytwo which version of flysystem do you have installed?

**Comment by frankdejonge** [comment]
@nodefortytwo if it was the `aws-s3-v3` package the latest version fixed a large contents listing issue: https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/changelog.md#109---2015-11-19

**Comment by nodefortytwo** [comment]
Sorry mate, thought I checked that, i was on 0.8. 

Will update now. sorry again

**Comment by frankdejonge** [comment]
@nodefortytwo no worries! :+1:
