### ISSUE TITLE
FTP Try/Catch Still Throws Errors

### ISSUE THREAD

**Issue by sparkweb** [thephpleague/flysystem#581]
I'm doing this:

    try {
    	$filesystem = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Ftp($args));
    	$filesystem->put($filename, $localpath_filename);
    	echo "SUCCESS";
    } catch (\Exception $e) {
    	echo $e->getMessage();
    }

And it's catching the exception with `Could not connect to host: [the ip], port:21` but it's also throwing PHP warnings:

`Warning: ftp_systype() expects parameter 1 to be resource, boolean given in /vendor/league/flysystem/src/Adapter/Ftp.php on line 426`

and

`Warning: ftp_close() expects parameter 1 to be resource, boolean given in /vendor/league/flysystem/src/Adapter/Ftp.php on line 158`

Shouldn't it bail out of the process right away if the exception is thrown on connection?

Looking at the source, what if this went into the beginning of the isConnected() function in Ftp.php:

    if (is_bool($this->connection)) return false;

Doing this solved the issue on my local install.

**Comment by GrahamCampbell** [comment]
A Try Catch won't catch warnings, because they're not exceptions.

**Comment by sparkweb** [comment]
Right. Definitely. What I'm saying is that even after the Exception is caught, the FTP adapter is throwing warnings because it's not accurately figuring out the connection. It's calling `ftp_systype($this->connection)` when `$this->connection` is a boolean not a resource. Thus throwing the warning.

**Comment by sparkweb** [comment]
I went ahead and did a PR for this: https://github.com/thephpleague/flysystem/pull/583
