### ISSUE TITLE
Preferred behaviour when adapter doesn't support operation

### ISSUE THREAD

**Issue by cwhite92** [thephpleague/flysystem#585]
I'm writing an adapter for flysystem to allow developers to use Backblaze's B2 service. Unfortunately, their API doesn't allow operations such as copy or rename. My adapter implements `AdapterInterface`, which requires me to implement the `copy()` and `move()` methods. At this point I have two options:

* Remove the `AdapterInterface` implementation and don't implement the `copy()` or `move()` methods. This will lead to inconsistencies, and users may face fatal errors. For example, if some code uses `copy()` with S3 and they switch to B2, all of a sudden that will break with a fatal error.
* Implement the `copy()` and `move()` methods by manually downloading the file from B2 and reuploading. This won't break code that people have written, but is a potentially expensive procedure.

What would flysystem's preference be in this case?

Thanks!

**Comment by frankdejonge** [comment]
@cwhite92 Hi, I'd recommend the second option and have notes on the readme about that operation. Sometimes the more expensive operation is the only way, a user will do the expensive stuff anyway if they need it.

**Comment by cwhite92** [comment]
Good stuff, that's what I hoped you'd say :)
