### ISSUE TITLE
FTP Recursive listing largely unsupported

### ISSUE THREAD

**Issue by trideout** [thephpleague/flysystem#586]
PHP's implementation of recursive directory listing uses the argument -R to fetch directories recursively. This functionality has been removed from IIS and is largely unsupported in general. Is there interest in a new implementation which lists and recursively queries directories given a flag on instantiation of the FTP adapter?

**Comment by frankdejonge** [comment]
@trideout that'd be much appreciated! Perhaps we should call listings recursively in cases where recursion is not supported in any way too. I can review PR's, but I'm on holiday right now so can't allocate time to do it myself.

**Comment by trideout** [comment]
Cool, I'll write it up soon. Unfortunately there doesn't appear to be any way to query the server for support, it's just on a per server basis. My implementation would simply add a new config variable to the FTP Adapter, defaulting to false for backwards compatibility.
