### ISSUE TITLE
getMetadata() shows different item "type" than listContents()

### ISSUE THREAD

**Issue by docmattman** [thephpleague/flysystem#589]
Was running some tests (using SFTP) and came across a situation where an item was reported as "dir" in the listContents() method call, but then reported as "file" when using getMetaData() call.  Here is a sample bit of code I used to show the difference (found different values for the "dev/console" item):

```
    $items = $filemanager->listContents('dev);
    foreach($items as $i)
    {
        if($i['path'] != 'dev/console') continue;
        echo print_r($i, true);
        $meta = filemanager->getMetadata($i['path']);
        echo print_r($meta, true);
    }
```

Here is the results from the above code:

```
    Array
    (
        [path] => dev/console
        [timestamp] => 1447977011
        [type] => dir
        [dirname] => dev
        [basename] => console
        [filename] => console
    )
    Array
    (
        [timestamp] => 1447977011
        [size] => 0
        [type] => file
        [visibility] => public
    )
```

Any ideas why the item "type" is being reported differently?

**Comment by twistor** [comment]
I'm closing this because I'm hoping you've figured it out. If not, please open an issue in the flysystem-sftp issue queue.
