### ISSUE TITLE
Large files?

### ISSUE THREAD

**Issue by jfi** [thephpleague/flysystem#590]
I'm using Flysystem to try and upload a ~580MB file by SFTP, and I'm getting the following error:

Warning: finfo::buffer(): Failed identify data 12:cannot allocate 4861887720 bytes (Cannot allocate memory)application/x-bzip2 in /var/www/portal/vendor/league/flysystem/src/Util/MimeType.php on line 25

My memory limit is currently set to 2GB. Does anyone have any experience in how much memory Flysystem will need to upload a file of this size?

Thanks!

**Comment by frankdejonge** [comment]
Hi, that buffer function is only called when you're uploading from string, I recommend uploading from a stream instead using fopen and writeStream instead.
