### ISSUE TITLE
[INFO] Download large from FTP

### ISSUE THREAD

**Issue by clagiordano** [thephpleague/flysystem#591]
Hi all,

there is a way with the ftp adapter (or other adapter) to download
file directly without passing by read() method?
In specific, it is useful for download large file from ftp to process locally 
but not read directly into variable without huge RAM consumption.

Thank you,
Best regards.

**Comment by ltouro** [comment]
I think uou should use readStream if you want to avoid to have all the file allocated in memory. 

You can then put the stream in a temp file and deal with it locally.

**Comment by clagiordano** [comment]
According to the documentations it seems to be useful for me.
I try this solution,

Thank you,
Best regards.

**Comment by clagiordano** [comment]
Perfect, read/write Streams works fine and don't waste RAM.

Thank you.
