### ISSUE TITLE
Support for encrypting and decrypting files

### ISSUE THREAD

**Issue by wubbajack** [thephpleague/flysystem#596]
It'd be really cool if we could get support for encrypting and decrypting files in Flysystem.

As it already has good support for working with streams it shouldn't be too difficult to implement a stream filter that can encrypt/decrypt on the fly (no pun intended).

**Comment by frankdejonge** [comment]
(Liking the pun.) You can quite easily wrap the filesystem class to do this. Which is the least intrusive for flysystem and also for you application.

**Comment by frankdejonge** [comment]
You can use the adapter decoator package for this: https://github.com/thephpleague/flysystem-adapter-decorator
