### ISSUE TITLE
writeOrUpdate && writeOrUpdateStream

### ISSUE THREAD

**Issue by mjacobus** [thephpleague/flysystem#602]
Hello there.

What about the above methods on the FileSystemInterface?

That makes live much easier, specially when unit testing code that uses Filesystem, since a complete test has to deal with both situations.

If your thumbs are up I would be more than happy to create a PR.

**Comment by frankdejonge** [comment]
@mjacobus Hi :) these methods already exist, they're called `put` and `putStream`.

**Comment by mjacobus** [comment]
Ha! :-)

Thanks man!
