### ISSUE TITLE
move method

### ISSUE THREAD

**Issue by funivan** [thephpleague/flysystem#603]
Hello. Thanks for great plugin.
I write atomic rename and delete operation. To be clear delete multiple files inside one directory or rename several files in one dir. 

Algorithm is simple:
1. Copy all to temp dir
2. Perform operation (delete, rename) inside temp dire
3. If all is ok just move temp dir

The last stage cant be atomic because adapter does not have Move operation. 
I can only `delete` old directory and `rename`  temp directory to new. But this is steel not atomic.
And if delete operation will remove only part of files then it will be hard to restore them.
Is there any way to solve my task. Or can it be possible to add `move` function to the API (AdapterInterface)

**Comment by frankdejonge** [comment]
@funivan Hi, unfortunately this issue can't be fixed due to incompatibilities with the different adapters. For instance, AWS and Rackspace don't allow move operations, which is one of the reasons it's not supported.

**Comment by PatrickRose** [comment]
If you just need an atomic local adapter then there is a PR I opened for this (#574)

**Comment by PatrickRose** [comment]
(Also I believe that Rackspace actions are atomic, and I imagine that S3 ones are as well)

**Comment by funivan** [comment]
@PatrickRose my use case: i need to rename several files inside one folder. If I cant rename one of them, then all files should not be renamed. I try to implement this with custom moveDir method. First step I copy all files with proper names to temp destination then if all is ok I just rename temp folder to current source folder.
