### ISSUE TITLE
Inconsistance of the rename method

### ISSUE THREAD

**Issue by funivan** [thephpleague/flysystem#604]
There is a bug with rename method inside `Local` adapter

API say : `Rename a file.` 
But local adapter can perform rename operations on directories

```
      $fs = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local('/'));
      $fs->createDir('/tmp/dir-test');
      $fs->put('/tmp/dir-test/df.txt', 'df file');
      $fs->put('/tmp/dir-test/other.txt', 'other file');

      $fs->rename('/tmp/dir-test', '/tmp/dir-test2/');
      $num = count($fs->listContents('/tmp/dir-test2')); // 2 (two files)
```

If we use `\League\Flysystem\Memory\MemoryAdapter` then the result will be `0`
It will be better to check if we rename file inside `Local` adapter

**Comment by funivan** [comment]
ping anyone

**Comment by twistor** [comment]
The memory adapter allows renaming directories, but it's true that some adapters don't allow it.

**Comment by twistor** [comment]
We need to document the ability of rename and make it consistent.

**Comment by funivan** [comment]
Any news?
