### ISSUE TITLE
Bug? can't copy file from /tmp/phpBlablabla

### ISSUE THREAD

**Issue by ARACOOOL** [thephpleague/flysystem#609]
https://github.com/creocoder/yii2-flysystem/issues/13

**Comment by zaak** [comment]
It's not a bug, it's a feature. All paths in Flysystem are relative, so files outside defined file system root can't be accessed (see #462).

**Comment by frankdejonge** [comment]
@ARACOOOL this is possible if the root is '/' or '/tmp'. It should go outside of its root.

**Comment by frankdejonge** [comment]
@zaak thanks for jumping in and helping out! Appreciate it :+1:

**Comment by ARACOOOL** [comment]
@frankdejonge Ok, What will be if I change LocalAdapter to SftpAdapter. Should I change local file path from relative to full path? Both servers has different folder structure.

When I use LocalAdapter, I can work inside singe root directory.
```
copy('tmp/somefile.jpg', 'upload/somefile.jpg')
```

But if I will change adapter to sftp
```
copy('/full/path/tmp/somefile.jpg', 'upload/somefile.jpg')
```
because, both servers has different folders structure. I can set root path only for remote server and it different from local

**Comment by frankdejonge** [comment]
@ARACOOOL a filesystem only operates on itself, not the outside world. So a copy like you're suggesting is something else. It would look like: 

```php
$stream = $localFilesystem->readStream($sourceLocation);
$destinationFilesystem->writeStream($destinationLocation, $stream);
is_resource($stream) && fclose($stream);
```
