### ISSUE TITLE
Can't catch exceptions during testing with AWS credentials

### ISSUE THREAD

**Issue by bandtank** [thephpleague/flysystem#611]
One of my tests breaks AWS credentials on purpose and it has been working with regular filesystem access, but flysystem throws FileNotFound (which makes no sense because the file is present in the S3 bucket - the credentials are the problem) and I can't seem to catch it.

```
try {
    $s3->delete($path);
} catch (Exception $e) {
    return $this->respondError($e->getMessage());
}
```
I saw the following comment in a closed issue: "... It [flysystem] is meant to be used when you have valid credentials."

Why doesn't flysystem fail earlier than here in src\Filesystem.php?
```
public function assertPresent($path)
{
    if ( ! $this->has($path)) {
        throw new FileNotFoundException($path);
    }
}
```

Here's the relevant code snippet from my controller, which includes the first snippet as well:
```
$s3 = \Storage::disk('s3');
if (!$s3) {
    return $this->respondInternalError("Couldn't establish a connection to file storage");
}

try {
    $s3->delete($path);
} catch (Exception $e) {
    return $this->respondError($e->getMessage());
}
```

The Laravel app handler is catching the error instead of my controller. That seems like a separate, but related, issue because I suppose it's possible that could be the first exception handler found by PHP. I'm still trying to find out how to have the exception thrown sooner than when delete is called or if that's even the right expectation. Lastly, is there a better way to test connectivity with S3/cloud filesystems? I'm not suggesting this method is the best in any scenario.

**Comment by bandtank** [comment]
Also, I should mention that the put doesn't fail the same way:

```
try {
    $s3->put($path, file_get_contents($file), 'public');
} catch (S3Exception $e) {
    return $this->respondInternalError([
        'message'           => "Trying to store the uploaded image failed",
        'AWS_Error_Code'    => $e->getAwsErrorCode()
    ]);
}
```

Fails with this error when the credentials are incorrect:
```
{
  "error": {
    "message": "Trying to store the uploaded image failed",
    "AWS_Error_Code": "InvalidAccessKeyId"
  },
  "status_code": 500
}
```

That's what I was expecting to see when I ran the delete test.

**Comment by bandtank** [comment]
Sending a post request to AWS through flysystem seems to throw an exception in the expected way regardless of which exception is thrown. So far, every exception has been caught by the try/catch around the `$s3->put` statement. However, the opposite seems to be true of the `$s3->delete` statement. To further test that hypothesis, I set the id and secret back to the correct values and then I removed S3 access for the AWS user used by my API.

As anticipated, the post request failed and threw an exception, which was caught by the try/catch:
```
{
  "error": {
    "message": "Trying to store the uploaded image failed",
    "AWS_Error_Code": "AccessDenied"
  },
  "status_code": 500
}
```

The delete exception was not caught by the try/catch and, instead, the default Laravel handler picked it up.
```
<span class="exception_message">Error executing &quot;DeleteObject&quot; on &quot;https://s3.amazonaws.com/.../users/60.jpg&quot;; AWS HTTP error: Client error: `DELETE https://s3.amazonaws.com/.../users/60.jpg` resulted in a `403 Forbidden` response:
```

Maybe this is the expected behavior, but it's surprising to me and I'd really like to understand what I can do to catch the exception in a controller.

**Comment by bandtank** [comment]
Bump - any thoughts?

**Comment by frankdejonge** [comment]
@bandtank Hi, which adapter are you using? v2 or v3?

**Comment by bandtank** [comment]
@frankdejonge "league/flysystem-aws-s3-v3": "^1.0",

**Comment by frankdejonge** [comment]
@bandtank do you know what kind of exception class is being thrown? Can you catch it with a global \Exception catch and print out the class name using `get_class`?
