### ISSUE TITLE
Call to a member function getTimestamp() on boolean (Incorrect format detection)

### ISSUE THREAD

**Issue by DuckThom** [thephpleague/flysystem#618]
I'm using laravel and the allFiles function seems to be throwing an exception in `src/Adapter/AbstractFtpAdapter.php` on line 429.

I've done some debugging and it looks like the 'correct date/time check' doesn't work correctly.
The $date variable is '03-15-2016' which is a 10 character string while the check is looking for an 8 character string.

```
var_dump($date); // 03-15-2016
var_dump($time); // 05:00PM

$format = strlen($date) === 8 ? 'm-d-yH:iA' : 'Y-m-dH:i';
```

The expected input for the $date variable is mm-dd-yy while the actual input is mm-dd-yyyy (The full year notation).

Changing the format check to `$format = strlen($date) === 10 ? 'm-d-YH:iA' : 'Y-m-dH:i';` fixes the issue for me but I suspect it would create new problems for other users if their input is mm-dd-yy.

**Comment by frankdejonge** [comment]
@DuckThom what kind of ftp server are you talking to?

**Comment by DuckThom** [comment]
It's not my server. Is there a way to get info about the FTP server from a client?
The only message I get back from the server is `Remote system type is Windows_NT.`

**Comment by DuckThom** [comment]
I've changed the check locally to this:
```
if ($dt = DateTime::createFromFormat('m-d-YH:iA', $date . $time)) { // dd-mm-yyyy
    $timestamp = $dt->getTimestamp();
} else if ($dt = DateTime::createFromFormat('m-d-yH:iA', $date . $time)) { // dd-mm-yy
    $timestamp = $dt->getTimestamp();
} else if ($dt = DateTime::createFromFormat('Y-m-dH:i', $date . $time)) { // yyyy-mm-dd
    $timestamp = $dt->getTimestamp();
} else {
    throw new Exception("Invalid datetime format: {$date}{$time}");
}
```

This works for me but I cant test the other statements. I'd write a test for it but I'm at work right now so, unfortunately, I don't have time for that.

**Comment by DuckThom** [comment]
I've made a new pull request as I've replace my previous fix with, what I think, a better solution.
