### ISSUE TITLE
Introduce a common exception for failed commands

### ISSUE THREAD

**Issue by BenMorel** [thephpleague/flysystem#620]
This is somewhat related to #611.

If I try to write a file on S3 using Flysystem, and a connection problem occurs, I get an S3 exception:

> Aws\S3\Exception\S3Exception: Error executing "PutObject" on ...

For Dropbox, I get a (subclass of) `Dropbox\Exception`.

First of all, these adapters do not respect the `AdapterInterface` contract by allowing an exception to be thrown, instead of returning [false on failure](https://github.com/thephpleague/flysystem/blob/master/src/AdapterInterface.php#L24).

Secondly, I would suggest throwing an exception in all cases when something goes wrong on the underlying storage. And to keep code portable (i.e. allowing to change the storage adapter at the flip of a switch), this exception should belong to the Flysystem package.

At the moment, I have to do:

``` php
try {
    $filesystem->write($path, $contents);
} catch (S3Exception $e) {
    // ...
}
```

If I decide to switch to Dropbox, I have to search through my entire codebase for Flysystem calls, and update them to something like:

``` php
try {
    $filesystem->write($path, $contents);
} catch (Dropbox\Exception $e) {
    // ...
}
```

And if I'm writing an app that can accept any adapter, using information from a config file, I have to take all possible errors into account:

``` php
try {
    $filesystem->write($path, $contents);
} catch (S3Exception $e) {
    // ...
} catch (Dropbox\Exception $e) {
    // ...
}
```

And so on, without forgetting any adapter. As you can see, this is not a very good practice.

Introducing a common interface for these errors would allow us to call:

``` php
try {
    $filesystem->write($path, $contents);
} catch (AdapterException $e) {
    // ...
}
```

This way, there is no need to rewrite any code when switching to another adapter.

As I understand the project in its current status, you decided to return `false` in some methods, when something goes wrong. The fact is, the few adapters I had a chance to look at do not respect this contract properly (S3 and Dropbox thrown their own exceptions, Ftp and Local raise PHP errors).

There are two solutions to this problem:
- Fix all the adapters to catch any exception or error (including PHP warnings for adapters relying on native functions) and return `false` where appropriate
- Change the contract to never return `false` on methods such as `write()`, and throw an `AdapterException` on failure instead

I would strongly suggest the second option, because it breaks the application flow when something goes wrong; otherwise an error could go unnoticed if the developer forgets to check the return value  using something like:

``` php
if (! $fs->write($path, $contents)) {
    ...
}
```

Plus, although returning `false` gives an opportunity to catch failures on operations such as `write()`, there is no such opportunity on methods that return boolean values, such as `has()`.

Having all of them throw an exception in case of a failure harmonizes the whole thing.

Happily waiting for your feedback on this one. I could help rewrite the code if you agree with the idea!

**Comment by frankdejonge** [comment]
@BenMorel you can just use the base exception class for this, after you catch the ones you expect you can add:

```php
try {
    // lol
} catch (SpecificException $e) {

} catch (\Exception $e) { 

}
```

This accomplished the same thing without needing to add all of the try catch rethrows in flysystem.

**Comment by BenMorel** [comment]
@frankdejonge Catching any exception is [quite a bad practice](http://stackoverflow.com/questions/2416316/why-is-the-catchexception-almost-always-a-bad-idea), you usually want to be able to catch a specific error, while leaving the others out.

As a best practice, each exception that can be thrown should be properly documented in the method's docblock, and you should be able to catch a specific one, while leaving the others out.

Otherwise, you quickly start encountering issues such as the one in #611. If you use fine-grained exceptions, you can handle each error separately:

```php
try {
    $contents = filesystem->read($path);
} catch (FileNotFoundException $e) {
    // handle this with specific business rules
} catch (AdapterException $e) {
    // probably a temporary issue with network or storage provider,
    // try again later
}
```

And if any another exception is thrown, believe me, you probably don't want to catch it blindly!

**Comment by yellow1912** [comment]
I agree with BenMorel here, it will be much better to have a consistent, reliable way of catching errors.

**Comment by BenMorel** [comment]
And about the rethrows, this is actually a best practice, called [nested exceptions](https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions).

You basically catch the original exception, and throw a higher-level, custom exception that wraps the previous one.

This is why you have a `$previous` parameter in [the Exception constructor](http://uk1.php.net/manual/fr/exception.construct.php).

As a result, your application can only expose its own exceptions, while allowing you to examine the cause of such an exception by checking its tree of previous exceptions. When dumping the exception, you would see something like:

```
GuzzleHttp\Exception\ConnectException: ...
Stack trace: ...

Next Aws\S3\Exception\S3Exception: ...
Stack trace: ...

Next League\Flysystem\AdapterException: ...
Stack trace: ...
```

**Comment by PatrickRose** [comment]
I also raised this in #570.

**Comment by johndodev** [comment]
I was about to send an issue about that but this post is just perfect. I don't even understand why we have to talk about it and why after all this time nothing change, it should be obvious. 

Adapters wich doesn't respect the interface are knowing the interface is bad about error handling, we are talking about API here, we have to try catch every API call to handle remote exceptions. 
An AdapterException is the good way, and the only way. You know it. Trust the force.

**Comment by BenMorel** [comment]
With all due respect @frankdejonge, especially for the otherwise quality work you've done on this library,  you don't seem to get the point of specific, [nested ](https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions) exceptions (no offense, I've been there too):

> you can just use the base exception class for this, after you catch the ones you expect you can add.
> This accomplished the same thing without needing to add all of the try catch rethrows in flysystem.

You actually closed #570 for the same reason:

> @PatrickRose you might as well catch the global exception class then. The wrapping and re-throwing seems redundant to me.

If that helps, here is an excerpt from the [Exception handling](https://en.wikipedia.org/wiki/Exception_handling) article on Wikipedia, which is worth reading:

> ... defining and declaring exception types that are suitable for the level of abstraction of the called method and mapping lower level exceptions to these types, preferably wrapped using [exception chaining](https://en.wikipedia.org/wiki/Exception_chaining) in order to preserve the root cause.

You *do not* want to catch any exception when calling a flysystem method. You want to catch a specific exception, that every adapter will throw by wrapping their own, lower-level exception inside.

To better picture how that would translate into code, your `AdapterException` could be very simple:

```php
class AdapterException extends \Exception
{
    public static function wrap(\Exception $e)
    {
        return new self($e->getMessage(), $e->getCode(), $e);
    }
}
```

The `FileSystemInterface` would look like:

```php
/**
 * Write a new file.
 *
 * @param string $path     The path of the new file.
 * @param string $contents The file contents.
 * @param array  $config   An optional configuration array.
 *
 * @return void
 *
 * @throws FileExistsException If the file already exists.
 * @throws AdapterException    If a low-level, adapter-specific error occurs
 *                             (disk full, permission denied, network error, ...)
 */
public function write($path, $contents, array $config = []);
```

And for example, the S3 adapter implementation would be something like:

```php
public function write($path, $contents, Config $config)
{
    try {
        return $this->upload($path, $contents, $config);
    } catch (S3Exception $e) {
        throw AdapterException::wrap($e);
    }
}
```

This way, all adapters would respect a homogeneous API, and one could switch to another adapter without having to change the exception handling code, and without having to blindly catch `\Exception`, which might incidentally catch some unrelated exception: for example, if the S3 adapter's `upload()` method suddenly throws something else than an `S3Exception`, it should not throw an `AdapterException`, and I *do not* want to catch this exception!

Also, may I insist that the S3 adapter, at least (I haven't checked others), doesn't respect the original contract, which would be to return `false` instead of throwing an exception in case of failure. Flysystem's error handling seems to need some tidy up, and this would be a very nice opportunity.

**Comment by BenMorel** [comment]
I wouldn't consider this issue stale, it's still very relevant and is missing feedback from the authors.

**Comment by BenMorel** [comment]
Still very much relevant.

**Comment by rulatir** [comment]
Yes, still relevant, and the lack of response from authors is very disheartening.

I am writing a rollback buffer decorator for adapters. It records all directories/files created/modified using it, along with original content of modified files. It is intended to be used for various file provisioning operations that must clean up if they fail midway through, or must be completely undoable (like provisioning for integration tests). The whole idea is that if anything goes wrong, the adapter throws, and the `catch` block after the entire provisioning operation performs a rollback. This would be completely defeated by the adapter not throwing on obvious failures.

**Comment by GrahamCampbell** [comment]
I'm sure contributions* to correct the cases where exceptions are thrown instead of the correct return happening would be gladly accepted. That would not be a controversial change, only a bug fix.

As far as I'm concerned, it would be a bad idea for flysystem to wrap up every exception that could occur. Flysystem should only handle the expected ones, and if anything else bad happens, it should allow the original exception to bubble up the call stack. I kinda like to think about exceptions in a similar way to how the Java type checker enforces them. Runtime exceptions are allowed through, but anything else you must handle properly and decide explicitly if you are going to catch it when you write function bodies. I think of unexpected vendor exceptions as "runtime errors", but the expected vendor exceptions do need to be correctly handled by the library.

\* Flysystem is provided free of charge, under a generous license, and if there's something it doesn't do or that doesn't work quite right, it is not necessarily the job of the maintainer to correct this. **Anyone** can (and should) contribute.

**Comment by BenMorel** [comment]
@GrahamCampbell The idea is not to catch *any* exception to re-throw it. The idea is to catch exceptions **that have a meaning for the flysystem interface**: permission error, disk full, connection timeout, etc. In the case of the S3 adapter, it so happens that pretty much every `S3Exception` meets the above criteria, and as such is a good candidate for wrapping into a higher level exception as proposed above. OTOH, if internally the S3 library also throws other exceptions (say, `InvalidArgumentException`), these should indeed not be caught and be allowed to bubble up.

The goal is to have a single umbrella exception, that belongs to the flysystem package, that consumers of flysystem can use to **detect if a transfer failed**. As a consumer of the `FileSystemInterface`, I should not have to worry about which adapter is being used under the hood, I should be able to `try` a transfer and `catch` a single exception type. If the transfer fails for a reason that's related to the underlying storage (permission error, disk full, connection timeout, ...) I should be able to safely assume that this exception will be thrown.

It would be a mistake to catch the root `Exception` class for this purpose: as I said above, if an exception is thrown **for an error that's unrelated to the transfer itself** (in my example above, an `InvalidArgumentException` that would be thrown because of a bug in an underlying library or a bad method call), **I do *not* want to catch it, this one should bubble up**.

> Flysystem is provided free of charge, under a generous license, and if there's something it doesn't do or that doesn't work quite right, it is not necessarily the job of the maintainer to correct this. Anyone can (and should) contribute.

Of course. I very much value the work already done, and I'd be more than happy to submit a PR to fix this issue; but the feedback from flysystem members on this issue has so far been quite negative, so I feel like this PR would likely not be accepted.

If I'm mistaken, please let me know, and I'll happily take the time to craft a PR and do my best to fix this issue as best as I can.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell The idea is not to catch any exception to re-throw it. The idea is to catch exceptions that have a meaning for the flysystem interface: permission error, disk full, connection timeout, etc. In the case of the S3 adapter, it so happens that pretty much every S3Exception meets the above criteria,

Yes, this is what I was saying I agree with, when I said "Flysystem should only handle the expected ones". :)

> but the feedback from flysystem members on this issue has so far been quite negative, so I feel like this PR would likely not be accepted.

I think bug fix PRs would be massively appreciated, so long as there aren't any false positives for other errors from the library from exceptions that are not related to "file not found" etc.

**Comment by frankdejonge** [comment]
This issue has been raised before and I've addressed it before. The exception structure (not talking about the false returns) are what they will be now and in the future. By wrapping the adapter specific exceptions into another exception allows you to catch them all, but so does catching a generic throwable or exception type. By catching, wrapping, and re-throwing you actually loose the ability to catch specific cases. This "catch-all" case has been ironically been used as an argument FOR using a wrapped exception. To call my stance on this disheartening is rude. Just because you don't agree with my stance doesn't make it invalid. Flysystem catches exceptions it is supposed to catch, the expected ones, the other ones it doesn't catch. This is because Flysystem should not be a black box. When time after time the same few people come and address this issue, I do indeed start to ignore it. I don't want to have to explain myself over and over and I don't want to give into to writing code that I don't stand by.

**Comment by GrahamCampbell** [comment]
@frankdejonge as I understand it, @BenMorel is not asking for flysystem to cache and re-throw everything. He's only asking for things like "file not found" to be handled as per the interface specifies. It looks like there remain a few unhandled cases? That is, there are just a few bugs in the existing model.

**Comment by BenMorel** [comment]
It looks like there is a strong misunderstanding indeed. I think I've already raised my concerns with the current approach extensively, but will summarize them here a last time:

- the current contract is broken by some adapters, that throw an exception when the contract states that [they should return `false` on failure](https://github.com/thephpleague/flysystem/blob/1.0.53/src/AdapterInterface.php#L24)
- *if* exceptions are expected, then this contradicts the above contract, and these exceptions are currently undocumented
- *if* exceptions are expected, there is no way to catch all filesystem-related exceptions (and **only** these ones) under a single umbrella exception, which  is standard practice and avoids having to know both the underlying adapter *and* its implementation details (the underlying library) to be able to catch the correct exception; **this defeats the whole purpose of using a unified interface in the first place** (BTW, [exception nesting](https://www.php.net/manual/en/exception.getprevious.php) allows you to get access to lower-level exceptions even though you're catching a higher-level one)
- catching *all* exceptions is an anti-pattern and cannot be the suggested approach for adapter-agnostic error handling

I raised [a similar issue](https://github.com/aws/aws-sdk-php/issues/120) a few years ago in the AWS SDK for PHP. The `S3Client` was letting underlying Guzzle exceptions (indicating a failed transfer) bubble up, and this was undocumented. This was prompty fixed by wrapping exceptions in `S3Exception`, and all **TRANSFER-RELATED** exceptions (I would emphasize this further if I could) can now be caught under a single, properly documented, umbrella exception.

(Note that the use case of AWS was slightly different, as Guzzle is the only underlying library; an OK alternative would have been to just *document* the Guzzle exception. This does not apply here, as there are many underlying implementations, that need to share a common error interface.)

If flysystem is is never going to fix this, I guess it's time to fork it or create a new implementation that gets this right, as there is currently no reliable way to handle errors with the current implementation.

**Comment by frankdejonge** [comment]
> If flysystem is is never going to fix this, I guess it's time to fork it or create a new implementation that gets this right, as there is currently no reliable way to handle errors with the current implementation.

@BenMorel what are you trying to achieve by posting things like this?

If there's missing cases that's doesn't require developer intervention (like authentication issues and the like) then feel free to send in a PR. But let it be known that if you keep posting stuff in this tone, you'll be blocked from the github repository. I have no problem doing that. This is my personal project, my personal time, my effort that I put in when and if I want to.
