### ISSUE TITLE
How to add additional file "meta-data" from database?

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem#624]
I have a requirement and I'm unsure as to whether this is possible with elFinder?

Ideally I need to list files (from Google Cloud Storage, this bit I have managed with elFinder extensions) and include additional "meta-data" that is stored in a database.

Files are going to be organised into folders with a name representing a "job" e.g. job_abc123, and this folder will contain various files for that job.

So, we can fairly easily reference a single file using the job folder name and the file name itself (ignore possible duplication issues for now)

Is there a way to use elFinder to call a database and append the data to the file information?

**Comment by frankdejonge** [comment]
@paulcanning Hi, I think you'll need to open an issue here: https://github.com/Studio-42/elFinder

**Comment by paulcanning** [comment]
Sorry, I have too many tabs open haha

**Comment by frankdejonge** [comment]
@paulcanning no worries :) good luck with the issue.
