### ISSUE TITLE
Exception thrown by Local driver attempting to create directory in quick succession

### ISSUE THREAD

**Issue by dmlogic** [thephpleague/flysystem#625]
I have an application where I allow a user to pick multiple files for upload from a web form. These are then submitted individually and asynchronously using jQuery and HTML FormData.

If I have several small files submitting at once, it is possible that the server arrives at [`Local::ensureDirectory()`](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L92) almost simultaneously and the [`if ( ! is_dir($root))`](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L94) check returns an incorrect result.

This can result in an `ErrorException` "mkdir(): File exists". I'm not sure you can reproduce the error without my app, but steps would be:

* Laravel 5.2 app running on local Vagrant Homestead instance with PHP7
* Multiple async submissions to a route which should result in creation of a directory that does not yet exist
* Produces exception below:

![screen shot 2016-03-24 at 13 40 53](https://cloud.githubusercontent.com/assets/1250252/14018998/81643dea-f1c8-11e5-8cf4-f6c7e249ef12.png)

This may well be a PHP problem and/or Vagrant not running fast enough in a local environment, but I wonder if it's possible to mitigate, perhaps wrapping in try/catch that looks for the "File exists" message? I've checked the Exception thrown for other problems such as permissions and unfortunately it's identical apart from the message - and I guess that may change in different languages.

**Comment by frankdejonge** [comment]
@dmlogic are you using an nfs mount?

**Comment by dmlogic** [comment]
I'm not sure and I don't immediately know how to find out. Usually I know with Vagrant but this is my first time using [Homestead](https://github.com/laravel/homestead) and it like to hide these things away.

**Comment by dmlogic** [comment]
as best as I can see, there is nothing specified, so it would be the default (I'm on OSX 10.11.3. Vagrant 1.7.4)

**Comment by frankdejonge** [comment]
@dmlogic by the look of the homestead repo there should be a folder.type option in the yaml config.

**Comment by dmlogic** [comment]
I just have this:

```
folders:
    - map: "/Users/darren/projects/my_project/www"
      to: "/home/vagrant/www"
``

If you think it's lag on nfs then I can look into refining the Vagrant file at some point as it's not causing me too much trouble, I was just a bit surprised to see that exception happen

**Comment by frankdejonge** [comment]
@dmlogic you can set the `type: nfs` option there and reload the box.

**Comment by frankdejonge** [comment]
@dmlogic did that fix it?

**Comment by dmlogic** [comment]
I've tried changing it to the following, followed by a `Vagrant reload`. Problem still remains.

```
folders:
    - map: "/Users/darren/projects/my_project/www"
      to: "/home/vagrant/www"
      type: nfs
```

**Comment by Rolice** [comment]
I have the same issue when I use symbolic link that links outside the project (Laravel 5.2), i.e.:

```sh
ln -s /var/www/platform/project1/storage/files /var/www/platform/laravel-5.2-project/storage/files
```
The driver detects that `files` is not a folder and runs `mkdir`.
The result is the same: `mkdir: File exists`

Is it possible to include check for symbol links?

**Comment by Rolice** [comment]
Hello, unfortunately, the commit does not seem to resolve the issue. With the fix at hand in `Local.php` I still receive the error message: `mkdir(): File exists`. This is due to the fact that is_dir returns false on the link or a subfolder of symbolic link.

This might requires an explosion of the path and checking and maybe for the same reason symlinks are not supported.

**Comment by frankdejonge** [comment]
@Rolice I've added a suppressor for the warning, unfortunately that's the only way to deal with the race condition AND not be blocking for miscellaneous dir creation, it'll shit with the upcoming release.

**Comment by Rolice** [comment]
Ah, I see.
Thanks

**Comment by frankdejonge** [comment]
/s/shit/ship whoops.

**Comment by cassianotartari** [comment]
Any update on this? I'm with the same symbolic link problem

**Comment by frankdejonge** [comment]
@cassianotartari it shipped with the last release.

**Comment by cassianotartari** [comment]
Bad news, I'm using Flysystem with ``oneup/flysystem-bundle``. I did a ``composer update oneup/flysystem-bundle`` and apparently I was in the [last version](https://packagist.org/packages/oneup/flysystem-bundle). After I did an ``composer update league/flysystem``
```bash
composer update league/flysystem
Updating dependencies (including require-dev)
  - Removing league/flysystem (1.0.24)
  - Installing league/flysystem (1.0.27)
    Downloading: 100%  
```

And the error keeps:
```
ContextErrorException in Local.php line 99:
Warning: mkdir(): File exists
```

What I'm trying to achieve? Using vagrant Homestead, create a symbolic link in my machine, to reflect in the virtual machine. For example: my physical machine has ``/home/cassiano/projects/demo/web/uploads`` that points ``uploads -> /media/cassiano/demo/uploads/``. And in homestead config has the map between ```/home/cassiano/projects/`` and ``/home/vagrant/projects``.

So when I ssh into vagrant the ``uploads`` seems to be wrong ``uploads -> /media/cassiano/archive/uploads/``

**Comment by frankdejonge** [comment]
@dmlogic that's odd, because the line number is incorrect. Could you re-check?

**Comment by frankdejonge** [comment]
It should be line 100 btw.

**Comment by cassianotartari** [comment]
But I think this is not a Flysystem issue, is more about vagrant. The reason I'm using symbolic is to move the content to other disk. My vagrant machine is running on my SSD with only 128GB and I'm trying to create a link inside web folder to the other hard drive. So keep my app will think that files are under ``web`` folder.

I've tested symbolic link in the same virtual disk inside vagrant and Flysystem worked right. The issue should be related to link my guest (vagrant) folder to a different disk in host.
