### ISSUE TITLE
getMimetype() reads entire file from FTP/SFTP

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/flysystem#629]
This is probably intentional, but requesting the mimetype of a file is pretty expensive on FTP/SFTP.

I understand that this is probably the only reliable way to detect the mimetype, but this seems a bit overkill for the regular use case. As far as I can see, these are the only ones who do this.
Perhaps it would be enough to try to detect the mimetype from the filename instead, when possible? Or make it configurable/extra parameter or something?

My use case was providing a directory listing in a filebrowser. For FTP this reads the entire directory (eg. 50 MB of photos), before determining that they're photos...

I've now switch to just calling `getMetaData()` and using the data available, but perhaps this might confuse others as well?

**Comment by barryvdh** [comment]
Or perhaps check if we have the `contents` already, otherwise return `false`?

**Comment by frankdejonge** [comment]
@barryvdh reading the contents is the best way of determining the mime-type. We could opt out of this, which would improve the speed. Also, getting the mime-type from the contents is what the cached adapter is for, that does _exactly_ that.

**Comment by barryvdh** [comment]
The cached adapter caches the content indeed, if you've read it before. But if you don't need to read the entire file, you're loading the contents just for the mimetype.

**Comment by frankdejonge** [comment]
@barryvdh that part only referred to `Or perhaps check if we have the contents already`.

**Comment by barryvdh** [comment]
I meant that we only use the `content`, when we've already have the contents in our metadata. So something like this:

```php
public function getMimetype($path)
{
	$metadata = $this->getMetaData($path);

	if (isset($metadata['contents']))) {
		$metadata['mimetype'] = Util::guessMimeType($path, $metadata['contents']);
	} else {
		$metadata['mimetype'] = MimeType::detectByFilename($path);
	}
	
	return $metadata;
}
```

**Comment by barryvdh** [comment]
Thanks!
