### ISSUE TITLE
directory level

### ISSUE THREAD

**Issue by hiscaler** [thephpleague/flysystem#633]
I use it to guzzle, like follow
```php
$stack = HandlerStack::create();
            $stack->push(
                new CacheMiddleware(
                    new PrivateCacheStrategy(
                        new FlysystemStorage(new Local('/tmp'))
                    )
                ), 'cache'
            );
```
I cache files is very many, How can i config directory level, like
/tmp/a1/aaaa.cache.file
/tmp/a2/bbbb.cache.file
/tmp/a3/cccc.cache.file

**Comment by frankdejonge** [comment]
@hiscaler this should be dealt with outside of flysystem. You can format the path before handing it off to the filesystem instance. Flysystem has no mechanism for this, and it's also not intended to have one.
