### ISSUE TITLE
How to handle large filelist? (malloc error)

### ISSUE THREAD

**Issue by nittonfemton** [thephpleague/flysystem#634]
Trying to do a $filesystem->listContents($path)

    PHP Warning:  ftp_systype(): OOPS: malloc in vendor/league/flysystem/src/Adapter/Ftp.php on line 446

The directory is huge, with millions of files. I've allocated 15gb to the PHP memory_limit value.

**Comment by nittonfemton** [comment]
Same error when I got 240 000MB allocated.

**Comment by nittonfemton** [comment]
Actually I think it's the FTP server that produces this error.

**Comment by frankdejonge** [comment]
@nittonfemton I was just about to say that. It seems like the FTP server might be under capacity.

**Comment by frankdejonge** [comment]
@nittonfemton did you find out anything more?

**Comment by nittonfemton** [comment]
Yes, it was a misconfigured ftp server and the error was on that part, not with flysystem.
