### ISSUE TITLE
the method  of read() in ftp not worked, File not found at path:xxx file

### ISSUE THREAD

**Issue by anglewgc** [thephpleague/flysystem#636]
My laravel vision is 5.2.*:in my config/flysystem.php ,here are configs:
```
'disks' => [
            'ftp' => [
            'driver'     => 'ftp',
            'host'       => 'myhost',
            'port'       => 21,
            'username'   => 'myusename',
            'password'   => 'mypassword',
            'root' => '/',
        ],
],
```

and my route is here:

```
Route::get('/flysystem', function () {
    Storage::disk('ftp')->put('hi.txt', 'Contents test');
    echo Storage::disk('ftp')->read('hi.txt');
});
```
it is error and output "FileNotFoundException in Filesystem.php line 381:
File not found at path: hi.txt";
My English is very bad ,please help me! thank you.

**Comment by frankdejonge** [comment]
@anglewgc is there anything in your error log? This is too little to infer anything from.

**Comment by anglewgc** [comment]
`
[2016-04-12 15:43:08] local.ERROR: exception 'League\Flysystem\FileNotFoundException' with message 'File not found at path: hi.txt' in E:\www\github\coding-net-github\laravel\vendor\league\flysystem\src\Filesystem.php:381
Stack trace:
#0 E:\www\github\coding-net-github\laravel\vendor\league\flysystem\src\Filesystem.php(176): League\Flysystem\Filesystem->assertPresent('hi.txt')
#1 [internal function]: League\Flysystem\Filesystem->read('hi.txt')
#2 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(380): call_user_func_array(Array, Array)
#3 E:\www\github\coding-net-github\laravel\app\Http\routes.php(51): Illuminate\Filesystem\FilesystemAdapter->__call('read', Array)
#4 E:\www\github\coding-net-github\laravel\app\Http\routes.php(51): Illuminate\Filesystem\FilesystemAdapter->read('hi.txt')
#5 [internal function]: App\Providers\RouteServiceProvider->{closure}()
#6 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php(158): call_user_func_array(Object(Closure), Array)
#7 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php(137): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#8 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#40 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#41 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#43 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 E:\www\github\coding-net-github\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 E:\www\github\coding-net-github\laravel\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}  

`

**Comment by frankdejonge** [comment]
@anglewgc can you see on the ftp server which operation failed? Did the file get written? This way we can figure out if the put call failed or the read call failed.

**Comment by anglewgc** [comment]
@frankdejonge 
In the ftp server, the file is writen,but can't read the file.

**Comment by frankdejonge** [comment]
@anglewgc could you check what the raw result from the ->has call is?

**Comment by anglewgc** [comment]
@frankdejonge In the flysystem\src\Adapter\AbstractFtpAdapter.php, the->has, the param '$path' is 'hi.txt', and return $this->getMetadata($path)  ,the value is 'hi.txt'

**Comment by xaviermarchegay** [comment]
I have the exact same issue with FTP (secure).

```
$filename = "test.txt";
Storage::disk('ftp')->put($filename, "test content");
$files = Storage::disk('ftp')->files();
$content = Storage::disk('ftp')->read($filename);
```

Results: 

- "test.txt"  is created (but empty)
- $files is empty
- finally, [League\Flysystem\FileNotFoundException] File not found at path: test.txt

What can I do to help?

**Comment by hughsaffar** [comment]
Is it a workaround for this issue? I do have the same problem and could not figure out to solve it yet!

**Comment by xaviermarchegay** [comment]
I remember trying to use the php functions (ftp_ssl_connect) and I had the same issue.
I am not sure about that but I think it has something about the certificate and the way ftp_ssl_connect works. I may be wrong about that.

**Comment by hughsaffar** [comment]
If I try to read the file with complete path there is no problem. But when I loop by foreach, it can not read some certain files.

**Comment by hughsaffar** [comment]
Something else I discovered... It happened to the 50th file in the list! I tried another shuffle list of files and again the 50th can not be found. Maybe the connection reset?

**Comment by hughsaffar** [comment]
I kind of solve my problem but not sure if it is a permanent/right solution! I chunked the list of my files to 25 or so and after reading every 25 files I reset my FTP connection.

**Comment by frankdejonge** [comment]
Sounds like this is a problem with the configuration of the FTP server rather than flysystem, I don't see any point where I can improve based on this input. Any other info you've got to help me find a solution?

**Comment by hughsaffar** [comment]
I'm assuming there should be a config on the FTP server that you can define the number of the files each connection can download. However, a software like Transmit could download an unlimited number of the files. Or maybe Transmit also reset the connection after downloading a certain number of the files.

**Comment by frankdejonge** [comment]
@hughsaffar we've already got a reconnection mechanism. It might be a limitation of PHP's ftp implementation.

**Comment by hughsaffar** [comment]
@frankdejonge That make sense! Because I tested my code with 3 different FTP and got the same result from all of them.

**Comment by frankdejonge** [comment]
@hughsaffar that's sad :(

Despite the unhappy outcome, this seems out of flysystem's reach to fix, therefor I'm closing the issue.
