### ISSUE TITLE
Replicate Adapter and MountManager

### ISSUE THREAD

**Issue by kamov** [thephpleague/flysystem#640]
hi,
when multiple adapters are setup via mount manager, we can add files to multiple adapter by specifing prefix before file, e.g. "local://"

But when I want setup replicate adapter, for example source = S3 and replica = local, then when I read file, I can just use prefix "local://" like below example:

```php

$contents = $manager->listContents('local://uploads', true);

```

and replica adapter will load from source (s3 in this example)?

Considering this setup of replica adapter:
```php

$source = new League\Flysystem\AwsS3V3\AwsS3Adapter(...);
$replica = new League\Flysystem\Adapter\Local(...);
$adapter = new League\Flysystem\Replicate\ReplicateAdapter($source, $replica);


```

**Comment by frankdejonge** [comment]
@kamov the mountmanager maps a prefix to a filesystem, so if this filesystem contains two filesystems, like with the replicate adapter your `local` might indeed map to a s3 filesystem. When using the mount manager this is what you are responsible for.

**Comment by kamov** [comment]
@frankdejonge thanks for your reply.

Yes I understand that I am responsable for handle alone the map to remote filesystems.

I would like to know if I can use both?

For example, I setup 3 filesystem using mountmanager, local, S3 and dropbox.

Then using replicateAdapter I map local and S3 automatically, and then use dropbox manually, for example for backup. 

Thanks

**Comment by frankdejonge** [comment]
@kamov you can do that, it all depends on what you're trying to solve.

**Comment by kamov** [comment]
Thank You!

**Comment by kamov** [comment]
Hi,
I try but is not work.
When I upload manually on dropbox, then is work, but not with replicate adapter.
This below is my test code:

```php

<?php

use League\Flysystem\Adapter\Local as LocalAdapter;
use League\Flysystem\Filesystem as Flysystem;
use League\Flysystem\MountManager;
use League\Flysystem\Dropbox\DropboxAdapter;
use Dropbox\Client;
use League\Flysystem\Replicate\ReplicateAdapter;
// require lib
require 'vendor/autoload.php';

    // all adapters
    $adapters = [];
    /* Init local adapter object */
    $adapters['local'] = new LocalAdapter( __DIR__.'/data/' );
    /* Init local filesystem object */
    $filesystem = new MountManager([
        'local' => new Flysystem( $adapters['local'] )
    ]);
    /* Dropbox filesystem */
    $adapters['dropbox'] = new DropboxAdapter( new Client('xxx', 'xxx') );
    $filesystem->mountFilesystem( 'dropbox', new Flysystem( $adapters['dropbox'] ) );
    /* Setup replicate adapter */
    $adapter = new ReplicateAdapter( $adapters['dropbox'], $adapters['local'] );
    if(isset($_FILES["myfile"]) && !empty($_FILES["myfile"])) {
        $stream = fopen($_FILES["myfile"]['tmp_name'], 'r+');
        $filesystem->writeStream("local://".$_FILES["myfile"]['name'], $stream);
        //$filesystem->writeStream("dropbox://".$_FILES["myfile"]['name'], $stream);  // THIS WORK 
        fclose($stream);
    }
    else {
        echo '
        <form action="fly.php" method="post" enctype="multipart/form-data">
            Select image to upload:
            <input type="file" name="myfile" id="myfile">
            <input type="submit" value="Upload Image" name="submit">
        </form>';
    }

```

**Comment by frankdejonge** [comment]
@kamov you're trying to mount an adapter but you should mount a filesystem, so wrap the `$adapterReplica` like this: `$filesystem->mountFilesystem('replica', new Flysystem($adapterReplica));`.

**Comment by kamov** [comment]
Oh.... Right! Many thanks!

**Comment by kamov** [comment]
Works perfectly now. Many thanks!
