### ISSUE TITLE
Memory adapter

### ISSUE THREAD

**Issue by kamov** [thephpleague/flysystem#641]
Using this adapter, if I understand correctly, file are stored in RAM, right?
But this not permanently memory, when server shoutdown, so I guess where are then this file after restart of server?

Does this adapter is created for quick testing or for good performance?

Thanks

**Comment by frankdejonge** [comment]
@kamov it's mostly for testing. After the request (or and the end of the cli script, the "files" are gone.

**Comment by kamov** [comment]
Thanks!
