### ISSUE TITLE
Using dropbox for application

### ISSUE THREAD

**Issue by kamov** [thephpleague/flysystem#642]
I would like to know if someone know about using dropbox for an application.

I need to store images and videos, I would like to know if this can be used in this way, or just for backup.

Does they offer a service like S3, or not. Does their content is served using a CDN?

Thanks

**Comment by frankdejonge** [comment]
I personally only use the dropbox adapter to help with uploads; people sync with dropbox and I read from dropbox. Server to server interaction is a lot faster than client to server. I wouldn't rely on dropbox as a CDN either. It's not designed for that purpose and won't behave in similar manners. If you need a CDN the easiest solution would be to use AWS S3 along with Cloudfront. That's quite easy to setup, there are many resources which show that.
