### ISSUE TITLE
Orientate image before storing

### ISSUE THREAD

**Issue by kamov** [thephpleague/flysystem#643]
Hi,
I would like to know how to fix image orientation before saving ?
I am using exif_read_data();
Thanks

**Comment by kamov** [comment]
Maybe I solve this, I read exif data from temp file name, and store again on temp file name, then store using flysystem..

**Comment by frankdejonge** [comment]
@kamov this should indeed be handled outside of flysystem, your suggested approach is correct. This should be done prior to uploads. You can use GD or Imagick to remove it.

**Comment by kamov** [comment]
Since I am using Intervention/Image I see that I can directly pass data to flysystem as below:

```php
// read image
$contents = $flysytem->read('foo.jpg');
$image = Image::make($contents);
// write image
$image->encode('png');
$flysytem->put('bar.png', $image);
```

But since I am using writeStream() I need resource. I see that you suggest:

> you can get the resource by calling the detach method on the GuzzleHttp\Psr7\Stream response.

But not sure how to get this work. Does I need to create a new instance of GuzzleHttp or there is a way to get this from flysystem?

Or maybe is better save on temp_file? 

Thanks
