### ISSUE TITLE
Storage::has(null) returns true

### ISSUE THREAD

**Issue by DuckThom** [thephpleague/flysystem#644]
As mentioned in https://github.com/laravel/framework/issues/13259, Storage::has(null) returns true
This is probably because the `has()` function will only do `file_exists('/some/path/prefix')` if the $path variable is null.
An easy change would be to return false if $path is null like so.
```
public function has($path)
{
    if ($path === null) {
        return false;
    } else {
        $location = $this->applyPathPrefix($path);
        return file_exists($location);
    }
}
```

**Comment by frankdejonge** [comment]
@DuckThom this is fixed and tagged as `1.0.21`.
