### ISSUE TITLE
Failed to upload file without extension into S3 bucket with users without ListObjects grants

### ISSUE THREAD

**Issue by clagiordano** [thephpleague/flysystem#646]
I recently encountered this problem, whereas before it had not occurred,
it is possible that it is due to some change of AWS server side?

Sample code:

```php
$fileSystem->put(
    'file_571f84c6653d2, 
    $content,
    ['StorageClass' => 'REDUCED_REDUNDANCY']
);
```

the problem occurs when the AmazonS3 Adapter try to call method doesDirectoryExist() 
into the has() method of the same object but doesn't return true because the file doesn't exists yet:

AwsS3Adapter Line 203:
```php
public function has($path)
{
    $location = $this->applyPathPrefix($path);

    if ($this->s3Client->doesObjectExist($this->bucket, $location)) {
        return true;
    }

    return $this->doesDirectoryExist($location);
}
```

Thank you and best regards.

**Comment by frankdejonge** [comment]
@clagiordano Flysystem requires the ListObject grant, not explicitly but relies on it in the "core" functionality.

**Comment by frankdejonge** [comment]
@clagiordano I've tried to reproduce this with your example, but the first time the put goes through and the second time the `$this->s3Client->doesObjectExist` call returns true.

**Comment by clagiordano** [comment]
It is correct but the weird thing is that it until a few days ago everything worked properly, that's why I was thinking a change from aws server side.

**Comment by frankdejonge** [comment]
@clagiordano also, why is the listobject missing? I did release an opdate to this adapter recently, which adds a directoryExists check which relies on the ListObjects grant.

**Comment by clagiordano** [comment]
To correctly reproduce the problem, you need to always try different filenames, use uniqid for this purpose, because the answers are cached aws.

```php
uniqid('test_file_');
```

**Comment by clagiordano** [comment]
The listobject grant is missing for security reason because the dedicated user can only putObject but not lists the folder or bucket.

**Comment by frankdejonge** [comment]
@clagiordano could you give me a testcase in full that reproduces this? Even with the `uniqid('test_file_')` it succeeds here.

**Comment by clagiordano** [comment]
Thank you for your answer,

this is a full, self contained, test case to reproduce always the problem:

[https://gist.github.com/clagiordano/209baec5734b9547e6b308dfbccd6ef7](https://gist.github.com/clagiordano/209baec5734b9547e6b308dfbccd6ef7)

**Comment by frankdejonge** [comment]
@clagiordano who is the one limiting access? Flysystem requires that grant for proper use. If you are limiting the capabilities you might want to solve it in your code rather than in AWS.

**Comment by frankdejonge** [comment]
This issue was resolved.
