### ISSUE TITLE
Azure InvalidHeaderValue

### ISSUE THREAD

**Issue by stefanedberg** [thephpleague/flysystem#647]
I'm getting this error when trying to use Flysystem with the Azure Blob Storage adapter:

```php
Fatal error: Uncaught WindowsAzure\Common\ServiceException: Fail: Code: 400 Value: The value for one of the HTTP headers is not in the correct format. details (if any): . in /var/www/...../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php:383 Stack trace: #0 /var/www/...../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php(276): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '', Array) #1 /var/www/...../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/RestProxy.php(141): WindowsAzure\Common\Internal\Http\HttpClient->send(Array, Object(WindowsAzure\Common\Internal\Http\Url)) #2 /var/www/...../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/ServiceRestProxy.php(86): WindowsAzure\Common\Internal\RestProxy->sendContext(Object(Wind in /var/www/...../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php on line 383
```

I installed Flysystem and the Azure adapter:

`composer require league/flysystem`
`composer require league/flysystem-azure`

Copied the example adapter code and added my credentials. If I alter the credentials it fails with either "Unable to connect..." or AuthenticationFailed so I'm guessing the credentials is correct. I'm still running the trail subscription on Azure if that matters.

```php
<?php
require_once "vendor/autoload.php";

use WindowsAzure\Common\ServicesBuilder;
use League\Flysystem\Filesystem;
use League\Flysystem\Azure\AzureAdapter;

$endpoint = sprintf(
    'DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=%s',
    'account-name',
    'api-key'
);

$blobRestProxy = ServicesBuilder::getInstance()->createBlobService($endpoint);

$filesystem = new Filesystem(new AzureAdapter($blobRestProxy, 'app1'));

$filesystem->has('file.txt');
```

**Comment by frankdejonge** [comment]
@stefanedberg Hi, I think you should open up an issue with the Azure SDK, I don't know why this would happen and it's outside of Flysystem's controle.

**Comment by stefanedberg** [comment]
You are right, the problem seems to be in Azure SDK. Updating STORAGE_API_LATEST_VERSION to 2014-02-14 in WindowsAzure\Common\Internal\Resources.php solves my problem.

http://stackoverflow.com/questions/35484677/invalid-x-ms-version-header-in-azure-php-sdk-with-blob-storage
https://github.com/Azure/azure-sdk-for-python/issues/288#issuecomment-74399273

**Comment by stefanedberg** [comment]
After updating to microsoft/windowsazure 0.4.3 Flysystem crashes:

```php
Type error: Argument 1 passed to League\Flysystem\Azure\AzureAdapter::__construct() must be an instance of WindowsAzure\Blob\Internal\IBlob, instance of MicrosoftAzure\Storage\Blob\BlobRestProxy given
```

https://github.com/Azure/azure-sdk-for-php/issues/840

**Comment by shuriktm** [comment]
It seems Flysystem adapter for Azure must be updated with the following rules from the latest Azure SDK release (see https://github.com/Azure/azure-sdk-for-php/releases):

> To update your code for the new storage SDK, change

```
"use WindowsAzure\Blob" to "use MicrosoftAzure\Storage\Blob", 
"use WindowsAzure\Queue" to "use MicrosoftAzure\Storage\Queue"
"use WindowsAzure\Table" to "use MicrosoftAzure\Storage\Table"
```

> For the following calls,

```
ServicesBuilder::getInstance()->createTableService($connectionString) 
ServicesBuilder::getInstance()->createBlobService($connectionString) 
ServicesBuilder::getInstance()->createQueueService($connectionString) 
```

> The new API will be called automatically. You don't need to update your code.
