### ISSUE TITLE
Bug when folder upper to lower case renaming

### ISSUE THREAD

**Issue by claesmelander** [thephpleague/flysystem#652]
When renaming directories in Dropbox (from and to upper to lower case) cause path comparision bug to discard exsting directories in Listing.

Possible fix shown below.

**src/Util/ContentListingFormatter.php**

```
    private function isDirectChild(array $entry)
    {
        return strtolower(Util::dirname($entry['path'])) === strtolower($this->directory);
    }
```

**Comment by furkanayata** [comment]
@frankdejonge Are you going to implement this fix?

**Comment by twistor** [comment]
There are several issues about this in the Dropbox issue queue.

https://github.com/thephpleague/flysystem-dropbox/issues/3
