### ISSUE TITLE
Clarify and clean up return values for metadata in MemoryAdapter

### ISSUE THREAD

**Issue by deviantintegral** [thephpleague/flysystem#653]
In MemoryAdapter, quite a few methods document that they return 'metadata' through the interface. As a developer, I'd expect this to be the same as calling getMetadata() on the path. However, update() includes the file contents in it's return value along with the rest of the metadata.

This is somewhat related to #635 - if we can standardize what metadata should be returned (even if it's still an array), it will make working with adapters much simpler.

**Comment by twistor** [comment]
Should this issue be in the MemoryAdapter queue?

You shouldn't be working with adapters directly. There are solid reasons why information returned is different for different adapters.

**Comment by deviantintegral** [comment]
This came about as I was using MemoryAdapter in tests. Assertions were more complicated than I expected because you couldn't just compare metadata return values directly.

This might just be a docs task (wish I could move issues), but working with undocumented array keys feels fragile to me. I agree that adapters should have control over what properties they support and how they are populated, but having some sort of structure for them would really help with testing and with understanding how to write a new adapter.

**Comment by twistor** [comment]
I fixed this in the memory adapter. https://github.com/thephpleague/flysystem-memory/commit/1374c18fa9984e15951e38d6da222bd0096acf61

I've created a new issue where we can document things #666

**Comment by frankdejonge** [comment]
For reference: http://flysystem.thephpleague.com/creating-an-adapter/

**Comment by frankdejonge** [comment]
Closing this because the other docs issue was resolved.
