### ISSUE TITLE
Caching issues with Google Storage Adapter

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem#656]
I am using a combination of Flysystem and the Google Storage Adapter with elFinder.

I am finding that there are huge issues with caching. I can create folders successfully, but they do not show up after a refresh, despite being in the GCS console.

Sometimes I see duplicates or even folder I have deleted.

Is there any caching in Flysystem I can disable?

**Comment by barryvdh** [comment]
Does it work when you use the GCS adapter without elfinder? (eg. just list the folders on the adapter directly)

**Comment by paulcanning** [comment]
How can I test this? I tried the following, but get no results (Just a blank page)

```
$credentials = new \Google_Auth_AssertionCredentials(
			'gcstest@MY_PROJECT.iam.gserviceaccount.com',
			[\Google_Service_Storage::DEVSTORAGE_FULL_CONTROL],
			file_get_contents('MY_SECRET_KEY.p12'),
			'notasecret'
		);

		$client = new \Google_Client();
		$client->setAssertionCredentials($credentials);
		$client->setDeveloperKey('MY_API_KEY');

		$service = new \Google_Service_Storage($client);

		$adapter = new GoogleStorageAdapter($service, 'MY_BUCKET');

		return new Filesystem($adapter);
```

**Comment by frankdejonge** [comment]
@paulcanning can you open an issue with them? This is not something we can fix from within this codebase.

**Comment by paulcanning** [comment]
Yea I did, however the main dev for Superbalist said he is too busy to fix things and the few fixes I made are kludges basically, so I can't put the into a PR really

**Comment by barryvdh** [comment]
Every PR helps, even if it's just to assess the problem :)
