### ISSUE TITLE
ftp_chmod(): Command not implemented for that parameter

### ISSUE THREAD

**Issue by nWidart** [thephpleague/flysystem#658]
Hello,

I'm on a laravel application, trying to use the FTP file driver.
Reading files from FTP is working perfectly fine.

However I'm getting the following error when trying to write to the ftp:
```
ErrorException in /home/vagrant/monitoring-assistance/vendor/league/flysystem/src/Adapter/Ftp.php line 423:
ftp_chmod(): Command not implemented for that parameter
```
With last stacktrace item:

```
at HandleExceptions->handleError('2', 'ftp_chmod(): Command not implemented for that parameter', '/home/vagrant/monitoring-assistance/vendor/league/flysystem/src/Adapter/Ftp.php', '423', array('path' => 'assets/media/nwpgcl.jpg', 'visibility' => 'public', 'mode' => '484'))
```

When trying to debug, and checking what's sent to the `ftp_chmod`:

```
ftp_chmod($this->getConnection(), 484, ''assets/media/nwpgcl-2.jpg)
```

I was thinking of a permissions issue on the FTP itself, however I can manually upload items on the ftp using transmit for example.

Did I miss something ? 

Thank you,

Edit: just got the heads up from client, it's a windows server 😱

**Comment by nWidart** [comment]
Currently in the process of moving to linux to avoid windows issues...

**Comment by frankdejonge** [comment]
@nWidart it would seem it doesn't support permission modification, which is super weird and difficult to work around.

**Comment by gsc89** [comment]
This is a really annoying error, I can't simply move to linux I am forced to use an existing windows platform, so I will need to look for a solution to this issue now.

**Comment by frankdejonge** [comment]
@gsc89 help would be greatly appreciated, I can only run tests on windows through CI, but other than that I have no way to help out here.

**Comment by gsc89** [comment]
Right so I am running filezilla on a Windows SBS 2008 server as I don't like or need to run full blown ISS. 

I can read files fine there has been no problems there but I only just ran into this when storing files.

I have got around this issue only by editing: 

'league\flysystem\src\Adapter\FTP.php' on line starting 438 I commented out the following.

//        if (!ftp_chmod($this->getConnection(), $mode, $path)) {
//            return false;
//        }

It would obviously be more ideal if in the driver definition there was a variable for windows such as:

`'visibility' => 'windows',`

Which could be checked and used to ignore on windows as permissions don't exist like they do on linux systems.

**Comment by frankdejonge** [comment]
@gsc89 I don't like "if X is Y then B is C" kind of solutions. What you could do it extend the Ftp class as a WindowsFtp class and just disable the permission setting there, would make more sense I'd say. It's explicit and doesn't mess with the normal handling.

**Comment by gsc89** [comment]
Yes that would be a better solution, thanks.

**Comment by bmitch** [comment]
Running into the same problem. @gsc89 did you end up resolving this? Did you extend the Ftp class to make a WindowsFtp class?

**Comment by bmitch** [comment]
For anyone else running into this or something similar I ended up doing what @frankdejonge suggested and extended the Ftp class and used it. To use it I followed the suggestion in this thread: https://laracasts.com/discuss/channels/general-discussion/l5-use-flysystem-replicate-adapter-with-filesystem
