### ISSUE TITLE
How to remove a directly that contains files?

### ISSUE THREAD

**Issue by jfi** [thephpleague/flysystem#660]
I've got the following code which loops over a number of dates (each corresponding to a daily database backup folder) and attempts to delete them. The folders aren't empty at this point, so I want to delete all the backups contained within them too.

        foreach ($period as $dt) {
            $path = 'databases/daily/' . $dt->format('Y-m-d');
            $exists = $filesystem->has($path);
            if ($exists) {
                if (count($filesystem->listContents($path, true)) == 0) {
                    $filesystem->deleteDir($path);
                }
            }
        }

I get the following error:

``Warning:  ftp_delete(): Permission denied. in /.../vendor/league/flysystem/src/Adapter/Ftp.php on line 278``

Flysystem has previously created the directories and written the files to them, using the same user. I can browse the directories/files in my FTP client, logged in as the same user, and also delete them. There is in fact only one user set up on the FTP server, and all directories/files are CHMOD 755 and owned by this user.

I have two queries:

1. Based on this, why would I be getting a permission denied error?
2. Why is `listContents()` returning an empty array when the directories definitely have files inside them?

Thanks!

**Comment by frankdejonge** [comment]
@jfi Hi, this seems to be a permission problem rather than a flysystem problem, flysystem deleted everything within a directory by default.
