### ISSUE TITLE
delete local file bug?

### ISSUE THREAD

**Issue by hu31166** [thephpleague/flysystem#661]
In src/Util.php line for 97
$normalized = preg_replace('#/{2,}#', '/', trim($normalized, '/'));

my file path /www/img.png  after processing into  www/img.png, del fail

**Comment by frankdejonge** [comment]
@hu31166 hi, this is correct, the local adapter makes sure the prefix is once again added. What's the root of the local adapter? In your case it looks like your root is (or should be) `"/"`. Is that correct?

**Comment by hu31166** [comment]
I see, thank you, it seems that I only debug half

**Comment by frankdejonge** [comment]
@hu31166 did you fix the issue? Or is there still a problem? If not, can you close the issue?
