### ISSUE TITLE
Fail to delete absolute path

### ISSUE THREAD

**Issue by dannoso** [thephpleague/flysystem#663]
In https://github.com/thephpleague/flysystem/blob/master/src/Util.php#L96

trim($normalized, '/') breaks any legit absolute paths.
I notice this because the delete method in Laravel 5 doesn't work anymore.

After further investigations seems that in https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L113
The applyPathPrefix() prepends junk.

My scenario is:

Path to delete:
/Users/dlattanzio/projects/php/goSouth/public/assets/appthumbs/pippo.txt

Path passed to file_exists(): 
/Users/dlattanzio/projects/php/goSouth/storage/app/Users/dlattanzio/projects/php/goSouth/public/assets/appthumbs/pippo.txt

![screen shot 2016-05-31 at 3 30 29 pm](https://cloud.githubusercontent.com/assets/1688537/15676262/da2eb02e-2745-11e6-8dfb-ad444ae91595.png)

**Comment by frankdejonge** [comment]
@dannoso you'll have to define the root of the filesystem to `/`, this is expected behaviour.

**Comment by dannoso** [comment]
I see thank you. I'm closing this.
