### ISSUE TITLE
Document metadata values and how they should be handled.

### ISSUE THREAD

**Issue by twistor** [thephpleague/flysystem#666]
The metadata array returned from adapters is confusing to say they least. There are valid reasons why it behaves this way, but it should be explained.

**Comment by twistor** [comment]
For reference, here I am trying to explain things https://www.drupal.org/node/2713657

I am not even sure if I'm right, that's simply my understanding :)

**Comment by frankdejonge** [comment]
@twistor this was previously documented here: http://flysystem.thephpleague.com/creating-an-adapter/

**Comment by frankdejonge** [comment]
Let me know if that isn't sufficient, PR's are also welcome.

**Comment by frankdejonge** [comment]
@twistor any feedback on the docs?

**Comment by twistor** [comment]
Looks good to me. I hadn't seen that page before.
