### ISSUE TITLE
unzip files remotely

### ISSUE THREAD

**Issue by Sejido** [thephpleague/flysystem#668]
hello am i  able to unzip files in remote server using sftp ?

**Comment by frankdejonge** [comment]
If you download it using the ftp adapter and extract it using the ziparchive adapter you can do that.

**Comment by kwazaro** [comment]
It seems the question was about UPLOADING zip archive to remote server using sftp and UNZIP this file on REMOTE server. Is there any way to do this?

**Comment by frankdejonge** [comment]
Not within Flysystem. It can work with zips, and it can work with FTP. What it cannot do is work with zips over FTP.
