### ISSUE TITLE
AzureAdapter must use MicrosoftAzure instead of WindowsAzure

### ISSUE THREAD

**Issue by shuriktm** [thephpleague/flysystem#671]
Flysystem adapter for Azure must be updated with the following rules from the latest Azure SDK release (see https://github.com/Azure/azure-sdk-for-php/releases):

> To update your code for the new storage SDK, change

```
"use WindowsAzure\Blob" to "use MicrosoftAzure\Storage\Blob", 
"use WindowsAzure\Queue" to "use MicrosoftAzure\Storage\Queue"
"use WindowsAzure\Table" to "use MicrosoftAzure\Storage\Table"
```

> For the following calls,

```
ServicesBuilder::getInstance()->createTableService($connectionString) 
ServicesBuilder::getInstance()->createBlobService($connectionString) 
ServicesBuilder::getInstance()->createQueueService($connectionString) 
```

> The new API will be called automatically. You don't need to update your code.

It used in the class **AzureAdapter** only.

**Comment by frankdejonge** [comment]
This is fixed and released.
