### ISSUE TITLE
Using listContents() with webdav adapter returns empty array

### ISSUE THREAD

**Issue by thorerik** [thephpleague/flysystem#673]
I've been trying to get a file listing from an Owncloud server using WebDAV, but when I call listContents('folder'), the resulting array is empty, but if I call the adaptor's listContents(), it returns an array as I'd expect.

Calling listContents() with recursion doesn't change the behavior.

Versions used:
Flysystem 1.0.24
Flysystem-webdav 1.0.2
Sabre/dav 2.1.10

Code displaying the behaviour:

``` php
<?php
$settings = array(
    'baseUri' => 'https://example.com/remote.php/webdav/',
    'userName' => '',
    'password' => '',
);
$davClient = new DavClient($settings);
$adapter = new WebDAVAdapter($davClient);
$flysystem = new Filesystem($adapter);
$files = $flysystem->listContents('folder');
var_export($files);
$files = $adapter->listContents('folder');
var_export($files);
```

**Comment by frankdejonge** [comment]
@thorerik could it be a case-sensitivity issue in the folder name?

**Comment by thorerik** [comment]
Don't think so, testing with both lowercase and capitalized folders exhibit the behaviour.

**Comment by frankdejonge** [comment]
@thorerik any way you can intercept the raw response from the webdav server?

**Comment by thorerik** [comment]
Running through Xdebug I picked up this body in sabre\dav\client:
```

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
<d:response>
    <d:href>/remote.php/webdav/Test/</d:href>
    <d:propstat>
        <d:prop>
            <d:getlastmodified>Wed, 29 Jun 2016 12:52:14 GMT</d:getlastmodified>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <d:displayname/>
            <d:getcontentlength/>
            <d:getcontenttype/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
<d:response>
    <d:href>/remote.php/webdav/Test/1</d:href>
    <d:propstat>
        <d:prop>
            <d:getcontentlength>0</d:getcontentlength>
            <d:getcontenttype>application/octet-stream</d:getcontenttype>
            <d:getlastmodified>Wed, 29 Jun 2016 12:52:02 GMT</d:getlastmodified>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <d:displayname/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
<d:response>
    <d:href>/remote.php/webdav/Test/2</d:href>
    <d:propstat>
        <d:prop>
            <d:getcontentlength>0</d:getcontentlength>
            <d:getcontenttype>application/octet-stream</d:getcontenttype>
            <d:getlastmodified>Wed, 29 Jun 2016 12:52:04 GMT</d:getlastmodified>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <d:displayname/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
<d:response>
    <d:href>/remote.php/webdav/Test/3</d:href>
    <d:propstat>
        <d:prop>
            <d:getcontentlength>0</d:getcontentlength>
            <d:getcontenttype>application/octet-stream</d:getcontenttype>
            <d:getlastmodified>Wed, 29 Jun 2016 12:52:05 GMT</d:getlastmodified>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <d:displayname/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
</d:multistatus>
```
Let me know if you want raw-er

**Comment by moebaca** [comment]
Any luck? I am receiving an empty array as well on directories when I use an http or https config. If I just use myserver:8080/webdav and modify  vendor/league/flysystem-webdav/src/WebDAVAdapter.php to remove the '/' inside the quotes below it works on line 201.. but I hate modifying code inside vendor...

$response = $this->client->propFind($location . '', [

**Comment by wbadrh** [comment]
The path of WebDAV uses: 'remote.php/webdav/your/folder'
In stead of the dirname: 'your/folder'
Which doesn't compare in: [isDirectChild()](https://github.com/thephpleague/flysystem/blob/master/src/Util/ContentListingFormatter.php#L100)

#### In:
-> [isEntryOutOfScope()](https://github.com/thephpleague/flysystem/blob/f2ccd52d8e8a271fb340f6636e01d24673e8087b/src/Util/ContentListingFormatter.php#L72)
-> [formatListing()](https://github.com/thephpleague/flysystem/blob/f2ccd52d8e8a271fb340f6636e01d24673e8087b/src/Util/ContentListingFormatter.php#L43)
-> [listContents()](https://github.com/thephpleague/flysystem/blob/fedd0e24ba2aa59521b2431dfaf2d8f1a6a70622/src/Filesystem.php#L273)

### Solution:

[https://example.com/**remote.php/webdav/**](#)

```php
$settings = [
    'baseUri'  => 'https://example.com/', /* without remote.php/webdav/ */
    'userName' => '',
    'password' => '',
];
```

```php
...                                                    /* add remote.php/webdav/ */
$adapter = new League\Flysystem\WebDAV\WebDAVAdapter($client, 'remote.php/webdav/');
...
```

_

This problem occurs in listContents(). Uploading does work when using: https://example.com/remote.php/webdav/ while not adding an optional prefix in WebDAVAdapter.

**Comment by jelofson** [comment]
@wbadrh Thanks for that solution in Nextcloud! Seems to work for me. Unfortunately, I have another dav server which returns the full url for the path, so it will never return results. I don't have control over that server so I can't tweak the settings. The WebDAVAdapter may have to do more massaging to the path prior to sending it to the ContentListingFormatter for more consistent results.

**Comment by wbadrh** [comment]
@jelofson Glad it helped you !
Seems like this is issue is very specific to Owncloud / Nexcloud / Stack

I don't seem to understand what your problem is on your other DAV server. Can you show me an example? I will help you figure it out.

**Comment by jelofson** [comment]
@wbadrh No worries. It's an OpenText document management server that is managed by corporate and they have some settings wrong. For example, the server runs over https, but the returned webdav url is http. Not a big deal as I don't think I will use flysystem with it. I will likely use Nextcloud with flysystem, so your suggestion really helped.
