### ISSUE TITLE
DigitalOcean Block Storage adapter

### ISSUE THREAD

**Issue by orrd** [thephpleague/flysystem#675]
DigitalOcean just announced their Block Storage service.

https://www.digitalocean.com/company/blog/block-storage-more-space-to-scale/

I was wondering if anyone is planning to work on a Flysystem adaper for it?

**Comment by frankdejonge** [comment]
@orrd unless you create a restful interface for that volume yourself, there's no way for Flysystem to interact with it. DO's block storage is a mounted volume, so you address it like a local volume. So in a way, Flysystem is already compatible with it. You'll just have to mount it to your droplet and set the root of the local adapter to the mount point of your block storage volume.

**Comment by orrd** [comment]
Ah, I see.  I had noticed there was a DO Block Storage API, but hadn't looked at it closely enough to realize that the API isn't intended for data or file-level access to Block Storage.
