### ISSUE TITLE
Massive uploads

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem#676]
I am looking to do some huge uploads (using elFidner and Google Cloud Storage) and it looks like I am running out of memory when doing so.

I just tried to upload a 3gb file, and I get a fatal memory error from Polyfill/StreamedWritingTrait.php

elFinder's debug information shows that it's using a peak memory of 5mb.

The upload is chunked into 10mb segments as well.

I'm wondering if there is anything that can be done?

Testing uploading to a local file system, everything is OK, and a file that is under 2gb (the current memory limit of PHP) also works, but I'm wondering if there is a way to have the upload streamed as bits, rather then the whole file?

**Comment by frankdejonge** [comment]
@paulcanning this needs to be dealt with in the Google Cloud Storage API (which is a third party one). The polyfill only ensures the same functionality is available in the adapters. The adapter should implement their own `writeStream` and `updateStream` methods.

**Comment by paulcanning** [comment]
Thanks, I've put an issue on the GCS Flystsem repo

**Comment by paulcanning** [comment]
Would I be correct in assuming that without the methods you mention, files are being uploaded to the applications memory and then written to the filesystem (in this case, GCS)?

**Comment by twistor** [comment]
@paulcanning that is correct. The polyfill reads the stream into memory before writing.

**Comment by richseyha** [comment]
@paulcanning Please could you guide me how to configure connector.minimal.php to manage bucket in Google Cloud Storage? I am looking forward from you!

Best Regards,
