### ISSUE TITLE
Union mount support 

### ISSUE THREAD

**Issue by ccirello** [thephpleague/flysystem#678]
I was checking this package and it seems it does not support union mount.

Questions:
1 - Is it so?
2 - Supposing it doesn't support union mount, would it be OK to implement it? Would it be acceptable to this package scope?
3 - Where may I find contribution guidelines?

**Comment by frankdejonge** [comment]
@ccirello what do you mean with "support"?

**Comment by ccirello** [comment]
@frankdejonge by support I mean that this library does not offer the given functionality.

**Comment by frankdejonge** [comment]
@ccirello but the functionality you describe is OS level functionality.

**Comment by ccirello** [comment]
OK
