### ISSUE TITLE
Local Adapter's getMimetype method is unreliable

### ISSUE THREAD

**Issue by afroewis** [thephpleague/flysystem#684]
With some files (I created an empty xlsx file (`test.xlsx`) with LibreOffice for my test), Flysystem's `Local` Adapter does not return the correct mime type in it's `getMimeType` method. The method returns `application/octet-stream`, even though the mime type would be guessable by the file's extension (`xlsx`). 

The `League\Flysystem\Util::getMimeType` method is much more reliable. It considers the file's extension and uses it as a fallback if the file's mime type can not be guessed with FInfo. 

I think it's a bit confusing that `Local::getMimeType` does not use `League\Flysystem\Util::getMimeType` and makes a FInfo call instead. The `Local` adapter should use the `Util` class, too. 

I would be happy to provide a PR that solves the problem.

**Comment by frankdejonge** [comment]
@afroewis this is fixed, a new version is tagged as 1.0.27.

**Comment by afroewis** [comment]
Perfect! Thank you very much for the really fast reaction.
