### ISSUE TITLE
how to get directory list?

### ISSUE THREAD

**Issue by zplzpl** [thephpleague/flysystem#686]
how to get directory list?

**Comment by zplzpl** [comment]
If can get to the directory tree better

**Comment by zplzpl** [comment]
$filesystem->dirtree(__DIR__);

like this;

**Comment by frankdejonge** [comment]
@zplzpl you can get a listing with `$filesystem->listContents($directory, $recursive);`. If you want a tree you'd have to build that up yourself. The standard list flat.

**Comment by zplzpl** [comment]
thankQ
