### ISSUE TITLE
Local Adapter with Stream Wrappers for Google Cloud Storage

### ISSUE THREAD

**Issue by iamacarpet** [thephpleague/flysystem#687]
Hello,

I'm having issues with the Local adapter using the Google Cloud Storage gs:// stream wrapper.

It appears to be because of the use of realpath, which isn't supported with stream wrappers[1](https://code.google.com/p/googleappengine/issues/detail?id=9626).

Pull Request #680 appears to fix this for me :).

Regards,
Samuel Melrose.

**Comment by mattsimpson** [comment]
Any updates on this? We will be encountering this shortly as well.

**Comment by twistor** [comment]
Using stream wrappers with the Local adapter is not supported. Try https://github.com/Superbalist/flysystem-google-cloud-storage

That said, `realpath()` usage is mostly removed.
