### ISSUE TITLE
Is there plans to add oficial adapter to google storage ?

### ISSUE THREAD

**Issue by adaojunior** [thephpleague/flysystem#691]
Google cloud now has a pretty good API: https://googlecloudplatform.github.io/google-cloud-php/#/docs/v0.7.1/storage/storageclient

**Comment by mattsimpson** [comment]
I one up this.

**Comment by twistor** [comment]
The Google cloud storage adapter exists here: https://github.com/Superbalist/flysystem-google-cloud-storage
