### ISSUE TITLE
Writing to Dropbox, need response, but only bool provided

### ISSUE THREAD

**Issue by nisbeti** [thephpleague/flysystem#692]
When writing to Dropbox, it can rename a file, if that file already exists. The Dropbox API returns the new 'path', which the Flysystem DropboxAdapter is storing in $result. However, the Flysystem.php API casts the returned $result information as (bool), for example:

``` php
118       return (bool) $this->getAdapter()->updateStream
```

Possible solution is for each client constructor to be fed a setting 'returnResult' to switch on or off the (bool) casting.

Without this, I have to test whether the filename already exists, rename it in code, then upload to Dropbox.

**Comment by twistor** [comment]
This would break the API for a Dropbox specific implementation.

If you're renaming a file, you already know the paths involved.

If I'm reading that wrong, then you're saying when you overwrite a file, Dropbox returns the new name of the existing file. This is odd behavior, and I would avoid building anything on top of it.

**Comment by nisbeti** [comment]
If you look at the Dropbox Asapter, it appears that at some point some effort was taken to collect the result, and the path returned. Then in Filesystem, this is all thrown away with the (bool). 
You know how on Windows, if you download a file into a dir with an similarly name file, then it appends (1), (2) etc after it. Dropbox does the same. Otherwise, I have to implement the same testing within my code, to avoid over-writing those files. It would be nice to take advantage of what already is provided by Dropbox. It also returns other useful information, such as mime type, size, modified date etc, immediately after upload. Surely returning info about the upload is a common thing across different file systems. 
My suggestion is not to break backwards compatibility, by keeping the default behaviour to throw it away with (bool), but have the option in Filesystem to keep it if desired.

**Comment by frankdejonge** [comment]
@nisbeti you need to provide that function with a stream, it's not a writeable stream.
