### ISSUE TITLE
File transfer errors

### ISSUE THREAD

**Issue by viraj-khatavkar** [thephpleague/flysystem#697]
@frankdejonge When I am uploading a multiple files (>300), sometimes I get following errors for uploading some of the files via FTP:

`ftp_rawlist(): php_connect_nonb() failed: Operation now in progress (115)`

`ftp_fput(): php_connect_nonb() failed: Operation now in progress (115)`

`fclose(): supplied resource is not a valid stream resource`

**Comment by frankdejonge** [comment]
Seems like these are internal issues with the FTP server, what kind of server is it?

**Comment by jacekkarczmarczyk** [comment]
In casy anyone faces the issue in 2019 - solution that worked for me was to add
```php
'ignorePassiveAddress' => true
``` 
to adapter options
