### ISSUE TITLE
ErrorException: fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by LucianoVandi** [thephpleague/flysystem#698]
Hello, I'm using FTPAdapter as driver in a Laravel project. The application download a file from an external FTP storage using Laravel filesystem. The download process is dispatched as job once a day to a Redis Queue and then executed by `php artisan queue:work`.

Everyday it throws this error: `'fclose(): supplied resource is not a valid stream resource' in /home/username/www/releases/xxxxxx/vendor/league/flysystem/src/Adapter/Ftp.php:455`

Untill I don't restart the worker with `supervisorctl restart all`... then downloading occurs without errors.

Note: the application root is symlinked to /home/username/www/current.

The Job class essentially does this: 
```
$ftp = Storage::disk('ftp');  
$file = $ftp->get($fileName);
$ftp->put('path/to/file.txt', $file);
```
This is the content of config/filesystems.php
```
'ftp' => [
   'driver'   => 'ftp',
   'host'     => env('FTP_HOST'),
   'username' => env('FTP_USER'),
   'password' => env('FTP_PASS'),
   'passive'  => true,
],
```
Supervisor config file:
```
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --daemon --env=production --tries=3
directory=/home/username/www/current
stdout_logfile=/home/username/www/storage/logs/queue.out.log
stderr_logfile=/home/username/www/storage/logs/queue.err.log
user=username
redirect_stderr=true
autostart=true
autorestart=true
numprocs=2
```

**System Info:**
```
Ubuntu 14.04.4 LTS
PHP 5.6.21-1+donate.sury.org~trusty+1
Redis 3.0.6
Laravel 5.2.31
FTP Server: ProFTPD 1.3.4a Server
```

Has anyone experienced this error? Thanks.

**Comment by LucianoVandi** [comment]
It's not a problem of the FTP driver. I've tried switching to an FTP library and the error persist. It seems something related to supervisord. No solution yet.

**Comment by pmartelletti** [comment]
@frankdejonge are you aware of any issue that supervisor may cause? I'm getting `fclose()` errors sometimes, and I'm running on laravel jobs as well. But I'm not sure if it's a server issue ( I don't have control over the server) or if it's supervisor the one causing the issue.

**Comment by frankdejonge** [comment]
Some SDK's close resources after consuming them. You should always first check if it is still a resource using `is_resource`

**Comment by pmartelletti** [comment]
@frankdejonge but how I'm supposed to do that, if it's the FTP abstraction that handles the resource / connection?

**Comment by LucianoVandi** [comment]
@sifex in my case the only solution was sending a restart signal to the queue without restarting supervisord. So, inside my Job class I'm catching the exception and execute `Artisan::call('queue:restart');`. Hope it helps.

**Comment by frankdejonge** [comment]
@pmartelletti seems like there's something else going on, perhaps you're re-using a stream by accident? Basically the stream you've given was invalid.
