### ISSUE TITLE
SFTP Adapter gets stuck while uploading a file with zero bytes

### ISSUE THREAD

**Issue by viraj-khatavkar** [thephpleague/flysystem#700]
@frankdejonge I have an use-case wherein a file with zero bytes might be uploaded. SFTP adapter gets stuck at this point. This might be because of the underlying `phpseclib` library. Do you know any workaround for this ? At the moment, I am uploading a file with a space if it is of zero bytes, but this seems to be a dirty workaround.

**Comment by frankdejonge** [comment]
@viraj-khatavkar there's nothing in flysystem that could cause this since we only pass on the resource. I'd say checking if the stream is empty before using it to write is a valid option. Another question would be, why is the stream empty in the first place?

**Comment by viraj-khatavkar** [comment]
@frankdejonge I specifically made this possible in a known behavior of events. If the file is empty then it just gets stuck. Below is my current implementation

```php
$filesystem->put($deployment_path, $contents);
```

If the `$contents` variable is `null` or `empty` the upload stucks, else it works fine

**Comment by twistor** [comment]
Does it get stuck if you provide an empty string?

**Comment by frankdejonge** [comment]
Closing this, it's most likely a phpseclib issue.
