### ISSUE TITLE
how to get local adapter upload root?

### ISSUE THREAD

**Issue by zplzpl** [thephpleague/flysystem#710]
i use local adapter.

            $adapter = new \League\Flysystem\Adapter\Local($root);
            $filesystem = new Filesystem($adapter);

how to get $root?

i view code , local adapter only get realRoot..

**Comment by frankdejonge** [comment]
If you already have the root, why do you need to retrieve it?

**Comment by zplzpl** [comment]
get it.

thank you for your job.
