### ISSUE TITLE
After 1.0.27 first caracter from file is removed

### ISSUE THREAD

**Issue by cristianvuolo** [thephpleague/flysystem#712]
![13241add984649a38f5a70f9cfbfa260](https://cloud.githubusercontent.com/assets/2281424/19519221/c7585e4c-95e9-11e6-96e1-9b5e89eff4c0.png)
![b13e41b911ab423299d6287e8f5cfa92](https://cloud.githubusercontent.com/assets/2281424/19519222/c765a61a-95e9-11e6-9655-aa1de469f7a3.png)

**Comment by frankdejonge** [comment]
@cristianvuolo do you know when this happens? We have a good number of tests proofing that how we handle filenames is correct.

**Comment by frankdejonge** [comment]
Also, which calls produce this error? This is not nearly enough information to do anything.

**Comment by cristianvuolo** [comment]
I'm using php artisan vendor:publish at laravel 5.3

version 1.0.27 works perfect, but 1.0.30 is broken.

**Comment by frankdejonge** [comment]
@cristianvuolo do you know which call produces the error? Not the console command but the actual call to flysystem?

**Comment by cristianvuolo** [comment]
@frankdejonge sorry I don't know, I'm only using this line on laravel to publish my migrations:

`$this->publishes([__DIR__ . '/../../resources/migrations/' => base_path('database/migrations')], 'migrations');`

**Comment by frankdejonge** [comment]
@cristianvuolo I found a bug in a PR from recently, 1.0.31 has just been tagged, could you see if that works for you?

**Comment by cristianvuolo** [comment]
@frankdejonge  same error :(

**Comment by frankdejonge** [comment]
Did you upgrade your laravel setup too?

**Comment by cristianvuolo** [comment]
@frankdejonge 1.0.28 works too, sorry by inaccurate info.

**Comment by cristianvuolo** [comment]
@frankdejonge 
![screenshot_1](https://cloud.githubusercontent.com/assets/2281424/19520734/f594b3d6-95ef-11e6-9515-085f87ef9684.jpg)

**Comment by frankdejonge** [comment]
@cristianvuolo did you update a laravel patch version?

**Comment by frankdejonge** [comment]
Because if you look here, there hasn't changed a lot, and what's changed is under test: [https://github.com/thephpleague/flysystem/compare/1.0.28...1.0.31](https://github.com/thephpleague/flysystem/compare/1.0.28...1.0.31)

**Comment by cristianvuolo** [comment]
@frankdejonge laravel is on latest version 5.3.19

**Comment by frankdejonge** [comment]
@cristianvuolo but did you update it?

**Comment by cristianvuolo** [comment]
no, the package only works on version 1.0.28 or less

**Comment by frankdejonge** [comment]
@cristianvuolo please be clear. Did you upgrade laravel? yes or no?

**Comment by cristianvuolo** [comment]
yes

**Comment by frankdejonge** [comment]
@cristianvuolo have you tried downgrading laravel to your previous version?

**Comment by cristianvuolo** [comment]
I downgrato to 5.3.10 and same error

**Comment by frankdejonge** [comment]
@cristianvuolo I've just created a new laravel project, updated flysystem, published a directory and a file from a service provider, everything works.

**Comment by cristianvuolo** [comment]
@frankdejonge You can try with my package? 

https://github.com/cristianvuolo/banners

**Comment by arcanedev-maroc** [comment]
@frankdejonge is related to Windows OS

You can reproduce this issue by checking this issue: https://github.com/laravel/framework/issues/15991

**Comment by frankdejonge** [comment]
@arcanedev-maroc @cristianvuolo I think I've got it, there was indeed a windows contents listing issue. I fixed that, tagged 1.0.32, could you check it out?

**Comment by arcanedev-maroc** [comment]
Thanks a lot @frankdejonge, work like a charm 👍

**Comment by frankdejonge** [comment]
Awesome, glad that's sorted. A bit difficult feedbackloop since I don't "windows".

**Comment by arcanedev-maroc** [comment]
Yeah, i know the struggle.
