### ISSUE TITLE
Flysystem Util/ContentFormatListing.php file have issue with child folder from dropbox.

### ISSUE THREAD

**Issue by ghost** [thephpleague/flysystem#717]
Hi,

This problem I'm facing from last year.

In Util Folder the file name ContentFormatListing.php at line 100 

you have below method.

```
/**
 * Check if the entry is a direct child of the directory.
 *
 * @param $entry
 *
 * @return bool
 */
private function isDirectChild(array $entry)
{
    return Util::dirname($entry['path']) === $this->directory; //this line not work for dropbox child folders, Please read below comments.  
}
```

with this line of code we can't get the child folder files listing. but if we put strtolower method before $entry['path']  like this strtolower($entry['path') === strtolower($this->directory) solve my issue but every time when composer update or new install it this settings removed just bcoz of getting new package. Now pleae advise what to d othere.

**Comment by twistor** [comment]
Sorry, Dropbox is no longer supported in Flysytem. There is a community supported version that you could bring this up to.
