### ISSUE TITLE
Laravel 5.3 Amazon S3 rename file problem

### ISSUE THREAD

**Issue by sunnyjayjay** [thephpleague/flysystem#722]
I get an error

```
FileNotFoundException in Filesystem.php line 385:
File not found at path: https:/s3-eu-west-1.amazonaws.com/artlookimages/1/items/3155.JPG
```

when trying to rename this file at S3. The file exists (copy the link above and view it to confirm) but the error is in the line which reads 

    assertPresent('https:/s3-eu-west-1.amazonaws.com/artlookimages/1/items/3155.JPG') 

I notice that the https: has only one slash after it. Could that be the problem and if so where is that coming from? If it's not the problem I need help! The files in the folder are set to "public" permissions.

**Comment by frankdejonge** [comment]
@sunnyjayjay looks like you're using the full path rather than the relative one. So without the domain and bucket you should only use `1/items/3155.JPG` as the path.

**Comment by sunnyjayjay** [comment]
Thanks. You are completely right, that solved it.

**Comment by frankdejonge** [comment]
👍
