### ISSUE TITLE
Can FlySystem read / write files from a separate server (not cloud)?

### ISSUE THREAD

**Issue by sunnyjayjay** [thephpleague/flysystem#723]
I want to have my images stored on a separate server to my app, so my app URL might be www.myapp.com and the images might be on www.myimages.com. How can I set flysystem config to handle this?

**Comment by barryvdh** [comment]
You could use https://github.com/thephpleague/glide with an FTP adapter.

**Comment by sunnyjayjay** [comment]
Is that the only way? I found Glide to be very slow and also I don't really want to have to use FTP. I was hoping to be able to define a disk by giving it a URL and valid authentication and then use it.

**Comment by barryvdh** [comment]
Why not use the other server directly? Using a cname or subdomain or whatever (media.myimages.com).

There is currently no HTTP Adapter, see https://github.com/thephpleague/flysystem/issues/253

**Comment by frankdejonge** [comment]
If somebody wants to contribute a http adapter, that would be 👍 though.

**Comment by frankdejonge** [comment]
@sunnyjayjay basically, the important part of this is not the flysystem stuff, what you want to look into is how do these servers communicate. Are the servers in the same network, maybe setup a filesystem mount and use that as the root. Or make sure that the one server writes to some cloud storage instead. It also depends on what your use-case is, which is not clear for me.

**Comment by sunnyjayjay** [comment]
My use case is that I am using S3 and Cloudfront for the images right now but I am finding performance issues. So I am thinking of creating my own image server instead. I don't want the images locally because the server disk will fill up too quickly. Essentially I am looking for a solution to overcome S3 performance issues with images.

**Comment by barryvdh** [comment]
An HTTP adapter probably won't help much, as it gives load on both servers. So why not setup your image server as static cdn and use that domain directly?

**Comment by frankdejonge** [comment]
@sunnyjayjay what does one of those request cycles look like?

**Comment by sunnyjayjay** [comment]
Not sure exactly what you want therein terms of request cycle but a real world image example is http://d8z37rm9cmbl3.cloudfront.net/1/items/FS_2937.JPG.

**Comment by twistor** [comment]
You can pipe output using https://github.com/twistor/flysystem-http, or https://github.com/twistor/flysystem-guzzle.

This is probably not what you want though. S3 and Cloudfront should be fast enough for most use-cases. Sounds like a configuration problem.
