### ISSUE TITLE
Proper way to create download links

### ISSUE THREAD

**Issue by Rikijs** [thephpleague/flysystem#727]
I have a problem with serving files that are uploaded to Flysystem endpoint. 
I asked this question also [on StackOverflow here](http://stackoverflow.com/questions/40643132/serving-files-for-download-with-symfony3-and-flysystem).
Upload works great  - problem is only with download.

At the moment I am using Local adapter, but sadly I did not see any `getObjectUrl`, `url` or `download` methods that would have aided me in this task.

Please advise.
Thank you for your time and knowledge.

**Comment by frankdejonge** [comment]
@Rikijs Hi, it depends on the adapter. Flysystem does not expose download URL's, mainly because the requirements and implications are fastly different per case. If you're using the local adapter you can just prefix the path with the publicly accessible url prefix, no "magic" needed there.

**Comment by Rikijs** [comment]
I see. You are suggesting I need to place serve-able files in the `web` directory of Symfony3 project.

At the moment I direct all the uploads to the 'data' folder in the root of the project (inaccessible from the web). So I would need to copy downloadable files to the ``web` directory (per file basis) and then acquire actual path leading to somewhere in the web folder.

**Comment by PatrickRose** [comment]
You could just stream the contents to the browser?

**Comment by Rikijs** [comment]
Indeed - streaming works from `data` directory in the root of the project. Thanks!
