### ISSUE TITLE
[RFC]Change return value of getTimestamp

### ISSUE THREAD

**Issue by zf2timo** [thephpleague/flysystem#728]
While developing a new feature i my application, I used the `getTimestamp` method to compare it with another Time stamp. 
I had some struggles with the condition, but in the end it worked as expected and my unit tests where green. Then i depolyed the feature to our staging system an testes the feature again and had completed different results than I expected.
So I take another look in the code and encountered that, the `getTimestamp` method don't return an integer or string but an array with additional information like name, size and so on.
This is an result which I would expect by calling a `getFileInformation` method.

For this reason I suggest to change the method and only return the time stamp and prevent other developer from being confused. Of course this is a BC break at can be done in the version 2.x.

If you like, I can create a PR

**Comment by frankdejonge** [comment]
@zf2timo looks to me like you've used an adapter directly instead of using the Filesystem class?

**Comment by zf2timo** [comment]
@frankdejonge yes, you're right. 
Thank you and Sorry to bother you.

**Comment by frankdejonge** [comment]
No worries @zf2timo
