### ISSUE TITLE
Local Adapter - Put method overwriting file

### ISSUE THREAD

**Issue by levidurfee** [thephpleague/flysystem#733]
I was using the Local Adapter with the Put method, and it kept overwriting the file. I expected it to append to the file if it already existed. Below is the code.

```php
<?php
include 'vendor/autoload.php';
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

$adapter = new Local(__DIR__.'/storage/files/');
$fs = new Filesystem($adapter);

$filename = date('Y-m-d').'.txt';

//$contents = $fs->read($filename); // I was reading the data and adding it to the message
$contents = '';

$message = 'hello';

$fs->put($filename, $message . "\n".$contents); // I appended the data with $conents
```

After looking into it, it appears I am able to pass write flags when creating the adapter. The code below will append to the file now.

```php
<?php
include 'vendor/autoload.php';
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

$adapter = new Local(__DIR__.'/storage/files/', FILE_APPEND);
$fs = new Filesystem($adapter);

$filename = date('Y-m-d').'.txt';

$message = 'hello';

$fs->put($filename, $message . "\n");
```

I'm fine with adding the write flag, but the docs made it sound like it wasn't needed.

**Comment by twistor** [comment]
`put()` doesn't append. It writes whether the file exists or not. `write()` only writes if the file does not exist, and `update()` only writes if the file exists.

**Comment by levidurfee** [comment]
Thank you for the clarification.
