### ISSUE TITLE
FTPAdapter error. Transfer complete

### ISSUE THREAD

**Issue by mikael-ohmy** [thephpleague/flysystem#736]
I get this error from time to time. I have failed to reproduce it with other clients. What I think I can see is when a successful transfer completes the connection is open and waiting for new files to send. The next file that is sent uses the same connection but receives a 226 transfer complete that is cached in the connection and cast the error. 

With Wireshark i can not see any ftp traffic at all after the first file is finished. So nothing is sent to the server when it is trying to send the second file.

I run version 1.0.32.

PHP 5.5.15

[2016-12-05 16:12:02] local.ERROR: exception 'ErrorException' with message 'ftp_fput(): Transfer complete' in /vendor/league/flysystem/src/Adapter/Ftp.php:210

**Comment by frankdejonge** [comment]
This seems to be a problem with the actual FTP servers giving out incorrect statuses, not really anything we can fix from Flysystem's side.

**Comment by mikael-ohmy** [comment]
@frankdejonge but shouldn't wireshark show some ftp traffic when sending the second file?
