### ISSUE TITLE
Doc for OwnCloud/NextCloud

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/flysystem#737]
Hi,

I almost hate to raise this as an issue but it did take me some hours to come back with an answer.  I was trying to find a flysystem adapter for owncloud / nextcloud since they appear to be gaining in popularity as personal/company cloud storage, but couldn't find one.  Only by stumbling on an old issue did it occur to me that the WebDAV adapter was the one to use for owncloud or nextcloud.

Can you perhaps adjust the README.md file to reflect that?

**Comment by Stelian** [comment]
@delatbabel you could do that yourself and it would be really helpful to all the other users. Just fork the repo and submit a PR with your findings.

**Comment by nckenn** [comment]
Anyone who succeeded using this? can you please share it with us :(

**Comment by NoelDeMartin** [comment]
Hey, I just suceeded in integrating Nextcloud using the WebDAV adapter :D. I'm not sure which part of the README or documentation is the best one to add this... For the time being, I'm leaving a comment. If someone can point me to the best place to document this, I'll be more than happy than open a PR.

In a nutshell, it works pretty much as you'd expect looking at the [Nextcloud WebDAV documentation](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#webdav-basics). But there were a couple of things that tripped me up; in particular I wasn't sure which parts of the url should go in the `baseUri` or in the path prefix.

This is the final working configuration:

```php
// Your nextcloud url.
$nextcloud = 'https://cloud.example.com';

// Username & Password.
// You can generate an application password in /settings/user/security,
// under "Devices & sessions"
$username = 'username';
$password = 'password';

// Folder you want to use within your Nextcloud storage.
$folder = 'Documents';

// Create adapter.
$client = new Client([
    'baseUri' => $nextcloud,
    'userName' => $username,
    'password' => $password,
]);
$adapter = new WebDAVAdapter($client, "remote.php/dav/files/$username/$folder/");

// Read a file.
// This will read the file at '/Documents/Example.md'
echo $adapter->read('/Example.md');
```
