### ISSUE TITLE
Local Adapter can't create directories when absolute path is given

### ISSUE THREAD

**Issue by ArminVieweg** [thephpleague/flysystem#739]
Because `$this->applyPathPrefix($dirname);` appends double backslash. 

Example:
```
C:\path\to\file => \\C:\path\to\file
```
Which is not a valid path and results with warning:

> PHP Warning:  mkdir(): Invalid argument in C:\path\to\vendor\league\flysystem\src\Adapter\Local.php on line 361

**Suggestion:** I would just don't apply path prefix on windows. For me this works.

Thanks for merging my PR, I'll attach.
~Armin

**Comment by twistor** [comment]
Absolute paths shouldn't be used in Flysystem. All paths are relative to the configured adapter root. The Local adapter prefix can be absolute, but any calls into it should be relative to the prefix.

**Comment by garygreen** [comment]
@twistor why? Absolute paths make perfect sense for local adapter I don't see why Flysystem needs to force you to do everything relative to a particular root path.

**Comment by frankdejonge** [comment]
@garygreen this is because it breaks the encapsulation guarantee it provides. It's easy to work around it by specifying `/` as the root. But breaking out of the root is not permitted by design.

**Comment by garygreen** [comment]
@frankdejonge Sometimes you don't always want to operate within root and as you say, you can get around it by specifying `/` as root but that doesn't translate to Windows very well. If you are use to interacting with absolute paths, which most people will be prior to using Flysystem, it's much easier to interact with the library by giving it a full path (particularly for the Local adapter) rather than having to strip out the path to where Flysystem wants the root to be.

To me, using everything relative to the configuration root file leads to uncertainty, I would prefer to be explicit in specifying paths but Flysystem by design is forcing you to be bound to be within a certain box.

**Comment by ArminVieweg** [comment]
Also on Windows you have no dedicated root, which embraces all drive letters. So how to copy a file from C:\ to D:\ using Flysystem (without creating a workarround symlink)

**Comment by twistor** [comment]
@garygreen 

> For example, if you find later on in your app you need access to one level above your root

That's an application level design. It's a security risk to allow arbitrary path traversal.

@ArminVieweg This is unfortunate I suppose. You can create a `MountManager` and move files between filesystems that way.

**Comment by garygreen** [comment]
> It's a security risk to allow arbitrary path traversal.

How is it a security risk? You either have access to a given path or you don't. If your app aribartarly allows for specifying the path where files are stored and that's a security risk, that's a vunerability in your app, not Flysystem. The root path thing for me should be more of a convenience than anything, but as noted it get's in the way when you want to use absolute paths - the path is still perfectly valid.

> This is unfortunate I suppose. You can create a MountManager and move files between filesystems that way.

Or to put it another way - "Screw you Window users!"

**Comment by twistor** [comment]
It's a security risk because the current design sanitizes paths and applications are built on that assumption. Sanitizing paths is surprisingly complex. Not having to worry about path traversal issues is a big deal.

Or to put it the way I said it,

>  You can create a MountManager and move files between filesystems that way.

**Comment by twistor** [comment]
> For example, if you find later on in your app you need access to one level above your root, you either a) change your config root path to be one above, but can no longer be certain that it won't break everything in your app, b) symlink to get around the restriction, c) don't use flysystem - neither options seem ideal to me.

You can just create another filesystem object and use that.
