### ISSUE TITLE
S3 adapter to many requests

### ISSUE THREAD

**Issue by AidasK** [thephpleague/flysystem#744]
https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L98

For s3 adapter `has` check should be avoided, because independent of its result, the same upload method is used to overwrite a file.
Removing this check can reduce upload time and can save some money.

**Comment by frankdejonge** [comment]
@AidasK have you looked into this: http://flysystem.thephpleague.com/performance/ ?

**Comment by AidasK** [comment]
Yes, and laravel ignores this, because it is using "put" method:
https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L98

I have looked at the code more deeply, and it looks like has method is much more painful than I thought, it creates two requests. One checks if file exists and other if directory exists. So we need 3 requests to upload a file. 
```php
    public function has($path)
    {
        $location = $this->applyPathPrefix($path);

        if ($this->s3Client->doesObjectExist($this->bucket, $location)) {
            return true;
        }

        return $this->doesDirectoryExist($location);
    }
```

**Comment by lukewaite** [comment]
Additionally, because we run a `doesObjectExist` against s3 before writing, this breaks the new object read-after-write consistency s3 provides.

> Amazon S3 provides read-after-write consistency for PUTS of new objects in your S3 bucket in all regions with one caveat. The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.

**Comment by AidasK** [comment]
So there is one benefit of checking if object exists before uploading it, but my application does not need that. I could reduce my expenses dramatically by removing these checks.

I think `disable_asserts` option should work for `put` method too.

**Comment by Edgpaez** [comment]
I would expect Laravel to pass config all the way down to the S3 adapter, right ? 
I think is doing so here: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Filesystem/FilesystemManager.php#L193

**Comment by franksl** [comment]
Hi,
Same problem with delete(), I think it should not call has() but could rely on client response.

**Comment by lukewaite** [comment]
@frankdejonge This should be closable now after https://github.com/thephpleague/flysystem/commit/fedd0e24ba2aa59521b2431dfaf2d8f1a6a70622
