### ISSUE TITLE
Expose StreamHasher::hash()

### ISSUE THREAD

**Issue by greg0ire** [thephpleague/flysystem#745]
I'm trying to get the hash of a file, and am planning to simply do the following : 

```php
$streamHasher = new StreamHasher('md5');
$streamHasher->hash($filesystem->readStream('my_file');
```

Is it safe though? `StreamHasher` does not seem to be part of the official api,  nor is it documented. If not, I'll problaby use https://github.com/emgag/flysystem-hash from  @maetthu

**Comment by frankdejonge** [comment]
@greg0ire it's not documented, but it's stable 👍

**Comment by greg0ire** [comment]
Thanks!
