### ISSUE TITLE
Symlinks created by flysystem? NO -- blame emacs! (PSA)

### ISSUE THREAD

**Issue by paxperscientiam** [thephpleague/flysystem#747]
Hello,

From time to time whilst developing, flysystem will throw an exception when it encounters a symlink pointing outside the root. That itself is as expected.

However, these symlinks are auto-generated and happen to have the same name as the view I'm editing.

Here is the error text:
````

Fatal error: Uncaught exception 'League\Flysystem\NotSupportedException' with message 'Links are not supported, encountered link at /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam//views/.#meta.php' in /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam/app/php/composer/league/flysystem/src/NotSupportedException.php:21 Stack trace: #0 /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam/app/php/composer/league/flysystem/src/Adapter/Local.php(425): League\Flysystem\NotSupportedException::forLink(Object(DirectoryIterator)) #1 /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam/app/php/composer/league/flysystem/src/Adapter/Local.php(274): League\Flysystem\Adapter\Local->normalizeFileInfo(Object(DirectoryIterator)) #2 /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam/app/php/composer/league/flysystem/src/Filesystem.php(270): League\Flysystem\Adapter\Local->listContents('', false) #3 /opt/local/apac in /opt/local/apache2/htdocs/www/sites/self/paxperscientiam.com/paxperscientiam/app/php/composer/league/flysystem/src/NotSupportedException.php on line 21
````

UPDATE (not edit):
So, I was just about to write that these anomalous symlinks are pointing to something like this: `cdr35@Prometheus.local.4798`. Basically, `[username]@[host].[PID]`.

After realizing that, in this case, `4798` is a PID and looking up the process corresponding to the PID in this instance, it turns out that it's emacs that's creating these symlinks. Why? I don't know yet.

So, this bug report is now a PSA! Hopefully, someone else will benefit from this info.

EDIT:

This is caused by emacs creating lockfiles. According to [this](http://stackoverflow.com/a/12974060), the feature can be turned off explicitly as of emacs 24.3.

````lisp
(setq create-lockfiles nil)
````

**Comment by frankdejonge** [comment]
There's nothing in flysystem that creates symlinks. So this is probably unrelated.

**Comment by frankdejonge** [comment]
For the record, we do throw that exception because symlinks break portability of consuming code when switching filesystems.

**Comment by paxperscientiam** [comment]
Hi @frankdejonge 

I think you misread my post -- it's a PSA that warns of a potential conflict between flysystem and emacs.

**Comment by frankdejonge** [comment]
👍

**Comment by frankdejonge** [comment]
Perhaps we can put something in the docs about this instead of having a GH issue floating around.

**Comment by paxperscientiam** [comment]
Title makes it clear that blame is with emacs. But I agree that a note
should be added.

Christopher

Sent from my iPhone

On Nov 22, 2017 10:31 AM, "Frank de Jonge" <notifications@github.com> wrote:

Perhaps we can put something in the docs about this instead of having a GH
issue floating around.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/flysystem/issues/747#issuecomment-346385046>,
or mute the thread
