### ISSUE TITLE
FTPS

### ISSUE THREAD

**Issue by eescalante** [thephpleague/flysystem#749]
Are there any way to upload a file to FTPS server?

I just found a few working php piece of code but it use CURL, i would like to try some filesystem native option, is it possible?

**Comment by frankdejonge** [comment]
Hi, you can use the SFTP adapter:  https://github.com/thephpleague/flysystem-sftp

**Comment by hooch** [comment]
FTPS != SFTP

**Comment by larsmyrup** [comment]
Hi @frankdejonge 
As @hooch points out - FTPS != SFTP. I'm currently having issues connecting to a FTPS server. If it really is possible to use the SFTP adapter, can you elaborate a bit on how?

Edit: trying to do an implicit FTPS connection.
