### ISSUE TITLE
will MountManager's copy throw exceptions?

### ISSUE THREAD

**Issue by Edgpaez** [thephpleague/flysystem#754]
From what I can tell copy (and hence move) uses `readStream` from the Adapter: 
https://github.com/thephpleague/flysystem/blob/master/src/MountManager.php#L194

And the adapters wouldn't raise exceptions but swallow them to boolean return values:
For FTP: https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Ftp.php#L403
For S3: https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L427
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L453

Right now I'm not getting any exceptions, as I would expect, but only having my download function silently failing. 

Should I be doing something like:
```php
if (! $mountManager->copy("remote://$remotepath", "local://$localpath")) throw new Exception('ERR')
```
instead?

If I happen to get `FALSE` from copy, there's no way for me to know _why_ it failed, right ?

**Comment by Stelian** [comment]
@Edgpaez, the copy method does all other checks beforehand and exceptions are thrown for manageable cases (file exists, is reachable, etc). The only case where a boolean is returned is where there is no data available (like using ftp_fget() which returns boolean).

Some clients like S3 might have a way to retrieve the exception from the client.

On the actual check, you can go with something like:

```php
if (false === $mountManager->copy("remote://$remotepath", "local://$localpath")) {
    throw new Exception('Error occurred while copying file, please retry.')
}
```

**Comment by Edgpaez** [comment]
Thank you for answering @Stelian. 

I'm not sure I follow, though. I was having a problem where the MountManager wouldn't complain when the instance running the code didn't have enough storage so it couldn't download the file.

If exceptions are thrown in some cases, shouldn't we try and throw exceptions in every case we _know_ things can go wrong?

Does this mean that for me to know if `copy`works I have to boolean check it?
