### ISSUE TITLE
Is createDir working right? 

### ISSUE THREAD

**Issue by iseth** [thephpleague/flysystem#756]
when I  call `$filesystem->createDir('abc/')` it creates the folder `./Array/abc/` , instead of making `./abc`

**Comment by twistor** [comment]
What adapter are you using? What does its configuration look like?

**Comment by iseth** [comment]
<?php
    date_default_timezone_set('America/New_York');


    require __DIR__ . '/vendor/autoload.php';
    
    $accessToken = "";
    $appSecret = "";
    

    use League\Flysystem\Dropbox\DropboxAdapter;
    use League\Flysystem\Filesystem;
    use Dropbox\Client;

    $client = new Client($accessToken, $appSecret);
    $adapter = new DropboxAdapter($client, [$prefix]);

    $filesystem = new Filesystem($adapter);
    
    
    var_dump($filesystem->createDir('/www'));

    $contents = $filesystem->listContents('', true);
    //var_dump($contents);
    foreach ($contents as $key => $value) {
        echo($value["path"]) . "\n";
    }
    
    
    ?>

**Comment by iseth** [comment]
`<?php
    date_default_timezone_set('America/New_York');


    require __DIR__ . '/vendor/autoload.php';
    
    $accessToken = "";
    $appSecret = "";
    

    use League\Flysystem\Dropbox\DropboxAdapter;
    use League\Flysystem\Filesystem;
    use Dropbox\Client;

    $client = new Client($accessToken, $appSecret);
    $adapter = new DropboxAdapter($client, [$prefix]);

    $filesystem = new Filesystem($adapter);
    
    
    var_dump($filesystem->createDir('/www'));    
    
    ?>`

**Comment by iseth** [comment]
thats all the code I have

**Comment by twistor** [comment]
I have tried to reproduce your error, with and without a prefix, and I cannot.

```php
$adapter = new DropboxAdapter($client, 'prefix');

$filesystem = new Filesystem($adapter);

$filesystem->createDir('thing1');
$filesystem->createDir('/thing2');
$filesystem->createDir('thing3/');
```

**Comment by iseth** [comment]
here's a demo https://youtu.be/SetCsgOJ2zk

**Comment by frankdejonge** [comment]
@iseth I can't view that video.

**Comment by iseth** [comment]
try again it should work now

**Comment by iseth** [comment]
@frankdejonge I pu it as unlisted instead of private lol

**Comment by frankdejonge** [comment]
@iseth isn't the dropbox API v1 phased out? This could be the issue with the SDK actually.

**Comment by iseth** [comment]
@frankdejonge is that what flysystem the dropbox adapter uses? is there any plan on updating the adapter?

**Comment by frankdejonge** [comment]
@iseth there are currently no plans for that because they're not updating their SDK :/

**Comment by iseth** [comment]
@frankdejonge there are some PHP community SDK's which are listed on their API V2 page.

**Comment by frankdejonge** [comment]
@iseth I'm aware of that, though I think it's best if somebody who's invested in using the dropbox adapter to pick this one up, create the adapter and send a PR to be included in the docs as possible adapters. I'm currently not using dropbox and my free time is limited, the interface is rather easy to implement. So I'd really like to invite the community around flysystem to pick this up.

**Comment by iseth** [comment]
@frankdejonge thanks for mentioning this this to them. I'm really thankful this is was an actual bug and not a glitch on my end. If its not to much of a hassle I might just try and do it my self.

**Comment by twistor** [comment]
@iseth This isn't a problem with the V1 API yet. It's not shutting down until June 28, 2017. I can successfully use it.

@frankdejonge I would be willing to take this over. Fine with moving the project as well.

**Comment by twistor** [comment]
@iseth I was able to find your problem. Prefix is a string, not a `[$prefix]`. In the docs the brackets mean it's an optional argument, not that it takes a list of a string.
