### ISSUE TITLE
No absolute paths on remote?

### ISSUE THREAD

**Issue by ArminVieweg** [thephpleague/flysystem#761]
Hey, I've got problems using Flysystem.
I'm using SFTP adapter and when I ->write() all given absolute paths are handled relative, within home directory.

Instead of writing to file `/var/www/html/test.html` it writes to `var/www/html/test.html`. The current directory is `~`, so all my files getting created in the wrong location.

When I check the responsible code:
https://github.com/thephpleague/flysystem/blob/master/src/Util.php#L105

It looks like, that it has never worked before. You explode the path and iteratre through the path parts. But when a part is empty you strip it. In the end you implode the path parts, but because you've removed empty part from beginning, to trailing slash appears.

So this method "normalizes" all absolute paths, to relative ones.
I'm just wondering, that I am the first one who recognizes this.

**Comment by frankdejonge** [comment]
@ArminVieweg all paths in Flysystem are always relative. This is because of portability purposes. You can set the root of the adapter to `/` which will result in effectively having absolute paths.

**Comment by frankdejonge** [comment]
In other words, yes this is by design.

**Comment by ArminVieweg** [comment]
Great! Thanks for this hint. I needed to add "root" setting, to SftpAdapter.

This works now:

```
    $adapter = new SftpAdapter([
            'host' => $server->getConfiguration()->getHost(),
            'port' => $server->getConfiguration()->getPort(),
            'username' => $server->getConfiguration()->getUser(),
            'password' => $server->getConfiguration()->getPassword(),
            'privateKey' => $server->getConfiguration()->getPrivateKey(),
            'timeout' => 10,
            'root' => '/'
    ]);
    $adapter->setDirectoryPerm(get('directory_permissions'));
    $filesystem = new Filesystem($adapter, ['disable_asserts' => true]);
```

**Comment by frankdejonge** [comment]
👍
