### ISSUE TITLE
Method to send ftp raw commands

### ISSUE THREAD

**Issue by razik440** [thephpleague/flysystem#762]
I have some problems with file list via ftp driver. The problem is in charset encoding with cyrillic symbols in files names. The problem with charset can be resolved by sending ftp raw command like 
```php
ftp_raw($conn_id,'OPTS UTF8 ON');
```
How can I send raw command via ftp driver in flysystem?

**Comment by frankdejonge** [comment]
You can retriever the connection through $adapter->getConnection();

**Comment by frankdejonge** [comment]
*retrieve (damn autocorrect)

**Comment by razik440** [comment]
From controller it's look like this
`Storage::disk('ftp')->getDriver()->getadapter()->getConnection()`
Maybe, there shorter way to get a connection?

**Comment by frankdejonge** [comment]
Not really, but its quite easy to create a custom accessor which would always perform that action.

**Comment by RubtsovAV** [comment]
@razik440 Hi. The Ftp adapter already have utf8 mode. For enable it in Laravel, you need do this:
```
Storage::disk('ftp')->getDriver()->getAdapter()->setUtf8Mode(true); 

// in case the connection is already established, we need reconnect it
Storage::disk('ftp')->getDriver()->getAdapter()->disconnect(); 
```

**Comment by RubtsovAV** [comment]
I hope that the Laravel team in the future will make possible to use additional options directly in the config.
