### ISSUE TITLE
FTP: "Warning: fclose(): supplied resource is not a valid stream resource"

### ISSUE THREAD

**Issue by pmarien** [thephpleague/flysystem#763]
Sometimes the "isConnected"-Method from the Ftp-Adpater triggers a php warning:
"Warning: fclose(): supplied resource is not a valid stream resource"
This error occurs in the try-catch block on Line 495. (File: src/Adapter/Ftp.php)
The used php version is 7.0.11.

**Comment by twistor** [comment]
Fixed. Thanks!

**Comment by craftpip** [comment]
Hello, This fix has not yet been released, when will it be released ?

**Comment by frankdejonge** [comment]
@craftpip I just released 1.0.36, should be available on packagist shortly.

**Comment by craftpip** [comment]
Awesome thanks !
