### ISSUE TITLE
Implemented method to get settings Array from instance Config

### ISSUE THREAD

**Issue by hghandri** [thephpleague/flysystem#768]
Hi,

Recently I needed to create an adapter to use an external API service.

There is no way to retrieve the configuration from a "Config" instance in Array format.
The SDK used does not know the "Config" class.

I think it would be nice to add a "toArray ()" method in the "Config" class.
What do you think ?

**Comment by frankdejonge** [comment]
@hghandri 👍

**Comment by frankdejonge** [comment]
Closing because no PR was created and exposing internals of a config object is generally advices against.
