### ISSUE TITLE
Using class MimeType in a new Flysystem Adapter

### ISSUE THREAD

**Issue by Hemant-Mann** [thephpleague/flysystem#770]
Hey Can I use MimeType class while developing a new Adapter because it is mentioned as internal in Class Doc

Class located at
`League\Flysystem\Util\MimeType`

**Comment by frankdejonge** [comment]
@Hemant-Mann it's meant to be used in Adapters, indeed.

**Comment by Hemant-Mann** [comment]
Okay Thanks for clarification @frankdejonge
