### ISSUE TITLE
help for gridfs connector setup

### ISSUE THREAD

**Issue by dipenpatel235** [thephpleague/flysystem#773]
i have installed below things

installed -  https://github.com/Studio-42/elFinder
installed -  https://github.com/barryvdh/elfinder-flysystem-driver
installed -  https://flysystem.thephpleague.com/adapter/gridfs/

Now not getting idea how i can configure adapter - gridfs  with elfinder config connector.
so please let me some guideline to make it working with gridfs

Thanks

**Comment by frankdejonge** [comment]
@dipenpatel235 this is an issue for the elfinder documentation.
