### ISSUE TITLE
wont read files with spaces.

### ISSUE THREAD

**Issue by craftpip** [thephpleague/flysystem#774]
Im using the FTP adapter for this
I get a not found error, when i try to read a file from the server that has a space in its filename.
My root path is `/`
listContents() or listContent('/') output:
```php
Array
(
    [0] => Array
        (
            [type] => file
            [path] => a.txt
            [visibility] => public
            [size] => 1
            [dirname] => 
            [basename] => a.txt
            [extension] => txt
            [filename] => a
        )

    [1] => Array
        (
            [type] => file
            [path] => b b.txt
            [visibility] => public
            [size] => 4
            [dirname] => 
            [basename] => b b.txt
            [extension] => txt
            [filename] => b b
        )

)
```

Trying to read the files.
```php
print_r($connection->read('a.txt')); // successful
```
```php
print_r($connection->read('b b.txt')); // League\Flysystem\FileNotFoundException [ Error ]: File not found at path: b b.txt
```

**Comment by frankdejonge** [comment]
@craftpip what kind of FTP server is it?

**Comment by craftpip** [comment]
I'm not sure about this, its shared hosting using cpanel.

**Comment by frankdejonge** [comment]
@craftpip did you try using the Ftpd adapter?

**Comment by craftpip** [comment]
Its either ProFTPD or Pure-FTPd, i saw the cpanel docs,
okay, checking Ftpd adapter.

**Comment by craftpip** [comment]
Checked Ftpd, that's also not working for me

**Comment by frankdejonge** [comment]
@craftpip is it possible to check with flysystem:master? Because there was just a (unreleased) PR what had to do with escaping spaces for Pure-FTPd.

**Comment by craftpip** [comment]
okay, testing it with master.

**Comment by frankdejonge** [comment]
Thanks, if that works I'll release the PR asap.

**Comment by craftpip** [comment]
Yes, it works when using master.

**Comment by frankdejonge** [comment]
@craftpip 1.0.37 should be available on packagist any minute now.

**Comment by craftpip** [comment]
Thanks man! 👍

**Comment by frankdejonge** [comment]
Welcome 👍
