### ISSUE TITLE
File stream uploads

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem#776]
I am using the Google Cloud Storage adapter for FlySystem, and it now apparently supports streaming to the "disk" rather then uploading to memory then dumping the file. 

However, it seems that when FlySystem is used with elFinder, via middleware, it has to upload to the server first, before streaming to GCS? 

Do you have any idea about how elFinder can support streaming to GCS via the GCS FlySystem Adapter?

**Comment by twistor** [comment]
This will require custom code, and is outside the scope of Flysystem.
