### ISSUE TITLE
Undefined offset: 0 error in the FTP adapter

### ISSUE THREAD

**Issue by wojtekn** [thephpleague/flysystem#784]
Hello,

I'm getting following error when I try using the FTP adatper:

     “Undefined offset: 0 (File: /vendor/league/flysystem/src/Adapter/Ftp.php , line 372)”

It's ```getMetadata``` method and affected code part looks as follows:

        if (preg_match('/^total [0-9]*$/', $listing[0])) {
            array_shift($listing);
        }

        return $this->normalizeObject($listing[0], '');

File which is checked by getMetadata method does not exist and FTP server returns "total 0" response. array_shift removes the only element from the array what breaks the code around return. Response from the FTP server looks as follows:

    << Date Time : 4/25/17 2:05:42 PM >>
    LIST -la
    150 ASCII mode  data connection for -la (IP HERE).
    total 0
    226 ASCII transfer complete.

**Comment by wojtekn** [comment]
As far as I see, it can be simply fixed by adding one more empty array check just before the return statement:

        if (preg_match('/^total [0-9]*$/', $listing[0])) {
            array_shift($listing);
        }

        if (empty($listing)) {
            return false;
        }

        return $this->normalizeObject($listing[0], '');

It's not really elegant, but fixes the issue. Let me know if it makes sense, I can submit PR.

**Comment by frankdejonge** [comment]
@wojtekn that check is actually already there, but then before that first if.

**Comment by frankdejonge** [comment]
@wojtekn ah, wait I see, now. Just a sec.

**Comment by frankdejonge** [comment]
@wojtekn I've fixed it differently and it's tagged as `1.0.39` which should be available on packagist any minute now.

**Comment by wojtekn** [comment]
@frankdejonge thanks, sounds great.
