### ISSUE TITLE
[FTP Driver] Support for implicit SSL

### ISSUE THREAD

**Issue by vladimir-yuldashev** [thephpleague/flysystem#785]
Hello,

current ftp implementation supports only explicit SSL and does not work with implicit SSL connection, which is by default uses 990 port. 

Also, there is no support for implicit SSL in PHP. Research gave me only solution using `curl`.

I can make pull request to make implicit SSL connection work using curl. Or community can provide another options?

**Comment by RubtsovAV** [comment]
I think that's a great idea. We need to write a completely FTP adapter based on the CURL. It's worth a try. Perhaps with it we will have less problems and easier to support.

**Comment by vladimir-yuldashev** [comment]
Should it be in current driver or something called like CurlFtpDriver?

**Comment by RubtsovAV** [comment]
By analogy with other adapters, I think it should be called CurlFtp. But I'm not project's owner. It's just my opinion.

**Comment by RubtsovAV** [comment]
And like the other adapters, it should extend of the AbstractAdapter.

**Comment by frankdejonge** [comment]
The adapter should indeed be called `CurlFtp` or `CurlFtpAdapter` which is more inline with the external ones. In the long term all the adapters will follow this naming convention, but there's no real benefit in renaming them now.

**Comment by RubtsovAV** [comment]
+1 on CurlFtp, because other adapters do not have "Adapter" at the ends.

**Comment by RubtsovAV** [comment]
@frankdejonge Do you mean it should be an external package?

**Comment by frankdejonge** [comment]
We can develop it here and then move it out to release it, because then we can specify the right deps here. While curl is not specific people have complained about the FTP adapter being released here because you can't express that you require the ftp extension for it.

**Comment by RubtsovAV** [comment]
Yea, perhaps, as an external adapter, he really would be better, but I think it is necessary that it was in the thephpleague repos. Then it will be have more trust and stable. )

**Comment by vladimir-yuldashev** [comment]
@frankdejonge I will make a pull request then.

**Comment by frankdejonge** [comment]
@vladimir-yuldashev cool 👍

**Comment by RubtsovAV** [comment]
And if it's like an external adapter, it's better to call it the `CurlFtpAdapter` (as other exetrnal adapters)

**Comment by vladimir-yuldashev** [comment]
So, I started to implement adapter. There are only two methods remained to implement: `setVisibility` and `getTimestamp`.

I request a feedback if I am on the right direction: https://github.com/vladimir-yuldashev/flysystem/blob/master/src/Adapter/CurlFtp.php

Also, there is no way to mock curl functions for unit testing. I can create `Curl` class which will be curl wrapper or include existing curl wrappers from composer or just ignore testing some methods.

Suggestions?

**Comment by RubtsovAV** [comment]
I not use CURL like FTP client - don't know. About mock of the CURL, check this http://stackoverflow.com/questions/7911535/how-to-unit-test-curl-call-in-php

**Comment by RubtsovAV** [comment]
What result in that code?
```
curl_setopt($this->curl, CURLOPT_CUSTOMREQUEST, 'LIST -aln '.$directory);
$result = curl_exec($this->curl);
```
I think,  it should be identical to `ftpRawList`.

**Comment by RubtsovAV** [comment]
`$this->createCurl();` should be in the connect() method.

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV 

> I not use CURL like FTP client - don't know. About mock of the CURL, check this

Thats exactly what I mean. 

> I think, it should be identical to ftpRawList.

Right.

**Comment by RubtsovAV** [comment]
> Right.
Then there must be a timestamp. Try to uncommenting a time in the `normalizeUnixObject()`, and then you can use `getMetadata()` for the `getTimestamp` method.

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV I tried to uncomment, but it's not so simple. Something FTP returns something like "Aug 5 2016", something "26 April 23:12"

**Comment by RubtsovAV** [comment]
Hm... Let's try that
```
curl_setopt($this->curl, CURLOPT_CUSTOMREQUEST, 'MDTM '.$path);
$result = curl_exec($this->curl);
```

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV I tried that, it returns just directory listing.

**Comment by RubtsovAV** [comment]
The `MDTM` command must returns the last-modified time of the given file on the remote host in the format "YYYYMMDDhhmmss": YYYY is the four-digit year, MM is the month from 01 to 12, DD is the day of the month from 01 to 31, hh is the hour from 00 to 23, mm is the minute from 00 to 59, and ss is the second from 00 to 59. 

Syntax: MDTM remote-filename

What ftp server you use?

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV I tried several ftp servers and none of them returned timestamp.

You can try for example public ftp server: speedtest.tele2.net

**Comment by vladimir-yuldashev** [comment]
I think I got `getTimestamp` work by tweaking `normalizeUnixObject` method. But I decided not to change parent because it may break other FTP drivers.

https://github.com/vladimir-yuldashev/flysystem/blob/master/src/Adapter/CurlFtp.php#L453

**Comment by vladimir-yuldashev** [comment]
Alright, guys. Seems like I finished. All methods, including `setVisibility` works.

What next?

**Comment by RubtsovAV** [comment]
@vladimir-yuldashev 
That must work for `getTimestamp`
```
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'MDTM '.$path);

$rawResponse = '';
curl_setopt($curl, CURLOPT_HEADERFUNCTION, function($ch, $string) use (&$rawResponse) {
	$length = strlen($string);
	$rawResponse .= $string;
    return $length;
});
$result = curl_exec($curl);

// reset all curl options for unset CURLOPT_HEADERFUNCTION
curl_reset($curl);

$lastRow = array_pop(array_filter(explode("\n", $rawResponse)));
list($code, $time) = explode(' ', $lastRow);
if ($code !== '213') {
	throw new RuntimeException("wrong response");
}

sscanf($time, "%4u%2u%2u%2u%2u%2u", $year, $mon, $mday, $hour, $min, $sec);
$timestamp = mktime($hour, $min, $sec, $mon, $mday, $year);
```
But after that we need to reset the curl options for unset `CURLOPT_HEADERFUNCTION`.

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV `curl_exec` returns `false`

**Comment by RubtsovAV** [comment]
Yes, and so had to use `CURLOPT_HEADERFUNCTION`. As you can see, the timestamp is taken from $rawResponse, which parsed from the callback function.

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV You rock! Now driver is totally ready. Expecting reply from @frankdejonge about further steps.

**Comment by RubtsovAV** [comment]
@vladimir-yuldashev Yea! :) Thanks . But what about unit tests?

**Comment by vladimir-yuldashev** [comment]
@RubtsovAV I am not sure if we can introduce `Curl` class into the main repository.

**Comment by frankdejonge** [comment]
@vladimir-yuldashev as @RubtsovAV mentioned, we first need to have some tests in place to test the adapter. I think in this case integration tests make sense, perhaps a docker based thing?

**Comment by RubtsovAV** [comment]
@vladimir-yuldashev Will be wait @frankdejonge ... Sorry for the tediousness, but maybe you'll add to the method connect this:
```
if ($this->isConnected()) {
    $this->disconnect();
}
```

**Comment by frankdejonge** [comment]
@RubtsovAV I don't understand your last comment.

**Comment by RubtsovAV** [comment]
While I write my message, you already came :) I already have case integration tests a docker based. You can see it there https://github.com/thephpleague/flysystem/pull/720 . But I don't undestand that why him failing a checks. I wrote it for the `Ftp` adapter, but I think it can be adapted for the `CurlFtp` also.

**Comment by vladimir-yuldashev** [comment]
@frankdejonge May be adding `docker-compose.yml` to root folder or to `tests` folder?

**Comment by vladimir-yuldashev** [comment]
@frankdejonge Also, phpunit seems to be outdated in composer.json. Can I update that?

**Comment by vladimir-yuldashev** [comment]
@frankdejonge I am not so proficient in docker, so I would like to introduce `Curl` class in `League\Flysystem\Util` namespace and use `Curl` object instead of `curl` functions. Will it suit?

**Comment by RubtsovAV** [comment]
@vladimir-yuldashev Let's do it as an external adapter? I can help with that. 

My skype: RubtcovAV

**Comment by vladimir-yuldashev** [comment]
So, we are developer external adapter with functional tests using docker.
It's already in composer and we just tagged v1.0.0.

Repository: https://github.com/vladimir-yuldashev/flysystem-curlftp
