### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by vladimir-yuldashev** [thephpleague/flysystem#786]
Hello,

What about updating PHP version of the library at least to 7.0?

**Comment by GrahamCampbell** [comment]
👎 I don't think there's any merit in arbitrary doing this. So:

1. Ok, if we update the version, that'll force people to upgrade to newer php, won't it? Well, no. It will mean that they are stuck on an old version of this package until they actually upgrade.
2. Ok, so people are on the old version, so we should probably give them security and bug fixes, so now we are maintaining two versions of the package, and for what reason, if all we do is bump the version, then use none of the features.

**Comment by vladimir-yuldashev** [comment]
Yeah, let's stay on the old PHP version, which is not supported from 21 July 2016.

**Comment by barryvdh** [comment]
Please don't break support for the sake of it. 5.6 still has security support for 1 year and 7 months; http://php.net/supported-versions.php

**Comment by vladimir-yuldashev** [comment]
@barryvdh But the library is on 5.5.

**Comment by frankdejonge** [comment]
Before this goes into a php version upgrade war. There's no real need now to up the version, the API is stable and uses mixed return types, so at this point in time it's not going to happen. When the next iteration comes along this decision will be re-evaluated. RL;DR: It's not holding us back and we don't gain anything by upgrading, so we won't. I'm a big fan of upgrading versions myself, but the backlash and doubled maintenance is not something I look forward too when we've got nothing to show for it.

**Comment by frankdejonge** [comment]
@vladimir-yuldashev I appreciate your feedback on the matter, and as soon as it makes sense I'll be the first to get that upgrade as far up as possible.

**Comment by vladimir-yuldashev** [comment]
@frankdejonge Your response looks kind and meaningful. Thanks.
