### ISSUE TITLE
Write utilises config but has/read does not

### ISSUE THREAD

**Issue by gabriel403** [thephpleague/flysystem#787]
This may be specific to what I'm trying to do, but when calling write/writeStream the Config object is created and passed through, this is then used by the adapters to pass further configuration along.

In my particular situation I'm using the aws s3 v3 adapter and then using server side encryption with client keys, by passing configuration to the constructor of AwsS3Adapter.
```
[
   'SSECustomerAlgorithm' => 'AES256',
   'SSECustomerKey'       => base64_encode(S3_ENC_PHRASE),
   'SSECustomerKeyMD5'    => md5(base64_encode(S3_ENC_PHRASE), true),
]
```

This works fine for writing files, however when we come to `has` or `read` the file back `has` always returns false, because the options aren't being passed along.

I can get it to work by tweaking the AwsS3Adapter changing the relevant line in `has` from

```
        if ($this->s3Client->doesObjectExist($this->bucket, $location)) {
            return true;
        }

```
to
```
        if ($this->s3Client->doesObjectExist($this->bucket, $location, $this->options)) {
            return true;
        }
```

and the relevant line in `readObject` from
```
        $command = $this->s3Client->getCommand('getObject', $options);
```
to
```
        $command = $this->s3Client->getCommand('getObject', $options + $this->options);
```

Is this something that needs changing in the aws-s3-v3 library as above or should it be something that changes in this main library to pass `Config  $config` through to all libraries on the has/read function? Updating the aws-s3-v3 library is probably the easiest solution, but is it the right one?

**Comment by frankdejonge** [comment]
@gabriel403 this could be a PR for the aws adapter. 👍

**Comment by gabriel403** [comment]
@frankdejonge https://github.com/thephpleague/flysystem-aws-s3-v3/pull/100
