### ISSUE TITLE
Possible to support a StreamInterface?

### ISSUE THREAD

**Issue by sean-uk** [thephpleague/flysystem#795]
Hi, I'm wondering if it would be possible to implement streaming using a high level stream interface such as the guzzlehttp/psr7 streams or hoa/stream.

This'd make custom functionality with streams simpler and more consistent. For instance, the native [`stream_get_meta_data` always reports user defined stream wrappers as seekable](https://secure.php.net/manual/en/function.stream-get-meta-data.php#115608), which is proving to be an issue for me!

I was going to fork and try to implement this myself, but perhaps you're already working on this? Or is there a reason I haven't thought of that it won't work?

Thanks!

**Comment by nash-ye** [comment]
It would be very helpful! :+1:

**Comment by sean-uk** [comment]
I'm having a go at this now! Here it is: https://github.com/sean-uk/flysystem

It's going off guzzlehttp/psr7, just because that was easier to get up and running with.
Trying to do this in a backwards compatible way so as not to create headaches for other adapter implementations.

Still experimental, and not tested in real world scenarios yet!

**Comment by faizanakram99** [comment]
Is this still an idea ?

**Valid use case:**
Write a file retrieved from a remote url as StreamInterface to some other location without killing server (out of memory error).

`FilesystemWriter::writeStream()` could accept StreamInterface as well (instead of just `resource`).

**Comment by ddzobov** [comment]
Any updates here?

**Comment by frankdejonge** [comment]
You can always use StreamInterface::detach to get the underlying resource. There is no need to bind an HTTP constructs to a filesystem abstraction.
