### ISSUE TITLE
Laravel File not found at path ?

### ISSUE THREAD

**Issue by shankhadevpadam** [thephpleague/flysystem#796]
I have problem while moving local file into dropbox.

i have configure Filesystem / Cloud Storage with dropbox adaptor which work successfully for 
```php
Storage::disk('dropbox')->put('file.txt', 'Hello laravel ');
```
But i get error while i am trying to move my local store file into dropbox
```php
Storage::disk('dropbox')->copy(public_path('test.txt'), 'text.txt');
```

Why i get error please give me some advice thanks.

**Comment by giftnuss** [comment]
copy works only inside of the adapter. If you need to copy a file from one adapter to another, you need to fetch the content or a stream from the source adapter and write this with the target adapter to the copied place.

**Comment by shankhadevpadam** [comment]
I have already fix the problem. Thanks for your support.

**Comment by windchime18** [comment]
How did you fix the problem? I am also having a hard time to move my files to another folder.
