### ISSUE TITLE
Missing mimetype attribute when using WebDav adapter

### ISSUE THREAD

**Issue by trylika** [thephpleague/flysystem#797]
When using WebDav adapter for flysystem, getting Mimetype results in error: `Undefined index: mimetype`

Applies to:
* league/flysystem v1.0.40
* league/flysystem-webdav v1.0.5

example code:
```
/** @var League\Flysystem\Filesystem $filesystem */
$filesystem->getMimetype($fileLocation);
```

this is due to two reasons:

1. `flysystem/src/Filesystem.php` not checking whether `mimetype` was returned in
https://github.com/thephpleague/flysystem/blob/3828f0b24e2c1918bb362d57a53205d6dc8fde61/src/Filesystem.php#L288

2. WebDav adapter does not return `mimetype` when fetching file's metadata
https://github.com/thephpleague/flysystem-webdav/blob/5fb6f5a45e5f2a5519a26032d98ad7d7c65f81d7/src/WebDAVAdapter.php#L367

**Comment by trylika** [comment]
no response?

**Comment by frankdejonge** [comment]
@trylika can you dump the webdav response? Btw, I recommend extending the webdav adapter for these kind of fixes. WebDAV is not nearly as standardized as I thought and it's impossible to account for all fixes.

**Comment by trylika** [comment]
@frankdejonge result returned from WebDAV was like this:
```
[
    'type' => 'file',
    'path' => '/foo/foo'/,
    'timestamp' => 'some date',
]
```
if you would look at the code link, you'll see that WebDAV adapter simply didn't returned `mimetype` field at all in all situations. And `Filesystem->getMimetype()` simply doesn't care if there is any `mimetype` returned which results in standard error mentioned above

**Comment by trylika** [comment]
as far as i can tell, current versions work the same

**Comment by frankdejonge** [comment]
This line checks if it's available tho: https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L284

**Comment by frankdejonge** [comment]
The webdav adapter accounts for mimtype, but only if in the raw response the 'content-type' field is set, which is the standard. I'm guessing the webdav server you're talking to doesn't return that. So extending the adapter is the way to go.
