### ISSUE TITLE
Handling special characters in path.

### ISSUE THREAD

**Issue by SamMousa** [thephpleague/flysystem#800]
This is probably just my lack of understanding, not a bug.

The documentation mentions, in `Core Concepts`, that all paths are relative. It ends the paragraph with:
````
Like the storage type, root paths are an implementation detail. 
When root paths are defined as configuration, the stability of your code improves.
````

From the filesystem perspective I understand that a root path is an implementation detail. For example, when I have an FTP backend, I specify the remote IP, username, password and path prefix.

Currently most of these are "enforced". Anything set on the adapter cannot be ignored by the filesystem, for example, I cannot read a file from a different FTP server. However, path prefixes are not enforced.

Consider a local file system, it is created like this:
````
$fs = new FileSystem(new Local('/somepath/share'));
````

I can't assume all files will be stored in that directory since the path used in an invocation might contains `..`:
````
$fs->write('../../etc/test', 'cool stuff', $config);
````

How the path is handled, is adapter specific, however to me it would make sense if adapters like `Local` do not allow paths outside their configured root.
Besides "escaping" from a configured root, I also think this has downsides with respect to portability.
````
Flysystem has a files first approach. Storage systems like AWS S3 are linear file systems, this means the path to a file is used as an identifier, rather than a representation of all the directories it’s nested in.
````

This assumption is not true for the `Local` adapter. There are an unlimited number of identifiers for each file. (I know technically it does not say that a file has only 1 identifier).
````
$fs->get('abc/../test') === $fs->get('abcd/../test');
````

Note that implementing something like the removal of occurences of `../` and `./` at the filesystem will break the above assumption for adapters that truly handle the path as an identifier, since `'abc/../test' !== 'abcd/../test'`.

I'm not sure if there is an actual problem, or what the solution would be...

**Comment by frankdejonge** [comment]
@SamMousa the path is normalized (so the traversal is removed) before it's used so it doesn't matter if you do `dirname/../something.txt` or `another_dirname/../something.txt` it'll both be normalized to `something.txt` before it's sent off to the adapters, this benefits cachability and allows is to detect when somebody wants to do path traversal, which is something we prevent.

**Comment by SamMousa** [comment]
Ah, I checked the adapters not the filesystem. Thanks!
