### ISSUE TITLE
FTP ADAPTER: Download files/folders  and Upload files/folders

### ISSUE THREAD

**Issue by myaot** [thephpleague/flysystem#801]
Hello Everyone,

I just want to clarify and know on how to download the files/folders in the FTP to local and upload the updated files/folders in the FTP. Anyone could help? 

I really appreciate it a lot your help. 

Btw, this is my current code: 
use Illuminate\Filesystem\FilesystemAdapter;
use League\Flysystem\Adapter\Ftp;
use League\Flysystem\Filesystem;

//the code
$filesystem = new FilesystemAdapter(new Filesystem(new Ftp([
            'host'     => 'host-name',
            'username' => 'host-username',
            'password' => 'host-password',
            'root'     => 'host-root',
            'passive'  => 'host-root',
        ])));

$items = $filesystem->listContents(null, true);

print_r(items);
OUTPUT:
Array
(

    [0] => Array
        (
            [type] => file
            [path] => index.html
            [visibility] => public
            [size] => 74
            [dirname] => 
            [basename] => index.html
            [extension] => html
            [filename] => index
        )

    [1] => Array
        (
            [type] => file
            [path] => keychain.php
            [visibility] => public
            [size] => 74
            [dirname] => 
            [basename] => keychain.php
            [extension] => php
            [filename] => keychain
        )

    [2] => Array
        (
            [type] => dir
            [path] => temp
            [dirname] => 
            [basename] => temp
            [filename] => temp
        )

)

$connection = $filesystem->getAdapter()->getConnection();
print_r(ftp_nlist($connection, '.'));
OUTPUT:
Array
(
    [0] => .
    [1] => ..
    [2] => index.html
    [3] => keychain.php
    [4] => temp
)

**Comment by twistor** [comment]
> I just want to clarify and know on how to download the files/folders in the FTP to local and upload the updated files/folders in the FTP. Anyone could help?

Can you explain this more clearly?
