### ISSUE TITLE
New normalizeRelativePath broke my remote path

### ISSUE THREAD

**Issue by Malin88** [thephpleague/flysystem#802]
Hi,
I use laravel 5.4.26 which use this package.
The last commit in `Util.php` broke my remote path to files when I trying to copy images.
When I paste `http://`, `normalizeRelativePath` method returns `http:/`

**Comment by twistor** [comment]
How are you using this?

The behavior you're describing is expected. Double slashes in a path normalize to a single slash.

**Comment by Malin88** [comment]
The `normalizeRelativePath` method is used by laravel `Storage::copy` method. I use this to get some images from external url like `http://some_image_url.jpg`.

**Comment by frankdejonge** [comment]
@Malin88 that's not what flysystem is for, you can just use file_get_contents or guzzle for that and either pass flysystem a stream or a string (from file_get_contents).

**Comment by Malin88** [comment]
Ok then, I will do this like you said. 

Thx ;)

**Comment by frankdejonge** [comment]
👍
