### ISSUE TITLE
Permission denied for fopen

### ISSUE THREAD

**Issue by Isengo1989** [thephpleague/flysystem#805]
: fopen(/var/www/XXXXX/webroot/files/Users/file/vtest.JPG.temp): failed to open stream: Permission denied [ROOT/vendor/league/flysystem/src/Adapter/Local.php]

I know it is an permission problem, I got it fixed by using chmod 777 for file folder, but I can use that in my Live enviroment. How can I fix the permission error? Did I miss a setting?

**Comment by frankdejonge** [comment]
👍

**Comment by zrshishir** [comment]
don't give permission to vendor file, give permission to your public directory.
