### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::putFile

### ISSUE THREAD

**Issue by ChrGriffin** [thephpleague/flysystem#807]
Hi,

I'm trying to use this with Laravel 5.4 to utilize Amazon S3 for storage. I read the docs (https://laravel.com/docs/5.4/filesystem), installed the dependency (`composer require league/flysystem-aws-s3-v3 ~1.0`), configured everything properly and tested it with this simple line:

```
Storage::put('test/test.txt', 'Testing!');
```

And it worked! I then moved on to the bit about streaming large files automatically by using `Storage::putFile()`. I gave it a try, providing a path to a file on my server to be uploaded, and... got the following error.

```
BadMethodCallException in PluggableTrait.php line 90:
Call to undefined method League\Flysystem\Filesystem::putFile
```

Should this method exist in Filesystem? Is the documentation on Laravel's side out of date and this doesn't exist anymore?

**Comment by frankdejonge** [comment]
That's not part of Flysystem and should be fixed ok Laravel's end. Perhaps it was added later?

**Comment by mh3720** [comment]
I'm having the exact same problem.

First, I tried `$request->file('foo')->save('myFiles')`, and then I tried `Storage::putFile('myFiles', $request->file('foo'))`.  Same result both ways.
