### ISSUE TITLE
FTP Server throws error while using has() method

### ISSUE THREAD

**Issue by patriziotomato** [thephpleague/flysystem#809]
Since I'm using the "has()" method very often in my application I'm realizing that the has() method is falling back to an getMetadata() in the FTP implementation. This one is using a

`if (@ftp_chdir($connection, $path) === true) {`

to early detect that the given $path is an directory before further checking file related things. By doing so, the FTP Server may/will throw an error while the client ignores the possible "error"-feedback once it's a folder.

![bildschirmfoto 2017-07-05 um 11 03 03](https://user-images.githubusercontent.com/544502/27857331-9029dafa-6171-11e7-9f4f-121540a42dac.png)

Nothing critical with our FTP Server is further happening, besides an endless error logfile which is quiet annoying. Since I read in #421 that this may cause other servers to strike, I would like to open this issue to improve the code.

It hopefully is possible to optimize the code so that no server side error is triggered while providing a similar performance and stability with various FTP server implementations.

**Comment by RubtsovAV** [comment]
@brainless81 Try this, please https://github.com/thephpleague/flysystem/pull/810
