### ISSUE TITLE
Function has() return 404

### ISSUE THREAD

**Issue by jglantonio** [thephpleague/flysystem#811]
Hi guys :

When i run my script , whit function `has` , this fail , return a 404 exception once true or false. This is strange.

````
/**
 * Check if an item exists by key.
 *
 * @param string $key
 *
 * @return bool
 */
 public function has($key)
 {
    if (array_key_exists($key, $this->settings)) {
         return true;
    }
    
 return $this->fallback instanceof Config
 ? $this->fallback->has($key)
 : false;
 }
````
## Problem

The function `has` return error 404 , when try connect to webdav.

### Solution one
The solution is version flysystem is the solution , upgrade the version whit composer.

### Solution two
Other solution is remove flysystem and reinstall whit composer.

**Comment by frankdejonge** [comment]
Hi, I don't understand this issue. You're referring to webdav, showing code from a config container and talk about fixing it by re-installing it. I don't have a clue what's going on.
