### ISSUE TITLE
Allow empty root path

### ISSUE THREAD

**Issue by garygreen** [thephpleague/flysystem#816]
I find this area of flysystem particularly problematic. I'm not the only one: #663, #761, #739, #698, #663, #661, #609 

At the moment, everything is forced to the root. If you want to store a file to an absolute path you can on unix by defining the root path as `/` - on windows your out of luck.

I would find the library so much more functional if you could operate on things from a non-root perspective from time to time, if needed.

```php
$filesystem->put('C:\absolute\path\test.txt', 'this path was automatically created as root option was empty');
```

**idea**
```php
$filesystem->put(new AbsolutePath('C:\absolute\path\test.txt'), 'this path was automatically created');
```

Or, couldn't anything starting with `/` or contains `:` be seen as absolute path?

**Comment by twistor** [comment]
This has been addressed in the referenced issues.
