### ISSUE TITLE
Recursive Directory Delete Support for FTP Adapter

### ISSUE THREAD

**Issue by aldee07** [thephpleague/flysystem#817]
Currently, the Ftp adapter doesn't support recursive removal of a directory.

```
    public function deleteDir($dirname)
    {
        $connection = $this->getConnection();
        $contents = array_reverse($this->listDirectoryContents($dirname));

        foreach ($contents as $object) {
            if ($object['type'] === 'file') {
                if ( ! ftp_delete($connection, $object['path'])) {
                    return false;
                }
            } elseif ( ! ftp_rmdir($connection, $object['path'])) {
                return false;
            }
        }

        return ftp_rmdir($connection, $dirname);
    }
```

This doesn't make sense if you really intend to delete the directory and all its content. I understand the limitation of `ftp_rmdir` function but it would be great to have such feature.

**Comment by twistor** [comment]
This looks like a problem indeed.

**Comment by twistor** [comment]
I think just deleting all the files first, then the directories would be enough, right?

**Comment by aldee07** [comment]
Thanks for looking into this. And yes, that could be an alternative. However, you have to connect to the ftp server multiple times just to achieve one goal. What do you think?

**Comment by twistor** [comment]
We're not really connecting multiple times. We're doing multiple calls on the connection. There's not a way to avoid it as far as I know.

**Comment by srmklive** [comment]
Can we get list of all directories in a specific directory and then delete those directories? To me deleting the files first & then directories seems like a real hassle.

**Comment by twistor** [comment]
@srmklive, what seems like a hassle about it? Did you look at the pull request?

We can list files and directories in a directory, but why when we can get a full listening?
