### ISSUE TITLE
How to upload folder with sub-folders to ftp?

### ISSUE THREAD

**Issue by abdullahseba** [thephpleague/flysystem#823]
Hi
I've been spending days trying to figure this out with no success.
How can I upload a complete folder with files and sub-folders? 
Or I can upload a zip but is there a way to extract it on the ftp server?
I tried this:
```
$stream = opendir($temp.'/content_server');
$filesystem->writeStream('/test', $stream);
closedir($stream);
```
but all I get is:
```
[02-Aug-2017 02:07:51 Europe/London] PHP Warning:  ftp_fput(): Invalid number of parameters. in C:\userfrosting4.1\app\vendor\league\flysystem\src\Adapter\Ftp.php on line 263
```
Tried `fopen` too and tho it works fine for folders I get a permission error even though it has all the permissions 
Thanks.

**Comment by frankdejonge** [comment]
For uploading directories you'll have to list a directory recursively and create all the files and directories.
