### ISSUE TITLE
Documentation lacks any code examples of how to actually get started with the library

### ISSUE THREAD

**Issue by samjarrett** [thephpleague/flysystem#826]
Hi guys,

I've used League for a while now, and suggested it to a colleague who almost immediately bugged me for an example of how to use it. I looked over your docs and noticed that there is no actual example of what object tree to create in order to actually use the library. 

Was wondering if this was an oversight or if we're both just blind?

Thanks!

**Comment by twistor** [comment]
https://flysystem.thephpleague.com/

There's docs for most adapters.

**Comment by beryllium** [comment]
I was able to get up and running, but examples like this could be built upon:

https://flysystem.thephpleague.com/adapter/aws-s3-v3/

One idea might be to have a single example/demo interface that allows you to select which adapter you want to see in action, and then auto-generate (client-side with JS?) a full top-to-bottom example of bootstrapping, writing data, and fetching data. Could be extra helpful for the ReplicateAdapter and variations of that nested-adapter concept.

**Comment by frankdejonge** [comment]
The docs got a major update and this should now be ok.
