### ISSUE TITLE
Local Adapter writeStream maxlength and offset params 

### ISSUE THREAD

**Issue by bratok** [thephpleague/flysystem#827]
Method writeStream of Local Adapter  has not config to set maxlength and offset params 

There are only resource and stream.

line 157 :  stream_copy_to_stream($resource, $stream);

**Comment by twistor** [comment]
Maxlength and offset params are optional, what is the problem?

**Comment by frankdejonge** [comment]
@bratok we only support resource and stream because those are supported cross platform, otherwise we'd have to recreate that across many more adapters, which is not the goal. If you want maxlength and offset then I suggest creating a trimmed stream before passing it to flysystem.

**Comment by bratok** [comment]
@twistor they are optional, but it is not mean that they are not needed 
why not do so
```
       $maxlength = $config->get('maxlength', -1);
        $offset = $config->get('offset', 0);

        stream_copy_to_stream($resource, $stream, $maxlength, $offset);
```
