### ISSUE TITLE
Bug with defaulting to s3 disk and using local disk, 

### ISSUE THREAD

**Issue by zRosenthal** [thephpleague/flysystem#830]
## Situation
* I am using Laravel with the flysystem for storing files in the cloud and locally.
* I currently store many files in S3, except for image preview thumbnails because we show 100s of them on a page at a time.
* I have the default disk set to S3.

I am accessing like this
```php
public function __construct(Illuminate\Contracts\Filesystem\Factory $storage) {
   $this->storage = $storage;
}

// later in code
$this->storage->disk('local')->get('img/path.jpg');
```

## Test I have ran
I have done all of these 10+ times each with very similar results each.
In each test the page loads properly and there are no errors.
* When I load the page with ~100 images it takes about ~24 seconds to render all images.
* If I remove the S3 secret key (set it to empty string) then load the same page it takes ~4 seconds to render all images.
  * Same result when removing the S3 access key
  * When removing the S3 bucket name I get a ~35 second load time.
* If I change the S3 access key or secret key or bucket name to something that is wrong (add character to it) I get a ~9 second load time
* If I set the default disk to `local` then load it takes ~3 seconds to render all images.

The images I am accessing are saved locally and not in s3.

Why does it take longer when using valid S3 credntials?
I can understand maybe a slight overhead ( < 1second) for using an S3 disk and a local disk
* which would explains the difference from defaulting to cloud with an empty access/secret key versus defaulting to local.
* but I cant understand the differences in the other cases.
I cannot figure out the reasoning behind this
### Potential Ideas:
* Since S3 is default when I use the factory it connects to S3 each time
* If it does not have valid credentials it tries to connect and fails, and does not try again

I have tested this repeatedly with the same results. 

Any ideas or solutions to this would be greatly appreciated, 3 seconds versus 24 seconds is a HUGE difference.
Thanks!

**Comment by zRosenthal** [comment]
Sorry this may be the wrong place for this, could be a laravel issue.

**Comment by frankdejonge** [comment]
This issue should be moved to the laravel repo.
