### ISSUE TITLE
SVG detection for somehow invalid images

### ISSUE THREAD

**Issue by NicoHaase** [thephpleague/flysystem#839]
Hi there,
since some months, we use your package. Today, we ran into an issue with SVG files that lack some parts for detection. Take for example the SVG found at https://icons8.com/icon/843/folder - it has no XML header, which causes finfo to return the mime type "text/plain". All major browsers are able to parse and display these files anyway.

Do you see any chance of implementing another check for such files? It could work the following way:
- getMimetype() calculates text/plain on first run
- file extension is ".svg"
- file can be parsed as XML
- return the mimetype image/svg+xml instead of text/plain

Regards
Nico

**Comment by NicoHaase** [comment]
According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829199, this is fixed in more recent versions of `file`.

**Comment by frankdejonge** [comment]
Hi @NicoHaase,

Thanks for bringing this to our attention. Unfortunately we can't fix those kind of bugs from within Flysystem. There are many of these issues, especially with finfo/mime-type related things, which would lead to an abundance of complexity in the package. My suggestion would be to handle this specific case in your app, preferably by encapsulating (or if needed extending the Filesystem) class.

**Comment by NicoHaase** [comment]
Frankly, this was the answer I expected :) As I found this bug fixed in more recent versions of `file`, I think it is acceptable to do a hot fix in our application. Thanks for your great work!

**Comment by frankdejonge** [comment]
@NicoHaase 👍
