### ISSUE TITLE
Inconsistency between FTP listing on windows and unix

### ISSUE THREAD

**Issue by insign** [thephpleague/flysystem#841]
I could make a PR to remove the comments at https://github.com/thephpleague/flysystem/blob/master/src/Adapter/AbstractFtpAdapter.php#L410

But I avoid make wrong PRs, sending before ask, so... Why are these vars ([at line 410](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/AbstractFtpAdapter.php#L410)) commented?

Unix servers (majority in the internet) do not comes with timestamp by default. But in [windows normalizer function](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/AbstractFtpAdapter.php#L447) it comes...

How could it be possible?

**Comment by frankdejonge** [comment]
The default response from unix servers had a date-time without a year, so it's practically useless. Windows does provide it, so we'll use it. It's a "best effort" kind of strategy. If we can use the output, fine. If not then an additional call needs to be made.

**Comment by insign** [comment]
Got it. So, to get the real timestamp needs to be one by one? Which is slowly...

**Comment by frankdejonge** [comment]
That’s correct, unfortunately. We’re limited by the output here. Nothing
we can do about it.

Op zo sep 24 2017, om 19:49 schreef Hélio:
> Got it. So, to get the real timestamp needs to be one by one? Which is
> slowly...> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/thephpleague/flysystem/issues/841#issuecomment-331726790

**Comment by insign** [comment]
Thank you, a comment in the code should help...

**Comment by beinbm** [comment]
Hi, 

with php >=7.2 we have a new command ftp_mlsd() to list a directory with all details we need. 
would it make sense that I add this as an alternative if available? 

1. https://secure.php.net/manual/en/function.ftp-mlsd.php
