### ISSUE TITLE
Plugin methods invisible to editor autocomplete

### ISSUE THREAD

**Issue by pbowyer** [thephpleague/flysystem#845]
Plugins using the plugin system are really easy to write, but the methods added are invisible to editor and IDE autocompletion. This is a problem, as team members forget them and occasionally the method name is misspelled, which can't be caught by automatic checking (as they all look like unimplemented methods).

Is there a work-around we have missed?

**Comment by frankdejonge** [comment]
@pbowyer Hi, the plugins are indeed not visible to IDE's, but there are ways to help IDE's with those "magic" completions. I suggest you look into those, they're the same for all the DI container packages, which have the same problem. Another way would be to extend the Filesystem instead. This was you can still use the plugin structure, but you can add a class level docblock which helps IDE's do autocompletion.

**Comment by pbowyer** [comment]
Thanks @frankdejonge I couldn't find the ways to help the IDE's with "magic" completions, so went the route of extending Filesystem, adding the class level docblock. Not ideal but does the job!
