### ISSUE TITLE
FTP Adapter Performance Improvements

### ISSUE THREAD

**Issue by ragingdave** [thephpleague/flysystem#850]
On using the FTP adapter I noticed that although ftp_rawlist will return all metadata about the file, we only parse and return a subset. In trying to get the timestamps using either Plugin available (getWithMetadata or listWith), the result is a very large slowdown since the adapter loads all the files, then queries for each metadata.

Upon initial inspection, listWith has logic to automatically skip querying a datasource if the key requested is already present. Given that, I purpose that at least for the ftp connections, parse out all the details we can. Specific to my reasons, this would include the timestamps, which I just noticed are parsed/populated for windows listings.

Are there other properties that should be returned? Is this even something that people want?

UPDATE: I might have jumped the gun here, and it seems the timestamp is SUPER unpredictable on linux/unix....

**Comment by frankdejonge** [comment]
Hi @ragingdave. All the metadata is returned in a "best effort" way. Everything we can derive from the result is returned, for anything not available we won't make subsequent calls to prevent extra calls per results. The timestamps returned from the basic FTP raw_list response doesn't include a year, therefor a timestamp cannot be reliably created from the response, rendering the output (month, day, hour, minute iirc) useless.

**Comment by ragingdave** [comment]
Yeah, I'll go ahead and close this. After some more looking into it, like you said, nothing additional can be reliably added.
