### ISSUE TITLE
Local adapter: getSize returns cached value when called multiple times

### ISSUE THREAD

**Issue by jkromski** [thephpleague/flysystem#853]
When you using Local adapter with a file which you use multiple times and you check size of that file then method getSize() returns first value which have been returned by getSize() method

calling getVisibility($path) solves it as getVisibility clears stat cache: clearstatcache(false, $path)

I guess it would be good to use clearstatcache in getSize too. If you got other solution please let me know.

**Comment by frankdejonge** [comment]
@jkromski seems like the way to go. Will you send a PR for this? Otherwise it's a small fix for me.

**Comment by jkromski** [comment]
give me few minutes

**Comment by jkromski** [comment]
#854 PR created

**Comment by twistor** [comment]
Seems like this conversation is over at the PR.
