### ISSUE TITLE
[WINDOWS] File not found if file name not latin chars

### ISSUE THREAD

**Issue by tr0yka** [thephpleague/flysystem#859]
laravel 5.4
"name": "league/flysystem",
"version": "1.0.41",

my fix:

where use `$path` need insert
`if(PHP_OS == 'WINNT'){
            $path = mb_convert_encoding($path, 'Windows-1251', 'UTF-8');
        }`

**Comment by frankdejonge** [comment]
Could you paste one of the paths you're using?

**Comment by tr0yka** [comment]
storage/uploads/301_редирект_для_3_страниц_по_офисам.docx

**Comment by frankdejonge** [comment]
You need to do this on your end before sending it to flysystem.

**Comment by tr0yka** [comment]
Working. But it's programming crutches.
