### ISSUE TITLE
flysystem in rabbitmq long life consumer auth error 401

### ISSUE THREAD

**Issue by kolyadin** [thephpleague/flysystem#865]
Hi all.
I have a php application (symfony3) with rabbitmq-bundle.
Also i have a long life consumer (several days).

I am using rackspace adapter and ovh cloud storage (https://www.ovh.ie/public-cloud/storage/object-storage/).

So, if my consumer working more than 24 hours, i see errors with 401 error code.
When i restart consumer no more errors for another ~24 hours.

How do you think, can it my because openstack auth mechanism has some timeout connection value?

**Comment by frankdejonge** [comment]
@kolyadin hi, this is a known "issue". Flysystem (or the adapter) won't become responsible for reauthentication, but I've helped somebody else out with this before, a solution to this problem can be found here: https://github.com/thephpleague/flysystem-rackspace/issues/22#issuecomment-336740744

**Comment by kolyadin** [comment]
Thanks
