### ISSUE TITLE
Externalize (make not internal) MimeType class maybe?

### ISSUE THREAD

**Issue by OJezu** [thephpleague/flysystem#868]
Because of problems with detecting mime type by contents (stupid jQuery having both doctype and html tag in sources), I've decided to detect mime type by file extension only, which seems a good enough approach for my needs. I've also found out that MimeType class has a nice API to do it, as Flysystem adapters fall back to extension-based detection in some cases.

But MimeType class is internal, which makes my IDE sad, and myself scared of API changes. Could it perhaps stop being internal, on merit of being quite useful? As I understand it is to be used in Adapters (as seen in #770), so I guess some BC guarantee should apply anyway.

**Comment by shahruslan** [comment]
I have the same question. I need to specify a different MimeTypeDetector. How to do it if the class is marked as @internal ?
