### ISSUE TITLE
Is there any way to get the free disk space on mounted filesystems?

### ISSUE THREAD

**Issue by nepda** [thephpleague/flysystem#872]
Hi there, first of all thanks for this great library!

I have not found yet a possibility to check the available disk space on mounted filesystems. Is there a good way to get information like this?

On a local adapter a PHP function like `disk_free_space` could be used.

**Comment by frankdejonge** [comment]
Hi, Flysystem is only a operational tool, it doesn't aspire to be a management tool. I suggest you use the available functions directly for whichever case it's applicable and available. From what I understand only local filesystems really have this. For example, S3, Dropbox, FTP and WebDAV don't support this.

**Comment by nepda** [comment]
Okay, thanks.
