### ISSUE TITLE
Best way to use getimagesize()

### ISSUE THREAD

**Issue by ghunti** [thephpleague/flysystem#874]
Hi.
I'm using the native PHP function [getimagesize](http://php.net/getimagesize) to get image dimensions. According to my understanding the method expects a stream path, so I'm wondering what's the best ways to use flysystem in this case.
Currently I'm doing:
```
$filePath = $filesystem->getAdapter()->applyPathPrefix(<file_path>);
list($width, $height) = getimagesize($filePath);
```
Is this the proper way to do it, or am I missing something?
Thanks

**Comment by frankdejonge** [comment]
Hi @ghunti,

Flysystem is meant to be used as purely a storage with portability in mind. This means sometimes when you're doing things locally it seems a bit weird. In this case your workaround is fine, but for cross adapter compatibility you'de have to loose the adapter specific behaviour. This means you'll first "download the file" ( which is just a copy action ) and then act on that file locally. In this case though that'd be much overkill becauce this works just fine for your current situation. My personal advice would be to store this code in a procedure class or function so IF needed later on you only have one location where you need to refactor this.

I hope this helps you out.

**Comment by ghunti** [comment]
Hi @frankdejonge 
I had thought about that "download file locally to act upon it" but as you said it seems overkill to my current needs. Glad I was on the right track ;)
Thank you for all the work you are doing!

**Comment by frankdejonge** [comment]
@ghunti 👍
