### ISSUE TITLE
Returns false.. How to get more data about not finding file?

### ISSUE THREAD

**Issue by mattCreative** [thephpleague/flysystem#875]
Sorry, I have no idea how to message anyone directly about this problem..

I am trying to use this integration with GoogleDrive to retrieve a file I have upload using this integration to Google Drive previously.

I have stored the Folder Path that is returned from `CreateDir()`, and I have stored the File Path that is returned when using `putFileAs()`, which I have verified to be the proper file path in Google Drive itself.

I have tried manually entering multiple variations of the file path to include and exclude parent directories, but I keep getting a false return, and I am unsure what I could be missing?

My implementation to put the file:
`$filePath = Storage::disk('user-drive')->putFileAs('', $request->file('file'), $filename);`

My implementation to retrieve the file:
`$metaData = Storage::disk('user-drive')->getAdapter()->getMetadata($filePath);`

I have also tried the above code, without `->getAdapter()`, but then it just throws a file not found laravel error.

https://github.com/thephpleague/flysystem/blob/2a12dff63eca980f103747935b6178862d9c88db/src/Filesystem.php#L353

**Comment by frankdejonge** [comment]
@mattCreative hi, we didn't built the Google Drive adapter perhaps you can ask the maintainer of that adapter? I didn't include a Google Drive adapter because it doesn't behave like a filesystem.
