### ISSUE TITLE
Flysytem removing whitespace from paths when reading file causes read errors on some files, e.g. MacOS Icon\r files.

### ISSUE THREAD

**Issue by OJezu** [thephpleague/flysystem#882]
We encountered an error, where when listing contents of Zip Archive with ZipAdapter, and opening all 
files, Flysystem raises an error when the archive contains a file with strange whitespace in path.

Our code does something not dissimilar to following:

```
$files = $filesystem->listContents('', true);
foreach ($files as $file) {
    if ($file['type'] === 'file') {
        $stream = $filesystem->readStream($file['path']);
    }
}
```

What happens in case of `Icon\r` files, is that readStream calls `Util::normalizePath` that strips the `\r` character from the path. As a result, filesystem tries to open non-existent file, and emits an error: `"File not found at path: data/Icon"`

While paths with caret returns in zip archives are stupid, the archives themselves are (probably) valid, and can be expected to contain such files when created on Mac OS X system, files can probably be also listed when Filesystem is using local filesystem adapter on Mac OS X.

Fix would be probably BC - dropping whitespace pruning when reading streams. IDK if that was implemented to offset some security issues, as checking for '..' in path was, so other "solution" could be warning about not supporting such files somewhere in documentation.

Another solution, that can however cause bugs and unexpected behaviour, would be not returning such strange files when returning list of filesystem contents.

More about elusive Icon\r files can be found here: https://superuser.com/questions/298785/icon-file-on-os-x-desktop

**Comment by frankdejonge** [comment]
What's your use-case?

**Comment by frankdejonge** [comment]
Just as a side note, in some cases filesystems act funny. But I tend to focus on real world use-cases, not the "I did some stuff for fun and something broke" situations. Correct me if I'm wrong, but it feels like this is just an experiment, not an actual issue for an application you're working on. Is that a correct assumption?

**Comment by OJezu** [comment]
Sending archive contents asynchronously to cloud. We have to do the upload itself within our code as Flysystem understandably does not support async uploads.

Synchronous uploads to Azure take way to long for us.

**Comment by frankdejonge** [comment]
I see, are you running this app on MacOS?

**Comment by frankdejonge** [comment]
And is that file a test file or actually something you want to support?

**Comment by OJezu** [comment]
No, but the archives themselves are usually created by MacOS users. This is a real-life archive we heave to support.

We are going to fix that by filtering out funny files before reading them, but the issue still remains, even if that will be no-fix or pr-welcome.

**Comment by OJezu** [comment]
Not stale maybe?

**Comment by OJezu** [comment]
@frankdejonge is this stale?

**Comment by frankdejonge** [comment]
Please provide a PR if you need this. It's not a common use-case for Flysystem. Currently, all non-standard filename whitespace is removed. If you can alter it in such a way that it'll preserve your case but still prevent path traversal, then the fix can go in. If not, it's not an option for the library since it'll break usage-bc in a non-acceptable way.

**Comment by OJezu** [comment]
I'm not pushing on this, as I said, we have a workaround, but I'm asking if it's ok to close this, although it was not fixed/documented.
