### ISSUE TITLE
New/improved Google Drive adapter

### ISSUE THREAD

**Issue by masbug** [thephpleague/flysystem#886]
Hi everyone,

I've made an adaptation of flysystem-google-drive adapter (by Naoki Sawada) which allows you to use normal paths instead of paths built from unique identifiers.

For example: "native google drive path" **/Xa3X9GlR6EmbnY1RLVTk5VUtOVkk/0B3X9GlR6EmbnY1RLVTk5VUtOVkk** becomes **/My Nice Dir/myFile.ext** and all ID handling is performed in the adapter (also with heavy built-in caching).

I also included a fix for Google_Http_MediaFileUpload which reduces used memory by using Psr7 streams.

Anyone interested can download the new implementation here:
https://github.com/masbug/flysystem-google-drive-ext

BR

**Comment by frankdejonge** [comment]
@masbug Hi, if you want you can send a PR to the readme to include this is the community supported packages. 👍
