### ISSUE TITLE
Slow connection to Pure-FTPd

### ISSUE THREAD

**Issue by dreadnaut** [thephpleague/flysystem#887]
I am using [PHPloy](https://github.com/banago/PHPloy), which is based on Flysystem, to connect to a server running Pure-FTPd. About a month ago I started seeing long delays on connection, above one minute.

The problem seems caused by the connection code in Flysystem, in particular to the _order_ of the commands issued around line 140 in `src/Adapter/Ftp.php`.
``` php
        $this->login();
        $this->setUtf8Mode();
        $this->setConnectionPassiveMode();
        $this->setConnectionRoot();
        $this->isPureFtpd = $this->isPureFtpdServer();
```
But if I move the Pure-FTPd check before the call that enables passive mode, everything works fine:
``` php
        $this->login();
        $this->setUtf8Mode();
        $this->isPureFtpd = $this->isPureFtpdServer(); // <--- moved here
        $this->setConnectionPassiveMode();
        $this->setConnectionRoot();
```

I wrote a couple of scripts to log timings. Unfortunately I don't have access to the server, so I cannot check versions or logs.
```
d:\var\www>php ftp-original.php
- Ftp::login() ran in 0.12s
- Ftp::setUtf8Mode() ran in 0.04s
- Ftp::setConnectionPassiveMode() ran in 0.04s
- Ftp::setConnectionRoot() ran in 0.08s
- Ftp::isPureFtpdServer() ran in 0.04s
- Ftp::isConnected() ran in 90.76s     <--- drama!

d:\var\www>php ftp-help-before-pasv.php
- Ftp::login() ran in 0.12s
- Ftp::setUtf8Mode() ran in 0.04s
- Ftp::isPureFtpdServer() ran in 0.04s
- Ftp::setConnectionPassiveMode() ran in 0.77s
- Ftp::setConnectionRoot() - ftp_chdir() ran in 0.04s
- Ftp::setConnectionRoot() - ftp_pwd() ran in 0.04s
- Ftp::isConnected() ran in 0.13s
```

I tried different orderings too, and `ftp_rawlist()` in `isConnected()` is not always the function timing out. It seems to be the first operation executed after the `HELP` command, if this is issued with passive mode enabled.

[edited to add details]

**Comment by frankdejonge** [comment]
Seems like this is a great candidate for a PR!

**Comment by dreadnaut** [comment]
The patch would fairly simple, but to be honest I'm not 100% sure of what is causing the issue here. It might be some server misconfiguration, or a specific version misbehaving.

I mainly posted here to see if anyone could reproduce it, but I'm happy to prepare the PR in the meanwhile 🙂

**Comment by dreadnaut** [comment]
Ok, maybe I got it now: the server does not support the `PASV` command. However, calling `ftp_pasv()` returns `true`, whether I set passive mode on or off. If I enable it, I get those timeouts, otherwise all works fine.

I'm tempted to say that the bug is in `ftp_pasv()` at this point, which should return `false` on failure. This is on PHP 7.1.11.

**Comment by frankdejonge** [comment]
@dreadnaut that would make more sense.

**Comment by tomzx** [comment]
@dreadnaut make sure that your FTP server passive ports are accessible and not firewalled.

It's likely that after you switched to passive mode your queries are now timing out (the call to `ftp_rawlist` in `FTP::isConnected()`.

**Comment by frankdejonge** [comment]
Is this issue still relevant?

**Comment by dreadnaut** [comment]
Probably not as originally stated. The issue turned out to be the php function [ftp_pasv()](https://php.net/ftp_pasv) in combination with the FTP server I was connecting to: the server _did not_ support passive mode, but the function does not to return `false` as documented. At that point Flysystem considers passive mode enabled, and successive connections time out.

The solution on my side was to disable passive mode in PHPloy (which also has an [issue with loading configuration flags](https://github.com/banago/PHPloy/pull/332)).

I don't think there's anything to be fixed in Flysytem, although the behaviour of `ftp_pasv` is still problematic.

**Comment by frankdejonge** [comment]
@dreadnaut gotcha. I'll close this issue then. FTP servers are a pain to work with, that's once again very obvious.

**Comment by banago** [comment]
Thanks @dreadnaut for providing a little fix for this annoying not-so-obvious bug. :100:
