### ISSUE TITLE
[Feature] add mimetype to local adaptor

### ISSUE THREAD

**Issue by ctf0** [thephpleague/flysystem#891]
is it possible to also include the file mimetype to the `getMetadata()` or even better `listContents()` ?

i know its not a big deal as its a local disk, but having it included will save the extra call for each file just to get its mimetype.

**Comment by ctf0** [comment]
it possible to be done by using the https://github.com/thephpleague/flysystem/blob/master/src/Plugin/ListWith.php

thanx so much for the awesome work.

**Comment by frankdejonge** [comment]
@ctf0 glad you figured it out! 👍 and thank you!

**Comment by ctf0** [comment]
@frankdejonge i wanted to ask you about the performance, does `listContents()` internally make a request for each item of the metadata or does it collect it on the first call ?

am asking because for some reason on my s3 bucket, whether i get the metadata one by one or use the `listContents()` the request time is the same.

**Comment by frankdejonge** [comment]
@ctf0 there's only one request for a listing, are you using an adapter cache?

**Comment by ctf0** [comment]
thanx for the fast reply & no not yet, am on laravel default , but am planning to retest with https://github.com/GrahamCampbell/Laravel-Flysystem

**Comment by frankdejonge** [comment]
Laravel-Flysystem is for older laravel versions I believe.

**Comment by ctf0** [comment]
its working up to 5.5 https://github.com/GrahamCampbell/Laravel-Flysystem/blob/24bcf45ccc61b6dae5211a58b672306e9f92864a/composer.json#L16

**Comment by frankdejonge** [comment]
What do you mean with "working" is something not working in newer versions? What adapter are yo using? The V2 or V3?

**Comment by ctf0** [comment]
i mean that you can use it if ur laravel version falls between 5.1 & 5.5, nothing related to flysystem though 👍

**Comment by ctf0** [comment]
@frankdejonge hi again, sorry for keeping jumping every now and then

i have a question about the memory caching, after some diving through the laravel implementation i found that it supports caching **memory caching to be exact** but its not documented,

however with testing i found that it doesnt work with aws "not sure it this is related to laravel or fs"
and on local disk it only cache the first level directory.

but i've built a custom disk of my own using the [Adapter Caching Setup](https://flysystem.thephpleague.com/caching/) and it works perfectly both ways, i cant even believe that the aws time dropped from 2.3mins to only 3.2sec after caching.

so the question is, what exactly is  `memory caching` and how does it work ?
