### ISSUE TITLE
[Suggestion] save persistent cache by adapter name

### ISSUE THREAD

**Issue by ctf0** [thephpleague/flysystem#892]
atm the cache adapter saves only the requested metadata but if you tried to switch the disk ex.`from local to s3` you are going to get the cached data of the old disk.

so is it possible for the cache to be saved under the adapter name, this way we can switch disks as we want and get the correct data.

**Comment by frankdejonge** [comment]
@ctf0 Hi, I think you ran into a Laravel problem rather than a Flysystem problem here. Disks are laravel specific things. Please open up an issue there.

**Comment by ctf0** [comment]
i have created a dynamic disk that adds cache and ListWith plugin to any disk/adapter & in this case they are local and aws so

```php
$fs           = config('flysystems.default'); // flysystems.default == local, s3, etc..
$fs['driver'] = 'ctf0';
config(['filesystems.disks.ctf0-media' => $fs]); // create new dynamic disk in laravel

Storage::extend('ctf0', function ($app, $config) use ($fs) {
    $userDisk = $app['filesystem']->disk($fs)->getDriver()->getAdapter();
    $local    = new Local(storage_path('framework/cache/media'));
    $cache    = new Adapter($local, 'file', 300); // 5 mins
    $adapter  = new CachedAdapter($userDisk, $cache);

    return (new Filesystem($adapter))->addPlugin(new ListWith());
});
```
