### ISSUE TITLE
[documentation] Please document the meaning of "public" and "private" permissions.

### ISSUE THREAD

**Issue by rulatir** [thephpleague/flysystem#893]
The Local adapter (and possibly others) takes a $permissions array that lists TWO kinds of permissions, "public" and "private", for both files and directories. I do not understand:

- what "public" and "private" means in this context
- when does Flysystem use one vs. the other
- whether I have any control of that

If this is explained somewhere in the docs, it would be nice if the explanation were hyperlinked to from every place that refers to these concepts. For example https://flysystem.thephpleague.com/adapter/local/ does not link to an explanation.

**Comment by juan88** [comment]
It would be nice to add examples to the docs as well.

Thanks!

**Comment by hit1205** [comment]
It's my first time to use the flysystem, I have the same question. After lookup the source of Local adapter, I think these are for setVisibility() when giving "public" or "private" in the argument.

**Comment by absolux** [comment]
Hello @rulatir,

> what "public" and "private" means in this context

The `public` and `private` visibilities are mapped internally to file permissions
https://github.com/thephpleague/flysystem/blob/611658dc9238501fcecb65ee9eadd31c285ecabe/src/Adapter/Local.php#L34-L43

> when does Flysystem use one vs. the other

visibility is optional, you chose which one during file system creation

> whether I have any control of that

[check the docs](https://flysystem.thephpleague.com/docs/usage/setup/index.html#global-configuration)

**Comment by mixisLv** [comment]
If visibility not set, file permissions  doesn't works!
