### ISSUE TITLE
FTP driver does not implement the has($path) function. Currently breaks FTP adapter.

### ISSUE THREAD

**Issue by kevinhamilton** [thephpleague/flysystem#898]
Note: moved this over from https://github.com/laravel/framework/issues/23246 where I thought it might be their issue. Copying my info here.

- Laravel Version: 5.5.34
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.5
- league/flysystem:  1.0.42

### Description:  

We FTP into a 3rd party FTP server, list files in a directory, then import the files listed. This process has worked great for a long time. We recently updated to Laravel 5.5 and php 7.2 from Laravel 5.4 and php 7.0. About that time this process stopped working.

### The code that breaks:
```
$files = Storage::disk('ftp')->allFiles('/outbound/edt');

foreach($files AS $file)
{
    $contents = Storage::disk('ftp')->get($file);

    ...
}
```

### If I dump out the $files I get a list of files that need to be imported. 

This indicates it's not a connection issue. I'm able to get a list of remote files.

``` 
array:12 [
  0 => "outbound/edt/ReceiveLog_20180205.log"
  1 => "outbound/edt/ReceiveLog_20180206.log"
  2 => "outbound/edt/ReceiveLog_20180207.log"
  3 => "outbound/edt/ReceiveLog_20180208.log"
  4 => "outbound/edt/ReceiveLog_20180209.log"
  5 => "outbound/edt/ReceiveLog_20180212.log"
  6 => "outbound/edt/ReceiveLog_20180213.log"
  7 => "outbound/edt/ReceiveLog_20180214.log"
  8 => "outbound/edt/ReceiveLog_20180215.log"
  9 => "outbound/edt/ReceiveLog_20180216.log"
  10 => "outbound/edt/ReceiveLog_20180219.log"
  11 => "outbound/edt/ReceiveLog_20180220.log"
]
```

### Error:

```
In FilesystemAdapter.php line 109:

  outbound/edt/ReceiveLog_20180205.log


In Filesystem.php line 386:

  File not found at path: outbound/edt/ReceiveLog_20180205.log
```

### Additional info
Note: I did try exists, with or without a leading forward slash (ex "/$file"). It returns false.

```
$exists = Storage::disk('ftp')->exists($file);
```

filesystems.php ftp config
```
        'ftp' => [
            'driver'   => 'ftp',
            'host'     => 'ftp.redacted-domain.com',
            'username' => '*****',
            'password' => '*****',
            'ssl'      => true,
        ],
```

### Update

Tracked it down to League\Flysystem\FileSystem.

``` 
    /**
     * @inheritdoc
     */
    public function read($path)
    {
        $path = Util::normalizePath($path);
        $this->assertPresent($path);

        if ( ! ($object = $this->getAdapter()->read($path))) {
            return false;
        }

        return $object['contents'];
    }
```

when League\Flysystem\FileSystem calls assertPresent($path), it will call has($path)

```

    /**
     * Assert a file is present.
     *
     * @param string $path path to file
     *
     * @throws FileNotFoundException
     *
     * @return void
     */
    public function assertPresent($path)
    {
        if ($this->config->get('disable_asserts', false) === false && ! $this->has($path)) {
            throw new FileNotFoundException($path);
        }
    }
```

This is what that League\Flysystem\FileSystem has() function looks like.  It will invoke the driver adapter's has($path) implementation.

``` 

    /**
     * @inheritdoc
     */
    public function has($path)
    {
        $path = Util::normalizePath($path);

        return strlen($path) === 0 ? false : (bool) $this->getAdapter()->has($path);
    }

```

which is not implemented in League\Flysystem\Adapter\Ftp. When you add that in, everything works fine. Of course this needs to be modified to actually look for the file's existence.

```
    public function has($path)
    {
        return true;
    }
```

Additionally, we can tell the system not to run asserts with this config change, even though it's not a desirable change.

```
        'ftp' => [
            'driver'   => 'ftp',
            'host'     => 'ftp.redacted-domain.com',
            'username' => '*****',
            'password' => '*****',
            'ssl'      => true,
            'disable_asserts' => true,
        ],
```

If you need anything else from me, let me know.

**Comment by kevinhamilton** [comment]
Thanks for the quick response @frankdejonge.

ftp_rawlist($connection, '/outbound/edt') output:

```
array:14 [
  0 => "total 1034"
  1 => "-rwxr-xr-x 1   10000           10000   18127   Feb 06 03:14 ReceiveLog_20180205.log"
  2 => "-rwxr-xr-x 1   10000           10000   48512   Feb 07 03:07 ReceiveLog_20180206.log"
  3 => "-rwxr-xr-x 1   10000           10000   16479   Feb 08 03:12 ReceiveLog_20180207.log"
  4 => "-rwxr-xr-x 1   10000           10000   16479   Feb 09 03:12 ReceiveLog_20180208.log"
  5 => "-rwxr-xr-x 1   10000           10000   13595   Feb 10 03:13 ReceiveLog_20180209.log"
  6 => "-rwxr-xr-x 1   10000           10000   15655   Feb 13 03:09 ReceiveLog_20180212.log"
  7 => "-rwxr-xr-x 1   10000           10000   47070   Feb 14 03:10 ReceiveLog_20180213.log"
  8 => "-rwxr-xr-x 1   10000           10000   18539   Feb 15 03:08 ReceiveLog__20180214.log"
  9 => "-rwxr-xr-x 1   10000           10000   14625   Feb 16 03:17 ReceiveLog_20180215.log"
  10 => "-rwxr-xr-x 1   10000           10000   14831   Feb 17 03:13 ReceiveLog_20180216.log"
  11 => "-rwxr-xr-x 1   10000           10000   27809   Feb 20 03:17 ReceiveLog_20180219.log"
  12 => "-rwxr-xr-x 1   10000           10000   45010   Feb 21 03:10 ReceiveLog_20180220.log"
  13 => "drwxr-xr-x 3   10000           10000   23      Feb 04 22:45 archive"
]
```

and output from ftp_systype()

```
UNIX
```

**Comment by frankdejonge** [comment]
It seems that your FTP server removes the expected directory item which is required to determine where we are (used for recursive listings too). So the problem is clear, the solution not so much tho. Also, is there any other information you can retrieve about the FTP server, "UNIX" basically only tells me it's not windows but Ftpd servers work differently too. Btw, did you try using the Ftpd adapter?

**Comment by kevinhamilton** [comment]
So I checked out getMetadata($path) like you said..


```

    public function getMetadata($path)
    {
        $connection = $this->getConnection();

        if ($path === '') {
            return ['type' => 'dir', 'path' => ''];
        }

        if (@ftp_chdir($connection, $path) === true) {
            $this->setConnectionRoot();

            return ['type' => 'dir', 'path' => $path];
        }

        $listing = $this->ftpRawlist('-A', str_replace('*', '\\*', $path));


        if (empty($listing) || in_array('total 0', $listing, true)) {
            return false;
        }

        if (preg_match('/.* not found/', $listing[0])) {
            return false;
        }

        if (preg_match('/^total [0-9]*$/', $listing[0])) {
            array_shift($listing);
        }

        return $this->normalizeObject($listing[0], '');
    }
```

I dumped $listing right after $this->ftpRawlist()

and this is my result


```

array:2 [
  0 => "total 0"
  1 => "-rwxr-xr-x 1   10000           10000   18127   Feb 06 03:14 /outbound/edt/ReceiveLog_SERF-4551_20180205.log"
]

```

right afterwards it checks for "total 0" and returns false.

```

        if (empty($listing) || in_array('total 0', $listing, true)) {
            return false;
        }
```

**Comment by frankdejonge** [comment]
Wait what? You server returns a total of 0 for a result-set of 1?

**Comment by frankdejonge** [comment]
Owwwww now i understand the first response. That's just the rawlist on a connection, not what we have in flysystem. Sorry, I probably wasn't clear enough, I did mean what you got back from within the Flysystem adapter.

**Comment by kevinhamilton** [comment]
Oh, ok. Yes the above result is from within League\Flysystem\Adapter\Ftp class. I just dumped $listing right ater this line:

```
$listing = $this->ftpRawlist('-A', str_replace('*', '\\*', $path));
```

Like I said I have no other access to this server. If there's a command that will give us any other information I can run it.

**Comment by kevinhamilton** [comment]
It's a very large company, I don't expect to be able to get an answer back very quickly, if I get any answer at all. I'll try though.

**Comment by frankdejonge** [comment]
For your specific case I suggest you extend the adapter and overwrite this function, remove the `total 0` check which should solve your problem. If I place this in Flysystem it could potentially break other people's programs. Since we can't determine your case specifically (no way to detect your FTP flavour) I feel like this is the best option. The FTP server you are talking to might be an exotic one. It's impossible to support all FTP adapters with one class (we already have an Ftpd extension for the same reason). I'm off to bed now. I hope this solves your issue for now (since you can extend the adapter), and I hope you understand why we can't just "fix" this.

**Comment by kevinhamilton** [comment]
Of course, not a problem. At least we know what's going on now. Thanks for your support! Have a good night.
