### ISSUE TITLE
Inconsistent handling of directories across adapters

### ISSUE THREAD

**Issue by kirkmadera** [thephpleague/flysystem#899]
Directories are second class citizens in Flysystem because not all filesystems support them in the same way. However, the methods has() and getMetadata() should still return consistent results.

Local Adapter:
has() on directory that exists: true
has() on directory that doesn't exist: false
getMetadata() on directory that exists: array
getMetadata() on directory that does not exist: exception

AWS S3 Adapter:
has() on directory that exists: true
has() on directory that doesn't exist: false
getMetadata() on directory that exists: false
getMetadata() on directory that does not exist: exception

Azure Blob Adapter:
has() on directory that exists: false
has() on directory that doesn't exist: false
getMetadata() on directory that exists: exception
getMetadata() on directory that does not exist: exception

These can be made to all return consistent results with some fairly simple wrapping code that makes use of listContents() which seems to have consistent behavior across adapters.

```php
/**
 * Overrode to deal with directories consistently across adapters
 *
 * @param string $path
 *
 * @return bool
 */
public function has($path)
{
    $path = Util::normalizePath($path);

    // Root path always exists. Skip the filesystem check
    if ('' == $path || '.' == $path) {
        return true;
    }

    if ($this->getAdapter()->has($path)) {
        return true;
    }

    // Deal with inconsistent adapter behavior.
    // Some adapters always return false for directories.
    // Check if this is an existing directory by checking if it exists in its parent's contents
    $parts = explode('/', $path);
    array_pop($parts);
    $parentPath = implode('/', $parts);

    foreach ($this->listContents($parentPath) as $parentContent) {
        if ($path == $parentContent['path']) {
            return true;
        }
    }

    return false;
}

/**
 * @param string $path
 *
 * @throws FileNotFoundException if file does not exist
 * @return array
 */
public function getMetadata($path): array
{
    $path = Util::normalizePath($path);
    $this->assertPresent($path);

    // Deal with inconsistent adapter behavior.
    // Some adapters will throw exceptions for directories; Some return false; Some return an array
    try {
        $metaData = $this->getAdapter()->getMetadata($path);
    } catch (\Exception $e) {
        // Do nothing
    }

    // If file exists, but returns no metadata, assume it's a directory
    if (empty($metaData)) {
        $metaData = [
            'type' => 'dir',
            'path' => $path,
        ];
    }
    return $metaData;
}
```

This results in all of the above three adapters returning these consistent results:
has() on directory that exists: true
has() on directory that doesn't exist: false
getMetadata() on directory that exists: array
getMetadata() on directory that does not exist: exception

If we really want to say directories are second class citizens and that has() should only work for files, then the LocalAdapter should be updated to return false on all directories. Adapters should be considered invalid if they don't conform to a defined behavior.

I'd strongly vote for making has() and getMetadata() actually work with directories consistently though. The alternative makes for really awkward code throughout the rest of your codebase.

**Comment by frankdejonge** [comment]
The has method is only reliable for files, which is the case across filesystems. Users should not use `::has` to check is dirs exist. Additionally Flysystem is build around the notion that directories don't even have to exist. The `getMetadata() on directory that exists: exception` seems like a bug. But other than that the guarantees flysystem makes are very loose for directories and are so by design.

**Comment by kirkmadera** [comment]
Thanks for the quick response. I've experienced that not being able to rely on has() makes for really awkward code though like this.

```php
// Get metadata. Some file adapters will return info for dirs, some will return false, and some will
// throw an exception
try {
    $metaData = $filesystem->getMetadata($path);
} catch (\Exception $e) {
    // Do nothing
}

if (empty($metaData)) {
    $metaData = [
        'type' => 'dir',
        'path' => $path,
    ];
}

$isFile = ('file' == $metaData['type']);
if ($isFile) {
    $hasFile = true;
    $contents = null;
} else {
    $hasFile = $filesystem->has($path);
    $contents = $filesystem->listContents($path, $input->getOption('recursive'));
}

if (!($hasFile || $contents)) {
    if (!$hasFile && false !== strpos($path, '/')) {
        $parentPath = preg_replace('%(.+)/[^/]+%', '$1', $path);
        $parentContents = $filesystem->listContents($parentPath);
        if ($parentContents) {
            foreach ($parentContents as $parentContent) {
                if ($path == $parentContent['path']) {
                    $tableOutput->render();
                    return 0;
                }
            }
        }
    }
    throw new Exception\RuntimeException("Path \"$path\" does not exist.");
}

// At this point, now I know whether the file/dir exists and I have the metadata
```

This is taken from an ls command I wrote which lists file or directory contents using Flysystem. I want to be able to let the user know whether the directory exists as opposed to being empty. With the existing behavior of Flysystem, this is only possible as far as I have found with the above code.

Compare https://github.com/conductorphp/conductor-core/blob/7269ea449edfa4db3377931468021af0ca0e1913/src/Filesystem/Command/FilesystemLsCommand.php#L89 to https://github.com/conductorphp/conductor-core/blob/67cdd725cfd131282dd2e8fc5f842a647c05640e/src/Filesystem/Command/FilesystemLsCommand.php#L94

**Comment by frankdejonge** [comment]
For me the question would be: what problem does knowing if a directory exist solve? 99 out of a 100 times is does not solve a problem people actually have. Cloud storage systems in general don't even have directories. This way of handling filesystem is a paradigm switch though. When you design programs in a deterministic way (so your program knows where the files should be) then directories don't matter anymore. Grouping can be achieved by using a common prefix (which translates to directories on non-cloud filesystems).

**Comment by kirkmadera** [comment]
My main use case here is the ability to provide user feedback when they enter a directory name wrong. Without being able to check if it exists, all we can tell the user is that listContents() returned empty for the requested prefix. But was it empty because it's actually empty or was it empty because it's a typo.

**Comment by twistor** [comment]
```
    // Deal with inconsistent adapter behavior.
    // Some adapters will throw exceptions for directories; Some return false; Some return an array
    try {
        $metaData = $this->getAdapter()->getMetadata($path);
    } catch (\Exception $e) {
        // Do nothing
    }

    // If file exists, but returns no metadata, assume it's a directory
    if (empty($metaData)) {
        $metaData = [
            'type' => 'dir',
            'path' => $path,
        ];
    }
    return $metaData;
```

That code is an immediate non-starter. It will swallow all sorts of adapter-related exceptions.

```
    // Deal with inconsistent adapter behavior.
    // Some adapters always return false for directories.
    // Check if this is an existing directory by checking if it exists in its parent's contents
    $parts = explode('/', $path);
    array_pop($parts);
    $parentPath = implode('/', $parts);

    foreach ($this->listContents($parentPath) as $parentContent) {
        if ($path == $parentContent['path']) {
            return true;
        }
    }

    return false;
```

The performance implications of this also make it a no-go.

It's hard to say without knowing know what your application is, but why make a user type in a correct directory name? Why not offer them a choice of directories?
