### ISSUE TITLE
Support append for adapters that support it

### ISSUE THREAD

**Issue by judgej** [thephpleague/flysystem#90]
I may just be missing this completely, but I cannot see a way to append to an existing file. Operations only allow files to be overwritten completely.

Some storage locations would not support appending (e.g. FTP) but some would (e.g. local). Being able to append it vital for being able to write to log files.

Just like different stream wrappers have different levels of support for some operations (e.g. some may support seek, some may not) is this something that would be acceptable to the adapters?

**Comment by jrondorf** [comment]
Will this feature request be implemented in future?

**Comment by frankdejonge** [comment]
@judgej it's highly unlikely.

**Comment by judgej** [comment]
Or even @jrondorf ;-) Can't even remember what I was working on at the time that needed this. But I guess the offer of accepting a PR is still open if someone needs it enough?

**Comment by frankdejonge** [comment]
At this point in time I'm not open to the PR because it's impossible to efficiently get it to work across filesystems and all cases I've seen where appending (or merging files) is needed are cases where that should be done locally, not in a filesystem level.

**Comment by jrondorf** [comment]
@frankdejonge fully understandable. Will use normal file access then.
