### ISSUE TITLE
Incorrectly caught Exception

### ISSUE THREAD

**Issue by marinus-kegstar** [thephpleague/flysystem#901]
Hi

Looking at my logs, I see an uncaught ErrorException. However, when I look at the code in src/Adapter/Ftp.php I see an attempt is made to catch this.

```
    public function isConnected()
    {
        try {
            return is_resource($this->connection) && ftp_rawlist($this->connection, '/') !== false;
        } catch (ErrorException $e) {
            if (strpos($e->getMessage(), 'ftp_rawlist') === false) {
                throw $e;
            }

            return false;
        }
    }
```

The ErrorException is thrown by the ftp_rawlist function, and the message is `ftp_rawlist(): php_connect_nonb() failed: Operation now in progress (115)`. This is not caught by the try/catch block.

I suspect the issue is an incorrect namespace, perhaps `catch (\ErrorException $e)` would rectify this?

Thank you

**Comment by frankdejonge** [comment]
@marinus-kegstar hi, the error exception is imported at the top. So this is effectively the same at adding a `\`. Could you verify in the stack trace it's rethrown there?

**Comment by marinus-kegstar** [comment]
hi @frankdejonge, thank you for the quick response. I saw the use statement at the top, however it does not have the leading backslash either. I confirmed again in my logs, the exception is definitely thrown by the ftp_rawlist function (line 532), and is not rethrown by that statement in the catch block.

**Comment by frankdejonge** [comment]
@marinus-kegstar the use statement is always from global, no `\` needed. If it's not rethrown by the catch block than you probably have a mechanism that converts errors into exceptions, which is not something we can fix from within flysystem. To be sure, can you share a stack-trace?

**Comment by marinus-kegstar** [comment]
Hi @frankdejonge, yes I have a stack-trace.

```
ErrorException: ftp_rawlist(): php_connect_nonb() failed: Operation now in progress (115)
#21 xxx/vendor/league/flysystem/src/Adapter/Ftp.php(532): handleError
#20 xxx/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): ftp_rawlist
#19 xxx/vendor/league/flysystem/src/Adapter/Ftp.php(532): isConnected
#18 xxx/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(579): getConnection
#17 xxx/vendor/league/flysystem/src/Adapter/Ftp.php(562): ftpRawlist
#16 xxx/vendor/league/flysystem/src/Adapter/Ftp.php(395): getMetadata
#15 xxx/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(539): has
#14 xxx/vendor/league/flysystem/src/Filesystem.php(57): has
#13 xxx/vendor/league/flysystem/src/Filesystem.php(385): assertPresent
#12 xxx/vendor/league/flysystem/src/Filesystem.php(179): read
#11 xxx/src/Warehouse/Sync/SyncDriver.php(41): sync
#10 xxx/src/Warehouse/Sync/Sync.php(45): in
#9 xxx/src/Warehouse/Sync/Sync.php(31): run
#8 xxx/src/Command/WarehouseSyncCommand.php(22): execute
#7 xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): run
#6 xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): doRunCommand
#5 xxx/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): doRunCommand
#4 xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): doRun
#3 xxx/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): doRun
#2 xxx/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php(45): doRun
#1 xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): run
#0 xxx/app/console(30): null
```

I see the second last item in the trace is Sentry, and it may be doing a conversion as you suggested. I'll do a further investigation my side. Thank you for your help.

**Comment by frankdejonge** [comment]
👍
