### ISSUE TITLE
Getting Issue related to permission while converting images

### ISSUE THREAD

**Issue by avanisolanki** [thephpleague/flysystem#903]
Hello, I am using laravel media library to manage media conversation. When I upload any image It's getting loaded as the queue to convert media is getting failed with below error.

ErrorException: mkdir(): Permission denied in /var/www/html/xevo/vendor/league/flysystem/src/Adapter/Local.php:367Stack trace:#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mkdir(): Permis...', '/var/www/html/z...', 367, Array)#1 /var/www/html/xevo/vendor/league/flysystem/src/Adapter/Local.php(367): mkdir('/var/www/html/z...', 493, true)#2 /var/www/html/xevo/vendor/league/flysystem/src/Filesystem.php(262): League\Flysystem\Adapter\Local->createDir('13/conversions', Object(League\Flysystem\Config))#3 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(593): League\Flysystem\Filesystem->createDir('13/conversions')#4 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Filesystem/DefaultFilesystem.php(152): Illuminate\Filesystem\FilesystemAdapter->makeDirectory('13/conversions/')#5 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Filesystem/DefaultFilesystem.php(42): Spatie\MediaLibrary\Filesystem\DefaultFilesystem->getMediaDirectory(Object(Spatie\MediaLibrary\Media), true)#6 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(92): Spatie\MediaLibrary\Filesystem\DefaultFilesystem->copyToMediaLibrary('/var/www/html/z...', Object(Spatie\MediaLibrary\Media), true)#7 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Support/Collection.php(337): Spatie\MediaLibrary\FileManipulator->Spatie\MediaLibrary\{closure}(Object(Spatie\MediaLibrary\Conversion\Conversion), 0)#8 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(95): Illuminate\Support\Collection->each(Object(Closure))#9 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(Spatie\MediaLibrary\Media))#10 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()#11 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#12 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#13 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#14 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#15 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)#16 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))#17 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))#18 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))#19 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)#20 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)#21 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()#22 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))#23 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))#24 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'media', Object(Illuminate\Queue\WorkerOptions))#25 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'media')#26 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()#27 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#28 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#29 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#30 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#31 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)#32 /var/www/html/xevo/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#33 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#34 /var/www/html/xevo/vendor/symfony/console/Application.php(938): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#35 /var/www/html/xevo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#36 /var/www/html/xevo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#37 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#38 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#39 /var/www/html/xevo/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#40 {main}

Can anyone please help?

**Comment by avanisolanki** [comment]
I tried to give permission 777 to the application folder still it's not working.

**Comment by frankdejonge** [comment]
@avanisolanki it looks like the user that handles the web requests is not the same as the user that handles the queue. This user doesn't have the right permissions to write in the directory.

**Comment by frankdejonge** [comment]
This is an issue with how you setup your environment (users/persmissions) not an issue with Flysystem. PHP can't create the directory because of these issues. You need make sure they have the correct permissions or belong in the correct group. If you're using something like supervisor you can set the user to the same user FPM uses (if you use php-fpm) which should fix the issue.

**Comment by avanisolanki** [comment]
User mentioned in Supervisor configuration is the same who is requesting.
Moreover the same is working in local environment but not working in staging environment.

In staging it's getting failed
![selection_002](https://user-images.githubusercontent.com/37375055/37458837-45266010-286c-11e8-99f4-b1ceea972c41.png)

**Comment by frankdejonge** [comment]
@avanisolanki I suggest you open an issue with either Laravel or the Laravel Horizon for this. I don't know enough about the internals to help you, sorry.

**Comment by avanisolanki** [comment]
@frankdejonge  Thank you for your support.

**Comment by frankdejonge** [comment]
👍 good luck!

**Comment by avanisolanki** [comment]
Hi @frankdejonge ,
I have query for the same issue. spatie/laravel-medialibrary using thephpleague/flysystem internally.
And My laravel application is running on virtual host in staging server. And I did dd in createDir() function in League\Flysystem\Adapter\Local.php. Which creates new directory with "www-data" user group And which displays with Lock icon in directory.
Below is the Permission Map for new directoy.
![selection_003](https://user-images.githubusercontent.com/37375055/37517547-cfeb8902-2937-11e8-97be-bdad2b4bbff3.png)


Can you suggest what should I change for it?

**Comment by frankdejonge** [comment]
@avanisolanki Hi, you need to match the permissions to your use-case. I suggest your look into how these permissions work on linux. It can be complex, it can be simple, but it's always specific to your case. In general you want the user who's creating the dir to be able to create that directory, so its parent directory needs to allow you to write create directories.

**Comment by avanisolanki** [comment]
Thank you @frankdejonge. I will look into it.

**Comment by avanisolanki** [comment]
I followed the steps written here http://laravel-recipes.com/recipes/25/creating-an-apache-virtualhost to run laravel app using virtual host.

I changed user in envvars file with my system user. So It is working properly!

**Comment by frankdejonge** [comment]
@avanisolanki 👍 awesome! Thanks for coming back and adding this information to the issue. I'm sure it'll help other people with the same issue.

**Comment by avanisolanki** [comment]
Thanks for your support also.

**Comment by affonso-rafael** [comment]
I solved this by changing the supervisor config that is responsible to run the horizon
In my case changed `user=nobody` to `user=www-data`
in `/etc/supervidor/config.d/horizon.conf`
Reboot the server and be happy
