### ISSUE TITLE
Delete file using full url

### ISSUE THREAD

**Issue by shigg1120** [thephpleague/flysystem#907]
I am saving an image attached to an article body coming from a wysiwyg editor on s3. Upon saved, I return a response with the full url of the image like this `https://xxxxx.s3.us-west-1.amazonaws.com/articles/md-15ac179ba39e1f.jpg` to assign it to `src` on `img` tag.

When I edit an article, I get all the images from the original article body and the edited article body and find removed image urls using `array_diff` to put into an array, so I can perform a delete operation.

But thing is the url in the array is saved as a full url `https://xxxxx.s3.us-west-1.amazonaws.com/articles/md-15ac179ba39e1f.jpg`. 

Is there a way to delete a file with the full url or do I have to use like `preg_match` to get a relative path?

**Comment by frankdejonge** [comment]
Hi @shigg1120,

Flysystem only works off a relative root, so you indeed have to preg_match or even str_replace to get the relative root. If I remember correctly the AWS SDK also doesn't allow this, so you'll have to do that regardless of using Flysystem or the SDK directly.
