### ISSUE TITLE
Empty string value for path results in downstream undifined index

### ISSUE THREAD

**Issue by mturro** [thephpleague/flysystem#908]
https://github.com/thephpleague/flysystem/blob/6458a02475da96115e3eaf95b882feefc4294e0b/src/Util.php#L17

I ran across this issue while using the flysystem-cache-adapter and flysystem-aws-s3-v3 adapter as indicated here: https://docs.bolt.cm/3.4/performance/remote-filesystem/amazon-s3 - This approach works as expected up to flysystem version 1.0.41. 

With the introduction of custom pathinfo functions in https://github.com/thephpleague/flysystem/pull/682 it seems that empty string as path value results in the pathinfo['dirname'] index not being set in the pathinfo array. This results in a downstream error of 'undefined index' in this function: https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/Storage/AbstractCache.php#L391

I'm working around for now by pinning flysystem to v1.0.41. Not completely sure if this is something that should be fixed in flysystem or in the cached adapter or if there should be a change in the way it's called from bolt. Any guidance would be appreciated!

**Comment by frankdejonge** [comment]
Thanks for reporting this, @mturro. I'll be releasing a version with the fix shortly.
