### ISSUE TITLE
cache invalidation

### ISSUE THREAD

**Issue by ctf0** [thephpleague/flysystem#913]
how does the cache invalidation works, sadly the [docs](https://flysystem.thephpleague.com/caching/) doesn't tackle this part.

- is it being handled automatically? if not then how to do it manually ? 
- is it possible to invalidate the cache on a directory level, for example lets say we have something like this
  ```
  root
    |_one.jpg
    |_two.jpg
    |_some_folder
      |_abc.jpg
      |_xyz.jpg
    |_some_other_folder
      |_aaa.jpg
      |_bbb.jpg
  ```
  now how to invalidate the cache for the `some_folder` directory items only without affecting the others ?

**Comment by frankdejonge** [comment]
Hi @ctf0,

Cache invalidation is too complex to standardise and should be tackled case by case. By default cache is invalidated according to the filesystem operations: deletes remove the item from the cache as well as delete dir calls. If you need more granular control over the invalidation process I suggest you implement your own caching strategy.

**Comment by ctf0** [comment]
awesome, actually ur answer has done half the issue, does file/dir renaming/moving also accounted for or should it be tackled manually ? if so i would appreciate any thought on how i might do that :+1:

**Comment by ctf0** [comment]
okay great, any plans to add this info to the cache docs ?
