### ISSUE TITLE
What data type is used for timestamps?

### ISSUE THREAD

**Issue by holtkamp** [thephpleague/flysystem#918]
What is the used / intended data type of a file timestamp?

Different types seem to be documents:

https://github.com/thephpleague/flysystem/blob/868cbf724368cb066d29f04245410d54c998e316/src/ReadInterface.php#L71-L78

https://github.com/thephpleague/flysystem/blob/868cbf724368cb066d29f04245410d54c998e316/src/MountManager.php#L35

But in my experience an integer is used:

```php
$file = 'someFile.txt';
var_dump($this->mountManager->getTimestamp('local://'.$file)); //Outputs: int(1524589467)
var_dump($this->mountManager->getTimestamp('phpcr://'.$file)); //Outputs: int(1524588605) 
```

Might be a `2.0 idea` to use return types to prevent such mismatches 🤓

**Comment by frankdejonge** [comment]
@holtkamp Hi, the read interface is part of the adapter interface, which is internal, so it uses the array return as documented here: https://flysystem.thephpleague.com/creating-an-adapter/#response-values

**Comment by holtkamp** [comment]
@frankdejonge aah, ok, missed that part of documentation. 

But then the MountManager could/should be marked as returning `int|false` right?

https://github.com/thephpleague/flysystem/blob/868cbf724368cb066d29f04245410d54c998e316/src/MountManager.php#L35

**Comment by glensc** [comment]
I also want timestamps: https://github.com/thephpleague/flysystem/issues/1174
