### ISSUE TITLE
allFiles() not working for simple FTP

### ISSUE THREAD

**Issue by Raccoon5031** [thephpleague/flysystem#919]
Sorry if this is laravel based 😞 

- Laravel Version: 5.6.7
- PHP Version: 7.2.4

### Description:
I'm trying to list all the files of my FTP. I found that the command `allFiles()` should be perfect for my use case.
When I use `Storage::disk('ftp')->allFiles()` it give me the same result as `Storage::disk('ftp')->files()` so no recursive.
I tried with my local and with an SFTP driver, and it's working very well. Therefore I think that the FTP driver is not permitting `allFiles()`

### Steps To Reproduce:
Set up an simple FTP driver
Create a folder with sub-folders and files in each sub-folders
Try to use `allFiles()`

**Comment by frankdejonge** [comment]
Hi, can you debug the responses you get from the `ftp_rawlist` function? And specify some more details about your FTP setup: which adapter classname, which ftp server type/version, what is the configured root path.

**Comment by frankdejonge** [comment]
The ftp_rawlist response is very unlikely, but if that's really the care there's nothing flysystem can do to fix this :/

**Comment by Raccoon5031** [comment]
I checked across the web and this error is coming from PHP xdebug.
I increased the max interation possible but then the server is on timeout.
This is coming from an infinite loop. I dug a little and found that it came from here

In AbstractFtpAdapter.php

```
public function getConnection()
    {
        $tries = 0;

        while ( ! $this->isConnected() && $tries < 3) {

            $tries++;
            $this->disconnect();
            $this->connect();
        }

        return $this->connection;
    }
```
Have you an idea of why is it hapening / how can I dig deeper or solve this?
And everything is working fine with a "classic" FTP client, so I guess that the error is not coming from my server

**Comment by frankdejonge** [comment]
Btw the fact that it works in a classic FTP doesn't mean there's nothing wrong with the server. There's too little information for me to give you meaningful directions. I suggest to either use step-through debugging or a var_dump/die approach to see why it loops.

**Comment by Raccoon5031** [comment]
Sorry I'm a beginner.
But there is something that I don't understand.

In In AbstractFtpAdapter.php, there is this `getConnection()` function. In the while loop, it's calling `$this->connect()` which is in fact the `connect()` in `Ftp.php`.

But this connect function in Ftp.php is immediatly calling `$connection = $this->getConnection();` (from AbstractFtpAdapter) and that's why it is looping, right?

**Comment by frankdejonge** [comment]
@Raccoon5031 are you using an outdated version of Flysystem perhaps? Because that method is not calling the `getConnection` method.

**Comment by Raccoon5031** [comment]
Indeed I was using `1.0.8` instead of `1.0.44`.
Anyway, should I create a new post / remove my old comment?

Because now I have the last version but my problem is still the same. 

But now, `ftp_rawlist` with option `-alnR` is giving me

```
array:2 [▼
  0 => "-rw-r--r-- 1 ftp ftp              0 Apr 24 14:24 root.txt"
  1 => "drwxr-xr-x 1 ftp ftp              0 Apr 25 12:50 test"
]
```

But I have files under my test folder

**Comment by frankdejonge** [comment]
You haven't actually described what your problem is, just that it is not working. This output looks correct, so what's the problem exactly?

**Comment by Raccoon5031** [comment]
I have other files under my test folder. And when I use `allFiles()` is only give me the file of the root folder. And not all the files under /test/*. The recursive way seems not working
