### ISSUE TITLE
[documentation] Variable name creates confusion

### ISSUE THREAD

**Issue by deepak1725** [thephpleague/flysystem#923]
On Page : [Setup Filesystem](https://flysystem.thephpleague.com/docs/usage/setup/) ,
`$adapter` is confusing, isn't it should be `$filesystem` ..?

**Comment by frankdejonge** [comment]
@deepak1725 correct! I've pushed the fix.

**Comment by deepak1725** [comment]
@frankdejonge  same with corresponding `Global Configuration` section

**Comment by frankdejonge** [comment]
@deepak1725 Fixed, thanks!
