### ISSUE TITLE
FilesystemInterface's get method is deprecated

### ISSUE THREAD

**Issue by garak** [thephpleague/flysystem#924]
There's no explanation in code source, nor in the commit 58a79bacae9b1fcf14d9b66cc7274cc2c2881218
What should be used instead?

**Comment by eremin** [comment]
Same question to File class.

**Comment by frankdejonge** [comment]
Hi @garak, the regular read/write/update (with or without Streams) should be used. The handlers are an OOP way of using it but they "leak" Flysystem into your application, which is not advised.

**Comment by garak** [comment]
Thanks for the explanation.
Anyway, I expect something more.
I expect that such suggestion is placed in:
a) the source code
b) an UPGRADE.md (similar) file in the repo
c) both

With last option best.
Such suggestion should include an upgrade path. E.g. something like "this method is deprecated since version X.Y.Z, use method fooBar instead"

**Comment by frankdejonge** [comment]
This is an open source project, I try to spend as much time on it as I can. If you "I expect something more", feel free to contribute.

**Comment by garak** [comment]
I'll be glad to open a PR, but I'm just a user here and likely I don't know the upgrade path.
For example, what about the `Handler` callback? It will just dropped? And what is planned release when deprecated function will be dropped?
Don't get me wrong about my expectations, I'm a maintainer of open source libraries myself (incidentally, one of which is using flysystem), and I'm just exposing what I expect as a library user (that is, of course, the same that I do as library maintainer). I think that leaving just a "deprecated" without explanations is a bit unfair. It's a bit like, you know, telling "RTFM" to your users.

**Comment by frankdejonge** [comment]
I didn't tell you to read a fucking manual nor did I treat you unfairly. Please consider your tone when opening issues on this repository.

**Comment by garak** [comment]
Frank, what I'm telling you that my tone was plain and it looks like you got me wrong.
Explaining "expectations" should be normal when discussing issues, since it should clarify what user expects and what is the actual result, helping the maintainer to get the situation without asking for further feedback.
Anyway, it looks like we started with wrong foot and probably is just a big misunderstanding, but well, it happens.
Can we start over, please?
My interest is to get an improvement about documentation of this library, do you mind to re-open this issue, at least to keep problem tracked unless it's solved?

**Comment by frankdejonge** [comment]
I've added a deprecations.md file, if that's not sufficient feel free to open another issue or a PR.

**Comment by stevleibelt** [comment]
@frankdejonge, thanks for this great project. I already saves me tones of time.
I'am writing this comment to link this explenation to your [Deprecated all things related to the handler](https://github.com/thephpleague/flysystem/commit/d2d9dc81df486d5ce8592987abd198f7c07abd4d#diff-41b5ea2bbaadc935cf6b51194eba6e68)-commit message.
Internally, we where debating if it make sense to switch to "your" file class but saw that it is marked as deprecated.

**Comment by frankdejonge** [comment]
@stevleibelt Hi Stev, thanks for your comment. I'm not sure what your question is or that this is just a general remark.

**Comment by stevleibelt** [comment]
@frankdejonge Sorry, I was reading through this conversation and ... "it all made sense in my brain" ;-).
My comment was a hidden request to add more information to your commit message. While searching for a reason why the file class was marked as deprecated, the commit message "Deprecated all things related to the handler" could not help to understand the why.
The why was explained within this issue comment log.
