### ISSUE TITLE
FTP not working with stream

### ISSUE THREAD

**Issue by Raccoon5031** [thephpleague/flysystem#926]
I want to transfer a large directory (recursively) from a location to another.
I am using flysystem V1.0.45 and flysystem-sftp V1.0.15

I am also using the Mount manager to make the transfert.

`$this->manager->put( 'ftp://'.$entry['path'], $this->manager->readStream('local://'.$entry['path']) );`

But it give me this error
`
fwrite() expects parameter 2 to be string, resource given`

When I tried with the SFTP adapter, everything is working well. Is it possible that the FTP adapter does not work the same way or is not working with stream?

**Comment by frankdejonge** [comment]
Hi @Raccoon5031, some adapter internally handle both strings and streams for put, but it's intended only to work for strings. There's `putStream` if you want to use resources.

**Comment by Raccoon5031** [comment]
It works perfectly thanks!
