### ISSUE TITLE
[Question] Best way to read and delete stream

### ISSUE THREAD

**Issue by Raccoon5031** [thephpleague/flysystem#928]
I'm using the mount manager to transfer big files from one adapter to another

`$this->manager->putStream( 'TO://'.$entry['path'], $this->manager->readStream('FROM://'.$entry['path']) );`

After the transfer is sucessful I want to remove the file from the 'FROM' adapter.
I've seen in the documentation that a `readAndDelete` function exist. It would be perfect for my use case if only it worked with stream. Something like `readAndDeleteStream`.

I wanted to ask if this function existed? Before coding something on my own

**Comment by frankdejonge** [comment]
@Raccoon5031 read and delete doesn't work for streams because the resource is open when the delete would happen, this makes the behaviour not portable across adapters.

**Comment by frankdejonge** [comment]
To answer your question, using readStream and writeStream and then a delete is the best way to do this.

**Comment by Raccoon5031** [comment]
So the best way to handle it is to check if the file has been transfered, and then delete it?

**Comment by Raccoon5031** [comment]
Ok thanks!

**Comment by Raccoon5031** [comment]
@frankdejonge Sorry to disturb you, I don't know if it's the best place to ask for this ... Anyway, is there an easy way to count the number of files (and not directories) by using the mount manager? Or should I go with basic php to check that?

**Comment by frankdejonge** [comment]
You can get a lit of entries using `listContents` and get a `count` from that: `$num = count($filesystem->listContents($directory, $recurseOrNot));`

**Comment by Raccoon5031** [comment]
But if I have subfolders in my directory. It will also count them, right?
I will go for this approach

```
public function isEmpty( $directory )
  {
    $contents = $this->manager->listContents( $directory , true);

    foreach ($contents as $content) 
    {
      if( $content['type'] != 'dir' )
      { return false; }
    }

    return true;
  }
```

**Comment by paritoshzom** [comment]
listContents( $directory , true);

The second parameter represents recursive - turn it false then it will only give contents of the current dir.
