### ISSUE TITLE
Breaking change introduced in 1.0.44 : getSize now throws a FileNotFound exception

### ISSUE THREAD

**Issue by Naouak** [thephpleague/flysystem#929]
### Bug Report

With 1.0.44. a file presence check was introduced to the method getSize. getSize used to return 0 when the file was not found but now throws an exception. This breaks any previous implementation that relies on this behavior in a minor version!

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.44

#### Summary

getSize now throws an exception changing it's actual behavior in a minor version.

#### How to reproduce

Use getSize on a non existing file on 1.0.43 will return 0 whereas in 1.0.44+ it will throw an exception.

**Comment by frankdejonge** [comment]
All the metadata getters have this. I'll add it do the documentation tho.

**Comment by Naouak** [comment]
The exception was not documented in the contract either in 1.0.43. This is a breaking change (this broke our system and was hard to trackdown). This should have bump the version to 1.1.0.

**Comment by frankdejonge** [comment]
For a BC break it would warrant a 2.0 actually, but I'm not going to do that because it was a bug.

**Comment by Naouak** [comment]
Throwing an exception in a function that used to not throw an exception is not a simple bugfix even if you intend to before. You changed the contract, even if it is for a bug fix, you need to bump more than a minor version.
