### ISSUE TITLE
Handling large files (stream)

### ISSUE THREAD

**Issue by benjaminb-** [thephpleague/flysystem#933]
Hello,

I'm using Flysystem in a Symfony app to manage files upload / download on S3.

````

$downloadableFileStream = $this->get("filesystem")->readStream($document->getDocument()),
$mimeType = $this->get("filesystem")->getMimetype($document->getDocument()),
$filename =$document->getDocument()

if (ob_get_level()) ob_end_clean();
return new StreamedResponse(function () use ($downloadableFileStream, $mimeType, $filename) {
    fpassthru($downloadableFileStream);
}, 200, [
    'Content-Transfer-Encoding', 'binary',
    'Content-Type' => "application/octet-stream",
    'Content-Disposition' => ('attachment; filename="' . $filename . '"'),
    'Content-Length' => fstat($downloadableFileStream)['size'],
]);
````

It's really slow for large files, i was thinking using stream does not put all file in memory, maybe i'm doing something wrong ? (i have the same problem with upload, i'm using putStream).

The download is instant for small files, but for large files, it seems the complete file is loaded in the filesystem before launch download.

Is there any way to "start" the download not get the entiere file ?

Any suggestions ?

Thanks :)

**Comment by frankdejonge** [comment]
The best we can do from Flysystem's side is to use the resource (stream) from the SDK, other optimisations possible have to be done either to PHP the language or the PHP code in the SDK for AWS.

**Comment by benjaminb-** [comment]
Yes i understand that and thank you for your great work :)

I was hoping is there any better solution to handle that problem.

I found a way to perform an efficient download (with S3 only) because my buckets are private.

Use the S3 client to generate a presigned request to get the file, there is no delay and the file download start like i want. I put the code if it could help someone.

```
$client = $this->filesystem->getAdapter()->getClient();
        if ($client instanceof S3Client) {
            $cmd = $client->getCommand('GetObject', [
                'Bucket' => $this->container->getParameter("s3_private_bucket"),
                'Key' => $file
            ]);
            $url = $client->createPresignedRequest($cmd, '+1 minute');
            return new StreamedResponse(function () use ($url, $file) {
                readfile((string)$url->getUri());
            }, 200, [
                'Content-Transfer-Encoding', 'binary',
                'Content-Type' => "application/octet-stream",
                'Content-Disposition' => ('attachment; filename="' . $file . '"')
            ]);
        }
```

**Comment by frankdejonge** [comment]
👍
