### ISSUE TITLE
laravel ftp doesn't work 

### ISSUE THREAD

**Issue by ShuiPingYang** [thephpleague/flysystem#943]
### laravel ftp doesn't work 
|    Q        |   A
|------------ | ------
| laravel Version     | Laravel Framework 5.5.40

when i use ftp as my file disk ,I cannot connect to ftp ,but whene i use php plain code ,i can upload file ,the laravel code as below : 
`$path = $request->file('file')->storeAs($save_path . '/' . date('Y-m'), $save_name, 'ftp');`

the error message is `Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN) Maximum execution time of 30 seconds exceeded`

and my plain code like below : 
```
$ftpserver = '52.xx.xxx.239';
$login = 'xxx';
$pass = 'xxx';    
$conn_id = ftp_connect($ftpserver);
ftp_login($conn_id, $login, $pass);
$file = app_path('Http/Controllers/HomeController.php');
$new_file = 'bbb.txt'; //新的文件名
$ret = ftp_nb_put($conn_id, $new_file, $file, FTP_BINARY);
while ($ret == FTP_MOREDATA) {
    // 任何其他需要做的操作
    echo ".==================";
    // 继续上传...
    $ret = ftp_nb_continue($conn_id);
}
if ($ret != FTP_FINISHED) {
    echo "There was an error uploading the file...";
    exit(1);
}
ftp_close($conn_id);
```

and this works !
my filesystems.php config like below : 
```
'ftp' => [
'driver' => 'ftp',
'host' => '52.xxx.127.239',
'username' => 'xxx',
'password' => 'xxx',
'root' => '/xxx/xx/data',
'passive' => true,
'timeout' => 300,
];
```
i donn't know where wrong .can you help me ?

**Comment by frankdejonge** [comment]
Are there any log messages with information?

**Comment by ShuiPingYang** [comment]
```
[2018-06-04 07:33:54] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at D:\\phpStudy\\WWW\\BCCKidAdmin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php:59)
[stacktrace]
#0 {main}
"} 
```
this is the error log ,that's it .

**Comment by frankdejonge** [comment]
what kind of ftp server is it? Have you tried passive mode turned off?

**Comment by ShuiPingYang** [comment]
and after i give 'timeout' => 300, it also time exceeded  . when i dig into ftp `use League\Flysystem\Adapter\Ftp;` login method ,,I find it cannot get the connection .it's just null . I don't know what's wrong .

when i change the mode into passive = false ,it turnout ;
```
ftp_mkdir(): Create directory operation failed.
```

**Comment by ShuiPingYang** [comment]
i already have a dir exist ,is that means ftp_mkdir will wrong ?and i read some message , they say it's a bug in createDir(); link as below 
https://blog.csdn.net/xiaoshu611/article/details/70242157

it should be change into this 
```
protected function createActualDirectory($directory, $connection)
{
    // List the current directory
    $listing = ftp_nlist($connection, '.') ?: [];

    foreach ($listing as $key => $item) {
        if (preg_match('~^\./.*~', $item)) {
            $listing[$key] = substr($item, 2);
        }
    }

    if (in_array($directory, $listing, true)) {
        return true;
    }
    if( @ftp_chdir($connection, $directory) === false )
    {
        return (boolean) ftp_mkdir($connection, $directory);
    }else
    {
        return true;
    }

}
```

**Comment by ShuiPingYang** [comment]
thank you @frankdejonge ,it's my fault . I make a diretory manually  ,and it's chmod is not right . than you again .

**Comment by frankdejonge** [comment]
👍 thanks for coming back after correcting it.
