### ISSUE TITLE
Memory exhausted issue while using 'local' adapter

### ISSUE THREAD

**Issue by peinhu** [thephpleague/flysystem#944]
Hello guys, first I sincerely pay the highest respect to your excellent works, and I'm using your package   in Laravel currently. But I found there is no way to 'append' some data to an existing file even if I use the 'local' adapter, and I have no idea about how to change the value of `$writeFlags`.  

The `$writeFlags` was set to `LOCK_EX` by default in ['Local.php'](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L74), and it is not changable unless in `__construct(..)`. If I want to append some data to a large file (more than 500MB) while `$writeFlags` is set to `LOCK_EX`, I have to read all the data of the large file to memory and append contents to it which may cause memory exhausted issue.    
<img width="737" alt="2018-06-05 17 37 27" src="https://user-images.githubusercontent.com/8167724/40968141-662ccd56-68e7-11e8-94fd-c6e81ad2a7da.png">

Since there is no 'append(...)' function in 'Local.php', is it possible to add a function to allow the modification of `$writeFlags`'s value? This will do the same trick as 'append(...)' function.  
e.g.
```php
    /**
     * @param $writeFlags
     * @return array
     */
    public function setWriteFlags($writeFlags)
    {
        $this->writeFlags = $writeFlags;

        return compact('writeFlags');
    }
```  
Or, if this is unacceptable, is there another way to append data to a file while using 'local' adapter? I really need some help, thank you.

**Comment by twistor** [comment]
Append operations are outside the scope of this library. There's no way to support them in a generic manner across adapters. If you're dealing with a 500MB file, your best bet is to drop down to native PHP file functions.

**Comment by frankdejonge** [comment]
The procedure for this would entail downloading the a local directory, merging files, overwriting the original. This is needed because cloud filesystems don't support append operations. How and where these operations take place is not easily standardised and quite easily implemented in an application.
