### ISSUE TITLE
FtpAdapter checking isConnected() is slow

### ISSUE THREAD

**Issue by brbrowning21** [thephpleague/flysystem#946]
### Question

|    Q        |   A
|------------ | ------
| Version     | 1.0.45

Almost every FTP operation checks that the connection is still open before executing. Inside that checking logic, it calls ftp_rawlist on the root of the FTP. This takes a nontrivial amount of time and I'm wondering if there are more efficient ways to check the connection.

```
    public function isConnected()
    {
        try {
            return is_resource($this->connection) && ftp_rawlist($this->connection, $this->getRoot()) !== false;
        } catch (ErrorException $e) {
            if (strpos($e->getMessage(), 'ftp_rawlist') === false) {
                throw $e;
            }
            return false;
        }
    }
```

Do we even need to do `ftp_rawlist` at all? I tried removing that part of the boolean statement and my code ran much faster.

**Comment by RubtsovAV** [comment]
If we delete this part, we will need to copy this logic for each action into our code. Because we don't know when ftp server will disconnect us. The main idea of the flysystem library is a single api for all kinds of file systems. Delete this function and we will need to check it manualy. This will kill the main idea.

**Comment by frankdejonge** [comment]
Unfortunately because PHP uses resources we need to actually perform an operation and check if the response is ok.

**Comment by ikari7789** [comment]
@frankdejonge Sorry to reply on a closed ticket, but I'm curious if it has to be the full file list. Couldn't a `NOOP` command be enough?

```
    public function isConnected()
    {
        try {
            return is_resource($this->connection) && ftp_raw($this->connection, 'NOOP') !== false;
        } catch (ErrorException $e) {
            if (strpos($e->getMessage(), 'ftp_rawlist') === false) {
                throw $e;
            }
            return false;
        }
    }
```
