### ISSUE TITLE
files retrieval error after delete when using cache

### ISSUE THREAD

**Issue by ctf0** [thephpleague/flysystem#948]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | league/flysystem-cached-adapter (1.0.7)

#### Summary

after deleteing a file, next time you try to retrieve the disk content you get an error
```
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/Users/novo/Public/www/_testing/six/vendor/league/flysystem/src/Util/ContentListingFormatter.php"
line:62
message: "Argument 1 passed to League\Flysystem\Util\ContentListingFormatter::isEntryOutOfScope() must be of the type array, boolean given"
```

this is probably because after file gets deleted the deleted item become
```
"test.png":false
```

#### How to reproduce
> for example using laravel "the issue is present even when creating a custom disk"

- enable caching https://laravel.com/docs/5.6/filesystem#caching
- delete a file
- try to get the disk content

**Comment by frankdejonge** [comment]
@ctf0 how is the file deleted? Cache should only be used if you're the only party influencing the filesystem.

**Comment by frankdejonge** [comment]
@ctf0 `1.0.8` of the cached adapter has been released to fix this.

**Comment by ctf0** [comment]
awesome, tested and all is good, thanx
