### ISSUE TITLE
How do I get a non-cached version of getSize() ?

### ISSUE THREAD

**Issue by cowai** [thephpleague/flysystem#949]
When I run getSize on a file two times with some seconds between them but the same request/php process, I get the same size. Even though I know the file is being updated.

How can I get the current size that is not cached?

**Comment by frankdejonge** [comment]
What adapter do you use? How is the file updated? By who/what/how? And do you use the cached adapter? (If so, don't use it in your case.)

This could be a million things but flysystem only returns cached data if you use caching, in which case: don't.

**Comment by cowai** [comment]
I am using https://github.com/GrahamCampbell/Laravel-Flysystem with the sftp adapter. The file is being updated by a separate process. I do not use any caching adapter at all. If I loop getSize in the same process I get the same result over and over. Is this how it is supposed to be?

**Comment by frankdejonge** [comment]
There is no caching of size in Flysystem or the SFTP adapter. Could be a phpseclib bug tho.

**Comment by cowai** [comment]
Ah okay. Makes sense. So if the round-trip time is 100ms, the first and second call to getSize should take  ~100ms, and not just the first one?

**Comment by frankdejonge** [comment]
Probably yeah, but if it's the first call the connection can be established then too, so I'd do more than 2 calls.

**Comment by cowai** [comment]
@frankdejonge This is no bug at all. This is intended functionality in phpseclib.
You need to call "disableStatCache()" to get desired functionality, but laravel-flysystem-sftp does not do that.

**Comment by frankdejonge** [comment]
@cowai what version was that introduced?

**Comment by cowai** [comment]
@frankdejonge Seems like it has been there a long time: https://github.com/phpseclib/phpseclib/commit/e09a6968da704dd26729e369b8f7a2b4a3df1a0a

Maybe it would be best to add an option to flysystem-sftp where one could disable it (or enable it)

**Comment by frankdejonge** [comment]
Version `1.0.16` of the sftp adapter has been tagged and released.
