### ISSUE TITLE
Plugin to increment file names when copying/renaming duplicates

### ISSUE THREAD

**Issue by druc** [thephpleague/flysystem#960]
Hello,

I know there's a `ForcedCopy` and a `ForcedRename` plugin, but can/should we add one for incrementing numbers at the end of the file name?

Example:
```php
$filesystem->incrementedRename('my_file.txt', 'path/my_file.txt');

// resulting in 'path/my_file_1.txt' if the file already exists
```

Or maybe there is already a nice way to do that and I haven't found it? 😄 

|    Q        |   A
|------------ | ------
| Version     | 1.0.46

**Comment by frankdejonge** [comment]
I recommend adding it in your own project if/when you need it.

**Comment by druc** [comment]
Ooki doki

**Comment by frankdejonge** [comment]
BWT, if you want to release it as a plugin package you can send me the link to the repo and I'll add the plugin in the main documentation.

**Comment by druc** [comment]
@frankdejonge I made this: https://github.com/druc/flysystem-incremental-naming

Please let me know if you have any suggestions on how to make it better. I'm quite new to this.

Regarding the docs. I only found about `ForcedCopy` and `ForcedRename` by digging into the issues.
