### ISSUE TITLE
Multi curl support in curl adapter class I post below in description

### ISSUE THREAD

**Issue by hirenaspl** [thephpleague/flysystem#961]
### Feature Request

|    Q        |   A
|------------ | ------
| Curl support | yes (I did that, please see below)
| Multi curl support    | yes/no (How to?)

#### Scenario

Long time ago, I created a curl adapter like below which seems to be working fine with my project:

`<?php
/**
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2017, Fiare Oy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fa\Bundle\ImportExportBundle\Adapter;

use League\Flysystem\Config;
use League\Flysystem\Adapter\AbstractAdapter;

/**
 * Adapter class
 *
 * @author Hiren Chhatbar <hiren@aspl.in>
 * @copyright 2017 Fiare Oy
 * @version v1.0
 */
class Curl extends AbstractAdapter
{
    /**
     * @var string path prefix
     */
    protected $pathPrefix = '/';

    /**
     * Write a new file.
     *
     * @param string $path
     * @param string $contents
     * @param Config $config   Config object
     *
     * @return array|false false on failure file meta data on success
     */
    public function write($path, $contents, Config $config)
    {
    }

    /**
     * Write a new file using a stream.
     *
     * @param string   $path
     * @param resource $resource
     * @param Config   $config   Config object
     *
     * @return array|false false on failure file meta data on success
     */
    public function writeStream($path, $resource, Config $config)
    {
    }

    /**
     * Update a file.
     *
     * @param string $path
     * @param string $contents
     * @param Config $config   Config object
     *
     * @return array|false false on failure file meta data on success
     */
    public function update($path, $contents, Config $config)
    {
        $absPath = $this->applyPathPrefix($path);

        $arr = $this->getSize($contents);

        $update = (is_file($absPath) && isset($arr['size']) && filesize($absPath) == $arr['size']) ? false : true;

        if ($update) {
            $binary = $config->has('binary') ? $config->get('binary') : false;

            $ch = curl_init($contents);

            if (true == $binary) {
                $fp = fopen($absPath, 'wb');
            } else {
                $fp = fopen($absPath, 'w+');
            }

            curl_setopt($ch, CURLOPT_FILE, $fp);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

            if (true == $binary) {
                curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
            }

            if ($config->has('username') && $config->has('password')) {
                curl_setopt($ch, CURLOPT_USERPWD,  $config->get('username').':'.$config->get('password'));
            }

            curl_exec($ch);
            curl_close($ch);
            fclose($fp);

            return array(
                'path' => $absPath,
                'size' => filesize($absPath),
            );
        }
    }

    /**
     * Update a file using a stream.
     *
     * @param string   $path
     * @param resource $resource
     * @param Config   $config   Config object
     *
     * @return array|false false on failure file meta data on success
     */
    public function updateStream($path, $resource, Config $config)
    {
    }

    /**
     * Rename a file.
     *
     * @param string $path
     * @param string $newpath
     *
     * @return bool
     */
    public function rename($path, $newpath)
    {
    }

    /**
     * Copy a file.
     *
     * @param string $path
     * @param string $newpath
     *
     * @return bool
     */
    public function copy($path, $newpath)
    {
    }

    /**
     * Delete a file.
     *
     * @param string $path
     *
     * @return bool
     */
    public function delete($path)
    {
    }

    /**
     * Delete a directory.
     *
     * @param string $dirname
     *
     * @return bool
     */
    public function deleteDir($dirname)
    {
    }

    /**
     * Create a directory.
     *
     * @param string $dirname directory name
     * @param Config $config
     *
     * @return array|false
     */
    public function createDir($dirname, Config $config)
    {
    }

    /**
     * Set the visibility for a file.
     *
     * @param string $path
     * @param string $visibility
     *
     * @return array|false file meta data
     */
    public function setVisibility($path, $visibility)
    {
    }

    /**
     * Check whether a file exists.
     *
     * @param string $path
     *
     * @return array|bool|null
     */
    public function has($path)
    {
        return true;
    }

    /**
     * Reads a file.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function read($path)
    {
        $path = $this->fixPath($path);

        $mime = $this->getMimetype($path);

        $binary = 'binary/octet-stream' == $mime;

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $path);

        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        if (true == $binary) {
            curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
        }

        $data = curl_exec($ch);

        curl_close($ch);

        if ($data) {
            return ['contents' => $data];
        }
    }

    /**
     * Read a file as a stream.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function readStream($path)
    {
    }

    /**
     * List contents of a directory.
     *
     * @param string $directory
     * @param bool   $recursive
     *
     * @return array
     */
    public function listContents($directory = '', $recursive = false)
    {
    }

    /**
     * Get all the meta data of a file or directory.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function getMetadata($path)
    {
    }

    /**
     * Get the size of a file.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function getSize($path)
    {
        $path = $this->fixPath($path);

        $ch = curl_init($path);

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_NOBODY, true);

        curl_exec($ch);

        $size = curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD);

        curl_close($ch);

        return ['size' => $size];
    }

    /**
     * Get the mimetype of a file.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function getMimetype($path)
    {
        $path = $this->fixPath($path);

        $ch = curl_init($path);

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_NOBODY, true);

        curl_exec($ch);

        $mime = curl_getinfo($ch, CURLINFO_CONTENT_TYPE);

        curl_close($ch);

        return $mime;
    }

    /**
     * Get the timestamp of a file.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function getTimestamp($path)
    {
    }

    /**
     * Get the visibility of a file.
     *
     * @param string $path
     *
     * @return array|false
     */
    public function getVisibility($path)
    {
    }

    /**
     * Fixes path
     *
     * @return string
     */
    protected function fixPath(string $path)
    {
        if (preg_match('/:(\/{0,1})[A-Za-z]/', $path)) {
            $path = preg_replace('/:(\/{0,1})/', '://', $path);
        }

        return $path;
    }
}
`

But now, I want to add multi curl support in it and it seems that checking main Filesystem, I won't be able to pass multiple URLs with methods like "update" with above class. So, I'm just thinking about the possible solution of the same. Can you please help me and suggest. One solution, I'm thinking is to pass those extra URLs as config option and set first URL as main which should work.

Also, aren't you planning to have an adapter for curl where we can download anything given as URL.

#### Summary

Your inputs will be really appreciated. Please guide.

**Comment by frankdejonge** [comment]
Flysystem is not designed for this and it would break encapsulation.
