### ISSUE TITLE
Define framework for public URLs

### ISSUE THREAD

**Issue by SamMousa** [thephpleague/flysystem#962]
# Feature Request
I'm aware of the previous discussion in #514.
I think it's time to reevaluate previous decisions.
Cloud storage has become more readily available and we need some way to formalize structure so implements can add support.

## What I propose is simple: extend the `FileSystemInterface` with 2 functions:
```php
public function hasPublicUrl($path): bool;
public function getPublicUrl($path): string;
```

### Make a plugin
Plugins bind to the `FileSystemInterface` object, meaning that they cannot access the adapter, and even if they could there is no framework for implementers of adapters to provide the public URL to this plugin.
If we add `getAdapter` to the interface this could work, we could then create an interface for the adapter.
```php
interface SupportsPublicUrl {
    public function hasPublicUrl($path): bool;
    public function getPublicUrl($path): string;
}
```
Then the plugin can provide the framework for implementers of adapters.

So in conclusion, to do this properly we must change  `FileSystemInterface` and add `getAdapter` to it.

### The external URL can be arbitrary
This is not a concern of the framework. An example that would work for any adapter, for example, is this: 
```php
class PublicUrlFtpAdapter extends Ftp implements SupportsPublicUrl {
    public function __construct(array $config, \Closure $hasPublicUrl, \Closure $getPublicUrl) {
         parent::__construct($config);
         $this->hasPublicUrlClosure = $hasPublicUrl;
         $this->getPublicUrlClosure = $getPublicUrl;
    }

    public function getPublicUrl($path) {
        return call_user_func($this->getPublicUrlClosure, $path);
    }
    public function hasPublicUrl($path) {
        return call_user_func($this->hasPublicUrlClosure, $path);
    }
}
```

The importance here is to separate configuration from consumption.
From a consumer perspective I don't care whether these functions give predictable / arbitrary results. As long as the results are accurate it's all fine.

This would allow my consuming code to always be the same (which is the goal of the FlySystem API).
- If my code requires public URLs to be supported I could throw exceptions.
- If underlying storage changes I don't care; I don't even have to know.

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

# Proposal 1
Extend the `FileSystemInterface` with 2 functions: `getPublicUrl` and `hasPublicUrl`.
To be decided: does `getPublicUrl` throw exception or return `null` (I'm in favor of exception).

If accepted, I'll make a PR with the following changes:
- Create `PublicUrlInterface`
- `FileSystemInterface` extends `PublicUrlInterface`
- Create `PublicUrlViaClosureTrait` (defining the private fields holding the closure, protected setters for the closure to be called from the constructor, public functions implementing the `PublicUrlInterface`. If not set there will be default implementations.)
- Add support to `NullAdapter` with simple implementation.
- Add support to (children) `AbstractFtpAdapter`, via the trait. (The setters can then be called by passing the config array).
- Add support to `Local` adapter via the trait. Closures will be optional arguments to the constructor.
- Optional: Create new `PublicLocal` adapter extends `Local`, takes a base URL in the constructor, creates closures for the parent constructor.

# Proposal 2
Extend the `FileSystemInterface` with 1 function: `getAdapter`. This will allow for a plugin to implement the structure as described above.
I'm not a fan of this solution since that means that all adapters have to implement interfaces from a different package (that might not be as well managed as this one).

**Comment by twistor** [comment]
You can do this in a separate library. It breaks our abstraction.

**Comment by SamMousa** [comment]
How does it break an abstraction? There are parts of the current abstraction not supported by all drivers, how is this different?

**Comment by frankdejonge** [comment]
For me this is an issue because while URL's are standardised, exposing files as URL's is inherently "custom" and difficult to standardise. You callback design is not the type of design I want to support because moving forward I want flysystems to have more explicit concepts and better type-safely.

For future reference: please wait for a response on these kind of things before moving forward to implement them, it saves you and me both times, especially when such concepts have previously been declined.

**Comment by SamMousa** [comment]
Well, I need the implementation whether it gets merged here, in a fork or in a separate library.

I agree that it is difficult to standardize, although we could easily use interfaces instead of closures.
While hard I don't think it's impossible though. And rather than try to create something and pray several other implementers will choose that implementation I hoped we could get some guidance in the core API.

I'm open for any discussion regarding implementation, but not doing it because it's hard or because not all filesystems support it seem like invalid arguments to me.

**Comment by frankdejonge** [comment]
This could also be achieved by using composition instead.

**Comment by absolux** [comment]
indeed @frankdejonge, you've right, composition will solve this issue easily, because the implementation is application specific, not the responsibility of this library.

```php
class SomeAdapter implements AdapterInterface {
  protected $adapter;

  public function __constructor (AdapterInterface $previous) {
    $this->adapter = $previous;
  }

  public function getPublicUrl ($path) {
    // TODO: specific logic to get the public URL
  }
}
```
Usage

```php
$fs = new FileSystem(new SomeAdapter(new Local('/root/dir')));
```
To get the public URL

```php
$url = $fs->getAdapter()->getPublicUrl($path);
```
What's missing here is the magic function `__call` to have a result like below

```php
$url = $fs->getPublicUrl($path);
```

Hope it gives you some insights @SamMousa

**Comment by SamMousa** [comment]
I know how to implement it; I'd just love to have a structure dictated by the core so that other implementers can do the same thing as well.
The point of abstraction is to not care about the underlying adapter in the consuming code.

```php
if (!$fs->hasPublicUrl('some/file')) {
    $publicUrl = $assetManager->publish('some/file');
} else {
    $publicUrl = $fs->getPublicUrl('some/file');
}
echo '<img src="' . $publicUrl . '">';
```
If I implement this the way you suggest then it will be hard to get 3rd parties to all implement support for my extension. If we extend the core API it'll be come easier and I can submit PRs to 3rd parties to add support for the extended API which will have higher chance of getting merged.

Currently you do the same thing for other concepts, like _visibility_. There's `NotSupportingVisibilityTrait`, which suggests that even though you have `setVisibility` in the interface you realize that this is not applicable to all adapters.
In my opinion this is not a technical discussion but an process discussion.

If we extend the interfaces provided by this package there's a higher change of third parties implementing support for those interfaces (even if they don't support the public URLs)... If I make my own implementation chances of that happening are slim.

> indeed @frankdejonge, you've right, composition will solve this issue easily, because the implementation is application specific, not the responsibility of this library.

This is simply not true. For a lot of adapters public URLs are not application specific, but adapter specific. Currently by not supporting it you make it application specific, this is why everyone rolls their own code to solve the same problem.

> Hope it gives you some insights @SamMousa

It does, but it wasn't needed. I already have a working implementation in my own application; the goal of this discussion is not to get my own code to work, but to create a consistent framework for everyone.
Currently my application works, but if I switch to a different adapter, say from azure to S3 I will have to do more than change configuration of the adapter since that adapter does not support public URLs. Basically I lose the abstraction that you have provided by being forced to implement adapter specific code.

**Comment by absolux** [comment]
@SamMousa,

As I've said before, the need for `getPublicUrl()` is application specific.
Some applications will use it for link sharing, others will not.
In addition, which protocol will you use for URLs ? which url prefix to use for adapters that do not support public URLs natively, like S3 ? ... etc. A simple method cannot respond to any use case.

> $assetManager->publish('some/file');

As you did, public URLs is the responsibility of the `asset manager` not the file system.

This is an open source project, @frankdejonge is the owner and didn't accepted you PR, but you can fork the project, add your vision, use it in your applications, make it public on github, upload to composer directory. It's `open source` you know !

**Comment by frankdejonge** [comment]
Before this escalates into a more heated discussion, the fact that this is a discussion to start with for me illustrates the complexity of such a solution. Thank you both for participating and sharing your thoughts on the matter.

**Comment by SamMousa** [comment]
@frankdejonge so the conclusion is that because it's complex, we shouldn't attempt to solve it?

For me that's the whole point, collaborating on complex stuff to come up with a good solution instead of everyone rolling their own mediocre and application specific solution.

I mean just because we don't directly see a viable solution doesn't mean we can't at least define the properties such a solution must have. That way if someone ever thinks of one they can check that it has the properties you would require to merge it into the base!

**Comment by frankdejonge** [comment]
When it's an order of magnitude more complex to make one thing do two things, one should just make two things.

**Comment by absolux** [comment]
I'm sorry if I misspoke. I just want to point on the fact that a `library` should solve one problem and have a single responsibility instead of many.

This library is an abstraction of the file system in general, it cannot, and should not, provide a solution for all use cases. It's not because `getPublicUrl` is useless, only that an abstraction is a solution for a basic and common case, and layers come later to add extensions. That's it.

Thank you
