### ISSUE TITLE
Should Util::normalizeRelativePath remove leading slash?

### ISSUE THREAD

**Issue by PHPGuus** [thephpleague/flysystem#965]
|    Q        |   A
|------------ | ------
| Version     | 1.0.47

when I want to retrieve the mimeType (through Laravel) of an absolute path, the function Util::normalizeRelativePath drops the leading slash, making an absolute path relative, causing the caller not to be able to find the file in question.

**Comment by twistor** [comment]
Flysystem file paths don't correspond to real files. This is intended behavior.

**Comment by twistor** [comment]
It seems like you either need to keep using the file-system abstraction, or if it's a special case, know how to translate the path.

**Comment by frankdejonge** [comment]
If you use a root path of `/` then this will work as expected.

**Comment by frankdejonge** [comment]
The main reason for this is scoping, this measure (along with others) prevents root path traversal.
