### ISSUE TITLE
Updata, Put do not work properly on Local adapter

### ISSUE THREAD

**Issue by Edrard** [thephpleague/flysystem#966]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.0.47

#### Summary

I have some problems there. I am want to use Local  adapter and **"put"** method to write data to the file.
But always its rewrited.

I looked at Local class on update method, and I do not see FILE_APPEND flag on file_put_contents function. I also maked few debug runs, and $this->writeFlags always have only LOCK_EX flag

My PHP Version 7.0.31
Test scripts was runned from CLI 

#### How to reproduce

Maked 2 test

use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

require 'vendor/autoload.php';

$adapter = new Local(__DIR__);
$filesystem = new Filesystem($adapter);

$response = $filesystem->put('test.file', 1);
$response = $filesystem->put('test.file', 2);
$response = $filesystem->put('test.file', 3);

Inside test.file I can see only number 3.
I am tryed code like this 

use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

require 'vendor/autoload.php';

$adapter = new Local(__DIR__);
$filesystem = new Filesystem($adapter);

$response = $filesystem->write('test.file', 1);   
$response = $filesystem->update('test.file', 2);  
$response = $filesystem->update($'test.file', 3); 

And have the same result

**Comment by twistor** [comment]
`PUT` is not append.

**Comment by Edrard** [comment]
Ist it Write or Update Files?
On my examples, is it fine, thats I recivieng number 3 in file?
Even on this one?

**Comment by Edrard** [comment]
Hmm, looks like its update content or write it to file if not exist and I need to to use putStream with a or a+

Sorry, just missunderstood.

**Comment by frankdejonge** [comment]
for context: put is a idempotent write
