### ISSUE TITLE
Local: option to fail if root directory does not exist

### ISSUE THREAD

**Issue by franksl** [thephpleague/flysystem#971]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Scenario

I noticed that the local adapter always calls the ensureDirectory() method. This method checks if root directory exists and, if not, just tries to create it. Creating directories on the filesystem should be, in my opinion, optional. 
Also I wouldn't do this operation in the constructor because read/writes may never happen and the system would be left with a "useless" directory. Creating the root (if requested) should be done when that directory is effectively used.

#### Summary

Add an option to allow the adapter to fail if root directory does not exist.
Move the root directory creation code outside the constructor.

**Comment by twistor** [comment]
I agree that we shouldn't be creating the directory in the local filesystem. Unfortunately, that would be a BC break.

I don't like adding yet another optional behavior to the local adapter. It seems like this is simple behavior that you could check before using flysystem.
