### ISSUE TITLE
Error handler executed when trying to read not existing file with Local adapter

### ISSUE THREAD

**Issue by hamuz** [thephpleague/flysystem#974]
### Bug Report

Code sample provided

|    Q        |   A
|------------ | ------
| BC Break    | yes?
| Version     | 1.0.47

#### Summary

When error reporting is -1, the handler is executed instead of simply returning false from read.

#### How to reproduce

https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L216-L218

```
<?php

use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

function handler($level, $message, $file = '', $line = 0, $context = []) {
  die("Failed");
}

error_reporting(-1);
set_error_handler(handler);

$adapter = new Local(__DIR__);
$filesystem = new Filesystem($adapter);
$contents = $filesystem->read('not_existing');
if (FALSE === $contents) {
  echo "Success";
} else {
  echo "Failed";
}

?>
```

**Comment by hamuz** [comment]
Original error is present in Laravel context.

The contributing factor in this case is Laravel error handling, which catches all errors.
https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L32

League Local adapter:
https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L216-L218

PHP documentation, pay attention to errors:
https://secure.php.net/manual/en/function.file-get-contents.php#refsect1-function.file-get-contents-errors

**Comment by hamuz** [comment]
@frankdejonge , any thoughts?

**Comment by frankdejonge** [comment]
Is this due to a race condition of some sorts? Do you have the asserts disabled?

**Comment by hamuz** [comment]
I don't think there is any race condition involved. See the stacktrace in: https://github.com/firefly-iii/firefly-iii/commit/4e9456b33b900eac9c35b8bc1baae84abeba6176#r30895234

**Comment by frankdejonge** [comment]
Ah, yeah, they use the internal adapter without the Filesystem, which is not supported. They break an internal guarantee, which was addressed in another issue too. For version 1 of Flysystem they should not do this.

**Comment by hamuz** [comment]
Thank you for your input @frankdejonge, could you elaborate abit more?
1. Who are they? (Laravel? Firefly? FallbackAdapter? ReplicateAdapter?)
2. Isn't the File system used in:
```
#4 /app/vendor/league/flysystem/src/Filesystem.php(181): League\Flysystem\Replicate\ReplicateAdapter-&gt;read(&#039;at-221.data&#039;)
#5 /app/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(109): League\Flysystem\Filesystem-&gt;read(&#039;at-221.data&#039;)
```

3. What internal guarantee do they break?
4. In what issue is it addressed?
5. I guess Laravel 5.7 uses flysystem 1.x, correct?

Sorry for the many questions, but I feel a bit confused by the response.

**Comment by frankdejonge** [comment]
Sorry, forgot to include that. It's this part of the stacktrace:

```
2018-10-14T14:40:57.933922+00:00 app[web.1]: #2 /app/vendor/litipk/flysystem-fallback-adapter/src/FallbackAdapter.php(221): League\Flysystem\Adapter\Local-&gt;read(&#039;at-221.data&#039;)
```

**Comment by frankdejonge** [comment]
So it's the fallback adapter.

**Comment by hamuz** [comment]
Thank you. I still feel this might not be the best API design choice if you are able to violate internal guarantee using public API.

I guess reverting to an older version where it has the "has" check before doing the read is the solution in this case. Thank you for pointing this out.

If you're interested, this is how we resolved it:
https://github.com/firefly-iii/firefly-iii/pull/1813

**Comment by frankdejonge** [comment]
This interface has a certain protocol, which when followed doesn't break. If I send valid commands to an FTP server in the wrong order then I also "break" functionality, but that doesn't mean the protocol is broken, the client is.

However you'll be pleased to know that the next major version will focus remove the need for the ::has check entirely, which eliminates this issue. Until then we'll have to follow this protocol.

**Comment by hamuz** [comment]
Looking at it from a security and usability perspective, you can't really expect the client to behave.

Can you please point me to relevant changes in the next version?

**Comment by frankdejonge** [comment]
> Looking at it from a security and usability perspective, you can't really expect the client to behave.

There's no security concern here, please refrain from suggesting there is.

**Comment by hamuz** [comment]
I didn't mean to imply there is a security issue here.

But, my point holds. You don't control the way the public API is used (and in this case in which order), which ultimately lead us here.

Same holds when analyzing designs of client-server interactions such as in the FTP server you mentioned. From a security standpoint, no matter how the client interacts with the FTP server, the FTP server should stay in safe and expected state.

Drawing the comparison here, having the error handler called, instead of `read` returning `false` as documented, **is not expected behavior** (which is why this issue was opened).

I'm happy that next version will deal this inconsistencies (and I'd be happy to look at those fixes).

I'll leave you with a good lecture on API design, I hope you find it useful:
Video: https://www.youtube.com/watch?v=heh4OeB9A-c
Slides: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/32713.pdf

Thank you for your work on this library, as it is cornerstone of PHP abstraction of many file systems.
