### ISSUE TITLE
Fallback adapter throws error in dev env.

### ISSUE THREAD

**Issue by andriusUlins** [thephpleague/flysystem#976]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.2

#### Summary

Fallback adapter throws error if file do not exists in local file system.

#### How to reproduce

Tools: `Symfony 4 (flex)`, `php 7.2`

I'm using FallBack adapter. Main adapter: `local`, fallback: `awss3v3`
When trying to resolve image from first adapter (`local`), I'm getting error in my dev env, at `src/Adapter/Local.php: 216`, `Warning: file_get_contents(/path to file): failed to open stream: No such file or directory`.

I'm getting error, because errors are not suppressed.
This problem could be solved by changing this:
```
public function read($path)
    {
        $location = $this->applyPathPrefix($path);
        $contents = file_get_contents($location);

        if ($contents === false) {
            return false;
        }

        return ['type' => 'file', 'path' => $path, 'contents' => $contents];
    }
```
To this:
```
public function read($path)
    {
        $location = $this->applyPathPrefix($path);

        if (!$this->has($location)) {
            return false;
        }

        $contents = file_get_contents($location);

        return ['type' => 'file', 'path' => $path, 'contents' => $contents];
    }
```

Also I think this bug appeared, because `Litipk/flysystem-fallback-adapter` made changes in `src/FallbackAdapter.php`
You can see git history here. `https://github.com/Litipk/flysystem-fallback-adapter/commit/ea2c887360ef6f1c877938884c621586883f96c0#diff-2e9c0b668144a63b311929ba3ccdbd81`

**Comment by frankdejonge** [comment]
They should not have removed the has check because it's not redundant.

**Comment by frankdejonge** [comment]
Also, I think the BC break and version info is not correct since flysystem doesn't have a 3.0 range and this is not a BC break by this library.
