### ISSUE TITLE
Digital Ocean Spaces CDN support?

### ISSUE THREAD

**Issue by royduin** [thephpleague/flysystem#977]
See: https://blog.digitalocean.com/spaces-now-includes-cdn/, is it supported? 

Now my endpoint is: `https://ams3.digitaloceanspaces.com` but it needs `https://ams3.cdn.digitaloceanspaces.com` for the frontend. Is that possible?

**Comment by frankdejonge** [comment]
That's not related to flysystem actually. Basically the exposed url needs to contain the `.cdn` segment, for flysystem you'll keep using the first one but for externally you'll need to replace the hostname part of the URL.

**Comment by royduin** [comment]
Ah, sorry. Using Laravel so I've to look there instead of here.

**Comment by royduin** [comment]
If someone else is coming by, I'm using the Medialibrary package from Spatie. To configure a CDN just change the url in the config (`medialibrary.s3.domain`).
