### ISSUE TITLE
take asf into account (video/x-ms-asf)

### ISSUE THREAD

**Issue by kcassam** [thephpleague/flysystem#979]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | x.y.z

#### Summary

In League\Flysystem\Util\ MimeType:: extensionToMimeTypeMap, there is no key for asf files. Please consider adding 'asf' key with value 'video/x-ms-asf'

**Comment by frankdejonge** [comment]
PR is welcome! 👍
