### ISSUE TITLE
remote copy

### ISSUE THREAD

**Issue by nathanaelmartel** [thephpleague/flysystem#981]
Hi, I don't knw if it is a bug or a feature.

I just tried to copy a file using copy() with sftp adaptator. As it was very slow, I monitor the network and it's appear that the function download and then upload the file.

It is not possible to make a remote copy, I mean without downloading and uploading the file ?

**Comment by nathanaelmartel** [comment]
By remote copy, I mind that both files are on the same filesystem, on the same server.

**Comment by frankdejonge** [comment]
Hi @nathanaelmartel some adapters don't support this and therefor we polyfill that behaviour, which indeed requires downloading and re-uploading the file unfortunately. SFTP is one of those.

**Comment by nathanaelmartel** [comment]
for people who have the same problem, I juste did that for the moment 

`$conn = ssh2_connect('example.com', 22);
ssh2_auth_password($conn, 'username', 'password');

$stream = \ssh2_exec($conn, 'cp source_file_path dest_file_path');`

It is not as convenient as using the API but it's work…
