### ISSUE TITLE
Read only modus

### ISSUE THREAD

**Issue by royduin** [thephpleague/flysystem#988]
It would be nice if there was a read only modus, when someone tries to write/delete it will be ignored.

**Use case**
I'm working on a Laravel application with [Spatie's Medialibrary package](https://github.com/spatie/laravel-medialibrary) which uses Digital Ocean Spaces through the S3 driver on production. 

To have the same data and images on the test environment I've copied the database which includes all the image references and the disk name where the image is stored. But when I remove an image it actually removes it from the DO Space, the same for uploads. So, if there was a read-only modus I could set S3 to read-only so nothing can be created, changed or removed there. The disk for new uploads is the local one on test so uploads work well. For example:

**config/medialibrary.php**
```
'disk_name' => env('APP_ENV') == 'production' ? 'spaces' : 'local',
```

**config/filesystems.php**
```
'spaces' => [
    'driver' => 's3',
    'read-only' => env('APP_ENV') != 'production',
],
```

Any thoughts?

**Comment by frankdejonge** [comment]
@royduin if you want this you can implement the AdapterInterface and block all the write calls and use that as a decorator.

**Comment by royduin** [comment]
@thijsbouwes just noticed the `$deletePreservingMedia` variable in Spatie's Medialibrary. Doing something like this in my base model does the job:

```
<?php

namespace App;

use Illuminate\Support\Facades\App;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    protected $deletePreservingMedia = false;

    public function __construct(array $attributes = [])
    {
        $this->deletePreservingMedia = App::environment(['local', 'staging']);

        parent::__construct($attributes);
    }
}
```

But still, maybe a nice addition to Flysystem?

**Comment by frankdejonge** [comment]
This kind of behaviour is out of scope for Flysystem.

**Comment by royduin** [comment]
> @royduin if you want this you can implement the AdapterInterface and block all the write calls and use that as a decorator.

Not something as feature for Flysystem?

**Comment by frankdejonge** [comment]
If you want this then you can open a PR for it.

**Comment by royduin** [comment]
If I come across this again in a project without Spatie's Medialibrary I'll create a PR.

**Comment by frankdejonge** [comment]
👍
