### ISSUE TITLE
upload to S3 Transfer Acceleration

### ISSUE THREAD

**Issue by michaelnguyen547** [thephpleague/flysystem#990]
### Question

Can I use S3 Transfer Acceleration ? AWS PHP SDK supports it (https://github.com/aws/aws-sdk-php/issues/1372)

|    Q        |   A
|------------ | ------
| Version     | 1.0.48

**Comment by frankdejonge** [comment]
for Flysystem that doesn’t matter. If the client supports it it’s ok.

**Comment by michaelnguyen547** [comment]
I am using Laravel on top of Flysystem, can you please show me how to enable S3 Transfer Acceleration?

**Comment by frankdejonge** [comment]
@michaelnguyen547 the issue you linked to contains the option you need to pass to the S3 client.
