### ISSUE TITLE
create CloudFront signed URL 

### ISSUE THREAD

**Issue by michaelnguyen547** [thephpleague/flysystem#991]
### Question

I am working with CloudFront to serve content from S3.

WIth S3 only

```
 // return a normal s3 url - correct
Storage::disk('s3')->url($image_path);

 // return S3 signed url - correct
Storage::disk('s3')->temporaryUrl($image_path, now()->addMinutes(30))
```

With CloudFront (Restrict Bucket Access is on, Restrict Viewer Access is on Use Signed URLs or Signed Cookies)

```
// return a normal CloudFront url - correct
Storage::disk('s3')->url($image_path); 

// return S3 signed url - incorrect . I expect CloudFront signed url
Storage::disk('s3')->temporaryUrl($image_path, now()->addMinutes(30)) 
```

|    Q        |   A
|------------ | ------
| Version     | 1.0.48

**Comment by frankdejonge** [comment]
Flysystem does not support URL’s, that’s a laravel feature.
