### ISSUE TITLE
Adapter\Local::has() method should return false for directories

### ISSUE THREAD

**Issue by mnavarrocarter** [thephpleague/flysystem#995]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.0.49

#### Summary

I think that `Adapter\Local::has()` method should return false for directories. Now, I've read #899 but I strongly disagree with the issue's author PoV, mainly because of the `FilesystemInterface` docBlock, that says the method has "Check whether a file exists.". **I think the implementations should stick to what is documented in the docBloc, to avoid confusion and ensure consistency.** If not, this can really cause trouble when swapping implementations, which is the sole purpose of this library.

For example, let's say I'm working with `GoogleStorage` adapter. Since Google Storage has no notion of directories, the method `has` on a directory path should return `false`, right? Now let's say that I swap the implementation for AWS S3 one. Since they have directories, now this method would return `true` to the same input. This, for me, makes the `FilesystemInterface` very unreliable and defeats the purpose of having an abstraction like this. The main point is: **if different implementations of the abstraction will give me different results to the same input, then I cannot trust it: it could break something.** 

This is exactly what happened to me implementing a `FilesystemMiddleware` for my application. I want to serve an static file if exists, so I relied on `has` and it was working fine. Swapped implementation, and suddenly exceptions were thrown. This was mainly because since the `has` call returned true to a directory, when I performed file relative operations to it (like read content, get content-type or get size), it failed terribly. Was hard to debug because my test mocks assumed that just files return `true`, which is what the docBlock says.

#### What is, in my PoV, the best way to solve this

Some adapters/filesystems could implement a `DirectoryAwareInterface` that could have a methods like `hasDir()` on them. This is more reliable, and it gives the developer the option to do something different if the implementation he's working on suddenly changes to one that is not aware of directories.

I don't think this is a breaking change as it is more of a feature. What we would be doing is creating some new methods to some adapters that support them. It is adapter's responsibility to implement them.

What y'all think?

**Comment by piotr-cz** [comment]
I agree, this is confusing.
As there is one method to check for both files and directories at least docblock should say it.
